### ISSUE TITLE
Add max queue size in HttpClient

### ISSUE THREAD

**Issue by meshuga** [eclipse/vert.x#1212]
In Vert.x 2 there was an option to limit the size of HttpClient waiting connection queue made in this PR - https://github.com/eclipse/vert.x/pull/849 (discussion in https://github.com/eclipse/vert.x/pull/845). Apparently, in Vert.x 3, due to the refactoring, this functionality wasn't included.
See https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/ConnectionManager.java#L95

**Comment by vietj** [comment]
thanks for pointing this out, that's something to consider for the next version.

**Comment by ddimensia** [comment]
I guess @meshuga beat me to it by a few hours.  I included the generated source also, can't get a clear understanding if those changes are intended to be committed or not based on past commits.

**Comment by meshuga** [comment]
You've got documentation, this time you win @ddimensia :wink:

**Comment by ddimensia** [comment]
You're optimistic, I wouldn't close the issue until one of the PRs is merged. :smile:

**Comment by meshuga** [comment]
Sorry, I wanted to close my PR.
