### ISSUE TITLE
Allow to plug a Context exception handler

### ISSUE THREAD

**Issue by vietj** [eclipse/vert.x#1216]
that would allow to trace the flow propagation (i.e when a context schedules the execution of a context and its later execution, etc...)

Vert.x Unit could use that to be aware of failures and somehow get rid of `TestContext` , for instance:

```
@Test
public void testSomething(TestContext ctx) {
  long now = System.currentMillis();
   vertx.setTimer(50, v -> {
      ctx.assertTrue(System.currentMillis() - now <= 50);
   });
}
```

could be pretty much like:

```
@Test
public void testSomething() {
  long now = System.currentMillis();
   vertx.setTimer(50, v -> {
      assertTrue(System.currentMillis() - now <= 50);
   });
}
```

the AssertionError would be caught by Vert.x Unit and make the test fail.

**Comment by aesteve** [comment]
:+1: 

As I said somewhere else, it would also mean : "if an exception occurs within an event-loop somewhere, the test FAILS" which is a huge lack in vertx-unit atm.

Example : 

```groovy
int count = 0
Async async = context.async()
vertx.eventBus().consumer('address') {
  count++
  if (count == 2) {
    throw new RuntimException
  }
  if (count == 3) {
     async.complete()
  }
}
3.times {
  vertx.eventBus().send('address', 'test')
}
```

This test will pass... Now remplace the `throw new RuntimException()` by parsing JSON (which would throw an exception if the sent message is not JSON formatted), and you've got real-life failure undetected.

**Comment by purplefox** [comment]
I think this would be solved when the "supervisors" feature is 
implemented (can't find it now, but we used to have an issue for that).

Basically the idea is to implement something like supervisors like you 
have in Erlang/Akka.

With supervisors, the thing that deployed the verticle can also receive 
any unhandled exceptions thrown by the verticle and then, depending on a 
policy decide to restart the verticle, or shut it down or escalate the 
failure to its own supervisor etc.

**Comment by vietj** [comment]
so this would not cover the embedded handlers ? those are used in Junit tests.

**Comment by vietj** [comment]
or they would be a default "supervisor" for all non verticle ?

**Comment by purplefox** [comment]
If you're referring to a non verticle case then I guess you would want some way to specify an exception handler on the Context object. This would be called for any unhandled exceptions thrown from contexts.

The supervisor functionality could use that to implement various policies for verticles.

**Comment by vietj** [comment]
and we need a default handler per Vert.x for all the handlers created by `getOrCreateContext()` calls when running in embedded junit that are not associated with any context.

**Comment by purplefox** [comment]
+1 If no exception handler is set for a particular context then a default exception handler on the Vertx instance could be called.

**Comment by vietj** [comment]
isn't it something we should put on ContextInternal to limit its visibility to api users though ?

**Comment by purplefox** [comment]
I don't see why it shouldn't be usable to all users, seems like useful functionality to me.

**Comment by vietj** [comment]
yes it would be, just thinking out loud :-)

**Comment by vietj** [comment]
@aesteve  the ultimate point is to report AssertionError to the unit test runner and avoid to have to use TestContext for this, which means we can ditch most of its usage and use JUnit assertions (need to see with other shims too) and allow the usage of popular stuff like Hamcrest or JAssert and their ecosystem

**Comment by aesteve** [comment]
Yes I perfectly understand the point.

I was just asking if it would **also** cover this (pretty terrible when it happens :( ) specific use case ?

**Comment by vietj** [comment]
I think it would and that's something that would make the test fails (or at least make it configurable which exception would fail and which would not)

**Comment by vietj** [comment]
note : I've done a simple initial impl of this because it's useful for writing HTTP/2 unit tests branch.

**Comment by purplefox** [comment]
The implementation in https://github.com/eclipse/vert.x/commit/febdc5b3608552580452312c49fa73f1ea69212d looks good to me.
An added feature that would be great for more of a supervisor style approach would be also to allow an exception handler to be specified at verticle deployment, e.g.

    vertx.deployVerticle("com.example.MyVerticle", ex -> {
        // This exception handler would be called for any unhandled exceptions in the verticle
    });

You could then have some default exception handlers for various common policies, e.g. restart the verticle, restart after a delay, etc.

**Comment by aesteve** [comment]
ping @vietj : the issue we were discussing this morning. 

The idea appeared here, too : https://github.com/vert-x3/issues/issues/211

I think the `exceptionHandler` might be a perfect starting point of such a Supervisor notion. But as @purplefox mentionned, the missing part might be "escalation". By using the context which deployed the Verticle, we might be able to react to an exception.

But exception doesn't necessarily mean "failure". Let's take the example of high availability : in this case, the verticle is automatically redeployed by another node from the cluster in case it's no longer responding.

I think we could discuss the unification of these 2 functional processes (`ExceptionHandler` and ha) under the `Supervisor` umbrella.

A `Supervisor` could be responsible of managing several verticles. Is this `Supervisor` itself a Verticle ? Maybe ? Maybe not, I really have no clue.

But we could imagine such a `Supervisor` as acting as an `TriConsumer<Verticle, Context, Failure>` where (pseudo category theory code, sorry but you get the idea) : `type Failure = (Exception | Shutdown | BasicallyAnythingThatCanGoWrong) with Timestamp`. Verticle is the actor, and Context is the original deployment context of that actor.

Let's imagine we wan't to react the same way to a brutal shutdown as to a severe exception =>e.g. publishing a "Temporary unavailable" message over the event bus and redeploying the Verticle after a certain delay : we'd only have to implement such a `Supervisor` and deploying the Verticle with it. 

No matter the failure cause, we'd act the same way.

Obviously I'm open to the discussion but I find the "let it crash" Erlang OTP approach very confortant. How many times do you have to perform "a fresh restart" some part of a distributed system when something wrong happened ?
