### ISSUE TITLE
HttpClientRequest end() could be invoked out of order

### ISSUE THREAD

**Issue by testn** [eclipse/vert.x#1217]
If HttpClient is not running inside a verticle/container. For example, it's running as a HTTP client application. HttpClientRequest.write()/end() are supposed to be called from outside vert.x event loop. When doing so, write() will be re-invoked in vert.x event loop but end() will not be. Therefore, complete flag may be set to "true" before all the write() calls are invoked. In such case, the request may end before it sends out all of its data.

**Comment by vietj** [comment]
hi, can you provide a small test to show how to reproduce this case ?

**Comment by testn** [comment]
@vietj It was my bad.. I was trying to workaround some of the deadlock bug in #1204. If I apply #1204 and revert my change, it seems to work fine.
