### ISSUE TITLE
ClientConnection should be closed upon http RequestTimeout

### ISSUE THREAD

**Issue by ddimensia** [eclipse/vert.x#1218]
If an HttpClientRequest get's in a state where it is no longer receiving data from a server and a request timeout fires then Vertx should force the connection to close so that it can be freed up so another request can be processed.   Most likely since the connection is in an unknown state it shouldn't be reused if keepalive is enabled.

This issue combined with issue #1212 can easily cause an OOM or stalled HTTPClient situation on high throughput servers.

**Comment by testn** [comment]
If `HttpClientOptions.setIdleTimeout` is set, it should provide exactly what you want I assume?

**Comment by ddimensia** [comment]
```HttpClientOptions.setIdleTimeout``` is not really the same and I believe is intended to handle unused keep-alive connections similar to Apache's [KeepAliveTimeout](https://httpd.apache.org/docs/2.4/mod/core.html#keepalivetimeout) setting.  You could try to use ```setIdleTimeout``` to handle this particular problem but it would be inadequate in some situations as it wouldn't handle slow senders and isn't a per-request setting.

Specifically, the requestTimeout/connection issue is something we saw with periodic packet loss on a high throughput api call with low timeouts.  Basically what can happen, is that if you have a short timeout, say 250ms and a high request rate you can get into a situation where a slow sender or waiting for packet retransmits can exceed the request timeout.  If the request rate is high enough this will cause requests to load up on the pool and force requests into the wait queue.  Since the ConnectionManager won't view the timed out connections as 'available' until it either sees a responseEnd or channel close the HttpClient will effectively block any new requests being handled.  This combined with bugs #1219 and #1212 and high load can cause a server to go into a death spiral where it can never catch up.  

I plan to provide a PR for this shortly, I plan on making the behavior configurable with it defaulting to the existing behavior.  The downside of closing the connection is that it has impacts on pipelined requests and the server you're connecting to so I could see how some may not want this behavior.

**Comment by ddimensia** [comment]
I finally got back around to working on a PR and just updated to the latest code that includes HTTP2 support.  With the latest code I found a few problems...

First, the new HttpClientRequestImpl has a 'connection' method that attempts to cast a HttpClientConnection to a HttpConnection.  This results in a class cast exception as one doesn't implement the other.  Since the code change I was intending on using the connection method to get and close the connection.  The alternative and maybe better approach would be to put a 'close' method on the HttpClientRequest interface, this would allow the underlying implementation to do the correct thing based on it's state (connected or not, http2 reset?).

This is bug is a blocker for me to move some our high volume infrastructure pieces off of our patched 2.1.x release and onto 3.x.  Would be happy to hear ideas on the best way to proceed.

**Comment by testn** [comment]
@vietj , there is also HttpClientRequestImpl.setTimeout() that does not work as advertised either:

```
/**
   * Set's the amount of time after which if the request does not return any data within the timeout period an
   * {@link java.util.concurrent.TimeoutException} will be passed to the exception handler (if provided) and
   * the request will be closed.  <------ the request won't be closed.
   * <p>
   * Calling this method more than once has the effect of canceling any existing timeout and starting
   * the timeout from scratch.
   *
   * @param timeoutMs The quantity of time in milliseconds.
   * @return a reference to this, so the API can be used fluently
   */
```

**Comment by vietj** [comment]
@testn can you clarify ? it says the request will be closed - which actually for HTTP/1 and HTTP/2 have different semantics (in 1 it would close the connection and not in 2)

**Comment by testn** [comment]
you can see that it only throw an exception but not really close the connection

```
  private void timeout(long timeoutMs) {
    handleException(new TimeoutException("The timeout period of " + timeoutMs + "ms has been exceeded"));
  }
```

**Comment by vietj** [comment]
ok

**Comment by creativeprogramming** [comment]
Uhm... I'm a bit out of coding activity in last period of time, so maybe what I'll add to this thread is pure bullshit (I apologize in any case)

But simply ad as as always trying to help  improving, is it possible that this issue is related to a memory leak I'm experiencing?

I've 1G of heap space outed by some traffic peaks, seems like lot of 'http client' objects stills in memory:

![image](https://cloud.githubusercontent.com/assets/954291/25114067/0e13ecf2-23fc-11e7-8de1-8d0c4420c96a.png)

Anyway I'm using a custom in-memory caching so maybe the issue is only on my code. Please cross check your number of httpclients in some real case usages (I fears also prematurely aborted connections 
 by smartphones etc)

**Comment by tsegismont** [comment]
Please post your question to the vertx user forum with a reproducer.
Otherwise the community can't help. Thank you

2017-04-18 6:00 GMT+02:00 Stefano Gargiulo <notifications@github.com>:

**Comment by ZJ-coding** [comment]
@ddimensia hello, i also found  there was packet loss on a high throughput api call when using httpclient. so have you solved this problem?

**Comment by vietj** [comment]
@ZJ-coding do you still observe this issue with the latest vertx version 3.5.4 ?
