### ISSUE TITLE
Waiting requests that have been timed out should not open a tcp connection.

### ISSUE THREAD

**Issue by ddimensia** [eclipse/vert.x#1219]
If a request goes into the HTTPClient wait queue and times out before being processed it will still cause an http connection to be opened and closed in a non-keepalive case.  This has the side effect of causing a large number of TIME_WAIT sockets on the local host and extra load on the server and network for no value.  

If a waiting request times out it should be ignored rather than cause an interaction with the connection pool.

**Comment by vietj** [comment]
hi, do you mean using `HttpClientOptions#setConnectTimeout` ?

**Comment by ddimensia** [comment]
See: https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/ConnectionManager.java#L163 
You will see that when a connection is closed a waiting request is polled from the internal queue.  A new connection is then created without regard to the exception state of the waiting request.  Once the connection is open then the HttpClientRequestImpls connect handler will be called, which upon seeing that it has received an exception will close the socket immediately. https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java#L587

In the case of keepalive things aren't as big of an issue as there is no actual opening/closing of a socket but there is still the cost of adding a task onto the event loop. https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/ConnectionManager.java#L118
