### ISSUE TITLE
VertX 3 can send an object via EventBus??

### ISSUE THREAD

**Issue by astrung** [eclipse/vert.x#1224]
I have a class,and i use Vertx.eventBus.send("Address",my_object).But i get this error:SEVERE: No message codec for type: for my_object.
So how to fix it???

**Comment by stream1984** [comment]
Yes, you can using MessageCode.
There are some describe in [here](http://vertx.io/docs/vertx-core/java/#_the_event_bus_api)

**Comment by astrung** [comment]
myCodec is implemented from MessageCode ??But how to implement it??I read MessageCode interface,but i don`t know how we should implement abstract method for this interface???

**Comment by astrung** [comment]
From MessageCodec methods, i see that MessageCodec encode-decode java object in to Buffer??

**Comment by cinterloper** [comment]
If i understand correctly;
You essentially have to serialize your object into a buffer (or essentially byte array), then deseralize it on the other side. there are some well known 'serializers' that will do this part. 
The supported way to do this is implementing MessageCodec and doing the work inside said implementation

i belive you would be better off asking this type of question on the mailing list, than in an issue

**Comment by vietj** [comment]
please discuss this on vert.x group, not in project issues :-)
