### ISSUE TITLE
HttpClientRequest timeout doesn't work as indicated

### ISSUE THREAD

**Issue by ddimensia** [eclipse/vert.x#1236]
Based on the code in [HttpClientRequestImpl#handleTimeout](https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java#L561) and the test [testRequestTimeoutExtendedWhenResponseChunksReceived](https://github.com/eclipse/vert.x/blob/master/src/test/java/io/vertx/test/core/HttpTest.java#L2814) it would indicate that the request timeout is supposed to be canceled at the end of the response with some grace period applied as long as data is being received.

The current code doesn't actually work in that manner and I question whether a sliding timeout window is desired behavior either.  

Currently, the timeout is canceled in [handleResponse](https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java#L392) which is called when the underlying connection handler receives the [Status-Line](http://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html) of the response in [HttpClientImpl.ClientHandler#doMessageReceived](https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/HttpClientImpl.java#L860).  Since this is the first packet of the response it means that the time it takes to receive the body, and the implied chunk handling timeout extension, is never included in the request timeout time.  A test that would illustrate the problem would be to set a requestTimeout, have the server send headers but delay the body for more than the timeout.  You should see that the timeout never fires as it was already canceled once the server sent the initial response packet.

It seems like the preferred behavior would be to cancel the requestTimeout timer in [ClientConnection#handleResponseEnd](https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/ClientConnection.java#L282) and remove the sliding window implied by the chunk handling or make it optional.

**Comment by ddimensia** [comment]
Example test illustrating problem:
```java
@Test
  public void testRequestTimesoutWhenIndicatedPeriodExpiresWithAPartialResponseFromRemoteServer() {
    long requestTimeout = 500;
    server.requestHandler(req -> {
      req.response().setStatusCode(200);
      req.response().setChunked(true);
      req.response().write("foo");
      vertx.setTimer(requestTimeout * 2, time -> {
        req.response().write("bar");
        req.response().end();
      });
    });

    server.listen(onSuccess(s -> {
      HttpClientRequest req = client.request(HttpMethod.GET, DEFAULT_HTTP_PORT, DEFAULT_HTTP_HOST, DEFAULT_TEST_URI, resp -> {
        fail("End should not be called because the request should timeout");
      });
      req.exceptionHandler(t -> {
        assertTrue("Expected to end with timeout exception but ended with other exception: " + t, t instanceof TimeoutException);
        testComplete();
      });
      req.setTimeout(requestTimeout);
      req.end();
    }));

    await();
  }
```

**Comment by vietj** [comment]
I think it's the expected behavior.

The javadoc of setTimeout says : _Set's the amount of time after which if a response is not received a `java.util.concurrent.TimeoutException` will be sent to the exception handler of this request._  

The _received_ interpretation is a bit vague.

However the manual says _If the request does not return any data within the timeout period an exception will be passed to the exception handler (if provided) and the request will be closed._

which clearly means the tested behavior.
