### ISSUE TITLE
HttpClient: Netty "decodeResult" not handled

### ISSUE THREAD

**Issue by gmagniez** [eclipse/vert.x#1241]
I have an issue when a server send a response with too large headers, when debugging I  see that Netty has put the status "decodeResult: failure(io.netty.handler.codec.TooLongFrameException: HTTP header is larger than 8192 bytes.)" on the DefaultHttpResponse but Vert.x HttpClient does not check this status and handle normally the response which has incomplete headers.
For example the initial content-length header is not present in the headers and that breaks the processing of the response. Processing that should not be done as Netty has failed decoding the response.
Can you fix this problem?
I have a second issue, I effectively have some big headers but the  "HttpClientCodec" parameters are not configurable, I will open a second issue for this point.

**Comment by vietj** [comment]
do you have a reproducer for this ? some of them have been handled recently.

**Comment by gmagniez** [comment]
I don't have a reproducer but I saw that it has been fixed several monts ago I think.

**Comment by vietj** [comment]
ok will close this issue for now
