### ISSUE TITLE
Make Netty HttpClientCodec and HttpRequestDecoder Configurable

### ISSUE THREAD

**Issue by gmagniez** [eclipse/vert.x#1242]
Add some options to HttpClientOptions and HttpServerOptions to let users customize the netty HttpClientCodec/HttpRequestDecoder options (maxHeaderSize/maxChunkSize).

**Comment by vietj** [comment]
is it related to https://github.com/eclipse/vert.x/pull/1238 ?

**Comment by testn** [comment]
please close this one
