### ISSUE TITLE
Shared instance of HttpClient is not guaranteed to be executed in the same thread

### ISSUE THREAD

**Issue by testn** [eclipse/vert.x#1248]
This does not behave as I expected where the callback of `HttpClient` called inside event loop is not guaranteed to be called back in the same event loop due to the connection from another event loop is reused in another event loop.

```
package io.vertx.test.core;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Future;
import io.vertx.core.buffer.Buffer;
import io.vertx.core.http.HttpClient;
import io.vertx.core.http.HttpClientRequest;
import io.vertx.core.http.HttpServer;
import org.junit.Test;

import java.util.concurrent.CountDownLatch;

public class HttpDeadlockTest extends HttpTestBase {

    @Test
    public void testDeadlock() throws Exception {
        CountDownLatch latch = new CountDownLatch(4);
        client = vertx.createHttpClient();
        HttpClient localClient = vertx.createHttpClient();
        vertx.deployVerticle(new TestVerticle(), x -> latch.countDown());
        vertx.deployVerticle(new TestVerticle(), x -> latch.countDown());
        vertx.deployVerticle(new TestVerticle(), x -> latch.countDown());
        vertx.deployVerticle(new TestVerticle(), x -> latch.countDown());
        latch.await();
        CountDownLatch latch1 = new CountDownLatch(100);
        for (int i = 0; i < 100; i++) {
            localClient.getNow(19009, "localhost", "/", res -> {
                latch1.countDown();
                assertEquals(200, res.statusCode());
            });
        }
        latch1.await();
        localClient.close();
    }

    private class TestVerticle extends AbstractVerticle {

        @Override
        public void start(Future<Void> startFuture) throws Exception {
            HttpServer httpServer = vertx.createHttpServer();
            httpServer.requestHandler(x -> {
                Thread serverThread = Thread.currentThread();
                HttpClientRequest req = client.get(80, "load.s3.amazonaws.com", "/pixel.gif");
                req.handler(res -> {
                    Buffer buf = Buffer.buffer();
                    res.endHandler(v -> {
                        Thread clientThread = Thread.currentThread();
                        if (clientThread != serverThread) {
                            x.response().setStatusCode(500);
                        } else {
                            x.response().setStatusCode(200);
                        }
                        x.response().end();
                    });
                    res.handler(buf::appendBuffer);
                });
                req.end();
            });
            httpServer.listen(19009, x -> startFuture.complete());
        }

        @Override
        public void stop(Future<Void> stopFuture) throws Exception {
            super.stop(stopFuture);
        }
    }
}
```

**Comment by vietj** [comment]
you are right.

as work around you should create one HttpClient per verticle and not share the same client among accros several verticles.

**Comment by vietj** [comment]
I should provide soon a branch you can try to see how it goes

**Comment by vietj** [comment]
would you mind to try https://github.com/eclipse/vert.x/tree/client_connection_correct_context ?

**Comment by testn** [comment]
still not working... the client callback is still from the wrong thread.

**Comment by vietj** [comment]
now this case *should* be covered as well. BTW I would rather discourage to share an HttpClient with keepalive between different event loops. But for testing like you do, it's fine.

**Comment by testn** [comment]
when you have multiple verticles and you don't want to create a new HttpClient every time, that's how you end up with this structure. Vert.x does not have a good mechanism to create HttpClient per event loop. It should have been done so automatically like what eventbus does.

**Comment by testn** [comment]
I haven't looked closely but from the way the code is written I think there are a lot of problems which may lead to stall and deadlock easily. I would probably prefer a lot more test around it

**Comment by vietj** [comment]
@testn which code are you referring to about deadlock ? we had a couple of deadlock before 3.2 but that was resolved by @purplefox 
@testn _It should have been done so automatically like what eventbus does_ what do you mean here ?

**Comment by purplefox** [comment]
The client wasn't designed to be used from different contexts.

As I've said before, if you respect the Vert.x threading model and don't share stuff between contexts your life would be a lot easier :)

**Comment by vietj** [comment]
agreed with you @purplefox

**Comment by testn** [comment]
if it's not meant to be open from the different context, there should be a helper function to help constructing it then. there is no good way to share most of the objects except HttpClient now

**Comment by vietj** [comment]
I think that when we an http request from a different context with a pooled connection that was created on another context we can easily detect that the contexts are not the same and we could log a warn.

in your code you should create an http client in each TestVerticle in the start. Each http client will use its own event loop.

**Comment by testn** [comment]
We use dependency injection so it will be a bit difficult to do since HttpClient is used in multiple places.

**Comment by testn** [comment]
With this bug, it is also fairly easy to create a deadlock when `HttpClient` is used outside Vert.x thread when there are multiple concurrent `HttpRequest`

**Comment by testn** [comment]
I wonder how difficult it is to make `HttpClient` itself be "shareable" among different `Context` correctly like what HttpServer does. If it's not possible, it may make sense to make it easier to detect when HttpClient is called from the wrong context. I think it should be prevented as it is very deadlock prone.

**Comment by vietj** [comment]
here is a PR that implement this : https://github.com/eclipse/vert.x/pull/1267

The idea is that in embedded we don't care much because it's a non Vert.x thread and callback have to be done on a Vert.x thread. But when there is a context, if the connection context is not the same as the request context : a warn is issued in the log.

And the documentation says clearly that such sharing should not be done.

**Comment by testn** [comment]
- It would probably be better to reject it by default to throw an exception. 
- One of the problems I have is that if you use `HttpClient` outside the verticle deployment especially when I want to use Vert.x HTTP client in an embedded application. In that case, I would create `HttpClient` without using Verticle deployment. If I invoke `HttpClient` outside the context, it will keep creating new context every time behind the scene which is very confusing and error prone.

**Comment by vietj** [comment]
- it is technically possible to share it but it would make the code more complex.
- you cannot thrown an Exception because with pooling you are going to re-use a connection coming a possibly other context
- my opinion is that for production usage you should use a context or verticle, embedding a client is useful for writing examples or unit tests.

**Comment by amitranjan-fk** [comment]
@vietj What is the recommended way to use `HttpClient` in production if we are using dependency injection to inject the `HttpClient` and are deploying multiple instances of the same verticle ?

**Comment by tsegismont** [comment]
Check you dependency injection tool documentation. It should be possible to inject so-called "new" or "dependent" instances of HttpClient.

**Comment by vietj** [comment]
each verticle instance needs to have its own instance of HttpClient
