### ISSUE TITLE
Update redeploy documentation

### ISSUE THREAD

**Issue by cescoffier** [eclipse/vert.x#1253]
Eclipse need the launcher-class

It should give a complete example with Gradle and Maven.

**Comment by aesteve** [comment]
re. Gradle it should be : 

```groovy
plugins {
  id 'application'
  id 'com.github.johnrengelman.shadow' version '1.2.2'
}

mainClassName = 'io.vertx.core.Launcher'
def mainVerticle = 'com.mycompany.MainVerticle'

shadowJar  {
    classifier = ''
    mergeServiceFiles {
        include 'META-INF/services/io.vertx.core.spi.VerticleFactory'
    }
}

run {
	args = ['run', '--redeploy="src/**/*.java"',  mainVerticle]
}
```

I can try this evening.

**Comment by aesteve** [comment]
Nope :\ doesn't work at all.

All it does is crashing the console :(

If you want to give it a try : https://github.com/aesteve/gradle-redeploy

**Comment by cescoffier** [comment]
Yes that's expected.

It works using something like:

java -jar ... -redeploy=... -launcher-class=... -on-redeploy='gradle shadowJar'

**Comment by cescoffier** [comment]
It needs to mention that `vert` requires the `launcher-class` option.
