### ISSUE TITLE
A call to routingContext.request().netSocket().isSsl() make the verticle to stop accepting new connections

### ISSUE THREAD

**Issue by poiuytrez** [eclipse/vert.x#1256]
I have a route that tries to retrieve if the request is an http or https request. 

private void handleAddEvent(RoutingContext routingContext) {
        routingContext.request.netSocket().isSsl();
        response.end();
}

The call the isSsl seems to stop the verticle to accept any new http request.

I use Vert.x 3.2.

**Comment by purplefox** [comment]
I think the javadoc explains this ;)

http://vertx.io/docs/apidocs/io/vertx/core/http/HttpServerRequest.html#netSocket--

**Comment by poiuytrez** [comment]
I see...
