### ISSUE TITLE
Exclude codegen.json from final vertx-core binary

### ISSUE THREAD

**Issue by Lagz0ne** [eclipse/vert.x#1257]
I am trying to utilize vertx-codegen to generate code, somehow it always picks up codegen from vertx-core instead of my own's. Would be great if you guys can just move it out of final release

**Comment by vietj** [comment]
you can filter the codegen.json to use in the processor options `codeGenerators` which is a comma separated list of processor to use. In this list you specify the name of the generators you want to retain.

**Comment by Lagz0ne** [comment]
Thanks @vietj, I figured out that option while reading codegen code
