### ISSUE TITLE
Enable adding netty logging handler to log HTTP requests/responses (for debugging)

### ISSUE THREAD

**Issue by yfinkelstein** [eclipse/vert.x#1262]
```
if (...)
   pipeline.addLast("log", new LoggingHandler())
```

Those who ever needed to debug Netty know that LoggingHandler is one of the first instruments.

**Comment by aderigs** [comment]
:+1:

**Comment by vietj** [comment]
note (for whoever is going to contribute this) : Netty HTTP2 has specialized logging classes like Http2OutboundFrameLogger, etc...

**Comment by soneyworld** [comment]
:+1:

**Comment by AWVotek** [comment]
:+1:

**Comment by felfert** [comment]
+1

**Comment by froth** [comment]
:+1:

**Comment by vietj** [comment]
that seems popular
