### ISSUE TITLE
How we can check if Verticle sends Message successfully or not???

### ISSUE THREAD

**Issue by astrung** [eclipse/vert.x#1268]
I have 2 Verticles :a sender and a receive.Sometimes - with sending-receiving first message ,i see that My Receive can not  handle first message -but ok with all other messages after it.So i have 2 assumptions: i have sent message when Receive haven't deployed completed ,or Message didn't send successfully.How can i fix it???

**Comment by vietj** [comment]
use a reply, the reply handler will either get the reply message (ack) or an error.

**Comment by vietj** [comment]
please next time ask the question on google group, issues should not be used for asking questions.
