### ISSUE TITLE
HttpClientRequest endHandler() is confusing

### ISSUE THREAD

**Issue by testn** [eclipse/vert.x#1272]
endHandler callback handler is not called when the `HttpClientRequest.end()` is called. However, it is called when it receives a `HttpClientResponse` which is quite unexpected. And worse, it is also called after the handler for `HttpClientRequest.handler(Handler<HttpClientResponse>)` being called. I would expected it to be called when the entire data has been written to.

**Comment by vietj** [comment]
The end handler is inherited from ReadStream<HttpClientResponse> so this is the normal behavior.
