### ISSUE TITLE
MessageProducer.writeQueueFull always returns `true`

### ISSUE THREAD

**Issue by sfitts** [eclipse/vert.x#1273]
The current implementation of this method in MessageProducerImpl will always return a value of `true`.    At least for my use case it would be preferable if it returned true only if the producer is out of credit and has started to place messages in its pending queue.  It looks like this may have been the intent (since the code checks the pending queue size), but the check is current `pending.size() >= 0` when I think it should be `pending.size() > 0`.

**Comment by sfitts** [comment]
This is for Vert.x 3.2.0.

**Comment by vietj** [comment]
any luck you checked ?

**Comment by sfitts** [comment]
Sorry, to held up doing a release of our own.  The changes you put in look good.  I did have a couple of follow up questions about the overall goals for flow control, based on what I think the current default behaviors are.  I have the following scenario:

   EB Producer ------->  EB Consumer -- Pump --> HttpServerResponse ----> Client

In this case I would like the rate of data transfer to be governed by the rate at which the client can process data off the network.  So if the client (or the network) slow down that exerts back pressure and the HttpServerResponse's write queue will fill.  In response to this the Pump will pause the Consumer.  What I'd like to happen at that point is for the Consumer to extert back pressure on the Producer, causing it to queue messages on it's side (and let the code upstream know via `writeQueueFull`.

Based on my current understanding of the code it seems that using the default configuration it is somwhat random as to whether things will work this way or whether the Consumer will simply drop messages.  This is becuase the Consumer has no way of influencing it's initial or current credit.  By default the Producer will give it 1000 messages and unless the Consumer is paused just as this number drops to 0 then the Consumer's default behavior is to discard messages when paused.  I can change this of course (and will), but it is just a different from what I'm used to.  The credit based approaches that I'm familiar with put the control of the credit value in the hands of the consumer, so it can tell the producer to slow down if it's client can't keep up.  Here the relationship is inverted (at least across the event bus, the Pump actualy behaves in a more familiar way).

Anyway, I'm just curious about this and how it is envisioned event bus flow control be combined with network flow control and the Pump abstraction.  Am I simply thinking about them incorrectly?

**Comment by giovibal** [comment]
There are workarounds for this issue ?

**Comment by sfitts** [comment]
As of 3.2.1. the originally logged issue has been fixed.  As for the questions about the interaction between the Pump abstraction and the currently implemented flow control, I never got a response.

**Comment by giovibal** [comment]
Actually my code is buggy because it uses Pump to connect the EventBus with tcp / websocket.
I've found this discussion (https://groups.google.com/forum/#!topic/vertx-dev/rGFSEmefmnI), so I'll try to checkout and test "eventbus-controlflow-work" branch with my code, and give you feedback.

**Comment by vietj** [comment]
good idea

**Comment by giovibal** [comment]
My tests are ok.
My code uses the same pattern of Pump to connect a websocket stream to the event bus.
With version 3.3.0-SNAPSHOT / branch: eventbus-controlflow-work the bug is gone.
As soon as possible, I'll put this configuration under more real scenario (our test env) to check stability.

**Comment by vietj** [comment]
thanks, I've been waiting for such feedback for this before merging

**Comment by giovibal** [comment]
Everyting is ok under normal conditions, our code run for about 4 hours as did with vert.x version 3.1.0.

**Comment by vietj** [comment]
ok thansk for the feedback
