### ISSUE TITLE
remove hazelcast workaround (or at least the comment, that indicate it as a workaround)

### ISSUE THREAD

**Issue by blackgwe** [eclipse/vert.x#1277]
Hi!

Issue https://github.com/hazelcast/hazelcast/issues/5220 had been closed in October, we should upgrade to the latest stable build 3.5.4 (http://hazelcast.org/download/ ) .

see https://github.com/vert-x3/vertx-hazelcast/blame/master/pom.xml#L44

and then we can remove the workaround here:

https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/impl/VertxImpl.java#L431

kind regards
Gabriel

**Comment by tsegismont** [comment]
I just tried @purplefox 's [reproducer](https://github.com/purplefox/hz-bug) with the latest version 3.8.2. The multimap is now empty as expected. I'll go ahead and remove the `ExtendedClusterManager` interface from the `HazelcastClusterManager`. Then I'll deprecate the interface in Vert.x core.
