### ISSUE TITLE
JsonArray.remove(int pos) should return JsonArray or JsonObject instead of their underlying implementations

### ISSUE THREAD

**Issue by Narigo** [eclipse/vert.x#1286]
The current implementation returns / leaks a `java.util.ArrayList<?>` in case of a `JsonArray` or a Map in case of a `JsonObject`. It should check for these implementations and return a JsonArray or JsonObject wrapper.

See https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/json/JsonArray.java#L482

**Comment by cescoffier** [comment]
I've fixed it in https://github.com/eclipse/vert.x/pull/1287.

However, it's an API change, so it can't be integrated in 3.2.1. It should be in 3.3.0.
