### ISSUE TITLE
Worker verticle cannot synchronously wait for EventBus.send even when using additional workpool thread

### ISSUE THREAD

**Issue by mstanescu** [eclipse/vert.x#1289]
The general idea is:
 - execute in an worker verticle
 - instantiate a countdown latch
 - use executeBlocking( { eventbus.send(...., { latch.countdown() } , **false** /* unordered */  )
 - wait for countdown latch.

From my observations the eventbus.send finish execution however nothing happens on the eventbus. The target does not get any message.

I tracked a bit the problem inside EventBus.send and it leads me to HazelcastAsyncMultiMap.get implementation which does an executeBlocking which is ordered with the caller. 
The body of execute blocking in HazelcastAsyncMultiMap.get is never executed.
This is strange however because the eventbus.send is executed by another worker thread than the caller. 

Is this the expected behavior? Seems to me like a problem.

Some code:

https://github.com/mstanescu/vertx-hazelcast/blob/master/src/main/java/io/vertx/spi/cluster/hazelcast/impl/HazelcastAsyncMultiMap.java

You can see the implementation of the awaitResult that i am using here.
https://github.com/mstanescu/thread-test/blob/master/src/main/java/com/qnective/qtalkng/Sync.java

And how i use it here:
https://github.com/mstanescu/thread-test/blob/master/src/main/java/com/qnective/qtalkng/SerializedRequester.java

Sorry but the project is not compileable as a standalone but you can just copy this class. Will notify when i make the project work as a standalone project.

**Comment by purplefox** [comment]
This is expected behaviour - standard verticles or normal worker verticles are single threaded.

Your CounDownLatch is blocking the worker thread, this means the reply from the event bus will never be handled until the CountDownLatch releases, otherwise you'd have two threads executing in the verticle at the same time.

Perhaps you could explain in more detail what you are trying to achieve here? Maybe we can advise a better way of doing it.

**Comment by mstanescu** [comment]
This is not the problem i am explaining. I understand the single thread thing. But i am using an additional thread to execute the send. (with unordered flag).

Please mind the executeBlocking(.../*unordered */) in the steps of my description

So there are 2 worker threads involved here.

**Comment by purplefox** [comment]
It doesn't matter if you are using the ordered flag or not.

The event bus reply handler must be executed in the context of the verticle in order to preserve the threading guarantees, but that can't happen until the countdownlatch is released, which clearly won't ever happen.

**Comment by mstanescu** [comment]
So what alternatives i have to really synchronously wait for an eventbus.send?

Is Context.runOnContext thread safe? Seems not and the documentation does not say so.
 
If not, i think it is an useful mechanism to be able to place events to be executed on the event-queue of another verticle. Cannot use eventbus.send because i cannot block the thread.

**Comment by purplefox** [comment]
If you could step back a bit and explain what you are trying to achieve here I can suggest better ways of doing it :)

**Comment by mstanescu** [comment]
Ok. I have a voip-calls state machine which orchestrates various other services in the system. This part is written (Still by me) in a synchronous way for a previous project. 

The goal is to keep this code synchronous-like. Its easier to read and write and for the scalability requirements i have this should fit the bill.

The code must be able to make a mix of  synchronous calls to:
 - sql database
 - have a dialog ever eventbus with other entities in the cluster
 - have a dialog over http-rest with other servers in the cluster

E.g of a synchronous execution of a request/event in the state machine
 - receive a request
 - request something from another service
 - wait for the answer
 - request something on another backend
 - reply to the request (success / failure)

Order matters and one operation is/might be based on the success of a previous one.

So i have two options now:
 - embrace asynchronicity but this means refactoring the business logic code to look like async code.
 - keep the state machine synchronous and wait for the completion of depending calls 

I took the later but i hit a wall with waiting for Eventbus.send.
Then i embraced vertx-sync. I have a decent experience with it. It could fit thebill however  there are a few drawbacks because of how quasar works
 - one has to add @Suspendable all functions on caller tree. Thats fine but how to do it for standard java library? :) so the whole functional-like things are impossible to do. (Like stream() and so on)
- if one fails the annotation code works in unexpected ways. (i tihnk i filed a problem in vertx-sync-examples that they do not actually execute correctly)

Hope this helps.

**Comment by purplefox** [comment]
One of the main advantages of Vert.x is great scalability because it doesn't block operating system threads. You get this if you just use standard verticles.

Worker verticles are really meant to satisfy an edge case where you have to use a legacy blocking Java library which you can't change. For the best scalability you want to avoid usage of worker verticles unless you really have no other choice.

So... I think if you realy want to reap the benefits of Vert.x you should embrace asynchronicity and refactor your code in that way, otherwise you might ask yourself the question of why are you using Vert.x at all? ;)

Yes, vertx-sync is another possibility - if you are having problems with forEach and the like, perhaps you could post a question on the vertx-sync issues and cc @pron - he might have an answer.

**Comment by mstanescu** [comment]
Yeah , i kind of agree. It is true that i do not need the full scalability potential of the asynchronous code  but this comes with a hefty dev price. I do not need it now but i might need it in the future thus is a nice thing to be able to have the option to do this in the future.

Getting back to the problem. I made my awaitResult work with EventBus.send but but you won't/might not give any blessings :)

In my awaitResult, instead of doing Vertx.getCurrentContext().executeBlocking(....) , i did Vertx.vertx().runOnContext()  which practically created a new instance of Vertx which executed the handler because it had no knowledge of my context so EventBus.send was executed from another thread. 

Since EventBus is thread safe the only thing remaining is if you know by any chance if runOnContext is thread safe?. It eventually translates if NioEventLoop.execute is thread safe.

Or a non-vertx thread pool could do the trick too.

**Comment by pron** [comment]
@mstanescu If I may weigh in, Quasar does let you specify Java library functions as suspendable (either automatically or manually), but it is often not what you want (e.g. it is not a good idea to block stream operations, at least not as they are in Java 8). I can also say that starting with Java 9, Quasar will most probably no longer require any manual designation of methods as suspendable, and the whole thing would be completely transparent.

**Comment by mstanescu** [comment]
@pron The Java 9 thing sounds interesting. Do you have more details on how this will aid quasar to be completely transparent?

**Comment by pron** [comment]
We are working with Oracle on exposing more runtime information about the call-stack that will make this possible.

**Comment by purplefox** [comment]
@mstanescu Another thing I'd recommend looking at is vertx-rx

**Comment by purplefox** [comment]
I'd recommend strongly against creating a new Vert.x with:

Vertx.vertx()

This is a heavyweight operation. It might be better to just create a new thread or use your own thread pool. But either way it's really a hack.

**Comment by mstanescu** [comment]
Thank you for all the inputs. I know its a hack but at least on the short term it should unblock other developers so i can have an asynchronous refactoring time.

As a personal suggestion. It would be nice to know which functions are thread safe and which are not (in the javadoc of vertx  api). Some people can get creative :) and at least people would know when they are hacking. Also makes a clear contract to the implementations of the API.  I would do this myself but i don't think its a good idea to write these kind of things by reverse engineering the thing.

**Comment by mstanescu** [comment]
While i accept your explanation , IMO Vertx still not behave at least as documented and as expected.

Also i think Vertx should support this kind of waiting of EventBus send in worker verticles in a native way. It is not so obvious and the guide documentation some things will not work.

I just followed these things:
http://vertx.io/docs/vertx-core/java/#blocking_code

     vertx.executeBlocking(future -> {
       // Call some blocking API that takes a significant amount of time to return
       String result = someAPI.blockingMethod("hello");
       future.complete(result);
     }, res -> {
       System.out.println("The result is: " + res.result());
     });

One does not expect that if i use the above code in a worker verticle and i substitute someAPI and the vertx EventBus and blocking method with send then everything freezes.

**Comment by purplefox** [comment]
Hopefully the issue here would be self evident given the Vert.x threading model.

http://vertx.io/docs/vertx-core/java/#worker_verticles

"Worker verticle instances are never executed concurrently by Vert.x by more than one thread, but can executed by different threads at different times."

So if you're blocking the thread yourself, then your verticle code can't be executed until the blocked thread exits, otherwise it would break that guarantee.

Furthermore, the example given in http://vertx.io/docs/vertx-core/java/#blocking_code shows a 3rd party blocking API being called. In your code, you are not calling a 3rd party blocking API you are calling a non blocking Vert.x API so it's quite a different situation.

**Comment by vietj** [comment]
there is this article I wrote too about event loop that explain the model https://github.com/vietj/vertx-materials/blob/master/src/main/asciidoc/Demystifying_the_event_loop.adoc

**Comment by purplefox** [comment]
@mstanescu Another workaround for you that's better than creating a new Vertx each time would be to use a multi-threaded worker verticle. Still a bit hacky, but a lesser of two evils I'd say ;)

**Comment by mstanescu** [comment]
I was not creating a Vertx every time. I moved that to some static member
but its not obvious to me if the runOnContext is thread safe (seems to go
into an NettyEventLoop which that is also not very clear if its thread
safe).

 Otherwise yes, your suggestion or just use a thread pool from java.
