### ISSUE TITLE
Add HAProxyMessageDecoder option to HttpServerOptions

### ISSUE THREAD

**Issue by cmolocznik** [eclipse/vert.x#1293]
WebSockets behind AWS Elastic Load Balancers will lose Client IP information since TCP load-balancing must be used instead of Layer 7 where it injects a HTTP header such as 'X-Forwarded-For'. In this environment and other similar load balanced environments the Proxy Protocol is used which was designed by HAProxy. Amazon AWS ELB supports it and is the recommended way of dealing with load-balancing WebSockets while retaining the Client IP and allowing the WebSocket connection to remain open indefinitely. Netty implements the decoder and is named HAProxyMessageDecoder. The dependency is netty-codec-haproxy. It would be ideal if HttpServerImpl could support this Decoder when setting up Netty internally as part of the ChannelInitializer. Perhaps it could be added as a flag on HttpServerOptions (i.e. boolean proxyProtocol). Essentially this option opens up the world of scalable load-balanced WebSocket servers with the simplicity of running just vert.x based HTTP server directly behind a cluster of load-balancers such as AWS ELB.

**Comment by sdaclin** [comment]
Hello I'm sharing the exact same need, and I wonder why did you close the ticket ?
Did you find a way out ?

**Comment by vietj** [comment]
we should find a way to acheive this

**Comment by sdaclin** [comment]
Hello @vietj, here is a possible implementation : https://github.com/sdaclin/vert.x/commit/621efe999738f2611119c2e3a03c20fada74f58f
WDYT ?
