### ISSUE TITLE
Use toArray(T[0]) where possible

### ISSUE THREAD

**Issue by aesteve** [eclipse/vert.x#1294]
See : http://shipilev.net/blog/2016/arrays-wisdom-ancients/

Sounds like an optimization we could have for free.

I took a look and can send a PR that's a very limited change (in core, at least). But @vietj pointed out we should have some microbenchmarks to rely on before doing such kind of things.

How should we do it ? 

Proposal : 
- create a repo within the vertx organization holding benchmarks
- initializing this repo with the benchmarking structure (using : [jmh](http://openjdk.java.net/projects/code-tools/jmh/)). So that layout is good to go
- creating a very simple "sample" benchmark people can use as a pattern on to add new bechmarks
- let the community add benchmarks through PRs

Maybe @purplefox has thoughts (or even already-tested benchmarks) to share ?

What do you guys think ?

**Comment by vietj** [comment]
it looks relevant but is not identified as an issue for now
