### ISSUE TITLE
io.vertx.core.Launcher doesn't launch launcher class

### ISSUE THREAD

**Issue by pazderak** [eclipse/vert.x#1296]
I tried to run gradle-verticles example. I followed a README, but after build and run, no verticle listens on the port.

**Comment by davidafsilva** [comment]
Can you detail a bit more?
Quickly tested the [gradle-verticle](https://github.com/vert-x3/vertx-examples/tree/master/gradle-verticles/gradle-verticle) and its working fine in here.

**Comment by pazderak** [comment]
Well, first I tried to follow automatic source redeploy example from blog: [http://vertx.io/blog/automatic-redeployment-in-eclipse-ide/](url).It didn't work, probably because a class in sample uses `public static void main(string[] args)` approach.
Then I moved to the gradle-examples - you are right it works, because a main class doesn't use static main approach, but normal `start` method override. But in the log it shows a message:

> WARNING: You're already on a Vert.x context, are you sure you want to create a new Vertx instance? 
> 

Is it this behavior intentional, or is it a bug?

**Comment by davidafsilva** [comment]
Afaik, when you want to use your own main class, you need specify it via `--launcher-class`. Nevertheless, the main class on which you boot your application remains the vert.x Launcher class.
Did you set it up correctly?

I'm not really familiar with eclipse anymore, haven't used it in a couple of years, but i do use redeploy with Intellij once in a while. I use it with maven though.
e.g.:
**main-class**: `io.vertx.core.Launcher`
**args**: `run --redeploy="src/**/*.java" --launcher-class=path.to.your.main.Class --on-redeploy="mvn compile"`

**Comment by cescoffier** [comment]
Are you trying to start:

1. your own `main` class with it's own `public static void main(String[] args)` method
2. a verticle that you would launch using the `io.vertx.core.Launcher` class

In the first case, you don't need the `Launcher` class, except in the case of the redeploy where it would be something like:

```
java -cp you-jar.jar io.vertx.core.Launcher --redeploy="src/**/*.java" --launcher-class=your-main-class --on-redeploy=...
```

In the second case, you don't need to create a main class, as you use one provided by Vert.x (`io.vertx.core.Launcher`).
