### ISSUE TITLE
Rxfied Buffer.buffer(byte[] bytes) is not available

### ISSUE THREAD

**Issue by EmadAlblueshi** [eclipse/vert.x#1301]
I'm trying to user Rxfied Buffer.buffer(byte[] bytes) but it seems not available

Any alternative solution !?

**Comment by vietj** [comment]
you can use an intermediate buffer : `Buffer buffer = new Buffer(io.vertx.core.buffer.Buffer.buffer(bytes))`

**Comment by EmadAlblueshi** [comment]
It works thanks @vietj
