### ISSUE TITLE
ConcurrentModificationException from ConnectionManager.close

### ISSUE THREAD

**Issue by laurionb** [eclipse/vert.x#1307]
I got this exception from `HttpClient.close`:

> java.util.ConcurrentModificationException
>  at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
>  at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
>  at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
>  at java.util.HashSet.<init>(HashSet.java:119)
>  at io.vertx.core.http.impl.ConnectionManager$ConnQueue.closeAllConnections(ConnectionManager.java:143)
>  at io.vertx.core.http.impl.ConnectionManager.close(ConnectionManager.java:78)
>  at io.vertx.core.http.impl.HttpClientImpl.close(HttpClientImpl.java:640)

I'm guessing the problem is with the synchronization on the methods of the inner `ConnectionQueue` class that access the `allConnections` member:
-  `ConnectionManager::ConnectionQueue::connectionClosed` and `ConnectionManager::ConnectionQueue::closeAllConnections` both synchronize on **`this`** (i.e. `ConnectionManager.ConnectionQueue.this`)
-  `ConnectionManager::ConnectionQueue::createNewConnection` synchronizes on **_`ConnectionManager.this`_**

See: [https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/ConnectionManager.java#L174](url)

**Comment by vietj** [comment]
closing this as we have a new pool impl in 3.5.1
