### ISSUE TITLE
vertx start failes silently if a verticle doesn't exist

### ISSUE THREAD

**Issue by Stwissel** [eclipse/vert.x#1310]
When using the vertx command line loader you can start a verticle:

```
   vertx run phantom
```

and you will get:

```
    java.lang.ClassNotFoundException: phantom
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
```

as expected. But when you start

```
  vertx start phantom
```

you get:

```
   Starting vert.x application...
   7cbd4867-036f-4eeb-bdb1-010b491abe65
```

Which doesn't indicate that phantom doesn't exist

**Comment by peterhendriks** [comment]
We have similar problems with the "start" command. Ideally, we would like the command to wait for the completion of the "start" lifecycle of the main verticle. When the main verticle could not be found, or did not start successful, we would like the start command to fail and show the corresponding error.

**Comment by vietj** [comment]
@cescoffier what's your opinion on this ?

**Comment by cescoffier** [comment]
It's the expected output. It starts the process as a background service, whether it fails or not is hard to know. If the application crashes, `vertx list` would not list it (that's one way). The "start" command has no knowledge about the launched application.

If you want the output, use: `vertx start phantom --redirect-output`.

When health check would be integrated, we can imagine a "readiness" check to verify whether or not the application is ready, and if it does not become ready in a specific amount of time, declare it as failed.
