### ISSUE TITLE
TCPSSLOptions: Some default values missing in Java doc

### ISSUE THREAD

**Issue by dan-lind** [eclipse/vert.x#1313]
I think these values was fetched from SocketDefaults earlier, which has now been removed

https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/net/TCPSSLOptions.java

I guess it is really just the comments that need to be updated to include the default value

```
/**
   * The default value of TCP keep alive
   */
  public static final boolean DEFAULT_TCP_KEEP_ALIVE = false;

  /**
   * The default value of SO_linger
   */
  public static final int DEFAULT_SO_LINGER = -1;
```

**Comment by harisankars** [comment]
I will make this change. Seems a simple one that will help me to start contributing.

**Comment by harisankars** [comment]
I made the changes and created a pull request. Please check.

**Comment by dan-lind** [comment]
Looks good to me. Someone with the proper authorization has to do the actual merge though.

**Comment by dan-lind** [comment]
Fixed by https://github.com/eclipse/vert.x/pull/1362
