### ISSUE TITLE
Improve documentation of getClusterWideMap

### ISSUE THREAD

**Issue by mstanescu** [eclipse/vert.x#1320]
There are many aspects when going distributed which are missing from the documentation

"Get the cluster wide map with the specified name. The map is accessible to all nodes in the cluster and data put into the map from any node is visible to any other node."

More specific topics:
 - how much HA is in there (is the data replicated?)
 - are there situations when data can be lost?
 - how about performance?
 - how about split brain? How about concurrent updates in a split brain situation? How about merging of the split brain?

------

Incorrect documentation for put with a TTL.

http://vertx.io/docs/apidocs/io/vertx/core/shareddata/AsyncMap.html#put-K-V-long-io.vertx.core.Handler-

It seems that the parameter is not a timeout but a TTL which does not match the comment below. 

"Like put(K, V, io.vertx.core.Handler<io.vertx.core.AsyncResult<java.lang.Void>>) but specifying a timeout. If the value cannot be put within the timeout a failure will be passed to the handler"

I assume the word timeout does not refer to the TTL in which case i assume there is some internal timeout to consider although not mentioned for other methods which take the completionHandler as parameter.

**Comment by cescoffier** [comment]
About the first part it depends on the cluster manager implementation you are using. If we take the Hazelcast one, you should refer to the Hazelcast manual. Clustered map are baked by a Hazelcast async map so:

* Backup and replication: http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#map
* split-brain: http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#network-partitioning-split-brain-syndrome

However this is for Hazelcast, the behavior may be (is) different with the other cluster manager. 

I will add a note to the documentation to explain this.

About the second point, you are absolutely right, it's a mistake. It's a time to live, not a timeout. I'm modifying the doc. In both methods (put and putIfAbsent), the entry will expire and get evicted after the given ttl.
