### ISSUE TITLE
Reuse existing connections for the HttpClient

### ISSUE THREAD

**Issue by vmaurin** [eclipse/vert.x#1323]
In the ConnectionManager used by the HttpClientImpl, it is only polling the first connection and if it is closed, creates a new one. Should it try to empty the queue first ?

https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/ConnectionManager.java#L97

**Comment by vietj** [comment]
valid remark :-)

**Comment by vietj** [comment]
in practice this rarely happens because when a connection is closed it is removed from the pool : see `Http1xPool#connectionClosed` and `Http2Pool#discard` methods
