### ISSUE TITLE
DatagramSocket.close() does't decrease metrics counter.

### ISSUE THREAD

**Issue by alatushkin** [eclipse/vert.x#1326]
`DatagramSocket.close(handler)` call `metrics.close()`
But  `DatagramSocket.close()`  ( --> `ConnectionBase.close()`) - does'not
This cause "vertx.datagram.sockets" (and i think other socket counting metrics) to show wrong data

**Comment by vietj** [comment]
would you be kind enough to contribute a test to show this failure ?

**Comment by alatushkin** [comment]
@vietj For sure [junit gist showing bug](https://gist.github.com/alatushkin/afb81146c03e0876ba10#file-datagramsocketclearmetricsissuetest-java)

**Comment by vietj** [comment]
the junit gist showing bug pass with current master

**Comment by alatushkin** [comment]
Finally :)
Dont forget about regression

**Comment by vietj** [comment]
I believe it was actually fixed long time ago as side effects of improvements.
