### ISSUE TITLE
Direct Scala support needs revival

### ISSUE THREAD

**Issue by Storycrafter** [eclipse/vert.x#1327]
Support for Scala as a first class citizen has gotten left behind in recent times.  It needs a champion (or four) to help it regain entry back to full citizenship.

**Comment by Storycrafter** [comment]
I'm throwing my hat in the ring for this, but can't commit any time until later next week (March 14 onwards)

**Comment by vietj** [comment]
please have a look here https://github.com/vert-x3/vertx-lang-scala , there are no contributions for a while.

**Comment by vietj** [comment]
closing this
