### ISSUE TITLE
Config should not be printed to log when JSON cannot be parsed

### ISSUE THREAD

**Issue by dan-lind** [eclipse/vert.x#1328]
Currently the entire config file (passed to -conf) will be printed to the log if it cannot be correctly parsed as a JSON object on vertx startup. Since the config potentially can contain sensitive information that you don't want printed in a log this is not a good default. 

I suggest vertx don't print the content of the config, rather just an error message telling that the config cannot be parsed.

**Comment by cescoffier** [comment]
Agreed. Gonna have a look

**Comment by dan-lind** [comment]
@cescoffier Did you have time to look at this yet? If not, would you like me to submit a PR?

**Comment by vietj** [comment]
I beleive there is an open PR for that, so it should be ok

**Comment by cescoffier** [comment]
@vietj so you saw a comment on this too. I did, and then can't find it. 

So to answer to the lost comment, yes it has been handled.

**Comment by dan-lind** [comment]
It was my comment. I asked if you wanted me to submit a PR, then I realised that there was one already, so I removed my comment.
