### ISSUE TITLE
Get the number of available threads in the worker pool from the vertx object

### ISSUE THREAD

**Issue by poiuytrez** [eclipse/vert.x#1332]
I would be nice to fine tune vert.x to know the number of available threads in the worker pool. I would me helpful for me to understand a bottleneck in a system.

https://groups.google.com/forum/#!searchin/vertx/poiuytrez/vertx/DgV9S2k_r9I/pMd2lCVlAwAJ

**Comment by cescoffier** [comment]
I guess this is part of the metrics improvements we are discussing at the moment (https://github.com/vert-x3/issues/issues/83). Shouldn't is be provided by the metric support not not by the vertx object ?
