### ISSUE TITLE
Get the number of execute blocking code waiting for a worker thread to be available

### ISSUE THREAD

**Issue by poiuytrez** [eclipse/vert.x#1333]
I would help me to identify a bottleneck.

**Comment by cescoffier** [comment]
I guess it should be done by the metric support (core implements the SPI). We want to improve the Thread reporting (https://github.com/vert-x3/issues/issues/83). Could you add your requirement on this issue.

**Comment by vietj** [comment]
we could have an SPI callback when a tasks enqueued / dequeued from a worker pool on the VertxMetrics interface

**Comment by cescoffier** [comment]
Yes, or just extend the executor service to have methods to know:

* the size of the waiting queue
* the number of idle/running/waiting threads
* whether or not some tasks are "stuck" (using a timeout)

It would be very close to the ManagedExecutionService (https://github.com/wisdom-framework/wisdom/blob/master/core/wisdom-api/src/main/java/org/wisdom/api/concurrent/ManagedExecutorService.java)

**Comment by vietj** [comment]
imho having an SPI callback would allow

- the metrics implementation to provide more accurate information in particular it can track the execute time of a task and report it (and report max / percentiles of execution time in addition of mean execution)
- provide a default implementation inlined to no-operation when jitted

**Comment by cescoffier** [comment]
Yes, but it will lack all the other information that are required for "production" monitoring. I'm not saying we should add them, but I think extending the executor service provide better monitoring support.

**Comment by vietj** [comment]
For this this case we should rather provide an SPI for creating executor service used by Vert.x for blocking tasks. The default executor services are plain `Executors.newFixedThreadPool` calls.

**Comment by cescoffier** [comment]
Well, this would not allow the metric provider to retrieve the data.

**Comment by vietj** [comment]
The code running vertx could set this with an implementation before creating vertx and access the implementation.

**Comment by cescoffier** [comment]
It is important to allow the metric provider to retrieve and expose the details about threads (we had many many questions about this). So far we can't because we don't expose any method (plain executor service are not really monitorable). 

The callback approach you propose just know what's come in and out, but has no idea about the status on the threads and the state of available / busy threads. So you will get events, but I don't see what you can do with these.

**Comment by vietj** [comment]
The thread is a fixed size thread pool. When you know a task is starting its execution, you can update the number of available / busy threads.

**Comment by cescoffier** [comment]
So sounds rather brittle, as we probably will forget about that and the metric provider is going to get "nosuchmethod" at runtime. It also bound the metric provider to a specific implementation (which is the opposite of the SPI idea)

**Comment by vietj** [comment]
We should prototype it in a branch and see what we can get from it to have a more precise idea.

**Comment by cescoffier** [comment]
Computing against the fixed size does not get you what's in the waiting queue from what's being executed. (or you need 3 callbacks, and here you are touching a limit of the plain executor service).

**Comment by vietj** [comment]
yes I meant 3 callbacks : schedule / start / end

**Comment by purplefox** [comment]
"whether or not some tasks are "stuck" (using a timeout)" is already available using the blocked thread checker.

I'd be very careful about adding instrumentation at this level as you can easily kill performance.

**Comment by vietj** [comment]
@purplefox agreeing with you. the default impl would do nothing (like the current metrics) . At the same time we are talking of worker pool that usually block and the overhead of the SPI (not the default noop one) compared to the blocking time of the task would be neglectable.

**Comment by cescoffier** [comment]
It would reuse the BlockerChecker we already have. There is no instrumentation, it's basically tell you what has been reported by the BlockerChecker (if any). I don't see a performance bottleneck here.

**Comment by cescoffier** [comment]
"yes I meant 3 callbacks : schedule / start / end"

That would not be supported by plain executor services. You know when something is "submitted" (schedule). I'm not even sure there is a way to know when it has been executed.

**Comment by purplefox** [comment]
When something is executed/submitted is known in the context (blocked thread checker code).

I suspect what you really want to do is abstract out / make available that information. If you think about it all this can be done on the context in a transparent way without having to know anything about thread pools.

**Comment by purplefox** [comment]
E.g.
context a has queue of size 1000, and average execution time of blah, and it's an event loop context
context b has queue of size 1000, and average execution time of blah, and it's a worker context
etc

**Comment by cescoffier** [comment]
I will have to see if everything can be done in the Context. For example, can we have the waiting queue size? The highest number of thread that has been used "simultaneously" ? The number of tasks that are currently executed (not waiting) ? This is the kind of data we often need in production. 

Obviously if it can be done on the Context, it's better to do it there.

**Comment by purplefox** [comment]
Yes I think all this information is available in the context.

You know when an event in "submitted" (this is when context execute/executeBlocking is called). So you can easily keep a counter representing queue size.

You know when it starts to be processed and ends being processed (see wrapTask and the current blocked thread checker code).

You also know the thread, so you can aggregate all this information on a per thread basis if you like.

**Comment by cescoffier** [comment]
Perfect, I will have a look to implement it directly in ContextImpl.

**Comment by bdesbiolles** [comment]
:+1:  also interested by the functionality.

**Comment by vietj** [comment]
available now via the pool metrics
