### ISSUE TITLE
Improve HttpServerMetrics SPI to include url pattern

### ISSUE THREAD

**Issue by pasfilip** [eclipse/vert.x#1342]
Currently the http server metrics passes the received url to the metrics provider implementation.

R requestBegin(S socketMetric, HttpServerRequest request);

However for monitoring purposes this leads to an explosion of monitoring statistics.

It would be interesting if vertx could pass the associated router that matches the url requested so the
url pattern can be used for monitoring purposes.

Suppose I have a router defined that matches urls of the type:
/persons/:personId

Where I visualize my monitoring metrics I don't want to see:

/persons/1 GET total 10 requests avg 5ms
/persons/2 GET total 5 requests avg 5ms
/persons/3 GET total 6 requests avg 5ms
/persons/4 GET total 2 requests avg 5ms

This will generate too many lines in monitoring tools.

I would like to be able to get access to the path so I can get something like this:

/persons/:personId GET total 23 requests avg 5ms.

In order to make this possible the matching route needs to be passed to the beginRequest method.

**Comment by tsegismont** [comment]
Closing as it's possible to [aggregate http server metrics](http://vertx.io/docs/vertx-dropwizard-metrics/java/#http-server-metrics)
