### ISSUE TITLE
Add "computeIf*" methods to LocalMap interface

### ISSUE THREAD

**Issue by sfitts** [eclipse/vert.x#1348]
These are very useful additions to the Java Map interface which it would be nice to see added to LocalMap (they greatly simplify concurrent population of the map).

**Comment by cescoffier** [comment]
If we add this method, we should add:

* `compute`
* computeIfAbstent`
* `computeIfPresent`

(following the spec from https://docs.oracle.com/javase/8/docs/api/java/util/Map.html).

Last time I used a `LocalMap`, I wondered why it didn't implement the `Map` interface. I need to check the possibility to implement all `Map` methods and so it would contain the `compute` methods.

**Comment by cescoffier** [comment]
I've opened a PR (https://github.com/eclipse/vert.x/pull/1354) extending `LocalMap` to implement `Map`.

**Comment by sfitts** [comment]
Thanks.
