### ISSUE TITLE
Clustered deserialization of a JsonObject within a JsonArray ends up a LinkedHashMap

### ISSUE THREAD

**Issue by shaunrader** [eclipse/vert.x#1349]
A tweak to the `JsonArrayTest.testClusterSerializable()` [seen here](https://github.com/eclipse/vert.x/commit/8885bd695d87453f1c3bb1e80bdf45f1500dfd56) reproduces the issue. Here is an example:

```
    JsonObject obj = new JsonObject().put("quux", "wibble");
    jsonArray.add("foo").add(123).add(obj);
    Buffer buff = Buffer.buffer();
    jsonArray.writeToBuffer(buff);
    JsonArray deserialized = new JsonArray();
    deserialized.readFromBuffer(0, buff);

    // this works
    JsonObject o1 = deserialized.getJsonObject(2);

    // this doesn't work and this cast exception occurs intermittently only when clustered
    JsonObject o2 = (JsonObject)deserialized.getList().get(2);

```

This was an issue for us because we frequently use the underlying `List` instead of the `JsonArray` and getting a `JsonObject` from that list would always work in our non-clustered dev environment. After clustering we experienced some intermittent issues where we would get random `java.util.LinkedHashMap cannot be cast to io.vertx.core.json.JsonObject` exceptions. 

You can work around it by using `JsonArray.getJsonObject` or converting the `LinkedHashMap` to a `JsonObject` but it was definitely hard to track down since it didn't happen in our non-clustered environment.

**Comment by tsegismont** [comment]
This is not a bug. JsonObject _get_ methods transform values of the underlying map. As explained in the Javadoc:

```java
  /**
   * Get the underlying {@code Map} as is.
   *
   * This map may contain values that are not the types returned by the {@code JsonObject}.
   *
   * @return the underlying Map.
   */
  public Map<String, Object> getMap() {
    return map;
  }
```
