### ISSUE TITLE
Deadlock between ClientConnection and HttpClientRequestImpl

### ISSUE THREAD

**Issue by kevlarC** [eclipse/vert.x#1355]
Hi,
After a week attached to our load balancer which does a simple poll to one of our rest end points (we have no other traffic right now) all 4 machines (4 instances) end up in deadlock and had to be "kill -9"ed , which  in theory brought down our whole DC. Since we are in testing stages this was not a big problem but I imagine to most it would be a bit hair raising.

From my simple analysis it seems that the Exception handling and the request response seem to be locking on the HttpClientRequestImpl->handleException->getlock -> (this)  and HttpClientRequestImpl->connect(this)->lamda->(this)

Also looking at the traffic it seems our load-balancer (a cisco content switch with ACE module) sends a request gets the response then resets the connection. I believe this behaviour is causing the deadlock, since this is important for us to go live I will try create a test to replicate this behaviour.

This was running 3.2.0 code (Ive seen no fixes in 3.2.1) and using JVM 1.8_74 on RHEL 6.5 

Here is the jstack information. 
<code>
Debugger attached successfully.
Server compiler detected.
JVM version is 25.74-b02
Deadlock Detection:
# Found one Java-level deadlock:

"vert.x-eventloop-thread-0":
  waiting to lock Monitor@0x0000000081060ac8 (Object@0x0000000081060ac8, a io/vertx/core/http/impl/ClientConnection),
  which is held by "vert.x-eventloop-thread-7"
"vert.x-eventloop-thread-7":
  waiting to lock Monitor@0x00007f6dac2a5e98 (Object@0x0000000081060bf0, a io/vertx/core/http/impl/HttpClientRequestImpl),
  which is held by the"vert.x-eventloop-thread-0"

Found a total of 1 deadlock.

Thread 19522: (state = BLOCKED)
- io.vertx.core.net.impl.ConnectionBase.writeToChannel(java.lang.Object) @bci=0, line=113 (Compiled frame)
- io.vertx.core.http.impl.HttpClientRequestImpl.writeHeadWithContent(io.netty.buffer.ByteBuf, boolean) @bci=24, line=678 (Compiled frame)
- io.vertx.core.http.impl.HttpClientRequestImpl.connected(io.vertx.core.http.impl.ClientConnection) @bci=82, line=629 (Compiled frame)
- io.vertx.core.http.impl.HttpClientRequestImpl.lambda$connect$82(io.vertx.core.http.impl.ClientConnection) @bci=27, line=593 (Compiled frame)
- io.vertx.core.http.impl.HttpClientRequestImpl$$Lambda$190.handle(java.lang.Object) @bci=8 (Compiled frame)
- io.vertx.core.http.impl.ConnectionManager$ConnQueue.lambda$responseEnded$66(io.vertx.core.http.impl.ConnectionManager$Waiter, io.vertx.core.http.impl.ClientConnection, java.lang.Void) @bci=5, line=129 (Compiled frame)
- io.vertx.core.http.impl.ConnectionManager$ConnQueue$$Lambda$233.handle(java.lang.Object) @bci=12 (Compiled frame)
- io.vertx.core.impl.ContextImpl.lambda$wrapTask$16(boolean, io.vertx.core.impl.ContextTask, io.vertx.core.Handler) @bci=177, line=335 (Compiled frame)
- io.vertx.core.impl.ContextImpl$$Lambda$24.run() @bci=16 (Compiled frame)
- io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(long) @bci=26, line=358 (Compiled frame)
- io.netty.channel.nio.NioEventLoop.run() @bci=106, line=357 (Compiled frame)
- io.netty.util.concurrent.SingleThreadEventExecutor$2.run() @bci=13, line=112 (Interpreted frame)
- java.lang.Thread.run() @bci=11, line=745 (Interpreted frame)

Thread 19465: (state = BLOCKED)
- io.vertx.core.http.impl.HttpClientRequestImpl.getLock() @bci=15, line=426 (Compiled frame)
- io.vertx.core.http.impl.HttpClientRequestImpl.handleException(java.lang.Throwable) @bci=1, line=381 (Compiled frame)
- io.vertx.core.http.impl.ClientConnection.handleException(java.lang.Throwable) @bci=17, line=324 (Compiled frame)
- io.vertx.core.net.impl.VertxHandler.lambda$exceptionCaught$17(io.netty.channel.Channel, io.vertx.core.net.impl.ConnectionBase, java.lang.Throwable) @bci=22, line=86 (Compiled frame)
- io.vertx.core.net.impl.VertxHandler$$Lambda$225.run() @bci=12 (Compiled frame)
- io.vertx.core.impl.ContextImpl.lambda$wrapTask$16(boolean, io.vertx.core.impl.ContextTask, io.vertx.core.Handler) @bci=167, line=333 (Compiled frame)
- io.vertx.core.impl.ContextImpl$$Lambda$24.run() @bci=16 (Compiled frame)
- io.vertx.core.impl.ContextImpl.executeFromIO(io.vertx.core.impl.ContextTask) @bci=17, line=225 (Compiled frame)
- io.vertx.core.net.impl.VertxHandler.exceptionCaught(io.netty.channel.ChannelHandlerContext, java.lang.Throwable) @bci=38, line=79 (Compiled frame)
- io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(java.lang.Throwable) @bci=6, line=256 (Compiled frame)
- io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(java.lang.Throwable) @bci=35, line=234 (Compiled frame)
- io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(io.netty.channel.ChannelHandlerContext, java.lang.Throwable) @bci=2, line=131 (Compiled frame)
- io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(java.lang.Throwable) @bci=6, line=256 (Compiled frame)
- io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(java.lang.Throwable) @bci=35, line=234 (Compiled frame)
- io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(io.netty.channel.ChannelHandlerContext, java.lang.Throwable) @bci=2, line=131 (Compiled frame)
- io.netty.channel.CombinedChannelDuplexHandler.exceptionCaught(io.netty.channel.ChannelHandlerContext, java.lang.Throwable) @bci=6, line=137 (Compiled frame)
- io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(java.lang.Throwable) @bci=6, line=256 (Compiled frame)
- io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(java.lang.Throwable) @bci=35, line=234 (Compiled frame)
- io.netty.handler.ssl.SslHandler.exceptionCaught(io.netty.channel.ChannelHandlerContext, java.lang.Throwable) @bci=62, line=729 (Compiled frame)
- io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(java.lang.Throwable) @bci=6, line=256 (Compiled frame)
- io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(java.lang.Throwable) @bci=35, line=234 (Compiled frame)
- io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(java.lang.Throwable) @bci=5, line=834 (Compiled frame)
- io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.handleReadException(io.netty.channel.ChannelPipeline, io.netty.buffer.ByteBuf, java.lang.Throwable, boolean) @bci=44, line=87 (Compiled frame)
- io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read() @bci=305, line=162 (Compiled frame)
- io.netty.channel.nio.NioEventLoop.processSelectedKey(java.nio.channels.SelectionKey, io.netty.channel.nio.AbstractNioChannel) @bci=42, line=511 (Compiled frame)
- io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(java.nio.channels.SelectionKey[]) @bci=37, line=468 (Compiled frame)
- io.netty.channel.nio.NioEventLoop.processSelectedKeys() @bci=15, line=382 (Compiled frame)
- io.netty.channel.nio.NioEventLoop.run() @bci=84, line=354 (Compiled frame)
- io.netty.util.concurrent.SingleThreadEventExecutor$2.run() @bci=13, line=112 (Interpreted frame)
- java.lang.Thread.run() @bci=11, line=745 (Interpreted frame)
  <code>

**Comment by vietj** [comment]
are you sharing the same HttpClient between several contexts ?

**Comment by kevlarC** [comment]
We are not intentionally using the same client between contexts but were are using using pooled clients set at 5.

**Comment by vietj** [comment]
ok, looking forward for the reproducer

**Comment by kevlarC** [comment]
our json config for the client pool is set to:
"http":{
    "keepAlive": true,
    "pipelining": true,
    "tcpKeepAlive": true,
    "maxPoolSize": 5,
    "connectTimeout_ms": 200
  }

**Comment by kevlarC** [comment]
FYI  the load-balancer is a ACE4710

**Comment by kevlarC** [comment]
It seems that another team were load testing against us and we an event loop queue length of 270 items and q response time around 20ms. Ill see what else I can gleam from our production logs.

**Comment by kevlarC** [comment]
I believe this is related to https://github.com/eclipse/vert.x/issues/1247

**Comment by purplefox** [comment]
If the Vert.x threading model is respected, this kind of thing should be impossible. Would be great to see a reproducer to verify if that is the case.

**Comment by vietj** [comment]
I tried to write one several times but I could not get something reliable.

**Comment by kevlarC** [comment]
Hi after a longer investigation we have found out what the issue is.

There was a timeout using rx-java without a scheduler specified hence it came back on an **event thread **... wait there is still a problem here.

It seems the RxHelper.schedulerHook which plugs into the rx-java is able to place what should come back on the correct thread on any 8 (4 cores) event threads. **I feel this is very dangerous** and this ability should be removed altogether. 

It may be more prudent to fail fast when a scheduler ( compute or io ) is not supplied (the trampoline scheduler should be fine). I.e. throw an exception instead of maybe sometimes causing a deadlock.

Im not sure if the fix that Julian helped me put into the scheduler would fix this at the rxJava plugin level though.
