### ISSUE TITLE
Support HttpClient access to https via proxy

### ISSUE THREAD

**Issue by alexlehm** [eclipse/vert.x#1361]
(please note that this description applies to HTTP 1.0/1.1, I am not sure how proxies will work with HTTP2)

When running applications in a network that does not have direct internet access but have e.g. a squid proxy, it is currently not possible to access https urls, since that requires a CONNECT tunnel request to the proxy, upgradeToSsl and then a http request to the origin server on the NetSocket.

It is also necessary to enable Proxy authentication for the CONNECT request since the proxy might require that, which is a different account/password than authentication on the origin site.

the section explaining the CONNECT method, but that is a bit brief: https://tools.ietf.org/html/rfc7231#section-4.3.6

an example request flow is the following:

client connects to proxy.example.com:3128
`CONNECT www.example.org:443 HTTP/1.1`
`Host: www.example.org:443`

server replies with
`HTTP/1.0 200 Connection established`

client and server do ssl upgrade
client sends on ssl netsocket
`GET / HTTP/1.1`
`Host: www.example.org`
`Connection: close`

server replies with http response

**Comment by alexlehm** [comment]
I have started implementing the proxy functionality based on the netty proxy handler, this makes the implementation very simple.

https://github.com/alexlehm/vert.x/tree/issues/%231361-https-proxy

It is currently implemented for HTTP/1.1 only, we will see how it is possible to implement it for HTTP/2

Currently the config options are available and the code works when I test it with a local squid, I will write a few tests including a local connect proxy next.

**Comment by vietj** [comment]
we need to handle the following case:

doing HTTP/2 on an HTTP/1.1 CONNECT
doing HTTP/1 and/or HTTP/2 on an HTTP/2 CONNECT

I think the later might be a bit more complex to do as the Handler won't be reusable

**Comment by pmlopes** [comment]
Maybe since you're at it, you could handle both issues, since they are related?

**Comment by alexlehm** [comment]
added a first version of a unit test with a simple ConnectProxy implementation

**Comment by alexlehm** [comment]
After reading a bit about HTTP/2 (and watched the hangout by Julien), I think connect proxy with HTTP/1.x is usable for HTTP/2 without any change, the SSL connect will work and then everything goes through the SSL tunnel anyway. So its probably sufficient to support adding the ssl proxy handler to the pipeline for HTTP/2

**Comment by vietj** [comment]
I'm looking at the PR.

shouldn't we resolve the proxy address in case it's an hostname ?

**Comment by alexlehm** [comment]
You are right, that should be done async, I assumed that the hostname is resolved when it is used by netty, but its done when creating the object.

**Comment by vietj** [comment]
I've done some work on the branch (in my repo) to support HTTP/2 https://github.com/vietj/vert.x/tree/issues/%231361-https-proxy

**Comment by vietj** [comment]
we need to clarify the DNS resolution

**Comment by alexlehm** [comment]
I have changed the proxy channel code to use a unresolved SocketAddress and resolve the proxy address, I will commit that this evening since it is missing a unit test for now
my current commit is here based on the branch from Julien https://github.com/alexlehm/vert.x/tree/julien%231361

**Comment by alexlehm** [comment]
Added javadoc for the setProxyXXX methods in the HttpClientOptions and added a section in the http.adoc docs. No unit test for the non-resolved address since there is apparently an issue in the netty code that breaks that, will write a bug in netty for that.

**Comment by vietj** [comment]
nice work Alex, will review that once you raise the PR

**Comment by alexlehm** [comment]
renamed the branch to issues/#1361-new, will create the pr when the CI build checks out

**Comment by alexlehm** [comment]
https://github.com/eclipse/vert.x/pull/1405

**Comment by alexlehm** [comment]
I added a unit test to verify that the hostname is really not resolved when accessing the proxy.
To build the test for that, I had to change the clientVerifyHost method to set the verification to off, previously the switch was essentially a no-op

https://github.com/alexlehm/vert.x/tree/issues/%231361-add_unit_test
