### ISSUE TITLE
Implementation of Future.completer()

### ISSUE THREAD

**Issue by michaelom** [eclipse/vert.x#1373]
vertx 3.2.1:

The else block of the `completer()` method does not make sense to me. It calls `failed()` on `AsyncResult` which returns a boolean indicating if the result failed or not. If the else block had been omitted altogether, the result of `completer()` would have been the same.

I was expecting the else block to mark the future as failed.

```
  default Handler<AsyncResult<T>> completer() {
    return ar -> {
      if (ar.succeeded()) {
        complete(ar.result());
      } else {
        ar.failed();
      }
    };
  }
```

Am I missing something?

**Comment by michaelom** [comment]
Just to be more specific, I was expecting something like:

```
  default Handler<AsyncResult<T>> completer() {
    return ar -> {
      if (ar.succeeded()) {
        complete(ar.result());
      } else {
        fail(ar.cause());
      }
    };
  }
```

**Comment by vietj** [comment]
this is a bug and it is fixed in master.

fortunately the implementations of Future.completer override it and don't use it, so this bug does not happen with FutureImpl or CompositeFutureImpl. It could happen with Future implementations that would use this complete() method as is...

**Comment by vietj** [comment]
https://github.com/eclipse/vert.x/commit/00e7d235b4c3486621b69a2ee67c73af3da48a7e#diff-42268d4f311e3716dd222159e98ee2b6

**Comment by michaelom** [comment]
@vietj 
Thank you for clarifying.
