### ISSUE TITLE
Fix Message Producer

### ISSUE THREAD

**Issue by amannocci** [eclipse/vert.x#1382]
Motivation:
We forget to add credit header in MessageProducer when we set it with `deliveryOptions`.
As a result the drain handler will never be call.

Modification:
Add credit header when we set delivery options.

Result:
The drain handler will be call in every situation.

**Comment by vietj** [comment]
Hi, can you contribute a test + implementation ?

**Comment by amannocci** [comment]
Tell me what you think about this little fix

**Comment by vietj** [comment]
looks good to me, however we should make a copy of the options because the same options may be used in two producers leading to problems.

can you add this ? then it will be good for a PR.

**Comment by amannocci** [comment]
Fixed https://github.com/eclipse/vert.x/pull/1513

**Comment by amannocci** [comment]
Fixed https://github.com/eclipse/vert.x/pull/1513
