### ISSUE TITLE
Support waiting for event bus replies in worker threads

### ISSUE THREAD

**Issue by beders** [eclipse/vert.x#1386]
In case where a worker thread is used to run a a business function, it would be useful if the worker could communicate with existing vertices in a blocking fashion.
Here's an example where a result from a reply handler is received (via an event thread) and passed to the worker thread (which calls the proposed vertx.runOnEventLoop method)

```
JsonObject result = vertx.runOnEventLoop(future -> { 
    vertx.eventBus().send("thop", cmd, reply -> {
        System.out.println(reply);
        if (reply.succeeded()) {
            JsonObject value = (JsonObject) reply.result().body();
            future.complete(value);
        } else {
            future.completeExceptionally(reply.cause());
        }
    });
});
```
runOnEventLoop would use any available event thread to run the lambda and then wait for the future to complete (and there might be variant with a timeout).

The dangers with respect to concurrency are somewhat limited: Control of runOnEventLoop only returns when the provided future is complete, so the original worker thread can't change state while it waits for the result.
However, the lambda calling future.complete could change state afterwards, which is potentially a bad thing.

Advantages:

- From the perspective of the worker thread it remains trivial to maintain state in a single-threaded fashion. There's no need to declare it a multi-threaded worker verticle, which would also look drastically different.
- the worker thread can participate in message exchanges on the event bus

Disadvantages:

- no guarantee that the event code can't change state in the worker thread after future.complete has been called.

Implementation:
This has been implemented using a secondary thread pool (a work stealing executor).
Those short-lived threads are used to pass the torch to an existing (or newly created) event loop.

**Comment by vietj** [comment]
I would rather not do that because Vert.x methods can be used in an eventLoop and this method should never be called within an event loop.

Instead you should rather use this idiom with Java 8 CompletableFuture:

```
    CompletableFuture<String> fut = new CompletableFuture<>();
    vertx.runOnContext(v -> {
      fut.complete("whatever");
    });
    fut.get(10, TimeUnit.SECONDS);
```

**Comment by beders** [comment]
I tried using CompletableFuture before proposing this.

It won't work, as `runOnContext` runs on the worker thread which will only execute after you get a timeout from `fut.get`...

`vertx.runOnEventLoop` could check if it is run from a worker threar or not.

I think it is a legitimate feature request if you can't have a regular verticle control the flow of executing but must instead rely on a worker thread.

**Comment by vietj** [comment]
right, this is executed from a worker thread ? I thought it was more like a main/test style.

In this case I would rather add a method to create an event loop Context (which is sometimes needed in other places) to schedule a task on this event loop.

**Comment by beders** [comment]
That would be great.

**Comment by mstanescu** [comment]
I managed to achieve this by spawning a local vertx static object and using the event loop of that to actually execute the send.

**Comment by vietj** [comment]
I gave some thoughts at this point, this is actually forbidden because worker concurrency model mandates that at most one thread can execute the worker at the same time.

Multithreaded worker model works with such a case, for instance this works:

```
  @Test
  public void testWorkerWaitForReply(TestContext tc) {
    vertx.eventBus().consumer("the-address", msg -> {
      msg.reply(msg.body());
    });
    Async async = tc.async();
    vertx.deployVerticle(new AbstractVerticle() {
      @Override
      public void start() throws Exception {
        CountDownLatch latch = new CountDownLatch(1);
        vertx.eventBus().send("the-address", "hello", reply -> {
          latch.countDown();
        });
        latch.await(10, TimeUnit.SECONDS);
        async.complete();
      }
    }, new DeploymentOptions().
      setWorker(true).
      setMultiThreaded(true));
  }
```
