### ISSUE TITLE
CompositeFutureImpl's all and any methods silently fail when composing >32 Futures

### ISSUE THREAD

**Issue by joydip** [eclipse/vert.x#1387]
Because a primitive int value is used as the flag to compute the composite status of all the component futures, and because an arbitrary number of futures can be passed using the variants that accept an arbitrarily-sized List, if a List with more than 32 Futures is passed in, the implementations will not function correctly and issue no errors.

**Comment by vietj** [comment]
we should document that there should not be more than 32 futures and test it.

if someone needs more than 32 futures, then that person should rather use something like vertx-rx or maintain an AtomicInteger counter.

**Comment by vietj** [comment]
actually it's possible to make it work for more than 64 with a counter instead of a bit mask
