### ISSUE TITLE
Vert.x command line tools/launcher should return an error code when a failure occurs

### ISSUE THREAD

**Issue by peterhendriks** [eclipse/vert.x#1401]
All Vert.x command line operations currently always return a "0" exit value, even if it is known the command did not run successful.

For automated deployment tooling (e.g. puppet scripts) it is very useful to return a non-zero exit value. This will allow tooling to check the exit value, stop executing when one command fails, and provide better feedback on which step a failure occurs.

**Comment by vietj** [comment]
+1

**Comment by cescoffier** [comment]
In addition in the "stop" command, the exit status of the terminated process need to be "propagated" (reused by the command)
