### ISSUE TITLE
The Vert.x "stop" command should check if native operations complete successful

### ISSUE THREAD

**Issue by peterhendriks** [eclipse/vert.x#1402]
The Vert.x stop command currently does not check if the underlying native commands complete successful. E.g. when the "kill" process fails due to a "Operation not permitted" failure, the vertx stop command does not report this problem. Instead, it reports the Vert.x application has been stopped (but it would likely still be running).

Native commands executed during the stop command should be checked for the exit value. When a failure occurs, any output of native processes should be shown in the vertx command process output to get more feedback on why the command did not run successful.

**Comment by cescoffier** [comment]
The status should also be propagated.
