### ISSUE TITLE
Missing Test for AsyncMap<X,Buffer> in ClusterWideMapTest.java

### ISSUE THREAD

**Issue by dinhnn** [eclipse/vert.x#1409]
ClusterWideMapTest.java don't have test method for `AsyncMap<X,Buffer>`

**Comment by cescoffier** [comment]
I don't understand. The ClusterWideMapTest creates a AsyncMap and call lots of methods on it. Actually this test is also executed by all cluster managers. Do I miss something ?

**Comment by cescoffier** [comment]
Got it, you mean with `Buffer` as value.
