### ISSUE TITLE
Http client metrics missing @<id>

### ISSUE THREAD

**Issue by lubos-bistak** [eclipse/vert.x#1416]
I am using Vert.x 3.2.1 and according to "http://vertx.io/docs/vertx-dropwizard-metrics/java/#_http_client_metrics" the id should match "vertx.http.clients.@<id>" (e.g. vertx.http.clients.@3b773558.get-requests.max), but it is "vertx.http.clients." (e.g. vertx.http.get-requests.max).

Was this change on purpose? 
If yes, documentation should be updated.

**Comment by vietj** [comment]
this was removed indeed because the ID does not make sense and will change over time with differnet clients doing the same job. There is a feature request on vertx-core to add a notion of metric name for HttpClient metrics.

**Comment by lubos-bistak** [comment]
Thank you for you quick reply.

Can you please provide link / id of the feature request?

So for now, there is no possibility to distinguish 2 different HttpClient instances from each other, i am right?

**Comment by vietj** [comment]
https://github.com/eclipse/vert.x/issues/1314

**Comment by lubos-bistak** [comment]
Thank you very much.

Is " #1314" going to be part of "Vert.x 3.3.0 - ~ Early June 2016" ?

**Comment by vietj** [comment]
Hopefully, looks feasible and useful
