### ISSUE TITLE
PostgreSql json datatype

### ISSUE THREAD

**Issue by zadoff** [eclipse/vert.x#1423]
Hi there!
Here is an example of calling a function with a json data type parameter: https://gist.github.com/zadoff/f5a33398ff81ba75a06cedf93fa97de8

If I use text data type instead of json it works well.

Could you please add support for this type?

**Comment by InfoSec812** [comment]
Out of curiousity, what does this afford you that doing something like:

    SELECT my_stored_proc(json)::text;

would not?

**Comment by zadoff** [comment]
@InfoSec812 text type for output is not ok too. If a function returns json as a text, vertx couldn't parse it correctly.
If the function
`return json_build_object('key','value')`
or
`return json_build_object('key','value')::text`

vertx shows this:
![image](https://cloud.githubusercontent.com/assets/17167771/15292547/429c1612-1b8c-11e6-90eb-5acde8af07c4.png)

**Comment by pmlopes** [comment]
Hi, did you check this post?: http://vertx.io/blog/vert-x3-and-postgresql-json-type/

When using JSON in pure JDBC you need to state the type so your strings is handled as JSON, and all returned JSON are also converted to String by the driver.

See:

http://www.postgresql.org/docs/current/static/datatype-json.html
http://www.postgresql.org/docs/current/static/functions-json.html

**Comment by zadoff** [comment]
Hi Paulo! Yes, I read this a couple of hours ago. It was my fault. Sorry!
