### ISSUE TITLE
vertx run xxxx.groovy,chinease chars will be garbled,but java file is OK

### ISSUE THREAD

**Issue by aruis** [eclipse/vert.x#1425]
`myverticle.groovy`

void vertxStart() {
    println("\u4f60\u597d")
    println "你好 starting"
}

void vertxStop() {
    println "stopping"
}

`$ vertx run myverticle.groovy`

你好

������ starting

Succeeded in deploying verticle

**Comment by vietj** [comment]
can you open this issue in this project instead ? https://github.com/vert-x3/vertx-lang-groovy
