### ISSUE TITLE
Future.failedFuture returns successful future if cause is null

### ISSUE THREAD

**Issue by dazraf** [eclipse/vert.x#1426]
A question from our team:

Should [`Future.failedFuture`](https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/impl/FutureImpl.java#L40) always return a failed future?
At present `failedFuture(null)` returns a succeeded future. 

Agree that we should never call failedFuture with null, but it can happen by accident ... and depending on the complexity of the system, finding the root cause can take some time.

Also perhaps, calling [`Future.fail(null)`](https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/impl/FutureImpl.java#L144) should really set the cause to `NoStackTraceThrowable`.

**Comment by vietj** [comment]
can you provide a failing unit test ?

**Comment by dazraf** [comment]
Hi @vietj 
created this project of breaking tests
https://github.com/dazraf/vertx-future-tests/blob/master/src/test/java/io/dazraf/futures/FutureTest.java
regards
@dazraf
