### ISSUE TITLE
multiple verticle instances as REST service with routingContext.next()

### ISSUE THREAD

**Issue by tobiloeb** [eclipse/vert.x#1427]
Hello,

I have a problem possible bug with multiple deployed instances of a verticle that is used as a REST endpoint. The service will receive every request and sanitize the payload. Then the next matching route (router.next()) will be called. 

The Sanitizer verticle do something like this:
`this.router.post("/*").handler(routingContext -> {
    // do something
    routingContext.next();
}`

This Sanitizer verticle is deployed several times:
`deploymentOptions.setInstances(5);
this.vertx.deployVerticle(verticleName, deploymentOptions);`

We use for all verticles the same router to go through all matching routes with routingContext.next(). For every request our Sanitizer is called, **but it is called 5 times** because it is deployed 5 times. Vert.x didn't notice, that´s the same verticle which is called multiple times. I want that the Sanitizer verticle is only called once and then the next route (e.g. /test/test).

Is this a bug in vert.x or should I handle the router in a different way?

Example of verticle (The Runner.mainRouter is initialized once in Runner class):
`public class App extends AbstractVerticle {

    public static void main(final String[] args) {
        Runner.run(App.class);
    }

    @Override
    public void start() {
 
        Runner.mainRouter.get("/rest/*").handler(rc -> {
            System.out.println("sanitizer " + this);
            rc.next();
        });

        vertx.createHttpServer().requestHandler(Runner.mainRouter::accept).listen(8090);
    }
}`

**Comment by vietj** [comment]
can you open this issue in the http://github.com/vert-x3/vertx-web repository ?
