### ISSUE TITLE
Solver - Logging with Slf4J not working for io.vertx.core.impl.ContextImp

### ISSUE THREAD

**Issue by dtrumpfheller** [eclipse/vert.x#1428]
Hello,

I have some problems with the logging of vertx. When using the default logging framework everything works fine. But when using SLF4J with logback some of vertx loggins don't appear in the log.

Classes like 'io.vertx.core.impl.launcher.commands.RunCommand' or 'io.vertx.ext.web.impl.RoutingContextImplBase' are logging as expected and the log entry is available in the log file.

The class 'io.vertx.core.impl.ContextImpl' (line 338 of vertx 3.2.1) logs if an error occurred but this log entry never appears in the log file. The reason so far is unknown.

Slf4J is set this way:

```
private static final String LOGGER_DELEGATE_FACTORY_CLASS_NAME_PROPERTY = "vertx.logger-delegate-factory-class-name";
private static final String LOGGER_DELEGATE_FACTORY_CLASS_NAME = "io.vertx.core.logging.SLF4JLogDelegateFactory";
static {
    System.setProperty(LOGGER_DELEGATE_FACTORY_CLASS_NAME_PROPERTY, LOGGER_DELEGATE_FACTORY_CLASS_NAME);
}
```

Could you please have a look? Thanks!

**Comment by jtrumpfheller** [comment]
Hello,

error is found. We are using a customer Logback converter which throws an exception sometimes. This exception is catched by Loback but never logged. Therefore we thought vertx would do something wrong.

It is not a vertx error - please close/delete this thread. Thanks.

**Comment by tsegismont** [comment]
Closed not a bug as per user comment
