### ISSUE TITLE
CompositeFuture.all/any fails for 1 single fail

### ISSUE THREAD

**Issue by chengenzhao** [eclipse/vert.x#1430]
Hi there:

We just encounter a problem and it is difficult to reproduce.
For example, if we use Future future = Future.future(); and then send the http request 
and if one of the request fails very fast like got connection refused instantly
and then we set the future.fails(url+" request failed");
and then interesting thing is 
CompositeFuture.all(...)/any(...) method some times execute without receiving other responses.
the difficulty of reproduce is not every time it happens, but happened in few tests

Our guess is when one of the future fails and it successfully registered in the compositeFuture and the other future has not registered successfully yet, thus the size of compositeFuture list/set is only 1 and the only 1 fails then the rest would fail also, not sure about the logic but it happens

We will continue test this problem and maybe later submit our code

Thanks

**Comment by vietj** [comment]
thanks for reporting this, waiting for your feedback

**Comment by vietj** [comment]
what you mean by "CompositeFuture.all(...)/any(...) method some times execute without receiving other responses." ?

a more detailed example is wished.

**Comment by chengenzhao** [comment]
Hi vietj:

Maybe it is our misunderstanding, for my understanding is CompositeFuture.all method will execute if any future fails without receiving other responses since it knows the result already(fail) and CompositeFuture.any method will execute if any future succeeded without receiving other responses since it knows the result(fail) already. Please correct us if I am wrong.

Thanks

**Comment by vietj** [comment]
the behavior is that these methods should succeed or fails as soon as possible.

so all will fail as soon as the first fails and any will succeed as soon as the first succeeds.

**Comment by chengenzhao** [comment]
Hi vietj:

Thanks a lot

I am closing this issue

Cheers

**Comment by vietj** [comment]
I've added clarification in doc : https://github.com/eclipse/vert.x/commit/8952de7b433fe1a26352a80482567bbb18b3be1a

**Comment by aschrijver** [comment]
Hi @chengenzhao !
I have created a PR, that extends `CompositeFuture` with the behaviours you expected.
See: https://github.com/eclipse/vert.x/pull/1533

**Comment by chengenzhao** [comment]
@aschrijver 👍 
cheers
