### ISSUE TITLE
vert.x could support socket.io

### ISSUE THREAD

**Issue by arden** [eclipse/vert.x#1436]
vert.x could support socket.io?

**Comment by hadv** [comment]
+1

**Comment by purplefox** [comment]
Vert.x has had a socket.io module 2014 https://github.com/keesun/mod-socket-io

https://github.com/keesun/mod-socket-io

But that was Vert.x 2 - it was never ported to Vert.x 3 afaik.

I think it would be great if someone ported this / or created new socket.io support for Vert.x 3. It would be a nice project if anyone was interested :)

**Comment by vietj** [comment]
Moving here https://github.com/vert-x3/issues/issues/226

**Comment by vietj** [comment]
moved elsewhere
