### ISSUE TITLE
Service loading of VerticleFactory does not work with mvn exec:java

### ISSUE THREAD

**Issue by paulmiddelkoop** [eclipse/vert.x#1437]
The service loading of VerticleFactory's does not work when starting Vert.x with Maven's exec:java target. When using the ServiceVerticleFactory the verticles are not started as a service but as a regular verticles. This means that the service descriptor is ignored (without any warning) and the worker verticles are started as non-worker verticles instead (resulting in blocking event threads). 

A quick fix is to supply the correct class loader to the SeviceLoader in the DeploymentManager. I will open a PR for that. 

PR: https://github.com/eclipse/vert.x/pull/1438

**Comment by cescoffier** [comment]
This can be closed, fixed by https://github.com/eclipse/vert.x/pull/1444

**Comment by paulmiddelkoop** [comment]
Tested and indeed fixed by #1444.
