### ISSUE TITLE
MimeMapping support for WOFF2

### ISSUE THREAD

**Issue by leolux** [eclipse/vert.x#1440]
Currently the file MimeMapping.java has no support for the new top level type "font" thus no support for WOFF2 files. Regarding the specification [1], [2] the mime type for woff2 should be "font/woff2".

[1] https://dev.w3.org/webfonts/WOFF2/spec/#IMT
[2] https://datatracker.ietf.org/doc/draft-ietf-justfont-toplevel/

This leads to a some parsing exception in chrome for example:
"OTS parsing error: invalid version tag"

**Comment by vietj** [comment]
@leolux can you contribute a PR ?

**Comment by leolux** [comment]
I didn't get the validation working. I did not pass Eclipse validation because I do not have valid CLA and my Signed-off-by footer is invalid.

Maybe someone elsse can contribute this PR: https://github.com/eclipse/vert.x/pull/1446
