### ISSUE TITLE
HttpServerRequestImpl.handleEnd() should catch endHandler.handle() exceptions

### ISSUE THREAD

**Issue by dgbustos** [eclipse/vert.x#1451]
The body handler I set on an `HttpServerRequest` threw an exception.  I expected the request's exception handler to be called, but it was not.  This is with Vert.x 3.2.1.  The stack includes

        at io.vertx.core.http.impl.HttpServerRequestImpl.lambda$bodyHandler$54(HttpServerRequestImpl.java:288)
        at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:411)

**Comment by vietj** [comment]
right

**Comment by vietj** [comment]
actually this is expected.

the request exception handler is for external exceptions (i.e usually protocol / networking errors) and not for developer errors.

in this case, the error should be caught by the Context and logged. Alternatively it is possible to set an exceptionHandler on the Context to catch uncaught errors and do some handling there.

**Comment by dgbustos** [comment]
@vietj How do I set an exceptionHandler on the Context?

**Comment by vietj** [comment]
vertx.getOrCreateContext().exceptionHandler(err -> {});

**Comment by dgbustos** [comment]
That was added for #1216
