### ISSUE TITLE
Only one certificate used in TLS handshake when using PemKeyCertOptions

### ISSUE THREAD

**Issue by danadam** [eclipse/vert.x#1453]
If you have a keystore file with certificate chain and you create ``NetServer`` and use ``setKeyStoreOptions(JksOptions)`` option, then the whole certificate chain will be sent to the client during TLS handshake.

If you have a pem file with certificate chain and you create ``NetServer`` and use ``setPemKeyCertOptions(PemKeyCertOptions)`` option, then only the first certificate in the chain will be sent to the client during TLS handshake.

The same problem exists in Vertx 3.3.0 and also when you use OpenSSL engine (``setSslEngine(SSLEngine.OPENSSL)`` option). And when using OpenSSL engine there is no alternative because it requires ``PemKeyCertOptions``.

**Comment by vietj** [comment]
thanks for reporting this : can you check this branch https://github.com/eclipse/vert.x/tree/chain-cert ?

**Comment by danadam** [comment]
Yes, that works.
