### ISSUE TITLE
Inaccessible client's certificate when using OPENSSL engine

### ISSUE THREAD

**Issue by danadam** [eclipse/vert.x#1461]
Little backstory...
Due to reasons our server requires client authentication during TLS handshake and accepts self-signed certificates. In order to make it work on Vertx we are forced to do an ugly hack with `getDeclaredField()` and `setAccessible()` in order to set `SSLHelper.trustAll` to `true` for `NetServer` object. This works and after accepting a connection we use `peerCertificateChain()` to get client's certificate and we do stuff with it.

It stopped working with `SSLEngine.OPENSSL`, we get `SSLPeerUnverifiedException` instead. The problem is surely in Netty but maybe also in Vertx.

[`javax.net.ssl.SSLSession`](https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLSession.html) declares two methods: [`getPeerCertificateChain()`](https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLSession.html#getPeerCertificateChain--) and [`getPeerCertificates()`](https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLSession.html#getPeerCertificates--). They both should return client's certificate and certificate authorities in the resulting array:

> Returns:
> an ordered array of peer certificates, with the peer's own certificate first followed by any certificate authorities.

But when Netty is configured to use OpenSSL engine, `getPeerCertificateChain()` returns only certificate authorities (`getPeerCertificates()` works correctly). In our case, `peerCertificateChain()` from `NetSocket` calls `SSLSession.getPeerCertificateChain()`, there are no certificate authorities (because self-signed certificate) and `SSLPeerUnverifiedException` is thrown.

So it is clearly a bug in Netty, but in `getPeerCertificateChain()` documentation there is also this:

> Note: this method exists for compatibility with previous releases. New applications should use getPeerCertificates() instead.

And Vertx doesn't provide anything that would call `SSLSession.getPeerCertificates()` (which, as I mentioned, works correctly).

BTW: it surely would be nice to get rid of the hack I mentioned at the beginning. Any chances to have `setTrustAll()` in `NetServerOptions`?

**Comment by vietj** [comment]
so this is a requests for actually two features ?

**Comment by vietj** [comment]
where can we find the "Note: this method exists for compatibility with previous releases. New applications should use getPeerCertificates() instead." ?

**Comment by vietj** [comment]
I think that:
concerning peer certififates I think we can provide a peerCertificates() in Vert.x.
concerning trustAll, it could be declared in TCPSSLOptions so it works with the client or the server in TLS

**Comment by danadam** [comment]
> so this is a requests for actually two features ?

Yes, but I can open separate ticket for trustAll if you prefer.

> where can we find the "Note:

It's there in [javadoc of getPeerCertificateChain()](https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLSession.html#getPeerCertificateChain--).

**Comment by dachaac** [comment]
Just created PR https://github.com/eclipse/vert.x/pull/2078 for adding peerCertificates() that would handle part of this issue.

**Comment by vietj** [comment]
closing this issue as the certificate access has been provided and the native OpenSSL support is partially covering certificate access which is not a defect of Vert.x per se
