### ISSUE TITLE
vertx-rx-java - Unnecessary wrapping of handlers while invoking setters on delegate

### ISSUE THREAD

**Issue by techpavan** [eclipse/vert.x#1463]
While consuming vertx-rx-java, I see that handlers set on delegate are wrapped objects of input parameters. This seems to pose two issues - 
1. The input parameters in rxjava as well as core packages are of io.vertx.core.Handler type. Still, in rxjava package, we wrap it to the same type through constructor before passing it to delegate. This creates unnecessary objects.
2. If null is passed as a parameter to rxjava package, it results in NPE in core package.

Example: 
io.vertx.rxjava.core.http.HttpServerResponse#drainHandler, closeHandler

```
  public HttpServerResponse drainHandler(Handler<Void> handler) { 
    ((io.vertx.core.http.HttpServerResponse) delegate).drainHandler(new Handler<java.lang.Void>() {
      public void handle(java.lang.Void event) {
        handler.handle(event);
      }
    });
    return this;
  }
```

---

My use case expects to wait for some data to arrive from an external source and write it to client. I register to drain handler when I have excess amount of data and write queue gets full. When I do not have data to write (as I wait for my source to send some), drain events make no sense and I unregister by setting drain handler to null. Though my overall functionality is not impacted, there are NPEs thrown from vertx and additional objects are created.

**Comment by vietj** [comment]
can you still see that with 3.3.0-SNAPSHOT ?

**Comment by techpavan** [comment]
Hi @vietj, I still see that in 3.3.0-SNAPSHOT.

**Comment by vietj** [comment]
I will try to improve this for this type. Beside the void type do you see any other type it applies to ?

I'll ping you when it is updated

**Comment by techpavan** [comment]
Yes, it seems like Buffer (handler / bodyHandler), AsyncResult(push / sendFile), HttpFrame (customFrameHandler), HttpServerFileUpload (uploadHandler) also have issues. AsyncResult methods also have some logic and thus a simple adapter fix cannot help here.

**Comment by vietj** [comment]
for Buffer it is not the same class : io.vertx.core.buffer.Buffer versus io.vertx.rxjava.core.buffer.Buffer

**Comment by vietj** [comment]
btw can you reopen this issue in the correct repository https://github.com/vert-x3/vertx-rx ?

**Comment by techpavan** [comment]
Created - https://github.com/vert-x3/vertx-rx/issues/42

Got it about the Buffer, but we would need a null check in that case.
