### ISSUE TITLE
launcher can't be subclassed as described in documentation

### ISSUE THREAD

**Issue by ashertarno** [eclipse/vert.x#1472]
there are actually two separate issues:

1. io.vertx.core.Launcher's main method is implemented as 
`public static void main(String[] args) {
    new Launcher().dispatch(args);
  }`
and therefore Launcher can't be effectively subclassed and customized - the instance created will be always of the parent class and not of hte implementation. 

2. io.vertx.core.Launcher provides some methods that can be used by Launchers subclasses, e.g. afterConfigParsed(), beforeStartingVertx(), beforeDeployingVerticle() and so on. it seems that none of these methods is implemented in launcher flow.

**Comment by cescoffier** [comment]
About 1, when you subclass the launcher, you need to have a main method calling your launcher, not the `io.vertx.core.Launcher` class.

About 2, If you use your implementation, then these methods are called, but you need to use your Launcher implementation.

**Comment by vietj** [comment]
can we close this issue ?

**Comment by ashertarno** [comment]
well, in case you believe there is no problem and i simply didn't understand the intention - you can.
frankly speaking i think what clement is describing in his answer isn't called "subclassing". if i'm the one to implement all those afterXXX and beforeZZZ methods - this is about a fully new implementation of launcher and not about customization of the existing one.

**Comment by cescoffier** [comment]
You have several choices:

1. You implement a new complete main (main is the entry point, the public static static main(Stirng[] args). In this case, yes there is no subclassing. You do you own way to launch the application
2. You implement a sub-class of of `io.vertx.core.Launcher` that can override the different lifecycle callbacks (beforeStarting, afterStarting...). **BUT** (and maybe that's what is unclear), you must have a `main` method calling your implementation:

```
public class MyLauncher extends Launcher {

    public static void main(String[] args) {
      new MyLauncher().dispatch(args);
    }

    public void beforeStartingVertx(VertxOptions options) {
        // customize options ....
    }

}
```
You launch your application using `MyLauncher` and not `io.vertx.core.Launcher`. Notice that in the `Launcher` class, all the before/after methods are empty. You don't have to implement all of them. 

3. You provide a new `Command` extending the `io.vertx.core.impl.launcher.commands.RunCommand` command.

For me, 2 is the subclassing case: you extend the Launcher (so you create a sub-class), change the behavior you need (options, config...). 

About @vietj, the documentation could be improved, and example should also be added. But, this is just improvement in the docs. From my understand of subclassing, it's actually the case. However, I let you judge.

**Comment by ashertarno** [comment]
ok, i understand your point now. thanks.

**Comment by manikantag** [comment]
@cescoffier Better mention this in the doc here: https://vertx.io/docs/vertx-core/java/#_sub_classing_the_launcher

I just wasted 2 hrs to figure this out. I debugged the flow and found out `BareCommand.beforeStartingVertx` is still seeing 'io.vertx.core.Launcher` as the launcher class (`main` holds that value) and then it stricken me if I had to call `dispatch()` on my custom sub class.
