### ISSUE TITLE
Add SNI support

### ISSUE THREAD

**Issue by aemkei3** [eclipse/vert.x#1477]
Maybe I just can't find the options for enabling SNI, but I think it is not supported.

It is already supported in netty and I found an example for it:
https://github.com/grahamedgecombe/netty-sni-example

Thank you!

**Comment by vietj** [comment]
hi, it's not supported yet. Perhaps you could contribute it ?

**Comment by vietj** [comment]
note : since Vert.x 3.3 the `KeyManagerFactory` creation is delegated to the KeyCertOptions and one can implement SNI using it, until it is contributed to Vert.x

**Comment by aemkei3** [comment]
Hi. Thank you for your input. 

I managed to get it working using https://github.com/ellebrecht/vert.x and implementing a KeyStoreSpi and a KeyManagerFactorySpi.

**Comment by creativeprogramming** [comment]
@aemkei3 can you share some code snippet? Thanks

**Comment by vietj** [comment]
@creativeprogramming https://github.com/ellebrecht/vert.x/commit/670567b4f62570fcaad3402bdf2cba3998c60ac1

**Comment by lulf** [comment]
Is there a way to set SSL parameters like SNI server names client side?

**Comment by vietj** [comment]
see https://github.com/eclipse/vert.x/pull/1698

**Comment by xkr47** [comment]
Would it be possible to add certificates "on the fly" without recreating the server i.e. without closing the server socket? This would enable using the ACME protocol's (LetsEncrypt) TLS-based challenges (https://shredzone.org/maven/acme4j/challenge/tls-sni-02.html) which need one to (temporarily) add specifically created certificates with a specific SNI name to verify ownership.

For example if one could specify a custom certificate provider along the lines of `Certificate getCertificateFor(String sniName)` then that could easily support dynamically changing what certificates are currently supported.

**Comment by vietj** [comment]
@xkr47 I think that the current `KeyCertOptions` class allows to provide a custom `KeyManagerFactory`
