### ISSUE TITLE
Unfinished Futures?

### ISSUE THREAD

**Issue by nkavian** [eclipse/vert.x#1478]
When result() is called it simply returns the member variable.  Documentation says this:

````
  /**
   * The result of the operation. This will be null if the operation failed.
   * @return the result or null if the operation failed.
   */
````

Is there anything that guarantees the future has completed before the result is returned?  Am I missing something about how this works?

https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/Future.java#L147
https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/impl/FutureImpl.java#L64

**Comment by vietj** [comment]
It will only return the result when it is available, if you call this too soon you won't get anything - usually you call result() in the handler callback set with setHandler() .
