### ISSUE TITLE
any chance for Jackson 2.5+ on vertx 2.x?

### ISSUE THREAD

**Issue by mohamnag** [eclipse/vert.x#1483]
We have a relatively large application based on vertx 2.1.6 which is not worth the effort for updating to vertx 3. however due to some problems we need to have Jackson at least 2.5+ as dependency. but it seems that vertx forces Jackson 2.2.2 no matter how we packages the module. 
currently we are packing everything as fat Jar and vertx puts Jackson 2.2.2 in its `lib/` and loads it even when Jackson 2.7.4 is present under `mods/module-name/lib`.

Is there any way to change this behaviour and to force using newer Jackson versions?

**Comment by pmlopes** [comment]
I'd say if you build from source you will be able to override the version for sure.

**Comment by vietj** [comment]
closing this
