### ISSUE TITLE
MQ-based ClusteredEventBus support

### ISSUE THREAD

**Issue by awara2012** [eclipse/vert.x#1484]
Sometimes we want to persist the event into the MQ to avoid it being lost in some special cases. For example, if the Vert.x node crushed, the unhandled events in this node will be lost.

**Comment by vietj** [comment]
hi, Vert.x 3 provides support AMQP bridge : http://vertx.io/docs/#integration

**Comment by vietj** [comment]
btw @awara2012 what exception are you talking about ?

**Comment by awara2012** [comment]
Thanks @vietj 

Sorry, maybe i used a confusing word "exception", and i have updated the comment.

I have read codes of vertx-rabbitmq-client and vertx-amqp-bridge you suggested, but i find they consume the message like that:
1. pull the message from the broker;
2. send the message to the eventbus;
3. ack if send the message successfully.

If the Vert.x node crushed, the unhandled events will also be lost. The reason of this problem is the message doesn't be persisted in the eventbus.

So maybe Vert.x can supply the extension for ClusteredEventBus(based on different communication protocols, such as NetServer-based, MQ-based, etc).

**Comment by vietj** [comment]
@awara2012 there will be soon a survey for Vert.x 3.4 and later versions, that's typically the kind of things you can ask for.

**Comment by vietj** [comment]
@awara2012 https://github.com/vert-x3/issues/issues with the "whishlist" label

**Comment by awara2012** [comment]
ok. Thanks @vietj !
