### ISSUE TITLE
Allow AsyncFile's to be opened in append mode

### ISSUE THREAD

**Issue by dgbustos** [eclipse/vert.x#1486]
Appending to a file requires three steps:
1. Open the file with `FileSystem.open()` with an `OpenOptions` object on which `setTruncateExisting(false)` and `setWrite(true)` have been called.
2. Get the file properties with `FileSystem.props()`
3. Call `setWritePos()` on the file with the length according to the properties.

It seems like a simpler and less error-prone way would be to add `setAppend()` and `getAppend()` to `OpenOptions` and make `AsyncFileImpl`'s constructor translate it to `StandardOpenOption.APPEND`.

**Comment by tsegismont** [comment]
@dgbustos PR #2073 sent

There's no need to use `StandardOpenOption.APPEND` as `AsyncFileImpl` maintains its own `writePos`.
