### ISSUE TITLE
SEVERE: java.io.IOException: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by a-reisberg** [eclipse/vert.x#1487]
On the server side (vertx), I have (earlier, `setChunked` is set to `true`)

```scala
route("/test").handler { rc =>
      rc.response().end("Cool stuff")
    }
```

On the client side (I'm using OkHttp3), I have
```scala
  val JSON = MediaType.parse("application/json; charset=utf-8")

  val client = new OkHttpClient()
  val requestBuilder = new Request.Builder().url("http://localhost:8080/test")
  requestBuilder.method("POST", RequestBody.create(JSON, ""))
  val request = requestBuilder.build()
  val response = client.newCall(request).execute()
  println(response.body.string())
  response.close()
```

The client prints `"Cool stuff"` as desired.  However, when the client exits, I get this error **on the server**
```
SEVERE: java.io.IOException: An existing connection was forcibly closed by the remote host
```

When I use `HttpURLConnection` instead of OkHttp, I still get the same error. Could someone please help?

Thanks!

**Comment by vietj** [comment]
without much more details we can't help you. can you provide more logging and a reproducer ?

**Comment by a-reisberg** [comment]
Thanks @vietj for the quick response. The minimal code that reproduces it could be found here:

https://github.com/a-reisberg/vertxIOExceptionBug

Thanks a lot.

**Comment by vietj** [comment]
can you explain how to run this from the command line ?

**Comment by a-reisberg** [comment]
I made a Java version of it (w/ Maven):
https://github.com/a-reisberg/vertx-ioexception-java

Thanks a lot.

**Comment by vietj** [comment]
how can we run that from the command line interface

**Comment by vietj** [comment]
I've run them from IDE but I don't see anything like what you describe.

**Comment by a-reisberg** [comment]
That's bizzare. I never ran it from the CLI. Inside Intellij, I run the server, wait a bit for it to finish, and then run the client (both by right click on the file and then run ...). Which IDE do you use?

**Comment by vietj** [comment]
I'm using intellij and the log remains blank

**Comment by a-reisberg** [comment]
Which OS? I'm using Windows 10. Maybe I should try to run it on a Linux box and see what happens.

**Comment by vietj** [comment]
yes - I suspect this is a connection reset when the process ends

**Comment by a-reisberg** [comment]
So I can safely ignore it? :)

**Comment by vietj** [comment]
normally yes - the best would be to run a tool like wireshark to see what happens at this level to confirm

**Comment by a-reisberg** [comment]
Ok. Thanks. I'll try to figure that out (never used wireshark before :/)

**Comment by a-reisberg** [comment]
There's no exception on a Mac. So I guess it's fine. Can you elaborate on "connection reset when the process ends"? Shouldn't the connection be closed after the request is finished already?

Thanks.

**Comment by vietj** [comment]
try to close the Vertx  before your program exit and block in the close() callback

**Comment by a-reisberg** [comment]
I'm a bit confused! Vertx is the server, why should it be closed? Could you please explain?

Thanks!

**Comment by vietj** [comment]
I mean the Vertx on the client
