### ISSUE TITLE
Implement HTTP Proxy for non SSL HttpClient

### ISSUE THREAD

**Issue by vietj** [eclipse/vert.x#1498]
At the moment the HttpClient proxy configuration uses CONNECT for non SSL HttpClient and instead it should do a straight connection with a target requestURI, i.e

```
client.get(80, "www.google.com", resp -> {});
```

should be equivalent to:

```
client.get(80, "the-proxy", "http://www.google.com", resp -> {}).host("www.google.com:80");
```

so we do have request like:

```
GET http://www.google.com HTTP/1.1
Host: www.google.com
```

while the client connects to `the-proxy` host.

Note: this does not affect `NetClient` that will always continue to create a tunnel using CONNECT

**Comment by techpavan** [comment]
My upvote for this issue. Consumers should find it easy and Vert.x should handle it internally.

**Comment by alexlehm** [comment]
@vietj should we consider this in the 3.3.3 version?

**Comment by vietj** [comment]
that's doable imho, depending on the complexity of the solution

**Comment by alexlehm** [comment]
I implemented a unit test and a first version of the fix

https://github.com/alexlehm/vert.x/tree/issues/%231498-http-proxy-request

**Comment by vietj** [comment]
what is the current status of this fix ?

**Comment by alexlehm** [comment]
I rebased my changes onto the current master from eclipse/vert.x, I will rerun the tests, I think its almost finished

**Comment by vietj** [comment]
you said you were missing tests before, that's why I'm asking there

**Comment by alexlehm** [comment]
Sorry, I forgot about that. I have implemented additional tests and added handling for login on the proxy. I could do a PR now I think.

**Comment by vietj** [comment]
would be great

**Comment by alexlehm** [comment]
https://github.com/eclipse/vert.x/pull/1540

for some reason the eclipse ip check fails on one commit, I think the format is correct though.

**Comment by alexlehm** [comment]
new pr #1548, this one is accepted by the eclipse check

**Comment by alexlehm** [comment]
new pr merged into the current master https://github.com/eclipse/vert.x/pull/1550
