### ISSUE TITLE
HttpClient - Netty - unhandled exceptions halt program when using proxy

### ISSUE THREAD

**Issue by FainTMako** [eclipse/vert.x#1503]
Hello, I'm enjoying the new implementation of socks proxy support in vertx but it looks like I'm not able to handle a few exceptions related to io with the proxy server.

Jul 07, 2016 5:41:29 PM io.vertx.core.http.impl.HttpClientRequestImpl
SEVERE: java.net.ConnectException: Connection refused: no further information:

I get that when using an invalid proxy.
I was also getting another exception in netty that I cannot reproduce right now. It was a unhandled netty exception coming from the channel pipeline.

I'm looking for a fix that would allow me to put my own exception handlers on the pipeline for netty through vertx.

**Comment by vietj** [comment]
it will be fixed in 3.3.1 out soon, can you check with current master ?

**Comment by vietj** [comment]
@FainTMako see https://github.com/eclipse/vert.x/issues/1489
