### ISSUE TITLE
Missmatch between documentation and implementation for LocalMap

### ISSUE THREAD

**Issue by froth** [eclipse/vert.x#1509]
The documentation of LocalMap states:

The map only allows immutable keys and values in the map, OR certain mutable objects such as {@link io.vertx.core.buffer.Buffer}

https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/shareddata/LocalMap.java

However the implementation in:

https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/shareddata/impl/Checker.java

Has only a whitelist of allowed Types. Immutable objects are refused. 

Not sure whether this is an implementation or documentation problem.

**Comment by tsegismont** [comment]
@froth a documentation problem. Fixed in #2077
