### ISSUE TITLE
Support for NPN and SPDY? (In addition to ALPN)

### ISSUE THREAD

**Issue by creativeprogramming** [eclipse/vert.x#1510]
I know it's not so cool, now that http/2 has replaced spdy, but in some real cases advertising and supporting also the spdy protocol can give good benefits, as http/2 is not yet supported by many mobile browsers (my vertx apps are webapps accessed from mobile devices) especially android webviews.

The very same thing I'm asking for here, was just implemented by cloudflare for nginx, so you can agree... it can help in some real cases; check following post and the comments: 

https://blog.cloudflare.com/open-sourcing-our-nginx-http-2-spdy-code/

PS. SPDY and NPN are implemented by Netty, check SpdyServer.java example in netty repository.

**Comment by vietj** [comment]
would worth a contribution indeed!

**Comment by creativeprogramming** [comment]
Yes but for this i cannot write a solution myself, i tried but failed today, if you give me some tip i can try again.

With this feature vert.x would be the more awesome webserver in the word for me, and I can get rid to put a nginx reverse proxy in front of it for some websites i need this feature

**Comment by vietj** [comment]
that's a good point about ngninx

**Comment by vietj** [comment]
closing for maintenance purpose, reopen or just make a contribution via PR.
