### ISSUE TITLE
Proxying - Host header not formed properly

### ISSUE THREAD

**Issue by techpavan** [eclipse/vert.x#1511]
While proxying though the Vertx HTTP client, the Host header that goes as a part of CONNECT request (as only https targets are supported by Vert.x right now) is not appropriate as defined in the spec. 

Host header should contain the host:port of the target server, but currently it is populated with that of proxy server. Thus, some proxy servers / web applications might dishonor the request due to this discrepancy.

Reproducer is hard to implement, but below should explain the problem.
Target url: https://www.google.com
Proxy server: proxyhost.com:8888

**Expected request at the proxy:**
CONNECT www.google.com:443
Host: www.google.com

**Actual request at the proxy:**
CONNECT www.google.com:443
Host: proxyhost.com:8888

Spec: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23

**Comment by vietj** [comment]
this is a Netty bug :

https://github.com/netty/netty/commit/f52b07dedee99c0d0cf08a3b6732d56290185825#diff-95cd1e58ffefe4ca490c3855b1a4446c

Vert.x 3.3.3 will likely upgrade the version to the latest Netty version.

**Comment by techpavan** [comment]
cool. thanks.

**Comment by alexlehm** [comment]
@techpavan actually that is not a strict requirement, it is the responsibility of the proxy to insert the proper Host: header for the upstream server, the client can leave it either empty to write an arbitrary value.
Nevertheless it makes sense to do it similar to any normal browser.

**Comment by alexlehm** [comment]
+1 (sorry, I removed my previous comment about the host header, it makes sense to do it like described above)

**Comment by vietj** [comment]
do we have a test for this in Vert.x now ?

**Comment by alexlehm** [comment]
https://github.com/eclipse/vert.x/pull/1549
