### ISSUE TITLE
ns.upgradeToSsl fails hostname cert check

### ISSUE THREAD

**Issue by alexlehm** [eclipse/vert.x#1512]
When connecting with NetClient using upgradeToSsl (which is for example used in mail STARTTLS), the cert name is matched against the resolved ip address, which fails.

https://gist.github.com/alexlehm/8b609f70c848453ab7da5b360b740db0

**Comment by alexlehm** [comment]
I will try to implement a fix tonight

**Comment by alexlehm** [comment]
https://github.com/alexlehm/vert.x/tree/issues/%231512-certcheck-hostname

**Comment by vietj** [comment]
can you make a PR ?

**Comment by alexlehm** [comment]
https://github.com/eclipse/vert.x/issues/1516
fixes the issue and add Subject Alt Name to certificate for testing the cert check
