### ISSUE TITLE
WriteStream javadoc improvements

### ISSUE THREAD

**Issue by ahus1** [eclipse/vert.x#1518]
Looking at the API of WriteStream#drainHandler it says: 

> If the write queue is full, then the handler will be called when the write queue has been reduced to maxSize / 2

Implementations differ in the sense that they call it either **only once** the queue has been reduced or **every time** the queue has been reduced.

This looks suspicious to me and I wonder what is correct.

NetSocketImpl is calling the handler **every time**:
```
  private synchronized void callDrainHandler() {
    if (drainHandler != null) {
      if (!writeQueueFull()) {
        drainHandler.handle(null);
      }
    }
  }
```

MessageProducerImpl is calling the handler **only once** (by setting it to null):
```
  private synchronized void doReceiveCredit(int credit) {
    /* .... */
    final Handler<Void> theDrainHandler = drainHandler;
    if (theDrainHandler != null && credits >= maxSize / 2) {
      this.drainHandler = null;
      vertx.runOnContext(v -> theDrainHandler.handle(null));
    }
  }

```

**Comment by vietj** [comment]
I think the javadoc should be updated and let the drain trigger to be an implementation detail.

this was first designed and documented for Netty that uses low and high watermark.

**Comment by ahus1** [comment]
I think "when the write queue has been reduced to maxSize / 2" is an implementation detail and should be removed.

But how often (once only vs. every time) should be added, as it is important for the contract and how the client should implement it. Implementations should be updated to call it as often as stated in the contract.

**Comment by vietj** [comment]
@ahus1 I think that what does not matter is not how often, the important point is that the handler should be set when the stream is full in order to be called when it becomes writable
