### ISSUE TITLE
Using Netty 4.1's codecs from within Vert.x

### ISSUE THREAD

**Issue by testark** [eclipse/vert.x#1520]
Netty has a bunch of codecs (namely `codec-smtp` and `codec-mqtt`) which I'd like to use from within Vert.x. Is there any way I can plug them directly into a `NetServer` so that they encode/decode `Buffer`s or do I have to "manually" handle encoding/decoding using these (which seems to be hard enough as `encode`/`decode` methods are `protected` inside `final` classes)?

**Comment by vietj** [comment]
@testark Vert.x provides access to the Netty event loop (ContextInternal#nettyEventLoop) so you can build your own Netty server integrated with Vert.x event loop. Then you can wrap this using a Vert.x-y API (which can be polyglot). I can provide an example of this if you need.

**Comment by testark** [comment]
@vietj many thanks! It would be great if you could provide the example indeed :-)

**Comment by vietj** [comment]
will do, just need to find a simple and relevant example, any suggestion ?

**Comment by testark** [comment]
@vietj I could think of a simple server that would receive an MQTT `CONNECT` packet and respond with a `CONNACK` with the `0x03` return code and closing the connection, for example.

**Comment by vietj** [comment]
I was more thinking at an example using a Netty codec and exposing it as a Vert.x API

**Comment by vietj** [comment]
@testark do you have an idea of a minimal server using netty codec-mqtt that would call vertx business code ?

**Comment by vietj** [comment]
@testark I've added a chapter to the Vert.x random writings there https://github.com/vietj/vertx-materials . There is a new section about Netty integration both client and server.
