### ISSUE TITLE
Load the ndots value on linux from /etc/resolv.conf and allow a value of 0

### ISSUE THREAD

**Issue by poiuytrez** [eclipse/vert.x#1525]
I have issues to run a webserver connected to a redis server with Vert.x 3.3.2 in a docker environment. I get the following error: 
```
webserver               | java.net.UnknownHostException: failed to resolve 'my-redis.home'. Exceeded max queries per resolve 3
webserver               | 	at io.vertx.core.dns.impl.fix.DnsNameResolverContext.finishResolve(DnsNameResolverContext.java:435)
webserver               | 	at io.vertx.core.dns.impl.fix.DnsNameResolverContext.tryToFinishResolve(DnsNameResolverContext.java:362)
webserver               | 	at io.vertx.core.dns.impl.fix.DnsNameResolverContext$2.operationComplete(DnsNameResolverContext.java:160)
webserver               | 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:518)
webserver               | 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:492)
webserver               | 	at io.netty.util.concurrent.DefaultPromise.notifyListenersWithStackOverFlowProtection(DefaultPromise.java:431)
webserver               | 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
webserver               | 	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:99)
webserver               | 	at io.vertx.core.dns.impl.fix.DnsQueryContext.setSuccess(DnsQueryContext.java:197)
webserver               | 	at io.vertx.core.dns.impl.fix.DnsQueryContext.finish(DnsQueryContext.java:180)
webserver               | 	at io.vertx.core.dns.impl.fix.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:680)
webserver               | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
webserver               | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
webserver               | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
webserver               | 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
webserver               | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
webserver               | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
webserver               | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
webserver               | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1320)
webserver               | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
webserver               | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
webserver               | 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:905)
webserver               | 	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
webserver               | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:563)
webserver               | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:504)
webserver               | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:418)
webserver               | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:390)
webserver               | 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
webserver               | 	at java.lang.Thread.run(Thread.java:745)
```

It works perfectly with Vert.x 3.2.1.

I made a repoducer: 
https://github.com/poiuytrez/vertx-redis-issue-reproducer

**Comment by vietj** [comment]
hi @poiuytrez can you try this branch ? it should fix the issue you are seing.

**Comment by poiuytrez** [comment]
Thank you. However, I am having a hard time to compile Vert.x Core. I have many errors like:
Error:(147, 5) java: cannot find symbol
  symbol:   variable OptionConverter
  location: class io.vertx.core.cli.Option

This option class seems to be in the generated folder. I am not sure on how to handle it. I have basically opened the pom.xml with IntelliJ.

**Comment by vietj** [comment]
can you use "mvn clean install" ?

**Comment by vietj** [comment]
otherwise you need to add the src/main/generated in intellij as source

**Comment by vietj** [comment]
src/main/generated right click -> Mark Directory As -> "Source root"

**Comment by poiuytrez** [comment]
I can now compile. However, it is not working (I have the DNS issue). It might be a stupid configuration issue. I will dig on Monday.

**Comment by vietj** [comment]
I tried with the project you provided and it worked for me.

**Comment by poiuytrez** [comment]
I was a mistake on my side. It is working properly 👍

**Comment by vietj** [comment]
glad to hear that :-)

**Comment by jan-zajic** [comment]
Thank you for fix, we having same issue. I rollback our applications to vert.x 3.2.1 until new version with this fix will be released.

**Comment by vietj** [comment]
@jan-zajic you can use the system property `-Dvertx.disableDnsResolver=true` to disable the resolver and have the same behavior than 3.2.1

**Comment by ernestojpg** [comment]
Hello guys,

I'm using Vert.x 3.3.3 but still having the issue. Note that the stack trace is slightly different now:

```
java.net.UnknownHostException: failed to resolve 'keycloak-server'. Exceeded max queries per resolve 3
	at io.netty.resolver.dns.DnsNameResolverContext.finishResolve(DnsNameResolverContext.java:476)
	at io.netty.resolver.dns.DnsNameResolverContext.tryToFinishResolve(DnsNameResolverContext.java:398)
	at io.netty.resolver.dns.DnsNameResolverContext$3.operationComplete(DnsNameResolverContext.java:193)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:488)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:102)
	at io.netty.resolver.dns.DnsQueryContext.setSuccess(DnsQueryContext.java:195)
	at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:178)
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:694)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:551)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:465)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)
```

I'm running the containers using Docker for Mac version 1.12.1.
The content of the `/etc/resolv.conf` file inside my container is:
```
search local
nameserver 127.0.0.11
options ndots:0
```

Any ideas?

**Comment by vietj** [comment]
what is the full name of "server-keycloak" to be resolved ?

**Comment by ernestojpg** [comment]
Hello @vietj ,

Inside the container, a ping command is resolved correctly:
```
ping keycloak-server
PING keycloak-server (172.18.0.4): 56 data bytes
64 bytes from 172.18.0.4: icmp_seq=0 ttl=64 time=0.143 ms
64 bytes from 172.18.0.4: icmp_seq=1 ttl=64 time=0.096 ms
64 bytes from 172.18.0.4: icmp_seq=2 ttl=64 time=0.095 ms
64 bytes from 172.18.0.4: icmp_seq=3 ttl=64 time=0.138 ms
```
But the vert.x application cannot resolve the "keycloak-server" hostname.

**Comment by vietj** [comment]
I'm using a mac too, can you provide a docker compose file for reproducing it ?

**Comment by ernestojpg** [comment]
Sure, I was trying to run this tutorial:

https://github.com/sczyh30/vertx-blueprint-microservice

**Comment by ernestojpg** [comment]
Hi @vietj ,

Were you able to reproduce it? Did you want me to open a separate issue?

**Comment by ernestojpg** [comment]
Hi @vietj ,

Just to let you know that updating to Docker Mac version 1.12.3 (13776) solves the issue :)

Regards.

**Comment by vietj** [comment]
how does it solve it ?

**Comment by ernestojpg** [comment]
I don't know, but everything works fine for me now ... :\

These are the Release Notes: https://docs.docker.com/docker-for-mac/release-notes/#/docker-for-mac-1123-2016-11-09-stable

**Comment by vietj** [comment]
this issue has been fixed in Netty and Vert.x though so it should not have happened anymore

**Comment by stempler** [comment]
I also had this problem after upgrading from VertX 3.2.1 - same behavior for all versions up to 3.4.1, running as container on Docker 1.11. The workaround w/ setting the system property and disabling the DNS resolver worked for me.

**Comment by vietj** [comment]
we might change this for Vert.x 3.5 and have the async resolver to be an external resolver and go back to the previous config out of the box

**Comment by jacek-** [comment]
Hi,

I hit the same issue and, digging a little, found that the underlying problem is in the netty dns resolver.
I can successfully run `ping` and plain-java dns resolution, like:

    import java.net.InetAddress;
    public class Test {
        public static void main(String args[]) throws Exception {
                InetAddress address = InetAddress.getByName("my-container-name");
                System.out.println(address.getHostAddress());
        }
    }

whereas the same with the netty resolver fails as reported by the OP:

    import io.netty.channel.nio.NioEventLoopGroup;
    import io.netty.channel.socket.nio.NioDatagramChannel;
    import io.netty.resolver.dns.DnsNameResolverBuilder;
    import io.netty.resolver.dns.DnsNameResolver;
    import io.netty.resolver.dns.DnsServerAddresses;

    public class TestNetty {
      private static NioEventLoopGroup bossGroup = new NioEventLoopGroup();

      public static void main(String[] args) throws Exception {
        DnsNameResolver res = new DnsNameResolverBuilder(bossGroup.next()).channelType(NioDatagramChannel.class).build();
        System.out.println(res.resolve("my-container-name").await().get());
      }
    }

And yes `-Dvertx.disableDnsResolver=true` works for me, too.

**Comment by vietj** [comment]
can you try with more recent Netty versions ?

**Comment by jacek-** [comment]
I was planning to do it but unable before the next week, sorry....

**Comment by jacek-** [comment]
A test with the latest final `4.1.12.Final` shows the same problem. I'm going to report it to the netty team.

**Comment by vietj** [comment]
thanks for the investigation

**Comment by vietj** [comment]
can you link the Netty issue you create to this issue ?

**Comment by jacek-** [comment]
@vietj Just to let you know, netty team has resolved the issue with domain resolution. Please, have a look at   https://github.com/netty/netty/issues/6844 and https://github.com/netty/netty/pull/6885 to find out more details.

Please let me know when the fix is incorporated with the vertx builds.

  Cheers,
  Jacek

**Comment by vietj** [comment]
we need to upgrade the Netty version and also have a gRPC version that runs with the same version at least. Can you creation a new issue to track this error ?
