### ISSUE TITLE
Overloads for CompositeFuture.all() and any() that collect results prior to completion 

### ISSUE THREAD

**Issue by aschrijver** [eclipse/vert.x#1532]
As discussed in this thread on the [Vert.x forum](https://groups.google.com/forum/#!topic/vertx/3V44vLG_LjI) there is a need for an additional set of overloaded static members of both`CompositeFuture.all()` and `CompositeFuture.any()` that have the same behaviour, except that the composite feature completes when _all_ of its constituent futures have completed (regardless of their outcome). The current behaviour has the composite future complete on the first success or failure.

The new method overloads have an additional parameter `collectResults` with a value of `true`.
The existing members will not be changed so as not to break backwards-compatibility and will defer to the composite future implementation with a default value of `false` for `collectResults`.

I will create a PR shortly that will implement this design and provide unit tests.

**Comment by vietj** [comment]
can you review https://github.com/eclipse/vert.x/issues/1555 ?

**Comment by aschrijver** [comment]
Looks good, @vietj ! Overall a better solution than the boolean flag from before..
