### ISSUE TITLE
SystemD watchdog integration

### ISSUE THREAD

**Issue by jhlange** [eclipse/vert.x#1536]
It would be nice if the Vert.x participated with SystemD's status info (starting, started, successful vertical deployment, etc)

and watchdog functions (e.g. add a ping/handle event on the event loops to notify the watchdog, add hooks for the application to do additional checks [on watchdog ping function]), 

It is easy to detect when a daemon is under the control of systemd, as certain environment variables are set, stating the location of a communication socket that can be written to, to notify the system of the process state.

This has an advantage with other external processes that can use systemd service status to determine the health of an instance (e.g. Linux-HA).
## The systemd commands are listed here:

http://0pointer.de/public/systemd-man/sd_notify.html
## An example of interacting with the socket and configuration without pulling in this dependency is here:

https://github.com/antirez/redis/blob/0a628e51025c4307c70cb00094dff9cdd1732f31/src/server.c
**See redisSupervisedSystemd**

An example of watchdog (in config files and being consumed in python is here:
https://gist.github.com/Spindel/1d07533ef94a4589d348

Discovering the ping interval

```
def watchdog_period():
    """Return the time (in seconds) that we need to ping within."""
    val = os.environ.get("WATCHDOG_USEC", None)
    if not val:
        return None
    return int(val)/1000000

```

Pinging on the configured interval

```
def watchdog_ping(address, sock):
    """Helper function to send a watchdog ping."""
    message = b"WATCHDOG=1"
    return sd_message(address, sock, message)
```

Service configuration

```
[Service]
Type=notify
Environment=PROBABILITY=0.1
ExecStart=/tmp/1d07533ef94a4589d348/watchdogged.py

Restart=always
RestartSec=30
WatchdogSec=1
```

**Comment by pmlopes** [comment]
I'm not fully aware of systemD details but i believe it uses a UNIX Socket to communicate with the daemon process. You don't have support for that out of the box in java i think.

The example and docs you show are C so not really applicable to the JVM.

If you want a simple way to notify systemD you could look at:

https://gist.github.com/yrro/18dc22513f1001d0ec8d

But be aware that that code spawns a new process for each notification (sure it is a short lived process, but it blocks for the status of the process anyway and blocking is not a good idea in vert.x.

**Comment by jhlange** [comment]
It seems to be supported by netty: https://github.com/netty/netty/pull/3344 .

I imagine vert.x could have several different service host providers, and could integrate with others [though I am not familiar with the required APIs], to connect to the ones in windows and elsewhere.

I have not had time to look into the integration details, but it shouldn't be too hard to do so.

**Comment by pmlopes** [comment]
We'll wait for your pull request ;)

**Comment by vietj** [comment]
I think it should rather be an external metrics implementation.

In addition vertx now supports domain sockets, so it makes this possible.

Please reopen an issue in vert-x3/issues instead if you plan to contribute this.
