### ISSUE TITLE
RxHelper should have an api to use WorkerExecutor

### ISSUE THREAD

**Issue by testn** [eclipse/vert.x#1538]
Since Vert.x 3.3 allready exposes  WorkerExecutor, RxHelper should have a convenient method to let RX to run on the custom workerexecutor.

**Comment by vietj** [comment]
This is the wrong project, can you open it in the vert-x3/vertx-rx project please ?

**Comment by testn** [comment]
I added https://github.com/vert-x3/vertx-rx/issues/45
