### ISSUE TITLE
Use unmodified hostname in exception about dns failure

### ISSUE THREAD

**Issue by alexlehm** [eclipse/vert.x#1541]
currently or with the new resolver code, the exception about dns failure mentions the hostname with a search suffix appended, e.g.

resolution of hostname.unknown.internal.mydomain.com failed, I this it would be better to put the original hostname from the resolver call into the error message

**Comment by vietj** [comment]
I guess it should be fixed in Netty.

**Comment by alexlehm** [comment]
You are right, the exception message is created in netty.
I will write an issue for it.

**Comment by alexlehm** [comment]
https://github.com/netty/netty/issues/5602

**Comment by alexlehm** [comment]
the pr was merged by Norman, so this will probably be in netty 4.1.5. I will close this issue as no change is required in vert.x

**Comment by vietj** [comment]
agreed, it's good to improve this, however it's not a critical fix per se.
