### ISSUE TITLE
BodyEndHandlers can be called after the full response has been read & flushed.

### ISSUE THREAD

**Issue by fzakaria** [eclipse/vert.x#1553]
BodyEndHandlers registered on the `HttpServerResponse` can be executed on the `EventLoop` thread after the response has been wholly received.

This is not-consistent with what the _javadocs_ have written

>  Add a handler that will be called just before the response body has been completely written. This gives you a hook where you can write any extra data to the response before it has ended when it will be too late.

Here is a test case that demonstrates this:

```
import io.vertx.core.Handler;
import io.vertx.core.Vertx;
import io.vertx.core.http.HttpServer;
import io.vertx.ext.web.Router;
import org.apache.http.client.fluent.Content;
import org.apache.http.client.fluent.Request;
import org.assertj.core.api.Assertions;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * {@link io.vertx.core.http.HttpServerResponse#bodyEndHandler(Handler)} is called afer the response has been written
 * to the channel. There's no guarentee it will occur before the client has consumed the request fully.
 */
public class VertxBugDemonstrateIT {

    private Vertx vertx;

    @BeforeClass
    public void beforeClass() {
        vertx = Vertx.vertx();
    }

    @AfterClass
    public void afterClass() {
        if (vertx != null) {
            vertx.close();
        }
    }

    @Test
    public void testDemonstrateBodyEndHandler() throws Exception {
        String message = "Hello World!";
        AtomicBoolean bodyEndHandlerHit = new AtomicBoolean();
        Router router = Router.router(vertx);
        router.route().handler(context -> {
            context.addBodyEndHandler(v -> {
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    Assertions.fail("Interrupted exception");
                }
                bodyEndHandlerHit.set(true);
            });
            context.response().end(message);
        });

        CountDownLatch serverStartedLatch = new CountDownLatch(1);
        final HttpServer server = vertx.createHttpServer().requestHandler(router::accept).listen(0, event -> {
            serverStartedLatch.countDown();
        });
        serverStartedLatch.await();

        int port = server.actualPort();

        bodyEndHandlerHit.set(false);
        //Blocking call
        Content context = Request.Get(String.format("http://localhost:%s", port)).execute().returnContent();
        Assertions.assertThat(context.asString()).isEqualTo(message);
        Assertions.assertThat(bodyEndHandlerHit.get()).isTrue();
    }

}
```

**Comment by fzakaria** [comment]
Within `HttpServerResponseImpl#end0` we can see that the bodyEndHandlers are called after the headers & body have been written to the channel.

I don't see how the client can expect to write any additional data in the bodyEndHandler.
(it should be called at the start of end0 likely)

**Comment by fzakaria** [comment]
@vietj both javadocs sound incorrect.
In both cases, the handlers are **not** called before the last part of the body is written to the wire
(as proof of my test case)

A better javadoc
"Provides a handler that will be called after the last part of the body is written to the wire.
 The handler may be called independently of when the response has been received. 
 This provides a hook allowing you to do more operations once the request has been sent over the wire"

**Comment by vietj** [comment]
@fzakaria agreed but first of all I would like to understand the original use case for this feature, i.e what the original intent is

**Comment by fzakaria** [comment]
@vietj Sounds good.

**Comment by pmlopes** [comment]
@vietj the original use case for this feature (in vertx-web) was to provide a simple clean up mechanism. The simplest examples is the logger handler, once a request is ended the end handler will be called and print out the final response status plus content length.

It was never conceived to allow writing after the last end was called.

**Comment by vietj** [comment]
so the fix is to change the javadoc in vertx-web

**Comment by vietj** [comment]
@fzakaria could you contribute a javadoc change for vertx-web as per your suggestion ?

**Comment by vietj** [comment]
thanks @pmlopes

**Comment by fzakaria** [comment]
@vietj I added fixes for vert.x web and core.
Please see PRs linked to the issue.

**Comment by vietj** [comment]
thank you

**Comment by fzakaria** [comment]
@vietj there's the vert.x-web fix too :)
