### ISSUE TITLE
netty resolver may get ipv6 addresses even when only ipv4 is available

### ISSUE THREAD

**Issue by alexlehm** [eclipse/vert.x#1570]
Following up on this groups thread https://groups.google.com/d/topic/vertx/7xTo_a_lOWk/discussion, it is necessary to switch to the next netty version 4.1.5 when it becomes available to get fix for the issue that the resolver might get a ipv6 address even though only ipv4 is available and is unable to connect to the address. This behaviour is switched off by -Djava.net.preferIPv4Stack=true, which was not honoured by the new resolver in netty 4.1.

The netty issue for the issue is https://github.com/netty/netty/issues/5657

**Comment by alexlehm** [comment]
issue is resolved in netty 4.1 branch

**Comment by vietj** [comment]
we can close this issue, right ?

**Comment by alexlehm** [comment]
yes, sorry i forgot about this issue. this was fixed with the netty update to 4.1.5

**Comment by alexlehm** [comment]
resolved by netty 4.1.5

**Comment by pacman123** [comment]
Is this issue closed? I can still see vertx3.5 dependent on 4.1.15. https://mvnrepository.com/artifact/io.vertx/vertx-core/3.5.0
