### ISSUE TITLE
HttpServerResponse.sendFile() returns status code 200 for non existing file

### ISSUE THREAD

**Issue by leolux** [eclipse/vert.x#1571]
Usually I would expect a webserver to respond with status code 404 for a non existing resource. Today I noticed that sendFile("doesnotexists.js") returns 200 with content-length = 0 instead of 404.

Does it work as expected? Regarding the javadoc [1] there is no word about status codes.
Btw, does sendFile() really bypass the userspace when using SSL?

[1] http://vertx.io/docs/apidocs/io/vertx/core/http/HttpServerResponse.html#sendFile-java.lang.String-long-long-

**Comment by vietj** [comment]
@leolux would you mind to contribute a unit test and a patch ?

with SSL, I believe that it does not bypass it, at least for HTTP/2 it does not use FileRegion stuff

**Comment by vietj** [comment]
@pmlopes we have similar functionality in vertx web with web server, how does that sound to you ?

**Comment by leolux** [comment]
Yeah, I like to give a first try to create/add a unit test for vert.x. I think that I should have enough time in the next week.

**Comment by pmlopes** [comment]
I think web handles this properly, but the static content handler does the validation of existence, etc... Setting the right status and headers before calling the sendfile method.

**Comment by vietj** [comment]
@leolux don't wait too long, there is 3.3.3 around the corner

**Comment by pmlopes** [comment]
I'm not sure if sendFile should return 404, the call exists as a way to stream from a file to the response and there is a variation of the call that should catch errors. Also on core there is no notion of error handler so automatically handling errors goes against the unopionated aspect of vertx no?

**Comment by vietj** [comment]
@pmlopes tha'ts a good opinion - so you mean that sendFile should just send data to the client and not interpret like a web server would do ? I tend to agree with you too

**Comment by leolux** [comment]
Totally agree that the handling of FileNotFoundExceptions should stay in the responsibility of the caller. Currently, this can easily be done by passing a resultHandler to the method sendFile().

As we agree on the benefits of an unopinionated implementation of HttpServerResponseImpl the issue can be closed.
