### ISSUE TITLE
Is it possible to get EventLoop for verticle by using open API only?

### ISSUE THREAD

**Issue by avasenin** [eclipse/vert.x#1572]
I need to get verticle's `EventLoop` to use it in netty-based library. I want to reuse it to avoid any issues with synchronization. I found only how to get `EventLoopGroup` but in this case this library will be executed on different `EventLoop`.

I found another way by using internal structure case `((ContextImpl) vertx.getOrCreateContext()).nettyEventLoop();` 

Is it possible to add this method to `Context` interface?

**Comment by cescoffier** [comment]
Check this article explaining how to do it:
https://github.com/vietj/vertx-materials/blob/master/src/main/asciidoc/output/Integrating_Netty.adoc

**Comment by avasenin** [comment]
They are using cast to `ContextInternal` interface. But this interface has note in JavaDoc
```
 * This interface provides an api for vert.x core internal use only
 * It is not part of the public API and should not be used by
 * developers creating vert.x applications
```

I'm asking about public API like `Vertx#nettyEventLoopGoup`. We have a public API to get EventLoopGroup but we don't have a public method to get EventLoop

**Comment by vietj** [comment]
@avasenin I think it's relatively safe to use these methods from `ContextInternal` for such case. `nettyEventLoop()` could be eventually moved to `Context` (like `nettyEventLoopGroup` in `Vertx`), however I think `executeFromIO` would be rather confusing to the normal developer.

Overall the methods in `ContextInternal` and `VertxInternal` provide more for doing integration with Vert.x, however these are subject to change from time to time but that's something we'd rather avoid to do, i.e only do it if there is a clear justification.

If we move such methods in the _public_ API, then it would be harder to change them.

**Comment by avasenin** [comment]
Thank for answer.
