### ISSUE TITLE
ConnectionHolder should log when queuing messages

### ISSUE THREAD

**Issue by mrothroc** [eclipse/vert.x#1575]
ConnectionHolder creates a queue and inserts messages bound for a remote host if it isn't connected.  It would be very useful it it logged debug messages when this happened.  It would also be exceptionally useful if it logged a warning for failed connection attempts to remote peers, including the attempted host/port.

Also, the queue appears to grow without bound.  It would be good to limit the size of the queue via a config entry, then stop queuing messages for that remote host once that limit is reached.

**Comment by vietj** [comment]
> On Aug 19, 2016, at 7:56 PM, mrothroc <notifications@github.com> wrote:
> 
> ConnectionHolder creates a queue and inserts messages bound for a remote host if it isn't connected. It would be very useful it it logged debug messages when this happened. It would also be exceptionally useful if it logged a warning for failed connection attempts to remote peers, including the attempted host/port.
> 
> 

seems like a good thing.
> Also, the queue appears to grow without bound. It would be good to limit the size of the queue via a config entry, then stop queuing messages for that remote host once that limit is reached.
> 
> 

no one reported problems there so far, have you experienced issues with this queue ?

**Comment by mrothroc** [comment]
We haven't had an issue with the unbounded queue, but that was because we attached a debugger to the server and stepped through it line by line to figure out what was happening.  In our case, the behavior was that some messages would silently "disappear".  While the system was (somewhat) functional, messages were being queued for the unreachable servers.  Our message volumes are high enough that the queue would have grown to consume significant memory.

We're just making this suggestion as defensive programming, and because we could see how this could be a significant issue in production.  However, we did not actually experience this in production as we identified it in development.

**Comment by luengnat** [comment]
there should definitely be a way to limit the size of the queue. Unbound queue size can cause a huge delay instead of allowing the server to fail fast when there is too much load.

**Comment by vietj** [comment]
thanks, that's something we need to flesh out as we are also looking improving the back pressure support for event bus, this seems related to this, as a back-pressured message would be enqueued in such scenario and a non back-pressured would be dropped.

**Comment by tsegismont** [comment]
Fixed in #2087
