### ISSUE TITLE
Bad documentation

### ISSUE THREAD

**Issue by luengnat** [eclipse/vert.x#1592]
In VertxOptions, DeploymentOptions, etc, the option to set the time seems to be documented inconsistently. Some of them are "ms". Some of them are "ns". (Even in the same method).

**Comment by vietj** [comment]
@luengnat can you point them out ?

**Comment by luengnat** [comment]
@vietj 

There could be more. I didn't go through them all.

https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/VertxOptions.java#L400
vs 
https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/VertxOptions.java#L407


https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/DeploymentOptions.java#L333
vs 
https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/DeploymentOptions.java#L340
vs
https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/DeploymentOptions.java#L347
vs
https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/DeploymentOptions.java#L349

**Comment by EmadAlblueshi** [comment]
@vietj are all of them in "ms" instead of "ns" ?

**Comment by EmadAlblueshi** [comment]
https://github.com/eclipse/vert.x/pull/1696
