### ISSUE TITLE
[Question] Current approaches and best practices for Dependency Injection on VertX

### ISSUE THREAD

**Issue by kennedyoliveira** [eclipse/vert.x#1595]
Hello There,

looking in the documentation and searching i didn't find any current approaches nor best practices for Dependency Injection with vertx, so i'm asking here for advices i hope someone can share their knowledge and approaches about that subject.

Maybe explaining my current problem could help you understand why i have doubts.

Currently i'm developing an service for integration with an external third party service, that integration will be via REST api calls.

In the current design, i have a Service that 'll handle the communication with this third party service, doing the network call, and this Service has 2 more dependencies, that works fine with Dependency Injection, based on Google Guice, the problem is, to do the network call i need a vertx instance to create the HttpClient, and i'm doing this to inject it: 

````
InjectorBuilder.fromModules(modulos)
              .overrideWith(new AbstractModule() {
                @Override
                protected void configure() {
                  bind(io.vertx.rxjava.core.Vertx.class).toInstance(io.vertx.rxjava.core.Vertx.newInstance(vertx)); // pretty weird solution, i think there maybe problems with this approach too, but don't know what problem
                  bind(MongoClient.class).toInstance(mongoClient); // Another weird solution for injecting it in a service :s
                }
              })
              .createInjector();
````

As you see, i'm sure that must have another way of doing it, because this approach i used is just for the sake of working, but i think maybe could have problems.

As you see on the binding, i use mongodb, i inject it in a class responsible for persisting the data, looks pretty weird too me too.

Could someone share their knowledge about it? How do you design your services / persistence modules to talk to vertx?

Thanks, and sorry for my english, if i failed somewhere.

**Comment by vietj** [comment]
Hi,

could you post this on vertx google group ? https://groups.google.com/forum/#!forum/vertx

that's where such kind of discussion happens.

thanks

**Comment by kennedyoliveira** [comment]
@vietj, i opened a topic there, thank you.
