### ISSUE TITLE
Making coming release compatible with RxJava2

### ISSUE THREAD

**Issue by SercanKaraoglu** [eclipse/vert.x#1610]
RxJava has just come out with one of the biggest [release candidate](https://github.com/ReactiveX/RxJava/releases) which includes bug fixes cleanups and improvments they changed whole api with this it is now closer to Java 8 and I would like vertx to be compatible with coming releases of RxJava

**Comment by vietj** [comment]
Hi,

can you open an issue in https://github.com/vert-x3/issues/issues with the wishlist tag instead ?

thanks

**Comment by vietj** [comment]
https://github.com/vert-x3/issues/issues/189
