### ISSUE TITLE
Infinite skip of control characters in an http request (beyond size limits)

### ISSUE THREAD

**Issue by mhstnsc** [eclipse/vert.x#1614]
Steps:
- have a web server 
- run from bash `while true; do printf '\xD'; done | netcat localhost 80`

The connection is not dropped. An attacker could keep connection open and slowly stream control characters.

The problem is caused by: https://github.com/netty/netty/issues/5796
however i am using Vert.x, that's why i also filed the bug here. 

I think Vert.x could fix the problem by adding some new ChannelHandler in the function below.

```
private void configureHttp1(ChannelPipeline pipeline) {
    if (logEnabled) {
      pipeline.addLast("logging", new LoggingHandler());
    }
    if (USE_FLASH_POLICY_HANDLER) {
      pipeline.addLast("flashpolicy", new FlashPolicyHandler());
    }
    pipeline.addLast("httpDecoder", new HttpRequestDecoder(options.getMaxInitialLineLength()
        , options.getMaxHeaderSize(), options.getMaxChunkSize(), false));
    pipeline.addLast("httpEncoder", new VertxHttpResponseEncoder());
    if (options.isCompressionSupported()) {
      pipeline.addLast("deflater", new HttpChunkContentCompressor());
    }
    if (sslHelper.isSSL() || options.isCompressionSupported()) {
      // only add ChunkedWriteHandler when SSL is enabled otherwise it is not needed as FileRegion is used.
      pipeline.addLast("chunkedWriter", new ChunkedWriteHandler());       // For large file / sendfile support
    }
    if (options.getIdleTimeout() > 0) {
      pipeline.addLast("idle", new IdleStateHandler(0, 0, options.getIdleTimeout()));
    }
    pipeline.addLast("handler", new ServerHandler(pipeline.channel()));
  }
```

**Comment by vietj** [comment]
can you tell how to reproduce it ?

**Comment by mstanescu** [comment]
`while true; do printf '\xD'; done | netcat localhost 11800`

**Comment by mstanescu** [comment]
I would also be happy if there would be a way to register a custom HttpRequestDecoder. This way these problems can be fixed fast

**Comment by creativeprogramming** [comment]
They surely can help you defining a way to register a custom HttpRequestDecoder (e.g. you can create a new HttpServerOption to set the custom request decoder class name )  anyway first of this can you please share your solution to the issue? Maybe having a '... extends HttpRequestDecoder ' class from you in a PR can speed up validation of that issue and proposed patch.

How do you want to handle this case? With a timeout? Or counting skipped chars into the limit?

**Comment by mhstnsc** [comment]
I had some talks with the netty guys and probably the solution is to include this into the limit. Maybe patch netty i just did not find the time for it but eventually i should. 

Ill keep you updated

**Comment by vietj** [comment]
thanks @mhstnsc - let's use this place for follow up

**Comment by vietj** [comment]
@mhstnsc any news about this ?

**Comment by mhstnsc** [comment]
Some good news. Eventually was fixed by one of my collegues in our local fork. I hope to create a pull request to netty guys. 
In our fork we took the code from netty, patched it and wired in vertx.

**Comment by vietj** [comment]
when you make an issue in Netty, can you link it to this one ?

**Comment by mhstnsc** [comment]
it is already linked

**Comment by vietj** [comment]
indeed I missed it, I was expecting to see a GitHub linkage in the page actually

**Comment by mhstnsc** [comment]
I don't know how to do that.

**Comment by vietj** [comment]
you can handle this case using `HttpServerOptions` idleTimeout that will close the connection when there is no HTTP activity after `n` seconds

**Comment by vietj** [comment]
I will add a reproducer for this case solved by idle timeout

**Comment by vietj** [comment]
labelled it as question
