### ISSUE TITLE
Add client side support for intercepting idle peers.

### ISSUE THREAD

**Issue by shvalb** [eclipse/vert.x#1622]
Hi,

When working with the following configuration: HttpServer using SockJS and Eventbus with Javascript eventbus in Google Chrome.

Those are the steps to  enable idle peers disconnecting when timeout occurs:

1.  Server:
```
BridgeOptions bridgeOpt = new BridgeOptions().setPingTimeout(timeout);
sockJSHandler.bridge(bridgeOpt,...);
```

2. Client:
`new EventBus(this.address, {"vertxbus_ping_interval": timeout_value});`

This works great, the only problem is that when server detects idle and disconnects client it's impossible for server to know the reason it could be de to client closing the browser application or client is idle.

Required:
Add client-side support so client also recognize that it has been disconnected from server due to timeout.

Thank You!

**Comment by shvalb** [comment]
> My configuration is HttpServer using SockJS and Eventbus with Javascript eventbus in Google Chrome.
> 
> I'm trying to set idle timeout when peer is on idle.

r

**Comment by vietj** [comment]
@shvalb this is rather something to be discussed on vertx-web GitHub repo, not here

**Comment by vietj** [comment]
can you move this issue there ?

**Comment by shvalb** [comment]
We did discuss it and that's what you guys agreed...

**Comment by vietj** [comment]
can you describe what would be the feature in vertx core ?

**Comment by shvalb** [comment]
Let me find the discussion on Google group..
[](https://groups.google.com/forum/#!topic/vertx/bMnzUH1LIHw)

I asked for a way to recognize idle peer on the Vertx core, but Pablo Lopez said that he doesn't want to change the protocol and it should be done in the client-side - and you confirmed....
honestly, I prefer it to be in the core!

**Comment by vietj** [comment]
@shvalb actually Paulo was referring to https://github.com/vert-x3/vertx-web/tree/master/vertx-web/src/client so it's in vertx-web

**Comment by shvalb** [comment]
I understood it's the simple javascript library from this comment:

"When i referred to a custom ping handler i wanted to say that it would be done at the client side in the vertx-eventbus.js I'm not proposing a change in the protocol."

If it would be done in vertx-web - that's GREAT news!! that the natural place for it 👍 

Do you have any estimation when it will be done? I'm eager for this one :-)

**Comment by vietj** [comment]
actually it's now just a request for feature, then the implementation would be done at some point. Obviously that is something you can contribute to help and make it implemented faster.

**Comment by vietj** [comment]
closing this issue
