### ISSUE TITLE
Log4j2 impl does not support logging method name and line number properly

### ISSUE THREAD

**Issue by alexlehm** [eclipse/vert.x#1634]
As reported on the groups https://groups.google.com/d/topic/vertx/6vwSXfcTlXs/discussion
the Log4j2 implementation does not log the method name and line number of the log statement, rather it logs  Log4j2LogDelegate.log():151 which is the log call in the log impl.

To fix this, it is necessary to provide the class name of the logger class and use logger.logMessage with ExtendedLoggerWrapper as described here https://issues.apache.org/jira/browse/LOG4J2-824

**Comment by alexlehm** [comment]
Casting Logger to ExtendedLogger and using logIfEnabled might be sufficient

**Comment by InfoSec812** [comment]
Thanks for picking up on this so quickly!!! Much appreciated!

**Comment by alexlehm** [comment]
added integration test for the issue
