### ISSUE TITLE
JsonObject#getMap() differs for json from string or built by chaining multiple JsonObjects

### ISSUE THREAD

**Issue by marcinczeczko** [eclipse/vert.x#1637]
I found some inconsistency in the underneath map of JsonObject. It looks to me as some inconsistency in how JsonObject builds underlying map. 

Consider following scenario.
1. Given I have Json as string received from some source, e.g.:
```json
{
   "data": "foo",
   "my": {
      "data": "foo"
   }
}
```
2. I can build JsonObject and then get it as map. "my" object is represented as below in the map
```
data=class java.lang.String
my=class java.util.LinkedHashMap
```
3. However, if I add another object to that json programatically, such as: json.put("other", new JsonObject().put("some","data")); and then will get it again as map, then "other" is not represented as Map
```
data=class java.lang.String
my=class java.util.LinkedHashMap
other=class io.vertx.core.json.JsonObject
```
If I'd use JsonObject methods to access any element in my json it would be fine. However, I'm doing this processing as explained above and finally convert it to Map as other elements of the system requires Map. However, current behavior is cumbersome, and when working with JsonObject by adding some new nested object I need literally use Maps to get consistency, I'd prefer to use JsonObject methods as they are fluent and more readable.

Below is very simple piece of code that you can see what I mean:
```java
    String jsonRaw = "{\"data\": \"foo\",\"my\": {\"data\": \"foo\"}}";

    JsonObject json = new JsonObject(jsonRaw);

    json.getMap().entrySet().stream()
            .forEach(entry -> System.out.println(entry.getKey()+"="+entry.getValue().getClass()));

    //I can go through Map and access my objects using map interface
    Map<String, Object> my = (Map<String, Object>)json.getMap().get("my");
    System.out.println(my.get("data"));

    System.out.println("--- Adding new object---");
    json.put("other", new JsonObject().put("some", "data"));

    json.getMap().entrySet().stream()
            .forEach(entry -> System.out.println(entry.getKey()+"="+entry.getValue().getClass()));

    //In this case I need to get JsonObject from map, then get Map in order to access data. 
    // it breaks the whole idea that JsonObject can be represented by Map.
    JsonObject other = (JsonObject)json.getMap().get("other");
    System.out.println(other.getMap().get("some"));
```

**Comment by vietj** [comment]
the getMap returns the underlying map that does not do the rewrapping, i.e it returns the map as is, so this is expected.

**Comment by marcinczeczko** [comment]
It would be useful to have this behavior somehow reflected in Javadoc for instance. 
However, it means that if at some point I'd need to use underlying map of JsonObject/Array then I can't mix JsonObject creation from String and modification of it using fluent API. 
Because the Json parsed from string will result different Map structure than Json build using api. Am I right ?

**Comment by vietj** [comment]
@marcinczeczko the thing is that when one use the JsonObject(Map) constructor, anything can be in the map and then the JsonObject wrapper will try to make its best to remap the entries. Entry remapping is done lazily, hence the behavior you observe.

Alternatively if you make a copy() of this JsonObject, the new map will be correct, so doing copy().getMap() should return a correct map.

**Comment by vietj** [comment]
yes probably it should be in the javadoc

**Comment by vietj** [comment]
added in the javadoc
