### ISSUE TITLE
Improve HttpClientRequest reset support

### ISSUE THREAD

**Issue by vietj** [eclipse/vert.x#1642]
Currently we support `HttpClientRequest#reset()` for HTTP/2 connections.

The support could be extended to:

- HTTP/1.x with keep-alive : close the current connection
- HTTP/1.x with pipe-lining : wait until all pending responses have been received and then close connection
- request not yet connected : the request has been queued waiting for a connection or perhaps it is triggered the creation of the connection, however the request should not be made anymore : simply put the connection back in the pool and let the pool find another request for this connection

It is useful for supporting reverse proxies implementations with Vert.x : when the client of the proxy sends an entity and something wrong happens (like an exception signed by the `HttpServerRequest#exceptionHandler`) the corresponding `HttpClientRequest` can be reset. For HTTP/2 it is natively supported, for HTTP/1.x this means closing the connection (and waiting for responses in case of pipelining). Having this behavior built-in the reset method for HTTP/1.1 makes easy to implement this for the proxy implementation.

**Comment by vietj** [comment]
@EricWittmann any thought ?

**Comment by EricWittmann** [comment]
This makes a lot of sense to me.  

Although in the case of the reverse proxy, it's not clear to me exactly under what conditions the server request exception handler would be invoked.  It's probably easy enough to figure that out though.

How about you, @msavy - what do you think?

**Comment by vietj** [comment]
in case of Http2 it could be a stream reset with the `StreamResetException`
