### ISSUE TITLE
WebSocketStreamImpl does not warn that it will ignore exceptionHandler and endHandler

### ISSUE THREAD

**Issue by gitplaneta** [eclipse/vert.x#1656]
If I use `webSocketStream(...)` and I chain  `exceptionHandler(...)` after the `handler(...)` method, the exception handler will be ignored, as the connection is established immediately after `handler(...)` call. Here's an example:

``` scala
 httpsClient.websocketStream(servicePort, serviceAddress, "/endpoint/" + data)
      .handler(wsPromise.success(_))
      .exceptionHandler(wsPromise.failure(_)) //this handler is ignored
```

Do you think it's reasonable if I create a PR with a state check whether a handler was already called? I think this way it's less misleading.

**Comment by vietj** [comment]
actually the right fix would be instead to have a method that is like:

```
HttpClient#websocket(port, host, uri, Handler<AsyncResult<WebSocket>>);
```

Using a stream for this was a mistake, so I would rather not do anything.

**Comment by vietj** [comment]
thanks for having concerns !

**Comment by vietj** [comment]
that being said you can make a PR for the documentation.
