### ISSUE TITLE
JsonObject.getByPath() (JsonPath implementation)

### ISSUE THREAD

**Issue by aesteve** [eclipse/vert.x#1661]
A lot of libraries offer the opportunity to use [JsonPath](http://goessner.net/articles/JsonPath/) to query json data. It's becoming quite a standard, like XPath, GPath, etc. (main inspiration for opening this issue comes from [gatling](http://gatling.io/#/))

In my opinion it could be a nice addition to the JsonObject / JsonArray implementations especially for testing (maybe for http clients, too).

Use-case :

```java
Double firstBookPriceInclTaxes =  json.getJsonArray("books").getJsonObject(0).getJsonObject("pricing").getDouble("inclTaxes");
Double firstBookPriceInclTaxes = json.getByPath("$.books[0].pricing.inclTaxes");
```
Or even better
```java
Collection<Double> allBookPricesInclTaxes = json.getJsonArray("books").stream().map(o -> ((JsonObject)o).getJsonObject("pricing").getDouble("inclTaxes")).collect(Collectors.toList());
Collection<Double> allBookPricesInclTaxes = json.getByPath("$.books[*].pricing.inclTaxes");
```

Relevant : 
* [a Java implementation](https://github.com/jayway/JsonPath)
* [a discussion in the Google Group](https://github.com/jayway/JsonPath)

Questions before trying to give the implementation a try :
* Do you think the feature is needed (if so, please upvote this issue) ? Or not.
* Should we rely on a third-party library (and thus not reinvent the wheel but add a library to the fatJars, maybe not needed for a lot of clients).

Difficulties : 
* mapping onto objects / typing may be very difficult : `json.getByPath("$.items[*].id")` will return a collection of Integers (or JsonArray ?) whereas `json.getByPath("$.items[0]")` will return a JsonObject : this might be very tricky
* dealing with errors ?
* ...

**Comment by pmlopes** [comment]
If we re-introduce the JsonElement as a common parent class for both JsonArray and JsonObject then your `getByPath(...)` method could just return `JsonElement` you would still to either check if it was a Document or an Array but If you know what you're doing you could quickly make a cast to the right type.

**Comment by aesteve** [comment]
Good news, I used to use the `JsonPath`implementation, but there's a standard called [JsonPointer](https://tools.ietf.org/html/rfc6901) which does pretty much the same thing and is integrated into Jackson natively.

So we don't need some json path library or whatever but can just rely on jackson :

We could even mimic the jackson API on `JsonObject`

```java
root.path("response").path("history").getValueAsInt();
```

wdyt guys ? It sounds worth giving the implementation a try, don't you think ?

**Comment by tsegismont** [comment]
Experimentation is rarely a bad thing. That doesn't mean it gets an
automatic passport to merging though :)

2016-10-14 18:23 GMT+02:00 Arnaud Esteve <notifications@github.com>:

**Comment by aesteve** [comment]
Mmmh, this is more "disturbing" than I thought it'd be.

Within JsonObject we already have the value decoded as a Map, and don't keep track of the origin JsonString. So we can't add `pointer(String)` directly on `JsonObject`. What do you think ? Either we add this String attribute on `JsonObject`, or we just add the methods to `io.vertx.core.json.Json` interface ?

Jackson's `JsonNode.at` returns a `JsonNode`, which will not be codegen-friendly, so we will need to add methods like `getInteger`, `getDouble`, this can be done easily.

An example, (in `io.vertx.core.json.Json` interface) :
```java
static JsonObject getJsonObjectByPointer(String json, String pointer) {
    try {
      JsonRoot root = mapper.readTree(json);
      JsonNode node = root.at(path);
      return new JsonObject(mapper.convertValue(node, Map.class));
    } catch (IOException e) {
      throw new DecodeException("Failed to decode:" + e.getMessage());
    }
    return root.at(json);  
}
```

Does this look dirty to you ? Or are you fine that ?

**Comment by tsegismont** [comment]
Given a JSON string and a pointer string, I'm not sure there is another
solution than the one you pointed above. Doesn't look dirty to me, but
definitely something to keep in user codebase.

2016-10-21 10:15 GMT+02:00 Arnaud Esteve <notifications@github.com>:

**Comment by aesteve** [comment]
I agree. Either we hide all that stuff within `JsonObject`, or do nothing and go with user-implementation.

I'm closing the issue. At least if someone looks for `json pointer` he'll find some piece of code to help !

**Comment by vietj** [comment]
isn't something that could be captured in the cookbook ?

**Comment by aesteve** [comment]
Sure, where is it ? googling Vert.x + cookbook only gave me chef recipes.

**Comment by pmlopes** [comment]
@aesteve we would like to collect those in the wiki for now and later once we have a proper site they would get listed there.

**Comment by vietj** [comment]
@pmlopes I think we could just start by creating a new github repository and use only the wiki to collect them with a format

**Comment by vietj** [comment]
something like vertx-cookbook

**Comment by vietj** [comment]
it would have to use asciidoctor and a common layout, then later we can see how to compile that in a document if needed or just leave it as is

**Comment by vietj** [comment]
not a project issue per se
