### ISSUE TITLE
RoutingContext getAsJsonObject throws exception

### ISSUE THREAD

**Issue by MostafaEbrahimi** [eclipse/vert.x#1666]
When sent a json object using some tools(like RestClient firefox) to server throw exception on convert body of request to jsonobject because json sent with some characters like "\n" and JsonObject can not convert this String to JsonObject but "org.json" has not this problem and can convert this string to JSONObject.

**Comment by EmadAlblueshi** [comment]
@Mostafa Hi, I think your issue should be opened in vertx-web with exception  details.

**Comment by vietj** [comment]
@MostafaEbrahimi can you open an issue there and close thisone ?

**Comment by MostafaEbrahimi** [comment]
ok.I will do it.
