### ISSUE TITLE
vertx HttpClient exception handler

### ISSUE THREAD

**Issue by maathavant** [eclipse/vert.x#1673]
Am using vertx 3.3.2. 
httpClient.exceptionHandler is throwing compilation error.
Whether its removed in this version and how to handle connection exceptions.
Could anyone please help on this.

**Comment by vietj** [comment]
can you ask this question on vertx@googlegroups.com ?

**Comment by tsegismont** [comment]
Not sure what you mean. Can you provide a reproducer?

2016-10-13 6:18 GMT+02:00 maathavant <notifications@github.com>:
