### ISSUE TITLE
Move Cookie interface from Vert.x Web to core

### ISSUE THREAD

**Issue by pmlopes** [eclipse/vert.x#1678]
Cookies are not specific from the web framework and if one is doing a HTTP server just with core it would be nice not to re-invent the API.

I'd like to propose to move:

https://github.com/vert-x3/vertx-web/blob/master/vertx-web/src/main/java/io/vertx/ext/web/Cookie.java

to core.

**Comment by vietj** [comment]
that would break the API ?

**Comment by pmlopes** [comment]
well in a small way yes, i don't think it would keep the old package `...ext.web`

**Comment by pmlopes** [comment]
Some extra info, doing this would allow vertx http clients to impersonate a browser which is useful to consume other services. In the same line of thought this could be expanded to provide a multipart mime encoder, which again could be used by http clients and is already used by the mail client.

Its a bit of functionality that is common across several components so imho should be kept on core

**Comment by vietj** [comment]
it seems used a bit around:

https://github.com/search?q=%22import+io.vertx.ext.web.Cookie%22&type=Code&utf8=✓

one possibility is to have Cookie interface in core, have the vertx-web Cookie interface extend it and be deprecated asking user to move to vertx-core cookie ?

**Comment by pmlopes** [comment]
This would make more sense to move to `web-common` however client cookies are not exactly the same as server cookies, so I'll close this issue as it is not relevant anymore.
