### ISSUE TITLE
RoutingContext getAsJsonObject throws exception

### ISSUE THREAD

**Issue by MostafaEbrahimi** [eclipse/vert.x#1679]
When send json to server using some plugins like restful client Firefox get this exception.
The problem is converting String to JsonObject. I test org.json.JSONObject and didn't get this exception.
The problem is by some characters like "\n" which will be added to json string in receiving in server side and JsonObject class can not convert to JsonObject but JSONObject didn't has this problem.

**Comment by pmlopes** [comment]
This issue was moved to vert-x3/vertx-web#471
