### ISSUE TITLE
Incorrect UDP source port in reply packet

### ISSUE THREAD

**Issue by onesse** [eclipse/vert.x#1680]
Hello,
I tried to develop a server receiving and sending UDP packets (see code snippet below). The issue is that the reply packets don't have the correct source port, that is, the port the server listens on.

``` java
public class VerticleUdp extends AbstractVerticle {

    public static final int RECEIVER_PORT = 5000;
    public static final String RECEIVER_HOST = "0.0.0.0";

    @Override
    public void start(Future<Void> fut) {
        // Starting listening on specific socket
        DatagramSocket socket = vertx.createDatagramSocket(new DatagramSocketOptions());
        socket.listen(RECEIVER_PORT, RECEIVER_HOST, asyncResult -> {
            if (asyncResult.succeeded()) {
                socket.handler(packet -> {
                    Buffer buffer = Buffer.buffer(new String("HELLO").getBytes());
                    // Send a Buffer
                    socket.send(buffer, packet.sender().port(), packet.sender().host(), isSent -> {
                        if(isSent.succeeded()){
                        }
                    });
                });
                fut.complete();
                System.out.println("Verticle UDP deployed");
            } else {
                fut.fail( asyncResult.cause());
                System.err.println("VerticleUdpReceiver : Cannot listen port");
            }
        });
    }
}
```

**Comment by onesse** [comment]
Good evening,
I'm not a real developer but I modified your class datagramSocket and implemented a new send function to use Netty's DatagramPacket class : 
```java
DatagramPacket(ByteBuf data, InetSocketAddress recipient, InetSocketAddress sender)
//Create a new instance with the specified packet data, recipient address, and sender address.
```
This function works just fine :smiley: 
Do not hesitate to contact me, if you want more feedback. 
Cheers.

**Comment by vietj** [comment]
@onesse yes we are interested, do you mind contribute the feature ?

**Comment by onesse** [comment]
@vietj I'll try to do something clear and submit a PR
:+1: Thanks

**Comment by onesse** [comment]
@vietj I thought it was a mistake but was only our fault. We didn't use correctly Vert.x to handle UDP packets. 

What we didn't understand : 
We need to use function `listen` to observe incoming packets on a specific port then use the same socket to `send` UDP packet to have the source port equals to the port listen.

Sorry !
