### ISSUE TITLE
Vert.x websocket client doesn't set host header

### ISSUE THREAD

**Issue by paulbakker** [eclipse/vert.x#1683]
The Vert.x websocket client doesn't set a Host header. I'm not sure this can be considered a bug, but I do see other clients behaving different. This is a problem for most load balancer configurations which makes it bit of a usability issue.

A workaround is easy though by passing the header manually:
```
httpClient.websocket(443,"mydomain.com", "/", MultiMap.caseInsensitiveMultiMap().add("Host", "mydomain.com"), ws -> {
```

**Comment by vietj** [comment]
hi @paulbakker , can you provide a reproducer because:

```
  @Test
  public void testHostHeaders() throws Exception {
    server = vertx.createHttpServer(new HttpServerOptions().setPort(HttpTestBase.DEFAULT_HTTP_PORT));
    server.requestHandler(req -> {
      req.response().setChunked(true).write("connect");
    });
    server.websocketHandler(ws -> {
      for (String name : ws.headers().names()) {
        System.out.println(name + ": " + ws.headers().get(name));
      }
      ws.write(Buffer.buffer("ok"));
    });
    server.listen(onSuccess(server -> {
      CaseInsensitiveHeaders headers = new CaseInsensitiveHeaders();
      client.websocket(HttpTestBase.DEFAULT_HTTP_PORT, HttpTestBase.DEFAULT_HTTP_HOST, "/", headers, ws -> {
        ws.handler(buff -> {
          assertEquals("ok", buff.toString());
          testComplete();
        });
      });
    }));
    await();
  }
```

sets the host

**Comment by paulbakker** [comment]
I think I found the problem, and as you already proofed in the test it wasn't actually a Vert.x issue. Our rules in HAProxy don't match when a port is included in the host header. Including a port is correct however according the HTTP spec. In most situations (port 80/443) it's omitted though, so we never saw it fail before, and this showed in our logs as no Host header.
I'm closing this issue as it the behaviour is correct.
