### ISSUE TITLE
HttpClient: Vert.x should default to port 443 when using https

### ISSUE THREAD

**Issue by MRechtien** [eclipse/vert.x#1687]
Hi everybody!

When not specifying a Port - using the Vert.x websocket client - results in connecting to port 80 in both cases - http and https. I think it makes sense to default to port 443 on https connections.

Greets, Markus

**Comment by pmlopes** [comment]
which api call are you using? most `HttpClient` `websocket` calls have a port argument so it looks tricky to identify where the issue is.

**Comment by MRechtien** [comment]
Sorry, for getting back to you this late! The affected vert.x version was 3.3.2, but I think it applies to 3.3.3 as well.

```JAVA
HttpClient httpClient = vertx.createHttpClient(new HttpClientOptions()
        .setSsl(true).setTrustAll(true));
httpClient.websocket(serverName, LOCATION_WEBSOCKET, s -> {
/* .... */
```
Now if you use SSL the Port still defaults to 80. I think it makes sense to switch to 443 in that case, though another API method (including a port number) could be used.

Greetings, Markus

**Comment by aesteve** [comment]
I agree, that's a pretty common issue I also faced when first starting implementing clients with Vert.x.

Pretty hard to debug as a beginner, too.

Careful though, it might be a breaking change (for people using https on port 80, ...). Maybe just add a note, not that much people should be affected.

**Comment by vietj** [comment]
you should configure the default port to 443 in the options when using SSL
