### ISSUE TITLE
Does not get response by second request

### ISSUE THREAD

**Issue by kostonstyle** [eclipse/vert.x#1691]
Hi 
I am trying to use vertx with rxjava in web router like:  

```
private void registerTooRoute(Router router) {

    ObservableHandler<RoutingContext> handler = RxHelper.observableHandler();

    handler
        .doOnNext(ctx -> ctx.response().putHeader("content-type", "text/html"))
        .subscribe(ctx -> {
          ctx.response().end("Hello");
        });

    router.get(API_TOO).handler(handler.toHandler());
  }
```

The first request to the server, I've got the result Hello as expected. But further request to the server, I've got only sandwatch from the browser.  

It seems to be, that is an error in vertx rxjava conversion. 

Thanks

**Comment by kostonstyle** [comment]
I created a new web server: 

package com.cloudware;


import io.vertx.rx.java.ObservableHandler;
import io.vertx.rx.java.RxHelper;
import io.vertx.rxjava.core.AbstractVerticle;
import io.vertx.rxjava.ext.web.Router;
import io.vertx.rxjava.ext.web.RoutingContext;

public class Web extends AbstractVerticle {

  // Convenience method so you can run it in your IDE
  public static void main(String[] args) {
    Runner.runExample(Web.class);
  }

  @Override
  public void start() throws Exception {

    Router router = Router.router(vertx);
    ObservableHandler<RoutingContext> observable = RxHelper.observableHandler();

    observable
        .subscribe(ctx -> ctx.response().putHeader("content-type", "text/html").end("Hello World!"));

    router.get("/foo").handler(observable.toHandler());


    vertx.createHttpServer().requestHandler(router::accept).listen(8080);
  }
} 

The result is the same, the first request works but further does not work, just waiting for response.

Thanks

**Comment by EmadAlblueshi** [comment]
Hi, @kostonstyle did you try below ?

```javascript
ObservableHandler<RoutingContext> oh = RxHelper.observableHandler(true);
oh.subscribe(ctx -> ctx.response().end("Hello World!"));

Router router = Router.router(vertx);
router.get("/foo").handler(oh.toHandler());
```

**Comment by kostonstyle** [comment]
It works like a charm. Thanks so much.

**Comment by EmadAlblueshi** [comment]
@kostonstyle You are more than welcome :)
