### ISSUE TITLE
Add an .editorconfig file in this repo?

### ISSUE THREAD

**Issue by creativeprogramming** [eclipse/vert.x#1707]
See: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

> We recommend that all repos should have a .editorconfig in the root folder with at least the following content:

> ```
> root = true
> 
> [*]
> charset = utf-8
> indent_style = space
> indent_size = 2
> trim_trailing_whitespace = true
> end_of_line = lf
> insert_final_newline = true
> ```
> 
> 

Why not add it in the root of this repo, so forks can follow rules automatically?

**Comment by vietj** [comment]
I think @pmlopes has not done a PR for this repo, you can make one if you like

**Comment by creativeprogramming** [comment]
I think it's better if you do that. There are a lot of wrong styled things in many source files too, i think a PR with a global reformatting is needed on the whole vert.x while adding editorconfing to the repo, SO I don't want to be credited for 'git authorship avatar' in any vert.x source file, I don't deserve so much, better if a commit like this is authored by a real vertx developer and not just a vertx user like me

**Comment by creativeprogramming** [comment]
e.g check what happened to this test i quickly did: https://github.com/creativeprogramming/vert.x/commit/520dc0b17ae0e58beff30bbaa9f8cdd261046a5f (wrong commit msg sorry...) it's just to show you how much changes it will produce

**Comment by pmlopes** [comment]
@creativeprogramming you don't need to reformat the code, you can add the file and as files are touched then we reformat them.

**Comment by creativeprogramming** [comment]
@pmlopes yes but this means that if another guy do a fork before you, he can get many things reformatted as he touch them and be unable to do a clean PR...

**Comment by vietj** [comment]
@pmlopes code needs to be properly formatted when committed in the repo
