### ISSUE TITLE
Unable to start vert.x with exploded mode

### ISSUE THREAD

**Issue by kameshsampath** [eclipse/vert.x#1718]
When running vert.x from CLI using command like:
`java -cp $MY_CP start  -id e8b0342b-7a65-495a-a58f-88071421e07c org.vertx.demo.SimpleVerticle --launcher-class io.vertx.core.Launcher`

The application is refusing to start saying no command by name `org.vertx.demo.SimpleVerticle`.. but when I do start with same set of options via Launcher.main(args)  form a custom main program from an IDE things run well.

Using **vert.x v3.3.3**

where $MY_CP is custom classpath which has jars/classes directory etc.,

**Comment by InfoSec812** [comment]
The correct syntax would be:

```
java -cp $MY_CP io.vertx.core.Launcher start org.vertx.demo.SimpleVerticle -id e8b0342b-7a65-495a-a58f-88071421e07c
```
