### ISSUE TITLE
Add Official Support For Kotlin

### ISSUE THREAD

**Issue by napperley** [eclipse/vert.x#1738]
Vert.x supports some of the JVM languages. Support is missing for [Kotlin](http://www.kotlinlang.org), which is odd considering that Ceylon is already supported. Would be wise to provide support for Kotlin if Vert.x is going to target Android since Kotlin has a [significant presence](http://androidweekly.net/issues/issue-232) in Android development.

**Comment by aesteve** [comment]
You can already play around with Kotlin with Vert.x Java API.

I think @vietj has made some huge progress on JVM-languages code generation through extension modules (see the latest Groovy improvements). Since Kotlin supports extensions too, I think this is gonna be a major key factor for Kotlin as an official supported language.

Also, iirc, someone from Jetbrains with also having a look at these extensions.

So, imo yes this is needed, but I guess it's a work in progress :)

**Comment by vietj** [comment]
@napperley we are going to support Kotlin in 3.4, however the dev has stalled recently :-( , if you mind to contribute that would be very helpful

**Comment by vietj** [comment]
@napperley can you instead create this issue in this tracker https://github.com/vert-x3/issues/issues and close this one ? thanks

**Comment by napperley** [comment]
Makes sense that Kotlin support is just getting started when the Vert.x
homepage doesn't have a Kotlin code example yet.

**Comment by vietj** [comment]
@napperley you can use Vert.x with Kotlin today, you don't need to wait for official support. Official support will add some ease for using Vert.x options and a VerticleFactory for compiling kotlin source to code

**Comment by aesteve** [comment]
Also, @napperley I forgot to mention that [here](https://github.com/aesteve/vertx-kotlin-todomvc) you can find a basic implementation of the "Todo backend" example using Kotlin.

Hope this can help you getting started with Vert.x + Kotlin. As @vietj said, official support is more a matter of ease-of-use and using 100% language-capabilities (overloaded operators, language conventions) than "using Vert.x with Kotlin". Any JVM-capable language is already *de facto* Vert.x compliant (through its Java APIs).

**Comment by napperley** [comment]
What was meant by the feature request is to add some Kotlin APIs to cover
some areas of Vert.x, where it would be highly advantageous for Kotlin
users to use the Kotlin API instead of the Java API (mix and match). An
excellent example of this is the Requery
<https://github.com/requery/requery> library which used to be Java only.

**Comment by vietj** [comment]
See https://github.com/vert-x3/vertx-lang-kotlin

**Comment by vietj** [comment]
done but should not be in this repo
