### ISSUE TITLE
RecordParser implement ReadStream<Buffer>

### ISSUE THREAD

**Issue by DanielJoyce** [eclipse/vert.x#1741]
That way we can trivially pump files or other ReadStream sources through it.

pump(asyncFile, recordParser)

**Comment by vietj** [comment]
good idea, would you mind to contribute it ?

**Comment by vietj** [comment]
I've updated the issue to have instead the record parser extends `ReadStream<Buffer>` and wrap optionally another `ReadStream<Buffer>`. This way is easier and does not require a pump, i.e if the parser would extends `WriteStream<Buffer>`, then it would anyway need to extends also `ReadStream<Buffer>`.
