### ISSUE TITLE
File caching implementation not thread safe

### ISSUE THREAD

**Issue by samekmichal** [eclipse/vert.x#1742]
The `FileResolver` implementation of caching is not thread safe. The problem occurs when the same file (that is about to be cached) is concurrently being read from multiple verticles. This issue can be reproduced with `FileSystem#readFileBlocking`, however, I believe that async implementation will yield similar results.

The problem here is the following. Consider a use case, when a file is read in multiple verticles in parallel. This file does not reside in a local filesystem, and as such `Vert.x` will try to cache the file by moving it to the `.vertx` directory.

1. First verticle that hits `FileResolver#resolveFile` will trigger the copying action of the resource to the designated `.vertx` cache directory. Only after this copy action is finished, the file will be read - thus this verticle will read _complete_ data.
2. Every other instance that hits `FileResolver#resolveFile` will find the cached file during resolution - as the file is currently being copied over there - however, it might happen that it will read the cached file before it is copied completely - thus this verticle will read only _partial_ data.

The problem can be reproduced by running supplied verticle in multiple instances. The verticle only reads 10 files from attached jar (all are 1MB in size) and outputs the size of read payload.

[vertx-fileread-bug.zip](https://github.com/eclipse/vert.x/files/656849/vertx-fileread-bug.zip)

`vertx run -cp data.jar --instances 3 FileLengthVerticle.java`

Sample output:
```
...
file data5: 1024000bytes
file data5: 1024000bytes
file data6: 1024000bytes
file data6: 1024000bytes
file data6: 1024000bytes
file data7: 1024000bytes
file data7: 1024000bytes
file data7: 1024000bytes
file data8: 65516bytes
file data8: 73703bytes
file data8: 1024000bytes
file data9: 646968bytes
file data9: 1024000bytes
file data9: 1024000bytes
```

**Comment by cescoffier** [comment]
Definitely a bug. I will have a look.

**Comment by samekmichal** [comment]
Hi, I had another look at this issue and believe that also block around https://github.com/eclipse/vert.x/blob/0f15327fcfe7c6a40ff796d1a25155c16ec2e364/src/main/java/io/vertx/core/impl/FileResolver.java#L160 should be adjusted.

Let's assume that `ENABLE_CACHING ` is set to false, then still the resource file is copied over to cache - and path to the cached file is returned at the end of the function. I would say it should more look like
```java
if (ENABLE_CACHING) {
  Files.copy(resource.toPath(), cacheFile.toPath());
} else {
  return resource;
}

```

**Comment by cescoffier** [comment]
We need the replace existing for people reloading their resources at development time. The method is synchronized, so you should not have concurrent accesses. Do we ?

**Comment by samekmichal** [comment]
No, my question is not about concurrent access. It is just not clear to me, why we still copy the file cachedir if caching is disabled.

**Comment by cescoffier** [comment]
@pmlopes can give more details. If I remember correctly, it's used when someone edits static resources (HTML, JS, CSS).

**Comment by pmlopes** [comment]
@samekmichal from `Files.copy` doc:

> By default, the copy fails if the target file already exists or is a symbolic link, except if the source and target are the same file, in which case the method completes without copying the file.

So it should be a NOOP if they are the same, or an error if the cache is corrupted.

And indeed caching is interesting for web developers since you can change the resources without having to constantly reload your application.

**Comment by samekmichal** [comment]
@pmlopes I totally agree with your statements. However, my question addresses a different issue. I will describe it more thoroughly.

Let's assume that the usser has disabled caching ==> `ENABLE_CACHING = false`

Within io.vertx.core.impl.FileResolver#resolveFile
```java
if (!file.exists()) {
  // Look for it in local file cache
  File cacheFile = new File(cacheDir, fileName);
  if (ENABLE_CACHING && cacheFile.exists()) { <<--  if caching is disabled, don't serve it from cache
    return cacheFile;
  }
  ...
```

Within io.vertx.core.impl.FileResolver#unpackFromFileURL
```java
...
if (ENABLE_CACHING) {
  Files.copy(resource.toPath(), cacheFile.toPath());
} else {
  Files.copy(resource.toPath(), cacheFile.toPath(), StandardCopyOption.REPLACE_EXISTING); <<-- even if caching is disabled, we still copy the file to cache
}
...
```

My question goes: if we will never serve the file from cache (implemented in `resolveFile`), why do we still copy the resource to cache in `unpackFromFileURL` instead of just passing the original file location to the caller?

**Comment by pmlopes** [comment]
That is a performance related decision. Serving files from a jar although possible is quite slow and requires some CPU usage. Sure if you don't use fat jars this is a bit less problematic but still is serving through the class path. So that's why files always get copied.

**Comment by samekmichal** [comment]
But `unpackFromFileURL` is not handling resources within jar archives, but only regular files instead
