### ISSUE TITLE
Message should have an acknowledge method

### ISSUE THREAD

**Issue by chrsoo** [eclipse/vert.x#1747]
The [Message](https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/eventbus/Message.java) class has a `fail` method for signalling failure but there is no corresponding method to signal that processing suceeded.

When implementing a [MessageConsumer](https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/eventbus/MessageConsumer.java) for a Message Broker this is problematic as messages need to be individually acknowledged by the client code in order to implement transactional behaviour.

My current work-around is for handlers to cast the message to an implementation specific message:

````java
ArtemisBridge.create()
        .createConsumer("INBOUND")
        .handler(message -> {
            try {
                // do something useful before acknowledging the message
                ...
                // acknowledge message
                ArtemisMessage artemisMessage = (ArtemisMessage) message;
                artemisMessage.acknowledge();
            } catch (TimeoutException e) {
                // rollback and try again later
                message.fail(ArtemisBridge.TEMPORARY_FAILURE, e.getMessage());
            } catch (Exception e) {
                // send message to DLQ
                message.fail(ArtemisBridge.PERMANENT_FAILURE, e.getMessage());
            }

        });
````

Introducing an `acknowledge()` method on the `Message` interface would avoid the ugly typecast and to me it seems this should be of general interest for all message handling.

Other names are of course possible, e.g. `succeed` which would match `fail` or perhaps `handled` to indicate that the `Handler` handled the message.

**Comment by vietj** [comment]
hi, you should have a convention for acknowledging a message, for instance using a special message header or using a special object like `msg.reply(ArtemisBridge.ACKNOWLEDGE)`

acknowledgements in event bus are explicit : http://vertx.io/docs/vertx-core/java/#_the_event_bus_api

**Comment by chrsoo** [comment]
Thanks for the "reply" ;-)

So... you are saying that I should have "magic" reply to message bodies (or headers) for differentiating between a message reply as in the [request-reply](http://www.enterpriseintegrationpatterns.com/patterns/messaging/RequestReplyJmsExample.html) pattern and an acknowledgement to the Event Bus (in this case an external Message Broker)  that the message has been consumed?

To me these are two very distinct operations - in the first case we are talking to the sender and in the second case to the transport mechanism.

**Comment by vietj** [comment]
Vert.x event bus api does not have acknowledgement, so it would not make sense to add one.

I think actually the API you proposed look fine to me, perhaps you could avoid the cast using a static method ArtemisMessage.acknowledge(message) instead.

**Comment by chrsoo** [comment]
No, it is true that Vert.X does not have an `acknowledge()` method as it does not care about transactional behaviour but from what I understand of Vert.X, _explicit_ error handling is an important feature. This is evident in asynchronous code that uses a `future`, for example:
````java
Vertx.vertx().executeBlocking(handler -> {
    try {
        // blocking code
        handler.complete();
    } catch(Exception e) {
        handler.fail(e);
    }
}, result -> {
    // result handler omitted
});
````
Now, for _receiving a message_ I think the Vert.X `Message` should in my mind have extended the `Future` interface where `complete()`/`fail()` would indicate the success of receiving the message. On top of `Future` the `Message` interface would have added the messaging specific semantics such as `reply()` for implementing the [request-reply](http://www.enterpriseintegrationpatterns.com/patterns/messaging/RequestReplyJmsExample.html) pattern.

Retrofitting using a `Future` might not be feasible but we could still add a missing `complete()`, `acknowledge()` or other method that achieves the same effect, i.e. separating reception of messages from request-reply. Such a method would be optional with a default implementation:

````java
default void complete() {
    // noop
};
````

Yes, there are workarounds and using a static acknowledge method could hide the typecast is an improvement in my case, but I think it would be a pity the Event Bus API could not be tweaked to cover a broader spectrum of Messaging usecases that includes transactional behaviour!

**Comment by vietj** [comment]
the issue I see is that then we need to explain that complete does not do anything by default but user should care about calling it because in some case it may have a useful effect

**Comment by chrsoo** [comment]
We already have a similar issue with the existing `fail()` method, from the javadoc:

> If you want to notify the sender that processing failed, then {@link #fail} can be called.
Seems pretty optional to me, although the documentation on the `fail()` method itself claims that the failure handler _will_ be called if the sender has specified it.

We would not really change the situation and you need to understand what you are doing and why you are doing it.

**Comment by vietj** [comment]
`fail` is a processing failure, not the failure that a message failed to be delivered.

you are just meaning that `acknowledge` would be equivalent to do an ACK reply.

**Comment by chrsoo** [comment]
Please define "processing failure" - it is ambiguous to say the least :-)

If you are doing Reliable Messaging where we have some kind of guarantee that messages are not lost, I would say there are three basic outcomes of any *message processing*:

1. It was a *success* and the message is  **acknowledged** 
1. There is a *temporary failure* and the message is recovered for **redelivery**
1. There is a *permanent failure* and the message is ** acknowledged** after forwarding it to the DLQ for *additional processing* (probably manual)

I would use the `fail` method with a code for the client to differentiate between the two last outcomes but I still need the client implementation to tell me when we can safely assume that processing succeeded. To just assume it went well if we don't hear otherwise won't work as we then would loose messages when processing fails due to a bug or service interruption.

Now, from what I understand the Event Bus API is not intended for Reliable Messaging at all and implementations would probably be a compromise. Consider the following:

1. Messages can not be sent/received reliably (cf. the above discussion on acknowledging messages)
1. Some methods in the Event Bus API cannot be consistently implemented (cf. the reply handlers that are supposed to be executed when the recipient has replied to the message which can happen hours, days, weeks later)
1. The Event Bus API seems to assume that the message can be returned as an instance of a single object (cf. the body method and compare it to the HTTP Request/Reply that is stream based)

(Regarding the last point I guess the body could be a stream, so maybe that can be worked around...)

Would you be open to supplementary Reliable Messaging API in the `io.vertx.ext` namespace?

**Comment by vietj** [comment]
@chrsoo we are totally open, however something in the `io.vertx.ext` namespace means it is a project under the Vert.x umbrella (https://github.com/vert-x3/wiki/wiki/Vert.x-3-Official-stack-and-component-maintainers) and it should have a maintainer and integrate with other projects of the stack (i.e we the vertx-proton project and it could benefit from this interface as well).

**Comment by chrsoo** [comment]
@vietj that is fine, I just want to make sure that if I invest time in proposing such an API you would not be refusing it due to overlap with other API's (such as the Event Bus) or on some principal grounds. 

So, when/**if** I have something I believe to be good enough to share I will contact you again. How do I best do that?

**Comment by vietj** [comment]
@chrsoo I believe this should be discussed on vertx-dev mailing list before you start investing time, specially discussion with @gemmellr . Perhaps there is overlap, perhaps there is not, the most appropriate is that you come up with a proposal and we discuss it on vertx-dev.

**Comment by vietj** [comment]
@chrsoo you want also to check https://github.com/vert-x3/vertx-proton

**Comment by gemmellr** [comment]
vertx-proton doesn't actually use the Message interface and can already do explicit acknowledgement/release/rejection etc, it is https://github.com/vert-x3/vertx-amqp-bridge that uses the Message interface and could relate to work done in this area. Both modules already work with Artemis via its AMQP 1.0 support, although the implicit reply handling support in the bridge module will need https://issues.apache.org/jira/browse/ARTEMIS-562 resolved before it could be used, but explicit replies will work already.

Back to holiday, I'll mostly be MIA until Jan 4th.

**Comment by chrsoo** [comment]
The way I see there is a need for an API for Reliable Messaging that the `vertx-amqp-bridge` would implement in addition to the Event Bus API. The bridge client application selects either the Event Bus or the Reliable Message (RM) API.

The main reason for using the RM API would the requirement for messages to be acknowledged by the client only when (asynchronous) processing has been successfully terminated. Other requirements could include API support for forwarding messages to a DLQ and handling large messages using the Vert.X Stream API.

@gemmellr is this the way you see it as well?

Note that for my usecase I would like to use the Artemis (or stock ActiveMQ) `vm` protocol bypassing networking entirely and only optionally would messages be shared with other VM's, i.e. other nodes in the same cluster and/or bridging to other brokers. This means I would implement the RM API directly in a dedicated ActiveMQ/Artemis bridge and also add support for easily embedding ActiveMQ/Artemis in my Vert.X applications.

For solutions that sports an external ActiveMQ or Artemis Message Broker the `vertx-amqp-bridge` would be a good choice assuming AMQP is an acceptable wire protocol.
