### ISSUE TITLE
Customization of Netty "initialBufferSize"

### ISSUE THREAD

**Issue by gmagniez** [eclipse/vert.x#1750]
Would it be possible to add a new configuration options in both HttpClient and HttpServer to allow to customize the initial size (128b default) of the parsing buffer of Netty HttpObjectDecoder.

I see that when handling an high load on my application with requests or responses with multiple headers, the CPU is mostly consumed by netty "AppendableCharSequence.append", which has to always grow and so has to copy char arrays.

```
Stack Trace	Sample Count	Percentage(%)
io.netty.util.internal.AppendableCharSequence.append(char)	2 160	6,472
   io.netty.handler.codec.http.HttpObjectDecoder$HeaderParser.process(byte)	2 160	6,472
      io.netty.buffer.AbstractByteBuf.forEachByteAsc0(int, int, ByteBufProcessor)	2 160	6,472
         io.netty.buffer.AbstractByteBuf.forEachByte(ByteBufProcessor)	2 160	6,472
            io.netty.handler.codec.http.HttpObjectDecoder$HeaderParser.parse(ByteBuf)	2 160	6,472
               io.netty.handler.codec.http.HttpObjectDecoder.readHeaders(ByteBuf)	2 141	6,415
                  io.netty.handler.codec.http.HttpObjectDecoder.decode(ChannelHandlerContext, ByteBuf, List)	2 141	6,415
```

Methods involved in vertx:
```HttpServerImpl.configureHttp1 -> HttpRequestDecoder```
```ConnectionManager$ChannelConnector.applyHttp1xConnectionOptions -> HttpClientCodec```

**Comment by tsegismont** [comment]
Would you mind to send a pull request? Usually, such pull requests get
better chances of inclusion if they come with a performance test
demonstrating the benefit.

2016-12-22 14:26 GMT+01:00 gmagniez <notifications@github.com>:

**Comment by vietj** [comment]
+1

**Comment by gmagniez** [comment]
Ok, I'll try to do that but I think it will be after Christmas and New Year :-)

**Comment by vietj** [comment]
@gmagniez any news ?

**Comment by leogomes** [comment]
@gmagniez: Please check my PR [here](https://github.com/eclipse/vert.x/pull/1881), if you have some time. It would be also nice if you could share the original use-case you had for this and/or have a look at the test case I wrote to benchmark the change. All mentioned in the PR.

**Comment by leogomes** [comment]
@vietj @tsegismont I guess you guys can close this one now that #1881 is merged.
