### ISSUE TITLE
Fragmented websocket frames sent to the SockJS bridge silently close the websocket connection

### ISSUE THREAD

**Issue by trho** [eclipse/vert.x#1751]
When SockJS messages are sent as fragmented websocket frames, the websocket connection is silently closed.
I post the issue here, because all data handlers of the ServerWebSocket are affected.

For the concrete problem see line 107 in the WebSocketTransport.java:
https://github.com/vert-x3/vertx-web/blob/09a2463262b46b1826c088624f549b3cbb6f4f01/vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/WebSocketTransport.java#L107

The listener (data handler) does not handle partial JSON messages and rejects them by closing the connection.
Further, the heuristic to detect a valid message might accept a partial message by chance.

Chrome already fragments messages < 3KB, making the bridge unreliable for our use-cases.

The pull request https://github.com/eclipse/vert.x/pull/964 offered a solution for this issue, but was declined because "... dataHandler should only be used for writing/receiving websocketframes if you know they're final binary frames".

This is not the case for the WebSocketTransport.WebSocketListener in vertx-web.
In general, data handlers do not have access to the underlying frames, they can only guess if the frame is a final or a continuation frame.

Could you please reconsider the mentioned pull request?
If it breaks existing code, I could rewrite the pull request to make the frame concatenation optional, e.g. by a configuration parameter.

**Comment by Crokoking** [comment]
I created a pull-request to fix this issue in vert.x-web [#534](https://github.com/vert-x3/vertx-web/pull/534).
It uses the frame-handler the vert.x-core provides and reconstructs the frame at a higher level.

**Comment by Crokoking** [comment]
Seems this was fixed here: https://github.com/eclipse/vert.x/commit/4d39bd169b9ae28b43b78d3e97176f701f887af5

**Comment by trho** [comment]
This looks promising.
I will test this once PR https://github.com/vert-x3/vertx-web/pull/520 (the replacement of https://github.com/vert-x3/vertx-web/pull/534) has been merged.

**Comment by vietj** [comment]
can you close this issue and open it in vertx-web ?
