### ISSUE TITLE
DNSclient.lookup4 does not return the ip address when a CNAME is used

### ISSUE THREAD

**Issue by alexlehm** [eclipse/vert.x#1752]
When resolving for example www.yahoo.com or www.msn.de, the result of DNSClient is a CNAME and not the final ip address. This is either caused by the number of consecutive dns operations are used up or only the first address is resolved in general.

````java
import org.junit.Test;
import org.junit.runner.RunWith;

import io.vertx.core.Vertx;
import io.vertx.core.dns.DnsClient;
import io.vertx.core.logging.Logger;
import io.vertx.core.logging.LoggerFactory;
import io.vertx.ext.unit.Async;
import io.vertx.ext.unit.TestContext;
import io.vertx.ext.unit.junit.VertxUnitRunner;

@RunWith(VertxUnitRunner.class)
public class DnsClientTest {

  private final static Logger log = LoggerFactory.getLogger(DnsClientTest.class);

  @Test
  public void testDnsClient(TestContext context) {
    Async async=context.async();
    Vertx vertx = Vertx.vertx();
    DnsClient client = vertx.createDnsClient(53, "192.168.178.1"); 

    client.lookup4("www.yahoo.com", res -> {
      if (res.succeeded()) {
        log.info("result "+res.result());
        async.complete();
      } else {
        context.fail(res.cause());
      }
    });
  }
}
````

**Comment by vietj** [comment]
@alexlehm can you check this issue again with Netty 4.1.8.Final ?

**Comment by alexlehm** [comment]
issue is still present with 3.4.0-SNAPSHOT with netty 4.1.8

**Comment by alexlehm** [comment]
I looked at the issue in DnsClientImpl and it turns out that its not related to netty, it is collecting the results wrong (so the code was wrong for a long time). Will implement a fix

**Comment by vietj** [comment]
@alexlehm thanks, it owuld make sense I think to remove some of the internal implementation to use more Netty now that it implements more DNS

**Comment by alexlehm** [comment]
Implemented a unit test and a fix keeping the internal code, even if we decide to use netty instead, the unit test will be useful.
https://github.com/alexlehm/vert.x/tree/issues/%231752-resolve-cname

**Comment by vietj** [comment]
@alexlehm great work! it does not pass the IP checks though

**Comment by alexlehm** [comment]
sorry, forgot to run the test of the other record types, the fix breaks everything else

**Comment by alexlehm** [comment]
@vietj pushed a new fix, this should work

**Comment by alexlehm** [comment]
could use some improvement still, I used a steam to check the record type
