### ISSUE TITLE
HttpClient leaves connection open on websocket request failure (resource leak)

### ISSUE THREAD

**Issue by xkr47** [eclipse/vert.x#1757]
When running this code:
```java
        Vertx vertx = Vertx.vertx();
        vertx.createHttpServer().requestHandler(req -> {
            req.response().setStatusCode(200);
            req.response().headers().set("Connection", "close");
            req.response().end();
        }).listen(44444);
        vertx.createHttpClient().websocket(44444, "localhost", "/", ws -> {
            System.out.println("WS Unexpectedly connected");
        }, t -> {
            System.err.println("WS Connection failed");
            t.printStackTrace();
        });
```
Then end result is `WS Connection failed` (as expected) but `netstat -natp|grep :44444` (in Linux) shows the connection is still ESTABLISHED. Only closing the java process (naturally) gets rid of the connection.

For a regular GET request:
```java
        Vertx vertx = Vertx.vertx();
        vertx.createHttpServer().requestHandler(req -> {
            req.response().setStatusCode(200);
            req.response().headers().set("Connection", "close");
            req.response().end();
        }).listen(44444);
        vertx.createHttpClient().get(44444, "localhost", "/", c -> {
            System.out.println("GET connected");
        }).end();
```

then `netstat -natp|grep :44444` shows no ESTABLISHED connections, as expected.

I added the `Connection: close` header so that HttpClient wouldn't pool the connection and leave it open because of that.

**Comment by vietj** [comment]
@xkr47 this is an expected behavior of persistent connections, you should disable keep alive in the client options

**Comment by xkr47** [comment]
Ok updated examples with keep-alive disabled:
```java
        Vertx vertx = Vertx.vertx();
        vertx.createHttpServer().requestHandler(req -> {
            req.response().setStatusCode(200);
            req.response().end();
        }).listen(44444);
        HttpClientOptions opts = new HttpClientOptions().setKeepAlive(false);
        vertx.createHttpClient(opts).websocket(44444, "localhost", "/", ws -> {
            System.out.println("WS Unexpectedly connected");
        }, t -> {
            System.err.println("WS Connection failed");
            t.printStackTrace();
        });
```
and
```java
        Vertx vertx = Vertx.vertx();
        vertx.createHttpServer().requestHandler(req -> {
            req.response().setStatusCode(200);
            req.response().end();
        }).listen(44444);
        HttpClientOptions opts = new HttpClientOptions().setKeepAlive(false);
        vertx.createHttpClient(opts).get(44444, "localhost", "/", c -> {
            System.out.println("GET connected");
        }).end();
```
Results are the same; websocket-attempting connection remains ESTABLISHED while plain GET request connection is closed.

I also tried running the GET request after the failed websocket request, and it opened a second connection (which was closed).

**Comment by xkr47** [comment]
A wild guess would be to add a call to `close();` just before line 192, just like is done further down in the same method on lines 215-216 in a seemingly similar situation:
https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/ClientConnection.java#L192

**Comment by vietj** [comment]
yes it might be a bug, can you change it to see how it goes ?
