### ISSUE TITLE
NullPointerException using ClusterManager with Vertx Groovy

### ISSUE THREAD

**Issue by leosilvadev** [eclipse/vert.x#1772]
I was making some tests with Vertx, Groovy and Zookeeper, then I got a NullPointerException.
After check it out I realized where is the problem:

```
VertxOptionsConverter.fromJson
```

This method is used from groovy to parse the Map -> JsonObject -> VertxOptions, but it does not look for a clusterManager, so it is always null

But my question is: should it be really fixed inside VertxOptionsConverter? Since a JsonObject should be exactly how it sounds and does not contain any complex type?

[]'s

**Comment by InfoSec812** [comment]
Leonardo,

    I, too, have seen this exact same problem and was forced to use the
Java API implementation of the Vertx class. In Vert.x 3.4.0, this problem
should be resolved because the Java and Groovy APIs are almost identical
(using extension methods to add Groovy sugar on top of the Java API).

Deven

**Comment by leosilvadev** [comment]
Great @InfoSec812, since this will be in 3.4.0 version I will close the issue.
Thanks!
