### ISSUE TITLE
Need JsonObject(Object) constructor that builds a map from POJO fields

### ISSUE THREAD

**Issue by lukehutch** [eclipse/vert.x#1773]
The standard way to serialize POJOs into a `JsonObject` seems to be

```java
JsonObject document = new JsonObject(Json.encode(myPojo));
```

However, this is inefficient: it serializes the POJO to JSON, then deserializes it again when the JsonObject constructor is called, then re-serializes it once the JsonObject is sent over the wire (or sent to Mongodb).

It would be great to have a constructor

```java
new JsonObject(Object pojo)
```

which reads the public fields of `pojo` (and the fields with getters), and builds a `Map<String, Object>` from these fields, then initializes the `JsonObject#map` field directly using this map, avoiding the extra serialization and deserialization.

**Comment by lukehutch** [comment]
I added PR #1774 as a suggested approach to this. I haven't signed the Eclipse CLA yet or anything, please give feedback on the patch first.

**Comment by vietj** [comment]
@lukehutch I'm wondering if we can let jackson do the mapping to JsonObject directly

for instance something like:

```
Json.mapper.writeValue(new GeneratorBase() {
  // Implement the methods from GeneratorBase to delegate to a JsonObject instead of a Wrtier  
}, obj);
```

**Comment by vietj** [comment]
solved differently.
