### ISSUE TITLE
Lack of custom log level support in the Vertx logging abstraction framework

### ISSUE THREAD

**Issue by angelacb** [eclipse/vert.x#1781]
Lack of custom log level support in the Vertx logging abstraction framework. JUL might not support this but Log4J2 do support custom log levels but the Vertx logging abstraction does not have support for this when Log4J2 specific logging functions are abstracted away.

**Comment by vietj** [comment]
why would it be needed ?

**Comment by vietj** [comment]
I believe this is not something Vert.x should do, although we provide an utility for logging, Vertx logger should not become a logging facade.
