### ISSUE TITLE
Suggestion: Skip blocked worker instance by option

### ISSUE THREAD

**Issue by oshatrk** [eclipse/vert.x#1782]
Currently if i run my verticle as a worker with 2 instances (multi-threaded worker launched with --worker --instances 2) then the request handler instance is choosed in simple order regardless of the blocking state of an instance.
And if one of instances is blocked (for example, by debugger) then 50% incoming requests aren't processed.

So in this case i wish to use another strategy - skip blocked instance and choose non-blocked one.

As currently worker instances are coupled with netty channels so one naive idea is to temporarily disable the netty channel corresponding to blocked instance (possibly in io.vertx.core.impl.BlockedThreadChecker) if there is some config option (--multi-threaded-worker-skip-blocked).

Also implement a public method to allow user to mark current instance as blocked. So user can write something like:

<pre><code>if(request.uri().contains("debug")) {
	vertx.setCurrentMultiThreadedWorkerBlocked();
	// set IDE breakpoint here
}</code></pre>

Suppose this will be usefull for production debugging ;)

**Comment by tsegismont** [comment]
If you want more requests to be processed by a worker verticle then you
need to:
- deploy more instances
- make sure the worker pool size is large enough

I'm not sure why you're talking about multithreaded workers here. I guess
it's because you want to set a breakpoint without blocking all requests. In
this case have a look at your IDE debugging options, you can probably mark
the breakpoint to stop the current thread only, and to deactivate
immediately after being hit.



Le 28 janv. 2017 20:50, "Oleg Chtchoukine" <notifications@github.com> a
écrit :

**Comment by oshatrk** [comment]
I have another example.

Let's see some worker routine like:
<pre><code>public class MyWorkerVerticle extends AbstractVerticle {
    static int requestCounter = 0;

    @Override
    public void start() {
        Logger logger = LoggerFactory.getLogger(MyWorkerVerticle.class);

        vertx
                .createHttpServer()
                .requestHandler((final HttpServerRequest r) -> {
                    int rc = ++requestCounter;
                    try {
                        if ((rc % 120) == 1) {
                            // do_hard_work();
                            Thread.sleep(20_000); // 20 s
                        } else {
                            // do_light_work();
                            Thread.sleep(10); // 0.01 s
                        }
                    } catch (InterruptedException ex) {
                        logger.error("Worker interrupted", ex);
                    }
                    r.response().end("Done " + String.valueOf(rc));
                })
                .listen(8080);
    }
}</code></pre>
Suppose I'll run this code with 5 instances (--worker --instances 5) and will send 120 requests in 1 minute (120 rpm, 2 requests per second).
It's obvious that only first request will do_hard_work() and will take 20 seconds for its processing.
It's ok.

However it isn't obvious that some "light" requests will be blocked while that one hard request was processed.
For this case in JMeter's results table I found 5 "light" requests that were blocked for some period of time from 0.3 to 16 sesonds.

This problem is quite hard to recognize with performance tests because of common testing metrics like an average response time or a throughput won't show it. But clients will sometimes tell about lags. 

And theese blockings doesn't disappear completely if I'll add more worker instances.

**Comment by tsegismont** [comment]
If you deploy 5 instances of this verticle, then 5 instances of this class
will created. So actually it's not only the first request which should take
20secs, but the first five.
Besides, a worker verticle guarantees that events will not be processed
concurrently by worker threads. So when new requests are assigned to your
worker verticle, it could be still processing the long initial request.

BTW, worker verticles do not guarantee it's always going to be the same
thread. So you should make your requestCounter volatile.

2017-01-31 2:54 GMT+01:00 Oleg Chtchoukine <notifications@github.com>:

**Comment by vietj** [comment]
@oshatrk you should not block multithreaded worker verticles, if you need to block, use worker verticles. You should not add breakpoint in production code.

**Comment by oshatrk** [comment]
Just a minute.

At first, it is important when testing my example with JMeter to clear "Use KeepAlive" flag of HTTP Request to simulate workload from a number of clients accurately.

At second. @vietj I need some clearance about the Vertx's term "Multithreaded Worker".
Would You say am I right using this term for general workers launched by Vertx with <code>--instances N</code> key?

At third and not depending on am I right or wrong with using that term.
@tsegismont When the worker from my example is launched by Vertx with <code>--worker --instances N</code> keys, Vertx creates N worker instances, and each of them is assigned to an individual events loop. So theese workers run in parallel (if requests income with high rate).
To illustrate the parallel work more clean one can use this example:
<pre><code>public class MyWorkerVerticle2 extends AbstractVerticle {
    static int requestCounter = 0;
    static int iters = 0;

    @Override
    public void start() {
        Logger logger = LoggerFactory.getLogger(MyWorkerVerticle2.class);

        vertx
                .createHttpServer()
                .requestHandler((final HttpServerRequest r) -> {
                    int x = iters;
                    String identifier = String.format(" [req# = %d ] %s",
                            ++requestCounter, Thread.currentThread().getName());
                    System.err.println("Start " + identifier);
                    try {
                        // Read from iters for 1 second:
                        for (int i = 0; i < 100; ++i) {
                            int y = iters;
                            if (x != y) {
                                System.err.println(String.format(
                                        "x != y : %d != %d (%s)",
                                        x, y, identifier));
                                x = y;
                            }
                            Thread.sleep(10); // 0.01 s
                        }
                        // Write into iters for 1 second:
                        for (int i = 0; i < 100; ++i) {
                             ++iters;
                            Thread.sleep(10); // 0.01 s
                        }
                    } catch (InterruptedException ex) {
                        logger.error("Worker interrupted", ex);
                    }
                    System.err.println("End " + identifier);
                    r.response().end("Done " + identifier);
                })
                .listen(8080);
    }
}</code></pre>
After I started this code with same <code>--worker --instances 5</code> as above and tested it with JMeter (Threads=5, Ramp-up=3, Loop=2, no keep-alive) I got something like:
<pre>INFO: Succeeded in deploying worker verticle
Start  [req# = 1 ] vert.x-worker-thread-5
Start  [req# = 2 ] vert.x-worker-thread-6
x != y : 0 != 2 ( [req# = 2 ] vert.x-worker-thread-6)
x != y : 2 != 3 ( [req# = 2 ] vert.x-worker-thread-6)
x != y : 3 != 4 ( [req# = 2 ] vert.x-worker-thread-6)
Start  [req# = 3 ] vert.x-worker-thread-7
x != y : 4 != 6 ( [req# = 2 ] vert.x-worker-thread-6)
x != y : 5 != 6 ( [req# = 3 ] vert.x-worker-thread-7)
x != y : 6 != 7 ( [req# = 3 ] vert.x-worker-thread-7)
x != y : 6 != 8 ( [req# = 2 ] vert.x-worker-thread-6)
x != y : 7 != 8 ( [req# = 3 ] vert.x-worker-thread-7)
x != y : 8 != 9 ( [req# = 3 ] vert.x-worker-thread-7)
x != y : 8 != 10 ( [req# = 2 ] vert.x-worker-thread-6)
x != y : 9 != 10 ( [req# = 3 ] vert.x-worker-thread-7)
...</pre>
So you can see that static field <code>iters</code> is changed in parallel.

At forth.
Now I completely understood that (for workers, at least) I must not use <code>--instances N</code> for N>1,
and I should use a cluster of Vertxs in case I wish improve availability.

**Comment by tsegismont** [comment]
2017-02-02 14:07 GMT+01:00 Oleg Chtchoukine <notifications@github.com>:

> Just a minute.
>
> At first, it is important when testing my example with JMeter to clear
> "Use KeepAlive" flag of HTTP Request to simulate workload from a number of
> clients accurately.
>
> At second. @vietj <https://github.com/vietj> I need some clearance about
> the Vertx's term "Multithreaded Worker".
> Would You say am I right using this term for general workers launched by
> Vertx with --instances N key?
>

No, --instances sets the number of instances. --worker sets the verticle to
deployed as a worker verticle


> At third and not depending on am I right or wrong with using that term.
> @tsegismont <https://github.com/tsegismont> When the worker from my
> example is launched by Vertx with --worker --instances N keys, Vertx
> creates N worker instances, and each of them is assigned to an individual
> events loop. So theese workers run in parallel (if requests income with
> high rate).
>


This is wrong. Worker verticles are not assigned to event loops. Worker
verticle events are handled by a worker thread, one after the other. Two
consecutive worker verticle events can be handled by two different worker
threads.

The level of parallelism you'll get depends on the number of worker
verticle instances, and the size of worker threads pool.
It can't be bigger than either the number of worker verticle instances or
the max worker pool size.


> To illustrate the parallel work more clean one can use this example:
>
> public class MyWorkerVerticle2 extends AbstractVerticle {
>     static int requestCounter = 0;
>     static int iters = 0;
>
>     @Override
>     public void start() {
>         Logger logger = LoggerFactory.getLogger(MyWorkerVerticle2.class);
>
>         vertx
>                 .createHttpServer()
>                 .requestHandler((final HttpServerRequest r) -> {
>                     int x = iters;
>                     String identifier = String.format(" [req# = %d ] %s",
>                             ++requestCounter, Thread.currentThread().getName());
>                     System.err.println("Start " + identifier);
>                     try {
>                         // Read from iters for 1 second:
>                         for (int i = 0; i < 100; ++i) {
>                             int y = iters;
>                             if (x != y) {
>                                 System.err.println(String.format(
>                                         "x != y : %d != %d (%s)",
>                                         x, y, identifier));
>                                 x = y;
>                             }
>                             Thread.sleep(10); // 0.01 s
>                         }
>                         // Write into iters for 1 second:
>                         for (int i = 0; i < 100; ++i) {
>                              ++iters;
>                             Thread.sleep(10); // 0.01 s
>                         }
>                     } catch (InterruptedException ex) {
>                         logger.error("Worker interrupted", ex);
>                     }
>                     System.err.println("End " + identifier);
>                     r.response().end("Done " + identifier);
>                 })
>                 .listen(8080);
>     }
> }
>
> After I started this code with same --worker --instances 5 as above and
> tested it with JMeter (Threads=5, Ramp-up=3, Loop=2, no keep-alive) I got
> something like:
>
> INFO: Succeeded in deploying worker verticle
> Start  [req# = 1 ] vert.x-worker-thread-5
> Start  [req# = 2 ] vert.x-worker-thread-6
> x != y : 0 != 2 ( [req# = 2 ] vert.x-worker-thread-6)
> x != y : 2 != 3 ( [req# = 2 ] vert.x-worker-thread-6)
> x != y : 3 != 4 ( [req# = 2 ] vert.x-worker-thread-6)
> Start  [req# = 3 ] vert.x-worker-thread-7
> x != y : 4 != 6 ( [req# = 2 ] vert.x-worker-thread-6)
> x != y : 5 != 6 ( [req# = 3 ] vert.x-worker-thread-7)
> x != y : 6 != 7 ( [req# = 3 ] vert.x-worker-thread-7)
> x != y : 6 != 8 ( [req# = 2 ] vert.x-worker-thread-6)
> x != y : 7 != 8 ( [req# = 3 ] vert.x-worker-thread-7)
> x != y : 8 != 9 ( [req# = 3 ] vert.x-worker-thread-7)
> x != y : 8 != 10 ( [req# = 2 ] vert.x-worker-thread-6)
> x != y : 9 != 10 ( [req# = 3 ] vert.x-worker-thread-7)
> ...
>
> So you can see that static field iters is changed in parallel.
>

I haven't looked at your code in detail. But the point of my comment is
that worker verticles events can (and will) be handled by different threads
so maintaining a primitive counter is a bad idea.


> At forth.
> Now I completely understood that (for workers, at least) I must not use
> --instances N for N>1,
> and I should use a cluster of Vertxs in case I wish improve availability.
>

I believe you should read the docs again, if you have already. Especially:

http://vertx.io/docs/vertx-core/java/#_verticle_types
http://vertx.io/docs/vertx-core/java/#worker_verticles

**Comment by tsegismont** [comment]
Also, if you have further questions, please ask them on the [Vert.x user forum](https://groups.google.com/forum/?fromgroups#!forum/vertx), as explained on the [Vert.x community page](http://vertx.io/community/).

**Comment by oshatrk** [comment]
@tsegismont Thank you.
