### ISSUE TITLE
Load balancing of datagram servers

### ISSUE THREAD

**Issue by tsegismont** [eclipse/vert.x#1789]
As of 3.3.3, you can deploy multiple instances of a verticle, and leverage load balancing for HTTP servers and TCP servers.

However, deploying multiple instances of a verticle creating a datagram listener will result in a `java.net.BindException: Address already in use`.

You can avoid the exception by enabling address reuse:
`vertx.createDatagramSocket(new DatagramSocketOptions().setReuseAddress(true))`

But only one verticle instance will handle the messages.

**Comment by tsegismont** [comment]
@normanmaurer @purplefox is this limitation due to some technical constraints? Or was not implemented due to lower priority?

**Comment by testn** [comment]
Did you try one with setReuseAddress(true)?

**Comment by alokmenonin** [comment]
Yes ,  Its stil giving , Failed java.net.BindException: Address already in use . Also  can refer to below post for more details. https://stackoverflow.com/questions/41952062/vertx-instantiating-multiple-vertical-instances-listening-to-same-socket

**Comment by testn** [comment]
Sorry... I meant REUSE_PORT. You might need to hack it by using reflection to set the option on the socket descriptor 
http://marrachem.blogspot.com/2014/09/multi-threaded-udp-server-with-netty-on.html

**Comment by testn** [comment]
@tsegismont It seems like too much hacking for the feature that Java does not really support out of the box?

**Comment by vietj** [comment]
agreed, we should do it if there is actual demande for it

**Comment by testn** [comment]
Epoll implementation of Netty actually supports that though.

**Comment by vietj** [comment]
good to know @testn we do have an epoll branch in this repo!

**Comment by tsegismont** [comment]
I thought again about this and the problem is that load balancing datagrams between verticles could be an issue if two datagrams coming from the same source are logically connected.

With TCP it is not a problem since packets of a single connection will go to the same verticle.

**Comment by vietj** [comment]
good point

**Comment by tsegismont** [comment]
Closing, implementing this would cause more problems than it would solve.

**Comment by alokmenonin** [comment]
Then it won't be a limitation in vetx for building  a scalable solution which handles datagram packets ?   Asynchronous messaging using UDP is so much relevant today especially for IOT applications. I think you guys should  give this a shot rather than leaving this item open.

**Comment by purplefox** [comment]
>> I thought again about this and the problem is that load balancing datagrams between verticles could be an issue if two datagrams coming from the same source are logically connected.

>> With TCP it is not a problem since packets of a single connection will go to the same verticle.

Yes there is basically the reason there is no load-balancing with datagrams, how would you know which verticle to send the packet too? Random or round robin load balancing probably wouldn't make sense for the user.

It might be possible to create some kind of abstraction which groups packets per source address and balances on that, but that would involve some hacking.

**Comment by vietj** [comment]
@alokmenonin you can achieve it using the event bus

**Comment by vietj** [comment]
@purplefox agreed, it means more or less creating a notion of connection for instance the QUIC protocol that has the notion of connection id

**Comment by pendula95** [comment]
What about a case where there is no logical connection between packages? This was also a limitation for SE java as there was no way for multiple threads to listen to same address but with introduction of SO_REUSEPORT in java 9 now it is possible. I would rethink this, with current testing I have done with java9 different source addresses are handled by different ports, maybe similar implementation can be made now or even to provide option to chose round robin or random as both would work for the case I want to build with vertx, radius-server, as connection is stateless. I think most of the time in UDP connection is stateless so this feature seems legit.

**Comment by vietj** [comment]
@pendula95 yes indeed, that being said nobody ever came with this use case for now

**Comment by vietj** [comment]
I think using event-bus would achieve the same because there is actually one event-loop that process packets, in the case of TCP it is different, one event loop accept sockets (the acceptor) and then load balance each channel to an event loop. In the case of UDP there is only one single channel, so using event-bus to distribute load would achieve exactly the same.
