### ISSUE TITLE
When cluster manager fails to join the cluster, VertxImpl discards the error, leaving the caller stuck

### ISSUE THREAD

**Issue by guss77** [eclipse/vert.x#1797]
As evident in https://github.com/eclipse/vert.x/blob/868595511d8c63a6589a260da7cdea585219f20c/src/main/java/io/vertx/core/impl/VertxImpl.java#L165

if the `clusterManager.join()` call returns a failure, the `resultHandler` submitted to the `VertxImpl` constructor is never called (neither success nor failure) resulting in the handler never completing and the caller getting stuck with an unresponsive stack.

**Comment by jan-zajic** [comment]
@vietj, @guss77 please close this issue, because it's resolved with #1798 ?

**Comment by vietj** [comment]
can you confirm @tsegismont ?

**Comment by tsegismont** [comment]
Yes, #1798 closes this issue.
