### ISSUE TITLE
Better exception handling

### ISSUE THREAD

**Issue by rscorer** [eclipse/vert.x#1801]
In eclipse/vert.x/src/main/java/io/vertx/core/impl/ContextImpl.java

`        log.error("Unhandled exception", t);`

should be

`        log.error("Unhandled exception" + t);`

Otherwise the exception is not logged - which seems to be the point of the original code.

So in my logs I currently see

```
Feb 07, 2017 5:42:32 PM io.vertx.core.impl.ContextImpl SEVERE: Unhandled exception
Feb 07, 2017 5:42:32 PM io.vertx.core.impl.ContextImpl SEVERE: Unhandled exception
Feb 07, 2017 5:42:32 PM io.vertx.core.impl.ContextImpl SEVERE: Unhandled exception
Feb 07, 2017 5:42:32 PM io.vertx.core.impl.ContextImpl SEVERE: Unhandled exception
Feb 07, 2017 5:42:32 PM io.vertx.core.impl.ContextImpl SEVERE: Unhandled exception
Feb 07, 2017 5:42:32 PM io.vertx.core.impl.ContextImpl SEVERE: Unhandled exception
```

which is not as useful as having a message for each exception.

**Comment by tsegismont** [comment]
Your suggestion is wrong. The right way to log a message with exception is by providing it as an additional param. You should check your logging configuration.

**Comment by rscorer** [comment]
Thanks its my first time using JUL!,

`java.util.logging.SimpleFormatter.format=%1$tb %1$td, %1$tY %1$tl:%1$tM:%1$tS %1$Tp %2$s %4$s: %5$s%6$s%n`

The (new for me) %6$s added the exception message and backtrace.

**Comment by tsegismont** [comment]
Good news. If you're more comfortable with another logging framework, have
a look at
http://vertx.io/docs/vertx-core/java/#_using_another_logging_framework

2017-02-08 12:29 GMT+01:00 rscorer <notifications@github.com>:
