### ISSUE TITLE
Better failure logging when handleMessage failes

### ISSUE THREAD

**Issue by rscorer** [eclipse/vert.x#1802]
In `eclipse/vert.x/src/main/java/io/vertx/core/eventbus/impl/HandlerRegistration.java` in method `deliver` there is a catch block which could be improved slightly.

It has been advantageous to me to see the address of the message handler which has failed (for whatever reason)

```
    } catch (Exception e) {
      log.error("Failed to handleMessage ", e);
      metrics.endHandleMessage(metric, e);
      throw e;
```

```
      if (message != null) {
        log.error("Failed to handleMessage '" + message.address() + "'", e);
      } else {
        log.error("Failed to handleMessage ", e);
      }
```

So now if my event handler "service.releaseaccount" has a failure I am told so by name, which could be quite useful

**Comment by jan-zajic** [comment]
PR #1896. Null check is useless as message method called about 9 rows above.
