### ISSUE TITLE
Feature: Support large message framing for text messages in websockets

### ISSUE THREAD

**Issue by rmelick** [eclipse/vert.x#1807]
We would like to send and receive large text responses over websockets from our vertx server.  Since the message may be too large for the default websocket frame, the vertx library should split it into multiple frames.

[io.vertx.core.http.WebSocketBase](http://vertx.io/docs/apidocs/io/vertx/core/http/WebSocketBase.html) already supports sending large binary messages with the writeBinaryMessage function, so I would like to add a new function writeTextMessage.

This would be required to resolve issue 521 in vertx-web (https://github.com/vert-x3/vertx-web/issues/521).  In the pull request (https://github.com/vert-x3/vertx-web/pull/520) for that issue, it was identified that making some changes to WebSocketBase in vertx-core would be the best way forward.

This is similar to Issues #932 and #964.

**Comment by vietj** [comment]
contribution done
