### ISSUE TITLE
httpclient will always timeout  for one server if it is timeout many times even thoughit is normal now

### ISSUE THREAD

**Issue by haochun** [eclipse/vert.x#1813]
like the title.i am use httpclient to get file from some server.the server use nginx to be the web server.but,recently i found that if some rqeuest always timeout.

then,i try to find the reason.i found that if httpclient timeout sometimes for one server.httpclient will always timeout even though this server is normal now.when i restart my app,it will be normal.

my core code is:
```
HttpClientOptions options = new HttpClientOptions().setKeepAlive(false);
		options.setConnectTimeout(2 * 1000);
		options.setPipelining(true);
		options.setKeepAlive(true);
		options.setReceiveBufferSize(64 * 1024);
		httpClient = this.vertx.createHttpClient(options);
```

```
httpclient.get(ip,url,res->{
//do something
})..exceptionHandler(t -> {
			LOGGER.error("connect client failed,ip:" + ip + ",url:" + url + ",error:" + t.getMessage());
			serverResponse.setStatusCode(500).putHeader("Content-Type", "text/html").end(Config.SERVER_ERROR + ": Connect Storage failed.");
		}).setTimeout(10 * 1000).end();
```

**Comment by vietj** [comment]
setConnectTimeout is not the same thing as setTimeout, can you clarify the issue ?

**Comment by haochun** [comment]
i know.i think the setConnectTimeout is connect timeout.the setTimeout is readTimeout,right?my app is occured the readTimeout.the error message is:  

`The timeout period of 10000ms has been exceeded`

**Comment by vietj** [comment]
read timeout is when you don't read data for XXX ms, each chunk received, resets the timer.

so what are you experiencing ? can you provide a reproducer with a vertx http server ?

**Comment by haochun** [comment]
my server is using nginx.my problem is occured when one server is busy sometimes.then the httpclient will trigger the exceptionHandler.but,when the server is not busy(normal),the httpclient is still trigger  the exceptionHandler.
the exceptionHandler is in following  code:

```
httpclient.get(ip,url,res->{
//do something
})..exceptionHandler(t -> {
			LOGGER.error("connect client failed,ip:" + ip + ",url:" + url + ",error:" + t.getMessage());
			serverResponse.setStatusCode(500).putHeader("Content-Type", "text/html").end(Config.SERVER_ERROR + ": Connect Storage failed.");
		}).setTimeout(10 * 1000).end();
```

**Comment by haochun** [comment]
if i restart my app.the app will be normal(not trigger the exceptionHandler).
