### ISSUE TITLE
SSL server multiple certificates

### ISSUE THREAD

**Issue by nevenr** [eclipse/vert.x#1820]
Hi,

this is more suggestion for new feature. 

These days I was working with OpenShift (Kubernetes) and I noticed quite nice feature called [named certificates](https://docs.openshift.com/enterprise/3.1/install_config/certificate_customization.html). You can specify more key/cert pairs and they are used accordingly request target hostname ([Server Name Indication](https://tools.ietf.org/html/rfc4366#section-3.1), similar to virtual hosting).
This can be quite handy when one need to expose SSL service on multiple endpoints (for example behind multiple load balancers). Also this allows certificate composition instead of regenerating one with alternative subject name.

One key/cert pair should be considered as default and vertx should fall back to this one if request target hostname does not match to any other key/cert pair hostname.

Regards,
N.

**Comment by vietj** [comment]
we do have an (unfinished) PR for this https://github.com/eclipse/vert.x/pull/1698 , I'll try to complete the PR before 3.4.0. Meanwhile I'm closing this issue as invalid.
