### ISSUE TITLE
The JSON File from --conf should be read with the UTF-8 Charset

### ISSUE THREAD

**Issue by yasargil** [eclipse/vert.x#1836]
The JSON File from --conf should be read with the UTF-8 Charset (JSON default encoding) and not with the underlying platform's default charset.

In our case we have problems with Verticle's which we are deploying with a json config file (encoded in utf-8). Some characters are not decoded correctly because the default charset of the platform ist not utf-8. 

A workaround is to set the default encoding via -Dfile.encoding to utf-8. But this could have other implications in existing code.

The Problem lies in the class io.vertx.core.impl.launcher.commands.RunCommand and possibly other locations.
The Scanner should use UTF-8 as default encoding. Perhaps you could add an option to specify the encoding along the --conf option too.

```
protected JsonObject getConfiguration() {
    JsonObject conf;
    if (config != null) {
      try (Scanner scanner = new Scanner(new File(config)).useDelimiter("\\A")) {
        String sconf = scanner.next();
        try {
          conf = new JsonObject(sconf);
        } catch (DecodeException e) {
          log.error("Configuration file " + sconf + " does not contain a valid JSON object");
          return null;
        }
      } catch (FileNotFoundException e) {
        try {
          conf = new JsonObject(config);
        } catch (DecodeException e2) {
          // The configuration is not printed for security purpose, it can contain sensitive data.
          log.error("The -conf option does not point to an existing file or is not a valid JSON object");
          e2.printStackTrace();
          return null;
        }
      }
    } else {
      conf = null;
    }
    return conf;
 }
```

**Comment by pmlopes** [comment]
The scanner should be hardcoded to unicode has defined by the spec:

http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf
and the original design:
http://json.org/
