### ISSUE TITLE
Address resolver should have a retry mechanism

### ISSUE THREAD

**Issue by testn** [eclipse/vert.x#1849]
In certain network configuration, the DNS server can be located remotely. Therefore, it might be susceptible to a packet drop. When that happens, AddressResolver seems to fail to resolve the DNS name. I would prefer that we have some DNS retry mechanism rather than letting the request fails.

**Comment by testn** [comment]
I opened a similar issue with Netty https://github.com/netty/netty/issues/6479

**Comment by vietj** [comment]
it does today, you should increase the maxQueries value, I've a PR to increase the default maxQuery to 4 . Please reopen an issue if you find that not increasing maxQueries does not solve your issue
