### ISSUE TITLE
Make it possible to customize DNS behavior

### ISSUE THREAD

**Issue by testn** [eclipse/vert.x#1850]
In Netty 4.1.X, https://netty.io/4.1/api/io/netty/resolver/dns/RoundRobinDnsAddressResolverGroup.html is added so that it can perform the load balancing more properly. It would be nice if we have a mechanism to plug in a different implementation into Vert.x

**Comment by vietj** [comment]
how about having it configurable on AddressResolverOptions with a boolean `useRoundRobin` and handle that automatically in Vert.x AddressResolver ?

**Comment by vietj** [comment]
I think it would be simpler to support this feature using `DnsServerAddresses` no ? the RoundRobinDnsAddressResolverGroup seems to be for load balancing among several resolver

**Comment by vietj** [comment]
can you check https://github.com/eclipse/vert.x/pull/1855 ? I've done improvements to allow round robin selection

**Comment by vietj** [comment]
can you reopen more specific issues instead ?
