### ISSUE TITLE
KeyStoreHelper just support PKCS8,Not support RSA private key

### ISSUE THREAD

**Issue by jeho0815** [eclipse/vert.x#1851]
`public PrivateKey loadPrivateKey() throws Exception {
      if (keyValue == null) {
        throw new RuntimeException("Missing private key path");
      }
      byte[] value = loadPems(keyValue.get(), "**PRIVATE KEY**").get(0);
      KeyFactory rsaKeyFactory = KeyFactory.getInstance("RSA");
      return rsaKeyFactory.generatePrivate(new PKCS8EncodedKeySpec(value));
    }`

**Comment by jeho0815** [comment]
public PrivateKey loadPrivateKey() throws Exception {
      if (keyValue == null) {
        throw new RuntimeException("Missing private key path");
      }
      String pem = keyValue.get().toString();
      byte[] value = null;
      KeyFactory rsaKeyFactory = KeyFactory.getInstance("RSA");
      KeySpec keySpec = null;
      if (pem.indexOf("RSA PRIVATE KEY") > 0) {
          value = loadPems(pem, "RSA PRIVATE KEY").get(0);
          List<BigInteger> rsaIntegers = new ArrayList<BigInteger>();
          ASN1Parse(value, rsaIntegers);
          if (rsaIntegers.size() < 8)  {
            throw new Exception("'"  + 
              "' does not appear to be a properly formatted RSA key");
          }
          BigInteger publicExponent = rsaIntegers.get(2);
          BigInteger privateExponent = rsaIntegers.get(3);
          BigInteger modulus = rsaIntegers.get(1);
          BigInteger primeP = rsaIntegers.get(4);
          BigInteger primeQ = rsaIntegers.get(5);
          BigInteger primeExponentP = rsaIntegers.get(6);
          BigInteger primeExponentQ = rsaIntegers.get(7);
          BigInteger crtCoefficient = rsaIntegers.get(8);
          keySpec = new RSAPrivateCrtKeySpec(modulus, publicExponent, privateExponent,
            primeP, primeQ, primeExponentP, primeExponentQ, crtCoefficient);
      }
      else {
          value = loadPems(pem, "PRIVATE KEY").get(0);
          keySpec = new PKCS8EncodedKeySpec(value);
      }
      
      return rsaKeyFactory.generatePrivate(keySpec);
    }
    
    private static void ASN1Parse(byte[] b, List<BigInteger> integers) 
            throws Exception  {
          int pos = 0;
          while (pos < b.length)  {
            byte tag = b[pos++];
            int length = b[pos++];
            if ((length & 0x80) != 0)  {
              int extLen = 0;
              for (int i = 0; i < (length & 0x7F); i++)  {
                extLen = (extLen << 8) | (b[pos++] & 0xFF);
              }
              length = extLen;
            }
            byte[] contents = new byte[length];
            System.arraycopy(b, pos, contents, 0, length);
            pos += length;

            if (tag == 0x30)  {  // sequence
              ASN1Parse(contents, integers);
            } else if (tag == 0x02)  {  // Integer
              BigInteger i = new BigInteger(contents);
              integers.add(i);
            } else  {
              throw new Exception("Unsupported ASN.1 tag " + tag + " encountered.  Is this a " +
                "valid RSA key?");
            }
          }
        }

**Comment by vietj** [comment]
is that a reproducer ?

**Comment by vietj** [comment]
can you provide a signed-off PR with tests ?

**Comment by jan-zajic** [comment]
+1 We have same problem every time our system engineers generate private keys.. We must tell them to convert it to PKCS#8

**Comment by jan-zajic** [comment]
@jeho0815 i created PR #1897. I used your implementation of method ASN1Parse, with your permission?

**Comment by vietj** [comment]
@jeho0815 can you grant permission to load the ASN1Parse method for #1897 ?

**Comment by vietj** [comment]
@jeho0815 have you signed Eclipse CA ?

**Comment by vietj** [comment]
it looks like the code was copied from here http://commandlinefanatic.com/cgi-bin/showarticle.cgi?article=art049

**Comment by vietj** [comment]
I'll workaround it by doing what most other project do, adapt a private key reader from jmeter sources like here https://github.com/rhuss/jolokia/blob/b6010e3c053648eb280e57c1255f741d579b0688/agent/jvm/src/main/java/org/jolokia/jvmagent/security/PKCS1Util.java

**Comment by vietj** [comment]
this may however mean it is in Vert.x 3.5 and not in 3.4.2 if it requires a CQ

**Comment by jeho0815** [comment]
Alse see #1897
