### ISSUE TITLE
Should use ResolverConfiguration whenever possible to find DNS configuration

### ISSUE THREAD

**Issue by testn** [eclipse/vert.x#1856]
On Oracle JVM, I think it is much simpler to use sun.net.dns.ResolverConfiguration to find the DNS configuration. Look at http://dnsjava.org/dnsjava-current/org/xbill/DNS/ResolverConfig.java for an example.

**Comment by vietj** [comment]
this is what Netty uses under the hood : https://github.com/netty/netty/blob/4.1/resolver-dns/src/main/java/io/netty/resolver/dns/DnsServerAddresses.java#L48

what else could it uses ?

**Comment by vietj** [comment]
if you find a setting that could be improved don't hesitate to reopen a more specific issue.

**Comment by testn** [comment]
Ah 4 probably makes sense if DNS is queried for both IPv4 and IPv6 names.

**Comment by testn** [comment]
Ah never mind. I was confused at line https://github.com/eclipse/vert.x/blob/237bc5d44d7bddf21af97daf708f9d1661a73374/src/main/java/io/vertx/core/impl/AddressResolver.java#L70

I didn't notice that ndot option is not provided by sun.net.dns.ResolverConfiguration

**Comment by vietj** [comment]
yes it is not, so we've custom code in vertx for this

**Comment by vietj** [comment]
@tests the problem with maxQuery is that it is complex to determine the number of queries done for a dns server as it varies between 1 and 3 at the moment:

- IPV4 or IPV6 : 1
- both : 2
- with CNAME resolution : 2 + 1

So I think Netty instead should handle the number of retries or something easier to calculate

**Comment by vietj** [comment]
so depending on your case, the number of max query varies
