### ISSUE TITLE
Don't get a lock with Hazelcast

### ISSUE THREAD

**Issue by marcelalburg** [eclipse/vert.x#1861]
Hello,

i wrote a small class for getting a lock with the Hazelcast Cluster manager.

This code will never get a lock and runs in a timeout. 

Why is this happen ?
Thanks 
Marcel

```
public class LockTestCluster {
	public static void main(String[] args) {

		String localIp = "127.0.0.1";

		VertxOptions vertxOptions = new VertxOptions();
		Config hazelcastConfig = new Config();

		hazelcastConfig.getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);
		hazelcastConfig.getNetworkConfig().getJoin().getTcpIpConfig().setEnabled(true);
		hazelcastConfig.getNetworkConfig().getJoin().getTcpIpConfig().addMember(localIp);

		hazelcastConfig.getNetworkConfig().setPublicAddress(localIp);
		vertxOptions.setClusterPublicHost(localIp);

		ClusterManager mgr = new HazelcastClusterManager(hazelcastConfig);

		vertxOptions.setClusterManager(mgr).setClustered(true);

		DeploymentOptions deployOptions = new DeploymentOptions();

		Vertx.clusteredVertx(vertxOptions, res -> {
			if (res.succeeded()) {
				Vertx vertx = res.result();

				vertx.sharedData().getLockWithTimeout("testLock", 10000L, lockRes -> {

					if (lockRes.succeeded()) {
						Lock lock = lockRes.result();

						lock.release();
					} else {
						System.out.println("Cannot get lock: " + lockRes.cause().getMessage());
					}
				});

				System.out.println("done");

			} else {
				res.cause().printStackTrace();
			}
		});
	}
}
```

**Comment by tsegismont** [comment]
If you create your own configuration programatically, you must set the
minimal Vert.x configuration as described in:

https://github.com/vert-x3/vertx-hazelcast/blob/master/src/main/asciidoc/java/index.adoc#using-an-existing-hazelcast-cluster

In particular, you need to set the "*__vertx.**" semaphores with initial
permits of 1.

2017-03-06 11:51 GMT+01:00 Marcel Alburg <notifications@github.com>:

**Comment by marcelalburg** [comment]
Uhh upps, i didn't read that. Thanks, works perfectly now.

Marcel

**Comment by tsegismont** [comment]
Just a note about filing issues.

If you have a Hazelcast related issue, file it in the
vert-x3/vertx-hazelcast repository.
If you're not sure if it's a core or Hazelcast or ... issue, file it in the
vert-x3/issues repository.

In general, it's a good idea to ask a question on the forum first to check
if you can get any help from the community (not all members get notified
about issues)


2017-03-06 12:21 GMT+01:00 Thomas SEGISMONT <tsegismont@gmail.com>:
