### ISSUE TITLE
JsonObject.mergeIn(JsonObject other, int depth) does not regard NULL values

### ISSUE THREAD

**Issue by joshiausdemwald** [eclipse/vert.x#1866]
Hi,

i am unsure if it's a imperfection or a design decision by intention:

Using JsonObject.mergeIn() with JSON object keys having NULL values leads to NullPointerException -- the reason for this is that Map.merge() requires the source map to be non-NULL.

Any idea or hint on this?

**Comment by joshiausdemwald** [comment]
Java Platform is OpenJDK 8, Vertx-Version is 3.3.4-beta1

**Comment by vietj** [comment]
so you mean something like

new JsonObject().mergeIn(new JsonObject().put(null, "foo"))

produces an NPE ?

**Comment by joshiausdemwald** [comment]
Actually not. Its a structure like
```
{
    key1: null
}

```

I will just try to reproduce it by code, just wait  a minute ...

**Comment by joshiausdemwald** [comment]
Hi,

my bad -- i  am not really able to reproduce it in a simple usecase.

The error happens after de-serializing some foreign formats (yaml) to json, then doing merging and mapping, with an older version of vertx (3.3.3), with a **manually** backported  version of mergeIn() from 3.4.0-beta1.

I have found a workaround,  and i am pretty sure that the actual root cause is hidden somewhere in the code i myself is guilty for.

Thanks :) and sorry!
