### ISSUE TITLE
Vert.x 3.4.0 doesn't start with Netty 4.1.9.Final

### ISSUE THREAD

**Issue by guidomedina** [eclipse/vert.x#1872]
```
java.lang.NoSuchMethodError: io.netty.resolver.HostsFileParser.parseSilently()Ljava/util/Map;
	at io.vertx.core.impl.AddressResolver.<init>(AddressResolver.java:156)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:157)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:123)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:119)
	at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:34)
	at io.vertx.core.Vertx.vertx(Vertx.java:80)
```

**Comment by vietj** [comment]
@guidomedina Netty 4.1.9.Final changed an unstable API that Vert.x uses, unfortunately there is nothing we can do as we intent to stick with 4.1.8.Final for now.

**Comment by guidomedina** [comment]
I only reported it, thought it might be helpful to do so, I haven't looked at the source code but it seems trivial enough to parse a file with something else?

Lately I see Vert.x releasing every several months, does that mean we are stuck with Netty 4.1.8.Final even if their fixes are compelling enough?

**Comment by guidomedina** [comment]
This is the change that is causing this error, it seems trivial enough to re-adapt to it:
https://github.com/netty/netty/commit/81f9de423c03ec4538f1ba04b89ae049959b698c#diff-fc846759966069225c9bfe87e547a86b

**Comment by vietj** [comment]
yes but then it would be not compatible anymore with 4.1.8.Final and the current gRPC integration would be incompatible.

I believe we should extract the DNS resolver part in a separate module and come up with an SPI. By default Vert.x Core would use blocking DNS instead of the async *unstable* non-blocking DNS resolver.

**Comment by vietj** [comment]
Do you have an urgent need for Netty 4.1.9.Final ?

**Comment by vietj** [comment]
By the way the *@UnstableApi* was not there previously :-)

**Comment by guidomedina** [comment]
I don't have an urgent need for it, but I got a bit scared when you say you guys are planning to stick to it, as the release record is something like 6 months one wonder if you mean only immediate future or the Vert.x slow cycle.

I can survive with Netty 4.1.8.Final for sometime, but judging by Netty fixes and the use I have for it which is low latency price streaming and trading via websockets for the financial industry one would like to stay updated with their release.

I only see two choices here due to breaking API:
- 3.4.1
- 3.5.0

In theory Netty requirement didn't jump a major version like from 4.1.x to 5.0.x so maybe 3.4.1 makes sense, but then if you have minor version patches it would make sense to keep 3.4.x for 4.1.8.Final (stuck version) and 3.5.x for 4.1.9.Final+

**Comment by guidomedina** [comment]
Umnmm, what am I thinking? your proposal of different SPI is much better than maintaining 2 versions.

**Comment by vietj** [comment]
@guidomedina the SPI would allow to have a version of Vert.x Core that depends less on an unstable Netty API, although the HTTP/2 API is not stable either (but I think more stable than DNS). This change would be done in a Vert.x 3.5.

And indeed we should release more often I believe, although releasing has a cost. My opinion is that 3.4.0 was a big (and awaited!) release with plenty of great stuff, but our current rate now is one 3.x release per year. I think that having 2 would be more reasonable.

**Comment by vietj** [comment]
fixed

**Comment by farrukh-obaid** [comment]
Hi i am using **Vertx 3.4.1** and i am getting some warnings from Netty when i deployed app on linux container
```
   "message":"Failed to find a usable hardware address from the network interfaces; using random bytes: 15:2a:bc:3a:2a:c1:ae:33"
   "path": "io.netty.util.internal.MacAddressUtil",
   "priority": "WARN",
   "logger_name": "io.netty.util.internal.MacAddressUtil",
   "thread": "vert.x-worker-thread-0"
```
this has been fixed in netty 4.1.9 final here
https://github.com/netty/netty/pull/6308
But vertx 3.4.1 is using netty 4.1.8

**Comment by guidomedina** [comment]
There isn't a strong requirement for Vert.x to use the latest Netty version, in your POM you can exclude all Netty modules and just include `netty-all` like I do and keep yourself on par with Netty updates as it is the core of Vert.x HTTP communication, other than that is irrelevant.

**Comment by farrukh-obaid** [comment]
@guidomedina 
It may break my code as it is not officially bundled with vertx. in Vert.x 3.4.1 umbrella they mentioned that Vertx 3.4.1 will include netty 4.1.9 final but it still using 4.1.8 i just wanted to know where this fixed applied? in Vertx 3.5.x version?

**Comment by vietj** [comment]
Vert.x 3.4.1 uses Netty 4.1.8.Final because grpc-java uses the same version.

When grpc-java will move to a later version of Netty we will likely upgrade too to the same version.

I don't think grpc-java will uses Netty 4.1.9.Final because this version has regressions for grpc-java (https://github.com/netty/netty/issues/6579)

**Comment by farrukh-obaid** [comment]
@guidomedina  @vietj i am only using NetServer and HttpClient is it safe to upgrade to Netty 4.1.9?

**Comment by vietj** [comment]
@guidomedina the best option is to run the Vert.x test suite with Netty 4.1.9.Final to figure out

**Comment by vietj** [comment]
we have done a commit in 3.4.1.Final to allow to run without the Netty DNS resolver (that is unstable API wise)
