### ISSUE TITLE
Can't run embeded Vert.x under JDK9

### ISSUE THREAD

**Issue by twasyl** [eclipse/vert.x#1889]
Hello,

I'm currently trying to migrate [SlideshowFX](https://github.com/twasyl/SlideshowFX/tree/feature_23) to JDK9 (build 161 with Jigsaw).
The application embeds Vert.x in order to provide a WebServer. Until now I have been using Vert.x 3.3.3 and the application was running "well". Now I'm trying to use versions 3.4.0 and 3.4.1 and when starting the application, I've got the following error and the application can't boot:

```
Error occurred during initialization of boot layer
java.lang.module.FindException: java.io.IOException: Provider class moduleName = io.vertx.ext.web.handler.VirtualHostHandler-module not in module
Caused by: java.io.IOException: Provider class moduleName = io.vertx.ext.web.handler.VirtualHostHandler-module not in module
```

When looking at the source code of `vertx-web`, I can see the `META-INF/services/org.codehaus.groovy.runtime.ExtensionModule` file. As specified by the [ServiceLoader](http://download.java.net/java/jdk9/docs/api/java/util/ServiceLoader.html) class, such files are used in order to define services not developed as JPMS modules but running as JAR files on the classpath. I suppose the addition of this file is intentional by the Vert.x developers but I can't figure out how to be able to start SlideshowFX again.

Have you encountered such issue and were able to fix it?

Thanks

**Comment by vietj** [comment]
hi can you open this issue on the Vert.x Web issue tracker instead ? https://github.com/vert-x3/vertx-web

**Comment by twasyl** [comment]
Hi,

I've opened the issue [567](https://github.com/vert-x3/vertx-web/issues/567).

Thanks.

**Comment by vietj** [comment]
thanks!
