### ISSUE TITLE
Race condition in Future setHandler/completion between threads

### ISSUE THREAD

**Issue by halajos** [eclipse/vert.x#1892]
In one of our projects we have encountered a problem with CompositeFuture.all() when running "outside"
of a verticle (in junit tests). Here is a sample program:

```java
import io.vertx.core.CompositeFuture;
import io.vertx.core.Future;
import io.vertx.core.Vertx;

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;

public class CompositeFutureTest {
    private static final int NUMBER_OF_LOOPS = 10_000;
    private static final Vertx vertx = Vertx.vertx();

    private static boolean testCompositeFuture() throws InterruptedException, ExecutionException {
        CountDownLatch finished = new CountDownLatch(1);
        AtomicInteger atomicCounter = new AtomicInteger(0);

        for (int i = 0; i < NUMBER_OF_LOOPS; i++) {
            Future<Void> future1 = Future.future();
            Future<Void> future2 = Future.future();

            vertx.runOnContext(future1::complete);
            vertx.runOnContext(future2::complete);

            CompositeFuture.all(future1, future2).setHandler(ar -> {
                if (ar.succeeded()) {
                    if (atomicCounter.incrementAndGet() == NUMBER_OF_LOOPS) {
                        finished.countDown();
                    }
                }
            });
        }

        boolean result = finished.await(10, TimeUnit.SECONDS);

        System.out.println(String.format("%s: %s == %s", result ? "OK": "ERROR", atomicCounter, NUMBER_OF_LOOPS));

        return result;
    }

    public static void main(String[] args) throws InterruptedException, ExecutionException {
        while (testCompositeFuture());
        vertx.close();
    }
}
```
After a while it prints something like
```
ERROR: 9985 == 10000
```
Inside implementation of CompositeFutureImpl.all() the setHandler() function is called upon each future in the composition (in our case two). The problem here is that the completion of futures runs in a different thread than setting the handler. Neither of the functions (setHandler() nor complete()) are atomic and it may result in
a situation when the handler is never called. The problem seems to be more fundamental. The future
implementation (FutureImpl) is not thread safe and using it from different threads may cause difficulties.
When running inside a verticle it's ok because asynchronous callbacks are serialized within the event loop
and should not run concurrently.

I don't know if this is an expected behaviour and Futures (and their compositions) should be used only
within verticles. Our understanding based on looking into the implementation of CompositeFutureImpl is that
the intention was to make it thread safe.

**Comment by vietj** [comment]
Initially the future were more internally used by Vert.x and only used to create a callback object already initialized. I believe that indeed the actual future should guarantees proper visibility between threads.

CompositeFuture are indeed explicitely synchronized because they are by nature explicitely concurrent  and have been synchronized for this reason.

I believe we should make FutureImpl synchronized and provide and implementation of AsyncResult that would have a final value and not be a future, so internally for a callback we just create an unsynchronized AsyncResult used as callback.

**Comment by vietj** [comment]
would you mind to check https://github.com/eclipse/vert.x/tree/future-safe ?

**Comment by halajos** [comment]
Hi, thank you for your quick answer. I looked at the code and it seems good. I made a quick test with the
sample code above and it's working too. I'm looking forward for next releases of Vert.x. You guys are doing
a really good job.

**Comment by vietj** [comment]
thanks, I'll add test cases before and then will do a PR
