### ISSUE TITLE
Type Matching Event Bus Messages?

### ISSUE THREAD

**Issue by InfoSec812** [eclipse/vert.x#1902]
I think it would be quite valuable to support an overloaded method for the EventBus consumer to allow specifying the type of the message:

```
EventBus eb = vertx.eventBus();
eb.consumer(address, Type<? extends Serializable>, handler);
```

This would allow for type-safe message handling and allow for matching different consumers to different types. I'll try to look into what it would take to make this possible. It obviously wouldn't easily apply to some of the dynamic languages though...

**Comment by vietj** [comment]
Hi,

I think it would work better if you use your own class to do that:

```
public static <T> Handler<Message<T>> matching(Class<T> match, Handler<Message<T>> consumer) {
  return msg -> {
    if (match.isInstance(msg.body()) {
       handler.handler(msg);
    }
  };
}
```

In addition it allows you to come up with a richer API if needed.

**Comment by InfoSec812** [comment]
How would that work with multiple consumers for different types though? I was thinking along the lines of:

```
String address = "event.update";
EventBus eb = vertx.eventBus();
eb.consumer(address, User.class, handler);
eb.consumer(address, Product.class, handler);
eb.consumer(address, BillOfSale.class, handler);
```

**Comment by vietj** [comment]
in this case `handler` has to be `Handler<Object>`

**Comment by InfoSec812** [comment]
Perhaps I'm not explaining it properly... It seems to me that your solution would deliver the message to all of the handlers, regardless of type; then the handler would discard non-matching items. In that case, wouldn't I have to "publish" so that multiple typed handlers could each receive the message? My thoughts on this would be that the eventbus code could have logic added so that it only tries to deliver to an appropriately typed handler. That way the "send" method could be used and the event bus would only deliver to the appropriately typed handler.

**Comment by vietj** [comment]
I understand but a message is sent/published regardless to an address, regardless of the recipient.

If you need such semantic I think you should use different addresses instead and use a convention to map the recipient to addresses.

**Comment by InfoSec812** [comment]
Yeah, I certainly see your point. I'll close this and think about it further...

Thanks!!!
