### ISSUE TITLE
Cannot process buffer in worker NetClient on channel inactive

### ISSUE THREAD

**Issue by rogelio-o** [eclipse/vert.x#1906]
In the new version 3.4.1, I get the following exception when I send an email through an non-shared client and a AWS SES server:
```
java.lang.NullPointerException
io.vertx.core.net.impl.NetClientImpl$1.handleMsgReceived(NetClientImpl.java:197)
io.vertx.core.net.impl.VertxNetHandler.lambda$channelRead$0(VertxNetHandler.java:64)
io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:335)
io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)
```

I think the problem is this: in the line 197 of NetClientImpl, the attribute _conn_ can be null because of the method _removeConnection_ has been called in the VertxNetHandler, so it causes a null pointer exception.

**Comment by vietj** [comment]
do you have reproducer ?

**Comment by rogelio-o** [comment]
I'm afraid I cannot reproduce the error neither in an isolate example nor in the main project. I saw the exception in the log. It happens sometimes when an email is sent, but only in local. Could it be related with a internet connection error? We didn't get this exceptions before the version update (3.3.0 to 3.4.1). We don't want to put in production the updated microservice without know why this exception happen.

Thanks for your answer! I will try to reproduce it.

**Comment by vietj** [comment]
@rogelio-o it seems to be a message received after the connection is become inactive which would be related to a race. As you as you reproduce it, it will definitely help.

**Comment by vietj** [comment]
ah I can see you are using this from a worker thread which might explain the race

**Comment by vietj** [comment]
it might be possible with some delay that a message is processed just after a connection is closed, going to investigate.

**Comment by rogelio-o** [comment]
Thank you! And thank you for your fixes. I will keep trying isolate an example considering a race as the problem, but I think with these fixes the exception won't happen anymore.

**Comment by vietj** [comment]
@rogelio-o I reproduced the issue and opened a PR for it
