### ISSUE TITLE
Vert.x HttpServerResponse serialization

### ISSUE THREAD

**Issue by YoavNordmann** [eclipse/vert.x#1914]
I have 1 Verticle which receives HttpRequests. This Verticle sends the data on to a processing verticle which in itself sends it on to a processing verticle  and so on untill all processing is done. At the end I would like to to send a response...

**And this is my problem: I cannot send the RoutingContext or the HttpResponse over the EventBus to the next Verticles otherwise I will loose the Vert.X Clustering capabilities since that object is not serializable.**

I tried saving the same object to a Apache Ignite Cache with the same result.

In the beginning I had an architecture which involved Orchestrator Objects in order to reply and so always return to the original Rest Verticle, but this is not scalable as I would like.

Any information on such a possibility would be appreciated.

Tim fox wrote in an older response to a similar [question](https://groups.google.com/forum/#!topic/vertx/zJgJDAk0T1w) the following 

> You could serialize it to a byte[] and deserialize it at the other end. Vert.x 3.0 supports custom serializers on the event bus, so you could create one for HttpServerRequest.

I would very much like to know how to do this as I am unsuccessful to do this.

Thank you in advance

Yoav

**Comment by silmeth** [comment]
You can write an EventBus `Codec` that just takes `HttpServerResponse` and returns it when writing to the EventBus (and the same when reading from EventBus).

That will, pf course, only work between Verticles working on the same JVM in the same process. And I am not sure sharing the `HttpServerResponse`, `Request` etc. between threads is a good idea.

**Comment by YoavNordmann** [comment]
Hi
I know this solution but in this case I am loosing the ability to cluster my Vert.X application.
There are 7 - 10 steps which I have to make in order to reach a response. It makes much more sense chaining those verticles than having all of them perform a reply. It makes a lot of sense to be able to stash the HttpResponse Object somewhere in order to answer the request. Another possibility would be that somehow the last verticle in the chain would need to be able to perform the "reply" to the first verticle.

**Comment by pmlopes** [comment]
@YoavNordmann you'll not be able to send the `HttpServerResponse` to other processes/servers, for the basic reason that you cannot share sockets and state across servers, you can however act as a proxy, your receiver handler will send the request body encoded as json for example to some other node and when this node replies your handler will write it to the `HttpServerResponse`.
