### ISSUE TITLE
3.4.1: Eventbus can only eat max 50% CPU 

### ISSUE THREAD

**Issue by mhstnsc** [eclipse/vert.x#1916]
Clustered vertx, core i7.

The test is about send and reply between verticles and then measure rate. 

The test has a bunch of eventloop verticles doing send to a bunch of worker/eventloop consumer verticles. When the senders receive a reply they send again (a kind of async/reactive busy loop)

The observed behavior is that i can never increase the CPU usage to more than 50%. I doubled the number of eventloop pool size and no effect.

Reproducer can be found here: https://github.com/mhstnsc/vertx-tests
Exact test is here: https://github.com/mhstnsc/vertx-tests/blob/master/src/test/java/io/vertx/test/performance/EventBusTest.java

You can run it with:
`gradle :test --tests io.vertx.test.performance.EventBusTest.testWorkerConsumer -i`

As a control test you can run another test which can load the CPU 100% by doing md5 computations in 200 worker verticles (can also be event loop verticles)
`gradle :test --tests io.vertx.test.performance.EventBusTest.testMaxCpuLoad -i`

![screenshot from 2017-03-31 10 25 35](https://cloud.githubusercontent.com/assets/236410/24542956/ead034b4-15fd-11e7-87d8-e2c4bf950ae7.png)
![screenshot from 2017-03-31 10 19 32](https://cloud.githubusercontent.com/assets/236410/24542957/ead24f74-15fd-11e7-9161-c44f62d66a6a.png)

**Comment by purplefox** [comment]
What does red represent in the above diagram? Thread blocked?

If so, then on about half your event loops they seem to be blocked most of the time, which doesn't seem right.

**Comment by mhstnsc** [comment]
"Monitor" is the BLOCKED state, in which the thread is waiting to obtain a lock on an object (because it's trying to enter a synchronized block or method while another thread already holds the associated lock).

http://stackoverflow.com/questions/6705400/java-jvm-profiling-thread-status-what-does-monitor-status-mean

So you are right...they are blocked. 

Could it be because i use a reply handler, could it be because of registration of the reply address?

**Comment by vietj** [comment]
it seems that you are using a case that you don't understand and you are deferring it as an issue to the issue tracker to have someone look at your case and explain the behavior. It would be best you ask rather for an explanation of what is going on AND also you try to understand better what happens in your system.

**Comment by purplefox** [comment]
If you add a profiler to the process it should be able to tell where the
threads are blocked.

or.. a quick and dirty way, if you get a dump of all stack traces (killall
-3 java) it might tell you something

**Comment by mhstnsc** [comment]
@vietj  What? I understand very well my case here. I have decided to place the issue here because it is a issue. 

I have used the same performance testing framework for another operaiton just to prove that i can load the CPU to 100% .

When i use the test framework on EventBus.send  it fails. For me it looks like an issue in the EventBus.

I tried to isolate as much as i could with the internals

**Comment by vietj** [comment]
can you tell how to measure the issue rather than screenshots ?

if I want to reproduce it on my machine, how can I tell wether or not the issue is solved ?

**Comment by mhstnsc** [comment]
Just run the reproducer i provided, i gave the command line. Keep it running and check your CPU level.

**Comment by vietj** [comment]
I am not saying there is no issue

I am saying that there is a behavior you cannot explain and you are deferring it is a defect of Vert.x.

What measn check the CPU level ? which tool should one use ?

**Comment by vietj** [comment]
also your test is quite complicated, can you simplify it without the framework you build around it so it's easier to understand what is going on ?

it seems also that you are doing an extreme case with 2000 sender verticles.

Perhaps you can simplify it to use less Verticles or one verticle per event loop (because I don't think that you need more than N sender where N is the number of eventloops).

**Comment by vietj** [comment]
i.e just a single test case with reasonnable numbers to exhibit the same issue with a test infrastructure around it (like MaxRateExecutor, etc...) would help.

we don't have much time to dedicate for each issue, and the simplest and the less overhead each issue has decrease the likelyhood someone can investigate what is going on and fully understand it and provide help.

**Comment by vietj** [comment]
so please come up with a simplified case (in the google group) and a way to objectively measure it (using maybe ThreadMXMBean mechanism) for everyone or at least the tool you are using and what should be precisely observe (I ran JProfiler and I saw 400+ threads in the VM so it's not easy to figure out what is good and what is not)

**Comment by purplefox** [comment]
I agree with Julien, I suspect that number of verticles is not necessary to
reproduce the issue.

Also there seem to be several classes in the reproducer which aren't used
or relevant.

To get things resolved quickly it always pays to submit the simplest
possible reproducer that exhibits the issue. This can often help isolate
issue too, as sometimes when you remove something you find the issue
disappears which can you a big clue to what is going on :)
