### ISSUE TITLE
Codegen does not work

### ISSUE THREAD

**Issue by kostonstyle** [eclipse/vert.x#1917]
Hi all 

I am trying to generate a service proxy but it does not work at all.
The code does not get generated.
You can find the project on the attachment.  Please help me.
[microservice1.zip](https://github.com/eclipse/vert.x/files/886029/microservice1.zip)

Thanks

**Comment by vietj** [comment]
hi can you instead send this to the community and not open an issue here ?

**Comment by kostonstyle** [comment]
sorry

**Comment by kostonstyle** [comment]
Can you help me please https://groups.google.com/forum/#!topic/vertx/phVvYvEyf8E. 

Thanks
