### ISSUE TITLE
What's the reason for own Buffer implementation?

### ISSUE THREAD

**Issue by Ziemien** [eclipse/vert.x#1926]
Hi

I wonder what's the benefit of using custom Buffer implementation as opposite to default Java's of netty's?

On a first sight seems a bit ineffective as there already many wrappers around exiting wrappers - to deserialise objects etc in many popular libraries. Very often there is a need to convert it to string or use getBytes which is coping operation. Seems like initialisation of BufferImpl itself requires copying. 

Is that all really necessary? 

I might miss a bigger picture, if I am wrong I apologise in advance.

**Comment by EmadAlblueshi** [comment]
Hi, you can ask questions in [Vertx Google Group](https://groups.google.com/forum/m/#!forum/vertx) Thank you

**Comment by vietj** [comment]
@Ziemien the actual Vert.x buffers aims to be easier to use than Netty's buffer for the end user. They don't expose the readerIndex/writeIndex and pooling, leaving these for the internal implementation. So we believe for the end user that _less is more_.
