### ISSUE TITLE
SelfSignedCertificate is always generated with the "example.com" domain name

### ISSUE THREAD

**Issue by zerola** [eclipse/vert.x#1927]
SelfSignedCertificate is always generated with the "example.com" domain name which is not very useful if we use it in tests where both server and clients are on the "localhost". Hence, unless we provide an option to the HttpClient - **setVerifyHost(false)** - the client cannot talk to the server using this generated certificate.

I suggest to override the _create_ method in SelfSignedCertificate with domain name as the parameter and pass this FQDN to the underlying Netty implementation.

**Comment by tsegismont** [comment]
I'm not sure this would be useful considering we already have to configure
the client to trust all certificates.

2017-04-07 8:45 GMT+02:00 Michal Zerola <notifications@github.com>:

**Comment by zerola** [comment]
Not sure what you mean by "we already have to". Imagine your application uses HttpClient and you want to test it using SelfSignedCertificate. You create a mock HttpServer in your tests and provide the generated certificate as the trusted certificates to the instance of your code which provides the HttpClient. There is no "trust all" option and you do not want to trust all certificates in your production code.

**Comment by tsegismont** [comment]
What I meant is that you already have to add this certificate in the trust
options. This is something you wouldn't do in production since you'd use a
valid certificate (signed by a trusted certificate authority). So you're
already not using the same code for test/production.

2017-04-07 10:09 GMT+02:00 Michal Zerola <notifications@github.com>:

**Comment by jponge** [comment]
Note: SelfSignedCertificate is *not* meant for production, only for
development and tests.

**Comment by zerola** [comment]
Of course I use SelfSignedCertificate in tests only and I provide the generated trusted part of the certificate to the class I am testing (the class provides the HttpClient). In production the class uses trusted valid certificate. The problem why I created this issue is the host name validation which happens between the client and server no matter the certificate is trusted.

**Comment by vietj** [comment]
agreed, the domain should be flexible.

for instance, in the testsuite we are running tests with non localhost domains

**Comment by vietj** [comment]
you can run tests with the corresponding certificate on the client without requiring to `setVerifyHost(false)` for instance you are writing a verticle that consumes an HTTP API and you configure this verticle to use a specific certificate. The `SelfSignedCertficate` should allow to do that.

**Comment by jponge** [comment]
@zerola Is #1958 what you had in mind?

**Comment by zerola** [comment]
Yes, that is exactly it. Thanks!

**Comment by jponge** [comment]
Great!
