### ISSUE TITLE
Request for a new ContextImpl that mimics a Worker Context but allows multiple queues

### ISSUE THREAD

**Issue by juanavelez** [eclipse/vert.x#1937]
I have run into the following issue in the past before using Vert.x and now that I am using it as well. I really like the functionality that a Worker Context provides: A separate thread that runs tasks in the order they were submitted to the context to be executed. However this functionality could be even more helpful if the Worker Context would allow the submission of tasks to be executed in order in different queues based on some (defined?arbitrary?) identifier/priority. For example, I have the need to "serialize" the execution of tasks but tasks which have different priorities could be executed in parallel but I still need the "serialization" feature for tasks of the same priority.

Thanks - Juan

**Comment by vietj** [comment]
hi, do you have an actual use case for this ?

**Comment by juanavelez** [comment]
Yes. I need to process several messages on a worker context but those messages can be categorized and there is no need for messages of category A to be processed sequentially with messages of category B, but all messages for category A/B need to be processed in order.. Think about messages for order processing (not my actual use case but close), I have a Verticle which processes messages (creation, activation, provision, etc.) but all messages for an order need to be processed sequentially but messages for different orders can be processed in parallel. I think this new ContextImpl would be some sort hybrid of Worker and Multi-threaded contexts.

**Comment by vietj** [comment]
why would you need a specific context implementation for this ?

there is this existing issue https://github.com/eclipse/vert.x/issues/1539 that could somehow help for your use case

**Comment by juanavelez** [comment]
@vietj I agree that requesting the creation of a new Context Implementation might not be the right approach. My main complain with a possible implementation of #1539 (unless I am wrong the issue has no solution yet, right?) is that there is no way to indicate how where to place the Handler in a specific TaskQueue for execution unless the signature of Context.executeBlocking can change to accept a new structure instead of a Handler (so you could determine what TaskQueue to use). I was hoping that there could be something of an `executeBlocking(blockingCodeHandler, "Category/Queue", resultCodeHandler)` that would allow the blockingCodeHandler to be executed on a particular TaskQueue. Anyway, it seems you have not warmed up to the idea, so please feel free to close the issue. IMHO I still think there is value in supporting something like this.

**Comment by juanavelez** [comment]
After some thought I was able to come up with a simple(r?) solution to what I think the improvement should be:

https://gist.github.com/juanavelez/bf47ae84f842896350ca046a1d88ac5f.

Let me know what you think. 

Thanks - Juan

**Comment by vietj** [comment]
it seems you can do it without requiring a modification in Vert.x itself with an helper

**Comment by juanavelez** [comment]
I am sorry I don't understand what you meant since my modifications where to Vert.x core code themselves: src/main/java/io/vertx/core/Context.java, src/main/java/io/vertx/core/Vertx.java, src/main/java/io/vertx/core/impl/ContextImpl.java, src/main/java/io/vertx/core/impl/VertxImpl.java, src/test/java/io/vertx/test/core/ContextTest.java

**Comment by vietj** [comment]
I mean that we cannot have this in Vert.x core and you should make your own helper based on Vert.x core to implement this particular use case you need

**Comment by juanavelez** [comment]
May I ask why you cannot have this in Vert.x core?

**Comment by vietj** [comment]
why should we have ?

**Comment by vietj** [comment]
no offense to your proposal but this code does not seem generic purpose enough to be in Vert.x Core and we prefer to keep the Vert.x Core API minimal (less is more) and not overload it with a different meaning.

In your case you seem to need to add the notion of priority to task execution and it seems better to handle this with your concurrency util build on top of Vert.x Context concurrency. This will also allow you to improve it and tune it to your needs.

If you think this can interest the community, I encourage you to create a library for it and publish it then on the vertx-awesome page https://github.com/vert-x3/vertx-awesome . That's what many people in the community do.
