### ISSUE TITLE
Local event bus reply handler result failure on successful reply.

### ISSUE THREAD

**Issue by wrightm** [eclipse/vert.x#1940]
When sending a ```vertx.eventBus().send``` message on a local event bus I am seeing a timeout failure on the reply handler of the ```vertx.eventBus().consumer``` ```Message<T> requestMessage.reply ``` for successfully replied messages. My consumer code looks something like this.

```
vertx.eventBus().consumer( address )
				.handler( this::reply );
```

```
void reply( Message<SomeObject> requestMessage ) {
	requestMessage.<SomeObject> reply( service.someRequest( requestMessage),
					result -> {
						// result.succeeded() == false
					} 
       );
}
```

I have had a quick look at ```HandlerRegistration``` and see this line of code in the constructor which starts a timed task to call the reply handler with a failure.

```
 if (timeout != -1) {
      timeoutID = vertx.setTimer(timeout, tid -> {
        metrics.replyFailure(address, ReplyFailure.TIMEOUT);
        sendAsyncResultFailure(ReplyFailure.TIMEOUT, "Timed out after waiting " + timeout + "(ms) for a reply. address: " + address);
      });
    }
```

This timed task is however stopped by ```EventBusImpl.deliverMessageLocally``` that invokes ```HandlerRegistration.doUnregister``` which then invokes 

```
if (timeoutID != -1) {
      vertx.cancelTimer(timeoutID);
    }
```
that should cancel the timed task when successfully replied to.

Since send reply only selects at most one handler I am a bit confused why this is happening? Can anyone with greater knowledge of the EventBus internals explain why this is happening?

***Note my ```vertx.eventBus().send``` command is one a different Verticle to my ```vertx.eventBus().consumer```***

**Comment by vietj** [comment]
can you provide a reproducer ?

**Comment by wrightm** [comment]
@vietj looking into reproducing the bug with a simple example

**Comment by wrightm** [comment]
I have pushed a small maven project that reproduces the error https://github.com/wrightm/vertx-eventbus-reply-error

**Comment by wrightm** [comment]
From what I can tell I think this is what is happening...

Since the send reply handler is unregistered once there is a reply

```
vertx.eventBus().send( EVENT, data, res -> {
						handleEventBusResponse( res, ctx );
					} );
```
```
try {
        if (!holder.isRemoved()) {
          holder.getHandler().handle(copied);
        }
      } finally {
        if (holder.isReplyHandler()) {
          holder.getHandler().unregister();
        }
      }
```

and the address of the sent message has the reply handler address

```
message.reply( responseMessage, result -> {
					if ( result.succeeded() ) {
						System.out.println( "We answered" );
					} else {
						System.out.println( "We failed to answer: " + result.cause().getMessage() );
					}
				} );
```

when the message reply handler is called the ```handlerMap.get(msg.address());``` lookup in ```EventBusImpl.deliverMessageLocally``` is always null

This leads to ```deliverMessageLocally``` returning false and ```sendContext.handlerRegistration.sendAsyncResultFailure``` being invoked.

**Comment by wrightm** [comment]
@vietj any update on this issue? Is it a bug/feature or is my setup incorrect?

**Comment by vietj** [comment]
we'll have a look, thanks for popping this up!

**Comment by vietj** [comment]
@wrightm this is the normal behavior, to get a reply you need to have the receiver to explicitly reply.

in your case you need to modify `handleEventBusResponse` with:

```
	private void handleEventBusResponse( AsyncResult<Message<Object>> res, RoutingContext ctx ) {
		if ( res.succeeded() ) {
			ctx.response().end( res.result().body().toString() );
		} else {
			ctx.fail( res.cause() );
		}
		res.result().reply("ok");
	}
```
