### ISSUE TITLE
Does the latest vert.x mongo-auth support "SCRAM-SHA-1" or "MONGODB-CR" authentication?

### ISSUE THREAD

**Issue by fightchwang** [eclipse/vert.x#1942]
**In the latest version of vertx-auth-mongo, an MongoUser object could be something like this:**
{"_id":"admin.root","user":"root","db":"admin","credentials":{"SCRAM-SHA-1":{"iterationCount":10000,"salt":"+HmC/o5CWNZtJkMkIYdzcw==","storedKey":"nLfofTgM/THsB8raY7308ilMw+8=","serverKey":"HHQ2IgOcWQIKapoT+0KUDu8zbPM="}},"customData":{"user":"xxx"},"roles":[{"role":"root","db":"admin"}]}

While the method, **examinePassword** of class MongoAuthImpl, retrieves the encrypted password from a given key ,which assumes it were a String value mapped by that key, but a JsonObject actually.

So i wonder if it supports the  "SCRAM-SHA-1" or "MONGODB-CR" authentication?

It would be better if there’s some sample code~

Thx!

**Comment by vietj** [comment]
can you open this issue in the vertx-auth repository https://github.com/vert-x3/vertx-auth and close this one ?
