### ISSUE TITLE
Please add support $numberLong

### ISSUE THREAD

**Issue by leotu** [eclipse/vert.x#1943]
Ref: https://docs.mongodb.com/manual/reference/mongodb-extended-json/#numberlong

JsonObjectCodec.java  still not support "$numberLong", 
when document is
```json
{
  "_id" : "32034ffb-9ab8-4dce-bf95-591053bd53d4",
  "_seqCounter" : {
    "$numberLong" : "7279"
  },

}
```
That write to MongoDB, it throws java.lang.IllegalArgumentException: Invalid BSON field name $numberLong

But  if I change to
 ```json
{
  "_id" : "32034ffb-9ab8-4dce-bf95-591053bd53d4",
  "_seqCounter" :  7279

}
```
That would be stored as BsonType.INT32 not the BsonType.INT64 which my data is Long type !

Note: There is new type $numberDecimal (https://docs.mongodb.com/manual/core/shell-types/#numberdecimal)

**Comment by vietj** [comment]
can you open this issue in the https://github.com/vert-x3/vertx-mongo-client repository and close this one ?

**Comment by leotu** [comment]
Sure, my mistake !
