### ISSUE TITLE
HttpClient does not use HTTP proxy when client options ssl=true overridden by request options ssl=false

### ISSUE THREAD

**Issue by bennylut** [eclipse/vert.x#1944]
Hello, 
I am trying to use the http client in order to access several restful apis through my proxy.
Some of the api providers use https  and some http, therefore I configured the http client to use ssl.
When doing so, the proxy settings is completely ignored when attempting to connect to a non https api. 

The following is a simple reproducer:
```java
import io.vertx.core.Vertx;
import io.vertx.core.http.HttpClient;
import io.vertx.core.http.HttpClientOptions;
import io.vertx.core.http.HttpMethod;
import io.vertx.core.net.ProxyOptions;

public class Reproducor {
    public static void main(String[] args) {
        Vertx v = Vertx.vertx();
        HttpClient c = v.createHttpClient(new HttpClientOptions()
                .setProxyOptions(new ProxyOptions()
                        .setHost("aaaaa")
                        .setPort(5555))
                .setSsl(true));
        c.requestAbs(HttpMethod.GET, "http://ifconfig.co/ip", response -> {
            response.bodyHandler(body -> {
                String str = body.getString(0, body.length());
                System.out.println(str);
            });
        }).end();

    }
}
```

My expectations was that this reproducer will fail sending the request as the given proxy does not exists. Instead, it works and return my machine ip (which defeat the point of configuring a proxy on the http client)

If I am not configuring the http client with `isSsl = true` then all the requests to the https-apis are failing with "not an ssl/tls frame" related exceptions

Am I missing something?

**Comment by vietj** [comment]
it might be a bug due to the fact that you `setSsl(true)` on the options but are using _http_ in the scheme which confuses the client.

**Comment by bennylut** [comment]
Yes, please see my referenced fix ( pull request #1945 )
I think that the client-global setSsl settings is really problematic -  I really cannot see any situation where you should set the useSsl to false since setting it to true allows for both http and https requests (ignoring the bug of course)

IMHO, this setting should be deprecated and the decision to use ssl or not is should depend on the schema of the request or by the request options only (which is the way it is implemented when the useSsl is true anyway) - but this is only my opinion..

**Comment by vietj** [comment]
indeed it's a bug

**Comment by vietj** [comment]
about the decision, there is an option by default and it is used when you do request like `get(8080, "localhost", "/somepath")` so it is still necessary

**Comment by vietj** [comment]
as workaround now you should create 2 http clients, it should be fixed in 3.4.2 release

**Comment by bennylut** [comment]
I see, so maybe it should have been named: useSslByDefault :) 
or maybe adding a DefaultConnectionOptions class with the host,port and ssl configuration will be less confusing, for example: 

```java
vertx.createHttpClient().setDefaultConnection(DefaultConnectionOptions()
    .setHost("host").setPort(8080).useSsl(true))
```


In any case - thank you for your help and for the workaround

**Comment by vietj** [comment]
would you mind to test the patch just commited in Vert.x core ?

**Comment by bennylut** [comment]
sure, give me a couple of minutes

**Comment by bennylut** [comment]
with my tests It works fine now  - thanks!
