### ISSUE TITLE
How to capture http request in vertx?

### ISSUE THREAD

**Issue by C0de8ug** [eclipse/vert.x#1946]
A code like this not works
![image](https://cloud.githubusercontent.com/assets/9106804/25076246/8b410bc0-2351-11e7-9ba1-159701ee2ee4.png)

But this works.
![image](https://cloud.githubusercontent.com/assets/9106804/25076255/9acd0e5e-2351-11e7-9ad6-03e8a915ffe2.png)

Anyone can help me?
Thanks.

I am using fiddler to capture this traffic and my vertx version is 3.2.1

**Comment by bennylut** [comment]
vertx http client has a proxy settings on its own - did you try use those instead of setting the system properties?  something like: 

```java 
vertx.createHttpClient(new HttpClientOptions()
    .setProxyOptions(new ProxyOptions()
        .setPort(9999).setHost("localhost")))
```

**Comment by C0de8ug** [comment]
this works in 3.4.1 but not works for 3.2.1. thanks for you answer~
