### ISSUE TITLE
LocalMap support ttl?

### ISSUE THREAD

**Issue by abcfy2** [eclipse/vert.x#1948]
I find that [`AsyncMap`](http://vertx.io/docs/apidocs/io/vertx/core/shareddata/AsyncMap.html#put-K-V-long-io.vertx.core.Handler-) supports `TTL`, but `LocalMap` does not support.

Will `LocalMap` plan to support this feature as `AsyncMap`?

**Comment by vietj** [comment]
@abcfy2 this is not planned at the moment
