### ISSUE TITLE
Add tags to repository

### ISSUE THREAD

**Issue by mystdeim** [eclipse/vert.x#1949]
Please add tags to repository, for example: `distributed-systems`, `concurrency `, `high-performance `.
It makes project more popular )

**Comment by aesteve** [comment]
👍 + netty + reactive + jvm + rx + messaging + http/2

**Comment by vietj** [comment]
I've most, some like rx, it's more for the vert-x3/vertx-rx repo

**Comment by vietj** [comment]
same for messaging
