### ISSUE TITLE
Requesting ftp urls via http proxy works incorrect

### ISSUE THREAD

**Issue by TanyaGaleyev** [eclipse/vert.x#1956]
If one has setup `HttpClient` to use http proxy and tries to request FTP resource via it then proxy requests HTTP resource. So the code
```java
HttpClient client = vertx.createHttpClient(new HttpClientOptions().setProxyOptions(...));
client.getAbs("ftp://ftp.example.com/file");
```
sends following HTTP request to the proxy:
```
GET http://ftp.example.org/file HTTP/1.1
Host: ftp.example.org

```
But uri should be `ftp://ftp.example.org/file`.
From [code](https://github.com/eclipse/vert.x/blob/f1485903823cdf19315c5d0a1168448c9b2ecd18/src/main/java/io/vertx/core/http/impl/HttpClientImpl.java#L949) I can see that `http` scheme is hardcoded.

**Comment by vietj** [comment]
is there a use case for this ?

**Comment by TanyaGaleyev** [comment]
In our production environment we use Vert.x http client for downloading some files (actually software updates) from Internet. And there are some FTP downloads. When HTTP proxy is configured we are trying to download FTP resources via that proxy. Actually Squid proxy server supports downloading FTP resources quite well.

**Comment by vietj** [comment]
ok, we can add support for this in the proxy case.

have you tried the following:

`client.getNow(proxyHost, proxyPort, "ftp://host/uri", handler).setHost(host).end()` ?

**Comment by alexlehm** [comment]
I think we have not covered this use case yet, the client checks for http and https only

**Comment by vietj** [comment]
someone feels to contribute this ?

**Comment by alexlehm** [comment]
I can take a look

**Comment by TanyaGaleyev** [comment]
Actually we utilized Vert.x when plain HTTP proxying did not work with `ProxyOptions`. So we used to write some code checking whether destination URL is plain or TLS. Also we used to have different `HttpClient` instances for plain and TLS connections. Latter used `ProxyOptions`. Former did something like:
```java
client.get(proxyUri.getPort(), proxyUri.getHost(), uri.toASCIIString())
    .setHost(uri.getHost() + ":" + uri.getPort());
```
Plus additional code handling proxy authentication.
So it sounded as a good idea to get rid of that code and use `ProxyOptions` everywhere.

**Comment by vietj** [comment]
thanks for the feedback @TanyaGaleyev .

@alexlehm is actually contributing the support of non http urls for proxy support

**Comment by alexlehm** [comment]
I committed a first version https://github.com/alexlehm/vert.x/tree/issues/%231956-proxy-ftp

**Comment by alexlehm** [comment]
this would even work for gopher urls, but Java doesn't support that

**Comment by vietj** [comment]
- can we make it work for any protocol and not just ftp ?
- can we have a test with the current test proxy server for ftp case ?

**Comment by alexlehm** [comment]
There is a test for the test proxy checking the ftp url  https://github.com/alexlehm/vert.x/blob/issues/%231956-proxy-ftp/src/test/java/io/vertx/test/core/Http1xTest.java#L2793, this test works even though the proxy does not support ftp urls itself (with forceuri)

It will work for other protocols, there is no limitation of the protocol in the vert.x code, but it has to pass the validation of java.net.URL. I have to check the docs which urls are allowed for proxy

**Comment by alexlehm** [comment]
The java.net.URL class accepts the following protocol types:

file, ftp, http, https, jar, mailto, netdoc

(not really sure what the last one is, probably javadoc specific one)

of these only ftp, http and https make sense to be requested via proxy, which means that if we use the URL class for getAbsUri, these are all protocols we can handle

**Comment by vietj** [comment]
@TanyaGaleyev can you have a check, the fix has been merged in master

**Comment by TanyaGaleyev** [comment]
Hi @vietj,

I have checked it in our code with 3.4.2-SNAPSHOT. Now requesting FTP resources via HTTP proxy works as expected.

**Comment by vietj** [comment]
thanks
