### ISSUE TITLE
--redeploy ignores -D system prooperties

### ISSUE THREAD

**Issue by javadevmtl** [eclipse/vert.x#1960]
Using vertx 3.4.1 see my thread here: https://groups.google.com/forum/?fromgroups=#!topic/vertx/fjlsWFqMiJk

I looked around: https://github.com/eclipse/vert.x/blob/65a1050b0922de38329cdbe90c5ecd8094a93a04/src/main/java/io/vertx/core/impl/launcher/commands/RunCommand.java

If I understand it correctly...
If --redeploy then initializeRedeployment() which calls startAsBackgroundApplication

There's a check here

```
if (systemProperties != null) {
      args.addAll(systemProperties.stream().map(s -> "-D" + s).collect(Collectors.toList()));
    }
```

But It seems that the properties are null at this point...

Calling System.getProperties().list(System.out); in our own verticle the passed in -D properties are gone only the java one show up. Removing --redeploy everything works as expected.

**Comment by cescoffier** [comment]
It's because the redeploy use a forked process. To pass parameters to the application in redeploy mode, use `--java-opts="-conf=... -Dfoo-bar`

**Comment by javadevmtl** [comment]
Ok that works, maybe it can be mentioned in the redeployment docs?

**Comment by cescoffier** [comment]
You are absolutely right. I was pretty sure it was documented, about a closer look just broken my "dreams". Gonna open a PR immediately. Please keep this issue open as I'm going to use it to track progress.

**Comment by cescoffier** [comment]
@javadevmtl can you review https://github.com/eclipse/vert.x/pull/1961 and tell me if it gives enough details?

**Comment by javadevmtl** [comment]
Done.

**Comment by cescoffier** [comment]
Thanks @javadevmtl !

**Comment by javadevmtl** [comment]
Just curious. There's a main java process that receives the properties and then forks a process. Can those properties not be passed to it instead of using --java-opts?

**Comment by cescoffier** [comment]
> On 8 May 2017, at 15:16, javadevmtl <notifications@github.com> wrote:
> 
> Just curious. There's a main java process that receives the properties and then forks a process. Can those properties not be passed to it instead of using --java-opts?
> 
> 

It’s hard to find which properties need to be passed to the child process. However, system properties passed using -D (as command line parameter, so after the “run” command) should be propagated to the child process.  
For instance:

```
java -cp target/hello-1.0-SNAPSHOT.jar io.vertx.hello.MyLauncher run io.vertx.hello.HelloVerticle --redeploy="src/main/java/**/*" -DPROP="hello" --conf=conf.json ….
```

This command propagates the `conf` param and the `PROP` system property to the child process.

However, this won’t work:

java -DPROP=“hello” -cp target/hello-1.0-SNAPSHOT.jar io.vertx.hello.MyLauncher run io.vertx.hello.HelloVerticle --redeploy="src/main/java/**/*" -DPROP="hello" --conf=conf.json ….

**Comment by cescoffier** [comment]
Fixed in https://github.com/eclipse/vert.x/pull/1961
