### ISSUE TITLE
Add support for jackson-modules-java8

### ISSUE THREAD

**Issue by javadevmtl** [eclipse/vert.x#1962]
Hi, can support for these modules be added or at least the Date/Time one?

https://github.com/FasterXML/jackson-modules-java8

When using Json.decodeValue(someString, SomePojo.class) or someJsonObject.mapTo(SomePojo.class) and we have Java 8 Instant type we get an exception.

See here: https://groups.google.com/forum/?fromgroups#!searchin/vertx/Instant%7Csort:relevance/vertx/uKeiQLMOR3I/FZApiU37AwAJ

JsonObject has getInstant() but that does a direct mapping with return new Instant(someDateString);

Thanks

**Comment by pmlopes** [comment]
Related: https://github.com/eclipse/vert.x/pull/1274

**Comment by vietj** [comment]
you can register yourself these extensions if you need to
