### ISSUE TITLE
Fix the CompletionHandler in AsyncFileImpl#writeInternal

### ISSUE THREAD

**Issue by vietj** [eclipse/vert.x#1967]
```
      public void failed(Throwable exc, Object attachment) {
        if (exc instanceof Exception) {
          context.runOnContext((v) -> handler.handle(Future.succeededFuture()));
        } else {
          log.error("Error occurred", exc);
        }
      }
```

should be a failed future, a test should be added

**Comment by tsegismont** [comment]
Any idea for testing? Because changing permissions or deleting the file after it is opened won't result in an error. The permission check happens before getting the file file handle, not on every write. And when the file is deleted the system will not clean resources until the last handle is closed.

Do we have tests with bytecode transformation?

**Comment by vietj** [comment]
why do we need bytecode transformation ?

**Comment by vietj** [comment]
so you mean it's a case that never happens ? otherwise it can be tested

**Comment by vietj** [comment]
I can see in the javadoc:

```
     * @throws  NonWritableChannelException
     *          If this channel was not opened for writing
```

**Comment by vietj** [comment]
so I'm guessing that opening the file for reading and trying to write should produce the case

**Comment by vietj** [comment]
yes it seems hard to produce because the AsyncFileImpl check that the channel is not closed before writing (and closing the channel is one way to achieve it).

one possiblity is to allow internally to create an AsyncFileImpl using a Path and provide a Path with a FileSystem that will exhibit this behavior.

**Comment by tsegismont** [comment]
I'm not sure we need it, I just couldn't think of another way to test the
change.

2017-05-05 17:07 GMT+02:00 Julien Viet <notifications@github.com>:

**Comment by tsegismont** [comment]
No, it can happen. I tried to explain why the user can't see the error if
he deletes the file via command line after Vert.x opened it.

2017-05-05 17:08 GMT+02:00 Julien Viet <notifications@github.com>:

**Comment by tsegismont** [comment]
The NonWritableChannelException is thrown if when the method is called, not
in the listener.

2017-05-05 17:09 GMT+02:00 Julien Viet <notifications@github.com>:

**Comment by tsegismont** [comment]
That sounds like a good idea. I'll give it a try.

2017-05-05 17:47 GMT+02:00 Julien Viet <notifications@github.com>:
