### ISSUE TITLE
Faster json parsing

### ISSUE THREAD

**Issue by amannocci** [eclipse/vert.x#1975]
Motivation:
We can speed up json parsing provide in Buffer. 
In fact, Jackson is a bit more efficient when the parsing is based on byte[] or InputStream ([Jackson-Performance](https://github.com/FasterXML/jackson-docs/wiki/Presentation:-Jackson-Performance)).
In addition, this will reduce intermediate String allocation.
We can use the underlying netty ByteBuf to achieve this.

Modification:
We need to add a method in Json to be able to decodeValue from Buffer.
And then we can modify toJsonObject and toJsonArray implementation in Buffer.

Result:
Better performance for json parsing based on Buffer.

**Comment by elad-yosifon** [comment]
@amannocci  what about exposing a static parser or ctor for InputStream and Buffer in addition to String and Map<String,Object> ?

**Comment by amannocci** [comment]
I think that exposing a ctor for InputStream and Buffer in JsonObject and JsonArray can be useful.

**Comment by vietj** [comment]
I disagree for InputStream, InputStream are blocking so it's not something we encourage to use in the context of Vert.x

**Comment by vietj** [comment]
have you done actual benchmarking ?

**Comment by vietj** [comment]
Actually Buffer has `toJsonArray` and `toJsonObject`, we should avoid to add new method that do the same thing.

**Comment by amannocci** [comment]
I agree with you for InputStream, this can be a problem when the underlying implementation is blocking.
I prefer to replace existing `toJsonArray` and `toJsonObject` method in Buffer instead of creating new one.
I will try to do a jmh benchmark.
Actually I have only done a very simple benchmark to check the article.

**Comment by vietj** [comment]
:+1:

**Comment by amannocci** [comment]
I have done a little JMH to confirm performance improvement and I think we can safely switch to the new version.
```
# Run complete. Total time: 00:27:14

Benchmark                         Mode  Cnt       Score     Error  Units
JsonBenchmark.testNewJsonArray   thrpt  200   51411,287 ± 369,807  ops/s
JsonBenchmark.testNewJsonObject  thrpt  200  103836,793 ± 944,890  ops/s
JsonBenchmark.testOldJsonArray   thrpt  200   39609,818 ± 273,973  ops/s
JsonBenchmark.testOldJsonObject  thrpt  200   78209,119 ± 519,875  ops/s
```
I get a boost of **~30% for JsonObject** parsing from Buffer and **~27% for JsonArray** parsing from Buffer.

**Comment by vietj** [comment]
seems to worth it

**Comment by vietj** [comment]
it has been merged
