### ISSUE TITLE
Log4j2LogDelegateFactory and Log4jLogDelegateFactory

### ISSUE THREAD

**Issue by nimo23** [eclipse/vert.x#1981]
I want to use **log4j2** instead of JUL. 

According to

http://vertx.io/docs/apidocs/

I have to set (version 1)

`vertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4jLogDelegateFactory`

and according to 

http://vertx.io/docs/vertx-core/java/#_using_another_logging_framework

I have to set (version 2)

`vertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory`

which one should I take?

Please update the api-doc.

**Comment by tsegismont** [comment]
The two vertx.io/docs links point to the same section of doc which says:

We provide pre-built implementations for Log4J (version 1), Log4J 2 and
> SLF4J with the class names io.vertx.core.logging.Log4jLogDelegateFactory,
> io.vertx.core.logging.Log4j2LogDelegateFactory and
> io.vertx.core.logging.SLF4JLogDelegateFactory respectively.
>

Sounds pretty clear to me. As for the Javadoc, it's just missing the Log4J2
reference (it was added later than Log4J). Fancy a PR ?

2017-05-10 11:50 GMT+02:00 nimo23 <notifications@github.com>:

**Comment by nimo23** [comment]
Okay, yes it clear. Thx.
