### ISSUE TITLE
MessageCodec for CollectionTypes?

### ISSUE THREAD

**Issue by nimo23** [eclipse/vert.x#1983]
I have this:

```
public class UserCodec  implements MessageCodec<Set<User>, Set<User>> {
..
}
```

and want to use this codec:

`vertx.eventBus().registerDefaultCodec(HashSet.class, new UserCodec());`

However, I get this error:

`
The method registerDefaultCodec(Class<T>, MessageCodec<T,?>) in the type EventBus is not applicable for the arguments (Class<HashSet>, UserCodec)`

Are Collection-Types (Set/Map) not allowed?

**Comment by tsegismont** [comment]
No they aren't because at runtime it's not possible to determine the type objects stored in the collection. As a workaround, you can encapsulate your collection in a transfer oject (e.g. UserSet) and register a default codec for it.
