### ISSUE TITLE
Mapping between JSON objects and Java objects by Codec

### ISSUE THREAD

**Issue by nimo23** [eclipse/vert.x#1984]
According to docs we can map between json and java object by using Jackson’s ObjectMapper#convertValue():

```
request.bodyHandler(buff -> {
  JsonObject jsonObject = buff.toJsonObject();
  User javaObject = jsonObject.mapTo(User.class);
});
```

However, I have a "MessageCodec" for "User.class" so the conversion between json and object can be handled by "vertx" instead of "jackson" (faster?). I can not find a method where I can convert it explicitly by using this MessageCodec:

Actually I have do something like this:

```
UserCodec c = new UserCodec();
String json = c.encodeToWire(Buffer.buffer(), d);
User user =  c.decodeFromWire(0, Buffer.buffer());
```

Would be nice if vetx can provide something like this:

```

// use static method of my custom MessageCodec to get JsonObject
JsonObject jsonObject = UserCodec.toJson(User);

// use my custom MessageCodec for conversion
User javaObject = UserCodec.fromJson(json);
```

**Comment by vietj** [comment]
so you mean you want an event bus message codec that would use jackson to encode / decode payload to faciliate encoding of custom classes ?

**Comment by vietj** [comment]
Look at the io.vertx.core.json.Json class, it provides what you want:

```
JsonObject jsonObject = Json.encode(user);

User javaObject = Json.decodeValue(json, User.class);

```
