### ISSUE TITLE
HttpServer no-body responses with Transfer-Encoding: chunked

### ISSUE THREAD

**Issue by TanyaGaleyev** [eclipse/vert.x#1986]
When we are trying to respond to HEAD request using `HttpServer` and specify `Transfer-Encoding: chunked` then single zero chunk is written. While [RFC](https://tools.ietf.org/html/rfc7231#section-4.3.2) says:
> The HEAD method is identical to GET except that the server MUST NOT
send a message body in the response (i.e., the response terminates at
the end of the header section).  The server SHOULD send the same
header fields in response to a HEAD request as it would have sent if
the request had been a GET, except that the payload header fields
(Section 3.3) MAY be omitted.  This method can be used for obtaining
metadata about the selected representation without transferring the
representation data and is often used for testing hypertext links for
validity, accessibility, and recent modification.

I tried following:
```
request.response()
    .setChunked(true)
    .end();

HTTP/1.1 200 OK
Transfer-Encoding: chunked

0

```
And:
```
request.response()
    .putHeader("Transfer-Encoding", "chunked")
    .end();

HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Length: 0

0

```
Also I suppose `Transfer-Encoding: chunked` similarly can be applied to 304 (Not Modified) responses.

**Comment by vietj** [comment]
as you said, setting a chunked response with a 0 length should be respected imho

**Comment by TanyaGaleyev** [comment]
What we are actually developing is proxy based on Vert.x. And when we see chunked encoding in response from origin server to proxy then we set chunked encoding to response from proxy to client. As said in RFC a response without message body can contain `Transfer-Encoding: chunked`. So we have a problem when trying to declare chunked encoding for response with no message body.
```
 ________               _______               ________
|        |----HEAD---->|       |----HEAD---->|        |
| client |             | proxy |             | origin |
|________|<--chunked---|_______|<--chunked---|________|
```
Another possible case is implementation of HTTP server responding with `Transfer-Encoding: chunked` in to HEAD requests.

**Comment by TanyaGaleyev** [comment]
Also after experimenting a little bit more I found that Vert.x `HttpServer` always adds `Content-Length` or `Transfer-Encoding: chunked` to all responses. But in fact it should not be so. In mentioned earlier RFC excerpt stated that response to HEAD should contain same `Content-Length` as response to corresponding GET or `Content-Length` may be omitted. But with Vert.x `HttpServer` we have `Content-Length: 0`.
Do you need separate ticket for this?

**Comment by vietj** [comment]
can you provide a reproducer with all the cases you mention ? that will make it easier and more explicit

**Comment by TanyaGaleyev** [comment]
Yes I can. But not immediately. I hope I will do it in couple of days.

**Comment by vietj** [comment]
any news of this ?

**Comment by TanyaGaleyev** [comment]
I have created a [gist](https://gist.github.com/TanyaGaleyev/fe143077fc635cc9adf73e8b0779adf1) containing some tests with HEAD method desired behaviour.

**Comment by vietj** [comment]
I will have a look soon

**Comment by vietj** [comment]
I believe that the behavior that Vert.x should respect is that if there is a payload header field, then it should be assumed that the user code knows what it's doing and should not override these fields, so:

```
response.putHeader("Transfer-Encoding", "chunked").end();
```

or 

```
response.putHeader("Content-Length", "0").end();
```

should just send

```
HTTP/1.1 200 OK
Transfer-Encoding: chunked
```

or

```
HTTP/1.1 200 OK
Content-Length: 0
```

and nothing more

**Comment by vietj** [comment]
well hard to tell :-)

**Comment by vietj** [comment]
pehraps that HEAD should be handled differently on HttpServerResponse.

I'm wondering how the HttpClient behaves correctly as I don't see specific treatment for HEAD in HttpContentDecoder and receiving an Content-Length: 10 with no content would confuse the decoder

**Comment by vietj** [comment]
it seems fine on the client:

```
    server.close();
    NetServer server = vertx.createNetServer();
    server.connectHandler(req -> {
      req.write(
        "HTTP/1.1 200 OK\r\n" +
        "Content-Length: 10\r\n" +
        "\r\n"
      );
    });
    server.listen(DEFAULT_HTTP_PORT, DEFAULT_HTTP_HOST, onSuccess(v1 -> {
      client.headNow(DEFAULT_HTTP_PORT, DEFAULT_HTTP_HOST, DEFAULT_TEST_URI, resp -> {
        System.out.println("begin resp");
        resp.endHandler(v2 -> {
          System.out.println("end resp");
        });
      });
    }));
```

works

**Comment by vietj** [comment]
but not if I use "getNow" as the client will expect 10 bytes of data

**Comment by vietj** [comment]
can you check https://github.com/eclipse/vert.x/tree/handle-response-for-head-method ? it does not handle the case setting a chunked encoding (see https://github.com/netty/netty/issues/6761)

**Comment by TanyaGaleyev** [comment]
@vietj,

Sorry for delay. I made an experiment with vertx `HttpClient` issuing head requests. vertx `HttpServer` response contains single zero chunk. When I make two subsequent requests are able to complete fine. But I can see errors in log:
```
May 22, 2017 5:51:49 PM io.vertx.core.net.impl.ConnectionBase
SEVERE: java.lang.IllegalArgumentException: invalid version format: 0
May 22, 2017 5:51:49 PM io.vertx.core.net.impl.ConnectionBase
SEVERE: java.lang.IllegalArgumentException: invalid version format: 0
```

According to you commits. I suppose that response body should not be allowed also for responses with codes 1xx, 204, 205, 304. And also for all 2xx responses to CONNECT.
But I believe that the important thing here is to avoid zero chunk for that cases.

**Comment by vietj** [comment]
so what is left to be done ? wich cases ?

**Comment by TanyaGaleyev** [comment]
I have added some comments to source code https://github.com/eclipse/vert.x/commit/ca2e4473229d9562f716cc8e667593d61305fa0e.
At least there should be test checking that if response code is one of mentioned before then it has no message body even if `Transfer-Encoding: chunked` is set. In pseudo code it is something like:
```
response = GET http://localhost/chunked_not_modified
assertThat(response.content).isEmpty()
assertThat(response.headers.get("Transfer-Encoding")).isEqualTo("chunked")
assertThat(response.headers).doesNotContain("Content-Length")
----
response = GET http://localhost/not_modified_with_content_length_10
assertThat(response.content).isEmpty()
assertThat(response.headers.get("Content-Length")).isEqualTo("10")
assertThat(response.headers).doesNotContain("Transfer-Encoding")
----
response = GET http://localhost/not_modified
assertThat(response.content).isEmpty()
assertThat(response.headers).doesNotContain("Content-Length")
assertThat(response.headers).doesNotContain("Transfer-Encoding")
----
```
Also it is good to pay attention for CONNECT response with 200 status code. Having `Transfer-Encoding: chunked` sound strange for such response, but there must not be content body. Perhaps it is better to throw some runtime exception in cases when someone tries to use chunked encoding for CONNECT response.

**Comment by vietj** [comment]
@TanyaGaleyev by `assertThat(response.content).isEmpty()` do you mean that there is no chunk ? if yes I'm afraid it's impossible due to the Netty issue

**Comment by vietj** [comment]
I'm going to make a PR for the branch but keep this issue open until we can fully implement the content behavior. Netty has been modified to allow extensibility of the content empty behavior and this would be implemented in Vert.x when we use this version of Netty.

**Comment by vietj** [comment]
@TanyaGaleyev I've fixed the last part that was failing with a proper fix implemented via the netty change referenced in this issue that allows to not send response content when the request method is head. Can you check how it goes on your side ?

**Comment by TanyaGaleyev** [comment]
@vietj I tried it with my tests and everything went fine.
But I noticed that if `response.setChunked(true)` is called responding to HEAD then no `Transfer-Encoding: chunked` is written to response. But it can be done manually `response.putHeader("Transfer-Encoding", "chunked")`. I don't know if is somehow bad.
In conclusion, looks good for me and meets RFC. Thanks!
P.S. Unfortunately we do not have Vert.x server in production anymore and I will not get any results from fields about this fix.

**Comment by vietj** [comment]
@TanyaGaleyev both are possible, `setChunked` is used by the developer that wants to send a chunked response, and usually the `Transfer-Encoding` chunked header will be set by proxy applications that will pass the content from the proxied response and will send the chunks later. I think what is important is that if you set yourself the `Transfer-Encoding` chunked header, then the response is actually encoded as chunked on the wire.

**Comment by luengnat** [comment]
Is this something that should be addressed by Netty too?

**Comment by vietj** [comment]
I don't think so
