### ISSUE TITLE
Calling ServerWebSocket reject is documented to return a 404, but returns 502 instead

### ISSUE THREAD

**Issue by CraigStuntz** [eclipse/vert.x#1996]
`ServerWebSocket.reject()` is [documented](http://vertx.io/docs/apidocs/io/vertx/core/http/ServerWebSocket.html#reject--) to return a HTTP 404, but we observe that it returns a 502 instead, and [the source code](https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/HttpServerImpl.java#L829) indicates 502 as well: 

          if (!ws.isRejected()) {
            // ....
          } else {
            ch.writeAndFlush(new DefaultFullHttpResponse(HTTP_1_1, BAD_GATEWAY));
          }

404 seems better than 502 to me, but certainly the docs and code should agree, and I think ideally the `reject()` should provide an obvious means of setting the status code.

**Comment by vietj** [comment]
I think reject could be overriden to set the status code indeed, I'm tried to look at the source code which one was originally there (the 502 or 404) but could not get past enough in the history to find out.

**Comment by mithunsasidharan** [comment]
@vietj : Can I pick this up. I'm new to Vert.x and eager to contribute. Kindly advice.

**Comment by vietj** [comment]
@mithunsasidharan sure, your first mission is to determine which is the proper code that should be used :-)

**Comment by mithunsasidharan** [comment]
@vietj : I see that presently, if isRejected() is true, then we return

`ch.writeAndFlush(new DefaultFullHttpResponse(HTTP_1_1, BAD_GATEWAY));`

But HttpResponseStatus BAD_GATEWAY stands for 502 Bad Gateway. The right status to be used is NOT_FOUND to be able to return 404 as expected.

`ch.writeAndFlush(new DefaultFullHttpResponse(HTTP_1_1, NOT_FOUND));`

**Comment by vietj** [comment]
@mithunsasidharan we need a test for this in the WebsocketTest class

**Comment by CraigStuntz** [comment]
We should be able to specify the status code. I like the idea of adding an overload to `reject()`. Or a fluent method like [`setStatusCode`](http://vertx.io/docs/apidocs/io/vertx/core/http/HttpServerResponse.html#setStatusCode-int-) / `setStatusMessage`

**Comment by vietj** [comment]
overloaded reject method looks good to me.
