### ISSUE TITLE
HttpServerRequestImpl Reject unfriendly Request URL

### ISSUE THREAD

**Issue by qinpeng2** [eclipse/vert.x#1997]
When I call a url running on Vertx like: 
http://localhost:8080/test?p={PARAM1}

It will cause an exception and not work. I think it should be accept the invalid charactars like "{", "}"

Refer to Jersey, jersey servlet container handle this as:
uri = new URI(ContainerUtils.encodeUnsafeCharacters(req.uri()));

So back to vertx, I suppose the io.vertx.core.http.impl.HttpUtils should adapter the unexcepted charactars. 

My solution is:
HttpUtils.absoluteURI -> line#96
URI uri = new URI(req.uri());
changed to ->  URI uri = new URI(encodeUnsafeCharacters(req.uri())); 
for the compatibility

**Comment by vietj** [comment]
can you show your code and the reported error ?

I believe it's up to you to provide a correct URL

**Comment by qinpeng2** [comment]
This url 
http://localhost:8080/test?p={PARAM1}
is the requested url. And the response is 500, it has a NPE error in log.

Yes, the main issue is the charactar "{" and "}" make it happen. But I think we should consider the compatibility.

**Comment by vietj** [comment]
can you show the stack trace you are getting ?

**Comment by pmlopes** [comment]
It shouldn't throw a NPE but it shouldn't modify that url either. According to the RFC 1738 it states that "unsafe characters" should always be encoded. And the reason why is that systems might modify these characters. If we would do this then we deviate from the RFC and and will introduce ambiguity, what if the user really means that character and not it's url encoded value?

**Comment by pmlopes** [comment]
I've look at it and I don't get an NPE i get:

```
SEVERE: Failed to create abs uri
java.net.URISyntaxException: Illegal character in query at index 11: /foo/bar?p={val}
```

but the request does not crash, the absolute path will just be null, so I believe that who ever is looking at the absolute path later will be suffering from it's null value.

**Comment by qinpeng2** [comment]
Yes, correct! It'll return a NULL from this method HttpServerRequestImpl.absoluteURI.

@pmlopes please check my solution in the first comment. 

_HttpUtils.absoluteURI -> line#96
URI uri = new URI(req.uri());
changed to -> URI uri = new URI(encodeUnsafeCharacters(req.uri()));_

**Comment by qinpeng2** [comment]
When I looking into the source code of Jersey. Jersey do the compatibility very well in their ServletContainer implementation. 
So I suppose we should also make it pass through with encoding the unsafe characters.

**Comment by vietj** [comment]
but with vert.x core encoding, would send "{PARAM1}" to the remote server, so I don't see the point. It would rather be something useful in Vert.x WebClient.

**Comment by pmlopes** [comment]
@qinpeng2 unless you show it with a reproducer, the NPE does not happen on vert.x core. And your "solution" is against what the RFC mandates, in that case and without a real good justification, I advice not to go that way.

@vietj yes in client it makes sense and it should be done as it is said on the RFC on the server side it doesn't.
