### ISSUE TITLE
timeout wrapper for Future

### ISSUE THREAD

**Issue by ruslansennov** [eclipse/vert.x#2001]
I often use this method to limit `future` execution time.

```java
public static <T> Future<T> withTimeOut(Vertx vertx, long millis, 
                               Future<T> future, Supplier<Future<T>> onTimeOut) {
        Future<Void> timeout = Future.future();
        vertx.setTimer(millis, l -> timeout.complete());
        return CompositeFuture.any(future, timeout).compose(cf -> {
            if (cf.succeeded(0)) {
                return Future.succeededFuture(cf.resultAt(0));
            } else {
                return onTimeOut.get();
            }
        });
}
```

Does it make sense to add something like this in `Future` interface?

```java
interface Future<T> {
    // ...
        
    Future<T> withTimeout(Vertx vertx, long millis, Supplier<Future<T>> onTimeOut);

    // ...
}
```

**Comment by InfoSec812** [comment]
Just my opinion, but the `setTimer` example could be simplified enough that the proposed API change wouldn't be necessary. For Example:

```
Future<MyResult> future = Future.future();
vertx.setTimer(millis, l -> future.fail(new TimeoutException));
vertx.eventBus().send(destAddr, message, future.completer());
```

It's 1 additional line of code to add a timeout on a future, so I'm not sure it's worth the overhead and long term maintenance to add a new feature to the API.

**Comment by ruslansennov** [comment]
@InfoSec812 but the main process (which we are waiting for) may call `fiture.complete` or `fiture.fail` after timeout. I believe that this will lead to exception.

**Comment by ruslansennov** [comment]
too ugly :)
