### ISSUE TITLE
provide "putHeader" for HttpClientOptions and RequestOptions

### ISSUE THREAD

**Issue by nimo23** [eclipse/vert.x#2005]
With "HttpClientOptions" we can set for example "setKeepAlive" or "setTryUseCompression" which results in putting appropriate headers for all requests . Would be nice to provide a  "putHeader"-Method to put common headers for all requests. 

For example, I want to set this:

`RequestOptions reqOpt = new RequestOptions().setHeader("Connection", "keep-alive").setHeader("Accept-Encoding", "gzip, deflate").setHeader("DNT", "1");`

or this:

```
HttpClientOptions options = new HttpClientOptions()
				.setKeepAlive(true)
.setHeader("Accept-Encoding", "gzip, deflate").setHeader("DNT", "1");
```

With this I can reuse my headers for different requests.

Both, "HttpClientOptions" and "RequestOptions" has no "putHeader"-Method. So I am forced to write my headers within each "HttpClientRequest" which can not be reused.

**Comment by tsegismont** [comment]
The Vert.x Web Client has been created to solve that kind of issues
http://vertx.io/docs/vertx-web-client/java/

Have you tried it?

2017-06-02 11:38 GMT+02:00 nimo23 <notifications@github.com>:

**Comment by nimo23** [comment]
Yes, I am using it. However, I dont know why not putting the "good parts" of web-client within vertx. vertx-web duplicates a few methods which are also found in vertx-web.

**Comment by vietj** [comment]
@nimo23 options are not meant to configure http headers, as Thomas said we recommend to use the web client as we want to focus usability efforts here and avoid duplicates.
