### ISSUE TITLE
Expose AsyncMap keys, values and entries

### ISSUE THREAD

**Issue by tsegismont** [eclipse/vert.x#2020]
Currently, AsyncMap lets you get/put/remove/replace entries asynchronously.

In some cases, you also need the ability to get the keys, values or entries (see @cescoffier 's comment in https://github.com/vert-x3/vertx-infinispan/issues/35#issuecomment-308135648)

**Comment by tsegismont** [comment]
I started a PR #2021. It's not ready yet but I wanted to share to gather feedback.

In this first attempt there are six new methods in the `AsyncMap` API

```java
  /**
   * Get the keys of the map, asynchronously.
   *
   * Use this method with care as the map may contain a huge number of entries.
   * In such cases, the invocation will much likely result in {@link OutOfMemoryError}.
   *
   * When in doubt, prefer usage of {@link #keyStream()}.
   *
   * @param resultHandler invoked when the operation completes
   */
  void keySet(Handler<AsyncResult<Set<K>>> resultHandler);

  /**
   * Get the values of the map, asynchronously.
   *
   * Use this method with care as the map may contain a huge number of entries.
   * In such cases, the invocation will much likely result in {@link OutOfMemoryError}.
   *
   * When in doubt, prefer usage of {@link #valueStream()}.
   *
   * @param resultHandler invoked when the operation completes
   */
  void values(Handler<AsyncResult<Collection<V>>> resultHandler);

  /**
   * Get the entries of the map, asynchronously.
   *
   * Use this method with care as the map may contain a huge number of entries.
   * In such cases, the invocation will much likely result in {@link OutOfMemoryError}.
   *
   * When in doubt, prefer usage of {@link #entryStream()}.
   *
   * @param resultHandler invoked when the operation completes
   */
  void entrySet(Handler<AsyncResult<Set<Entry<K, V>>>> resultHandler);

  /**
   * Get the keys of the map as a {@link ReadStream}.
   *
   * @return a stream of map keys
   */
  ReadStream<K> keyStream();


  /**
   * Get the values of the map as a {@link ReadStream}.
   *
   * @return a stream of map values
   */
  ReadStream<V> valueStream();


  /**
   * Get the entries of the map as a {@link ReadStream}.
   *
   * @return a stream of map entries
   */
  ReadStream<Entry<K, V>> entryStream();
```

The Javadoc should be pretty clear, in some cases the user knows that the number of entries is _small_ and wants all entries, keys or values at once. Otherwise he should get those as a `ReadStream`.

Note that the build fails for now because `codegen` doesn't allow parameterized types for method params like `Handler<AsyncResult<Set<K>>>`. I will update `codegen` or update the current proposal.

**Comment by Jotschi** [comment]
@tsegismont Will this change make it to 3.5.0? I just encountered the situation that I need to iterate over the keys of the map.

**Comment by vietj** [comment]
@Jotschi yes it's expected for 3.5

**Comment by vietj** [comment]
I think first @tsegismont wanted to solve codegen missing feature for this PR

**Comment by Jotschi** [comment]
@vietj Okay. Makes sense. Maybe https://github.com/eclipse/vert.x/pull/2021/commits/24e756a35e8725b3ca5dc8c2193828f636f719d0 already included that change? Lets just wait for his feedback.

**Comment by Jotschi** [comment]
@tsegismont I went ahead and implemented the AsyncMap changes in vertx-hazelcast since I need it for my implementation. Let me know whether I should open a PR for this. 
https://github.com/Jotschi/vertx-hazelcast/commit/f494e31e204316bfcbcd1a382ffab9f2cad15ab9
I also did a fix for the test testEntrySet in vert.x in order to get all tests to pass.

**Comment by tsegismont** [comment]
@Jotschi Thanks for the feedback. It seems this is a real gap in the API.

Please take a look at the vertx-dev thread https://groups.google.com/d/msg/vertx-dev/sgrrIGBoJTM/r3ube8DYAAAJ

I sent changes for codegen and tomorrow I'll start implementing the cluster managers (not only Hazelcast!) changes.

**Comment by tsegismont** [comment]
Just rebased the PR on master and marked new methods with `List<T>` or  `Set<T>` returns with `@GenIgnore`. The codegen change is not finished and I would like this to go in 3.5. We can revisit in 3.5.1.

**Comment by tsegismont** [comment]
@vietj all cluster managers (except JGroups) have been updated
