### ISSUE TITLE
DNS query fails for CNAME results

### ISSUE THREAD

**Issue by FroMage** [eclipse/vert.x#2028]
Using the vertx http client with:

```
HttpClientOptions options = new HttpClientOptions();
options.setSsl(true);
options.setTrustAll(true);
options.setVerifyHost(false);
HttpClient client = vertx.createHttpClient(options);
client.getNow(443,
  "raw.githubusercontent.com", 
  "/vert-x3/vertx-examples/master/resteasy-examples/src/main/java/io/vertx/examples/resteasy/asyncresponse/Controller.java", 
  resp -> {
    System.err.println("Got response");
  });
```

Fails with:

```
io.vertx.core.http.impl.HttpClientRequestImpl
SEVERE: java.net.UnknownHostException: failed to resolve 'raw.githubusercontent.com'. Exceeded max queries per resolve 100 
```

Debugging shows that the netty DNS resolver will simply loop on CNAME records because it will try to resolve the original `hostname` rather than the `cname` at https://github.com/netty/netty/blob/netty-4.1.8.Final/resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolverContext.java#L514

**Comment by tsegismont** [comment]
Could be fixed by
https://github.com/netty/netty/commit/ead87b7df8d923417475ead2d7680747b1a72f07

2017-06-21 14:44 GMT+02:00 Stéphane Épardaud <notifications@github.com>:

**Comment by alexlehm** [comment]
@tsegismont this commit was made before netty 4.1.8, so its in the version currently used in vert.x 3.4.2

@FroMage I tried your example and it works for me, I guess the issue happens when some additional condition is present in the dns server, maybe with the order of replies or with something in /etc/resolv.conf

**Comment by FroMage** [comment]
This is on Ubuntu which has a local resolver. Perhaps this one: http://news.softpedia.com/news/ubuntu-16-10-yakkety-yak-switches-to-a-universal-local-dns-resolver-service-504770.shtml

**Comment by alexlehm** [comment]
Works for me when I try ubuntu 16.10 or 17.04

Switching to Netty 4.1.12 requires some changes due to changes in unstable apis which vertx uses
