### ISSUE TITLE
Include netty dns resolution fix into the vertx build

### ISSUE THREAD

**Issue by jacek-** [eclipse/vert.x#2031]
As asked by @vietj, I'm starting the issue to track inclusion of netty dns resolution fix into the vertx build.
Details at the end of #1525 and also here: https://github.com/netty/netty/issues/6844 and https://github.com/netty/netty/pull/6885.

**Comment by jan-zajic** [comment]
It seems like vertx 3.5.0 will use netty 4.1.15, see https://github.com/vert-x3/vertx-dependencies/blob/master/pom.xml

**Comment by vietj** [comment]
it would be good to check this to see how it goes, I'm not sure we have an integration test for this

**Comment by rmtmckenzie** [comment]
FYI, I'm using vert.x 3.5.0 and still running into the issue on a GKE cluster. The workaround still works but it was annoying to diagnose.

**Comment by vietj** [comment]
@rmtmckenzie do you know if that's the a netty issue or provide more context about it ?

**Comment by rmtmckenzie** [comment]
Hi @vietj - thanks for the response. It appears to be the same netty issue previously reported to them - it isn't able to resolve a DNS name with the error "failed to resolve '...' after 3 queries", although it was reporting it was looking up the dns + google.internal  (i.e. facebook.com.google.internal). Switching to the java dns resolver solves the issue for now.

The resolv.conf in the container looks like this:

    fonts/ fstab
    nf 
    nameserver <ip address of ns>
    search <namespace>.svc.cluster.local svc.cluster.local cluster.local c.<gc network>.internal google.internal
    options ndots:5

I can report it directly to netty, but I don't have time atm to make a sample to test if the issue still appears with just plain netty...

**Comment by ieugen** [comment]
I'm on vertx 3.5.0 and we still get DNS failed inside kubernetes cluster. nslookup works fine we will see what we can do.

**Comment by jakeswenson** [comment]
@vietj Is there a reason this was closed?? We're still getting this in `3.5.0` on a kubes cluster.
netty version `4.1.15.Final`

**Comment by vietj** [comment]
@jakeswenson it is closed as invalid because it is a netty issue and it shall be fixed in 3.5.1 release, can you give a try with 3.5.1-SNAPSHOT ?

**Comment by vietj** [comment]
I'm removing the invalid tag (which is dubious) and set 3.5.1 as fix version

**Comment by pacman123** [comment]
@vietj Netty is not updated to 4.1.5  in vertx 3.5.1 (https://mvnrepository.com/artifact/io.vertx/vertx-core/3.5.1 ). We could we expect this update?

**Comment by vietj** [comment]
netty is 4.1.19.Final in 3.5.1
