### ISSUE TITLE
FileSystem methods do not accept options

### ISSUE THREAD

**Issue by DieterDePaepe** [eclipse/vert.x#2032]
I want to place an uploaded file at a certain location, replacing any file that may be present there.

Unfortunately, `FileSystem::copy` only accepts a `from`, `to` and `handler`, it does not allow me to pass Java's `CopyOptions`. This means I have to perform 3 asynch calls (check existence, remove and copy) rather than a single one for my use case.

Suggestion: add a way to specify additional file system options, or provide a `replace` and `deleteIfExists` method.

**Comment by tsegismont** [comment]
As a workaround to the 3 async calls, you can wrap
java.nio.file.Files#copy(java.nio.file.Path, java.nio.file.Path,
java.nio.file.CopyOption...) with executeBlocking
