### ISSUE TITLE
TrustOptions\PemTrustOptions does not provide an equals() method

### ISSUE THREAD

**Issue by andre2i** [eclipse/vert.x#2038]
Hello,
when validating equality of two instances of `HttpServerOptions`, if `PemTrustOptions` with the same values are added to both instances, the assert fails in `/io/vertx/core/net/TCPSSLOptions.java` at 
```
    if (trustOptions != null ? !trustOptions.equals(that.trustOptions) : that.trustOptions != null) return false;
```
regardless of the fact that both instances are configured with the same certificate paths.

**Comment by vietj** [comment]
yes indeed it's a bug, perhaps you can contribute a small fix with a test ?
