### ISSUE TITLE
question about DNS AddressResolver

### ISSUE THREAD

**Issue by ShakespeareLiu** [eclipse/vert.x#2039]
In the class io.vertx.core.impl.AddressResolver of version 3.3.3，If I don't set the dnServers in AddressResolverOptions, it will invoke the DnsServerAddresses.defaultAddresses() of netty to get dnsserver 
 of system. In  the class DnsServerAddresses, after fist time it got dnsservers from sun.net, it will not change dnsserver any more during runtime, because it's final: private static final DnsServerAddresses DEFAULT_NAME_SERVERS.
So if  I change the dnsserver in /etc/resolv.conf (linux) during runtime, the vert.x will not change dnsserver in it's cache, so what do you guys consider about this design, for Asynchronous ？for performance?

**Comment by vietj** [comment]
rather because it's convenient to read the value once and cache it for use, I guess it could be refreshed or invalidated.

**Comment by ShakespeareLiu** [comment]
I add a log in io.netty.resolver.dns.DnsNameResolverContext(Netty 4.1.5final),  found the nameServerAddr cann't be refreshed:
line 162     private void query(InetSocketAddress nameServerAddr, final DnsQuestion question, final Promise<T> promise) {
    	System.out.println("!!!!!!!!!!nameServerAddrs!!!!!!!!!" + nameServerAddrs.toString());
        if (allowedQueries == 0 || promise.isCancelled()) {
            tryToFinishResolve(promise);
            return;
        }
