### ISSUE TITLE
MIT licensed code

### ISSUE THREAD

**Issue by jpopelka** [eclipse/vert.x#2043]
Hi,

shouldn't the `<licenses>` section in [pom.xml](https://github.com/eclipse/vert.x/blob/master/pom.xml) contain also `MIT license` since there's a MIT licensed code in [io/vertx/core/http/impl/cgbystrom/](https://github.com/eclipse/vert.x/tree/master/src/main/java/io/vertx/core/http/impl/cgbystrom) ?

**Comment by vietj** [comment]
@jponge what's your opinion ?

**Comment by jponge** [comment]
The `licenses` section covers the _project_ license, not those of 3rd-party code.

That package contains code from a 3rd party and integrated into the Vert.x source code.
Proper credit is being given to the creator(s), and the license on these files have been retained.

The MIT license is permissive and doesn't have any provision that requires further publicity, and it doesn't conflict with the fact that the larger project is ASL+EPL licensed.

BTW adding the MIT license to our POM would mean _"Vert.x is also licensed under the terms of the MIT license"_, which is clearly not the case.

So clearly, that's a no.

**Comment by vietj** [comment]
thanks for clarifying
