### ISSUE TITLE
overriding clusterHost and clusterPort on start

### ISSUE THREAD

**Issue by zyclonite** [eclipse/vert.x#2051]
I've a Launcher class which extends io.vertx.core.Launcher that changes the vertx options in beforeStartingVertx(VertxOptions) method including setClusterHost and setClusterPort.

what happens: these settings are ignored and it falls back the host with getDefaultAddress() from BareCommand.java (https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/impl/launcher/commands/BareCommand.java#L154)
in our cause this is always resulting in choosing the wrong interface

would be nice if it would take the host and port from the options if set before handling null and falling back to the "default address"

**Comment by tsegismont** [comment]
Would you like to contribute a fix ?

2017-07-14 17:47 GMT+02:00 Lukas Prettenthaler <notifications@github.com>:

**Comment by zyclonite** [comment]
here you go https://github.com/eclipse/vert.x/pull/2062

**Comment by vietj** [comment]
fixed
