### ISSUE TITLE
Let users connect with absolute websocket urls

### ISSUE THREAD

**Issue by tsegismont** [eclipse/vert.x#2063]
As a matter of usability, the `HttpClient` should let users connect with absolute websocket urls (`ws://` or `wss://`)

**Comment by vietj** [comment]
you mean add `websocketAbs` method ?

**Comment by tsegismont** [comment]
Yes, did I miss them?

2017-07-20 10:36 GMT+02:00 Julien Viet <notifications@github.com>:

**Comment by vietj** [comment]
no, but it wasn't explicitly said :-)

**Comment by tsegismont** [comment]
Please do not merge yet. I have a prepared a branch to tame the number of websocket client permutations. I will send a mail to vertx-dev to discuss the proposal.
