### ISSUE TITLE
Vert.x ReadStream hangs in paused if WriteStream fails

### ISSUE THREAD

**Issue by CarstenLeue** [eclipse/vert.x#2065]
I have the following usecase for a vert.x aplication:

 - write a REST handler for a GET request
 - in this handler copy data from a ReadStream onto the response

This looked straight forward, in the handler I would create the ReadStream and then use a Pump to pipe the stream onto the response (WriteStream).

I noticed however that it can happen that the client closes the HTTP connection to my handler while the pump is still active. In this situation I had expected an exception on the WriteStream instance to occurs. However this is not the case, instead the WriteStream#writeQueueFull method returns "true" which sets the ReadStream into paused mode. It now waits for a drain event, but this event is never sent, because the write connection has been closed. The result is that over time the number of open (paused) ReadStreams grows, eventually generating a leak.

What is the correct way to handle this situation?
The first aspect that looks strange is that there is no exception on the write stream. But even if I were able to figure out the error situation (e.g. by listening on the close event on the response), what am I supposed to do with the ReadStream? It cannot be canceled but it also cannot stay open. The approach I can think of is to pump its content into a nil stream (i.e. consume it but ignore its content).
Overall this makes the complete pumping process pretty complicated. 

The example below shows a simple testcase to reproduce the issue. The main method makes a request against a verticle and closed the connection immediately.
On the server (i.e. in the verticle) no exception is triggered, instead the ReadStream is locked in paused state.

The output of the sample code is:

    request
    false
    starting to pipe ... false
    response closed: false
    writeQueueFull false
    closed ...
    writeQueueFull true
    pause: 1
    response is closed
 
Any suggestions are highly appreciated.

    package com.ibm.wps.test.vertx;

    import java.io.File;
    import java.io.InputStream;
    import java.net.HttpURLConnection;
    import java.net.URL;
    import java.util.concurrent.CompletableFuture;

    import io.vertx.core.AbstractVerticle;
    import io.vertx.core.Future;
    import io.vertx.core.Handler;
    import io.vertx.core.Vertx;
    import io.vertx.core.buffer.Buffer;
    import io.vertx.core.file.AsyncFile;
    import io.vertx.core.file.OpenOptions;
    import io.vertx.core.http.HttpServer;
    import io.vertx.core.http.HttpServerResponse;
    import io.vertx.core.streams.Pump;
    import io.vertx.core.streams.ReadStream;
    import io.vertx.core.streams.WriteStream;

    public class CancellationTest {

	private static final class ReadStreamProxy implements ReadStream<Buffer> {

		private int countPause;

		private final ReadStream<Buffer> delegate;

		private ReadStreamProxy(final ReadStream<Buffer> aDelegate) {
			delegate = aDelegate;
		}

		@Override
		public ReadStream<Buffer> endHandler(final Handler<Void> endHandler) {
			delegate.endHandler(endHandler);
			return this;
		}

		@Override
		public ReadStream<Buffer> exceptionHandler(final Handler<Throwable> handler) {
			delegate.exceptionHandler(handler);
			return this;
		}

		@Override
		public ReadStream<Buffer> handler(final Handler<Buffer> handler) {
			delegate.handler(handler);
			return this;
		}

		@Override
		public ReadStream<Buffer> pause() {
			countPause++;
			delegate.pause();
			System.out.println("pause: " + countPause);
			return this;
		}

		@Override
		public ReadStream<Buffer> resume() {
			countPause--;
			delegate.resume();
			System.out.println("resume: " + countPause);
			return this;
		}

	}

	private static final class TestVerticle extends AbstractVerticle {

		private HttpServer server;

		@Override
		public void start(final Future<Void> startFuture) throws Exception {

			final String data = new File(CancellationTest.class.getResource("data.txt").toURI()).getCanonicalPath();
			System.out.println("data " + data);

			server = vertx.createHttpServer();
			server.requestHandler(req -> {
				System.out.println("request");

				final HttpServerResponse resp = req.response();
				System.out.println(resp.closed());
				resp.exceptionHandler(th -> {
					System.out.println("exception from response " + th);
				});
				resp.closeHandler(v -> {
					System.out.println("response is closed");
				});
				resp.setChunked(true);

				vertx.setTimer(100, l -> {
					System.out.println("starting to pipe ... " + resp.closed());

					final OpenOptions opts = new OpenOptions();
					opts.setWrite(false);
					opts.setRead(true);
					vertx.fileSystem().open(data.toString(), opts, fileRes -> {
						final AsyncFile file = fileRes.result();
						file.exceptionHandler(ex -> {
							System.out.println("file exception " + ex);
						});
						file.endHandler(v -> {
							System.out.println("file ended");
						});
						
						System.out.println("response closed: " + resp.closed());

						pipe(file, resp);
					});
				});
			});

			server.listen(8080, result -> {
				if (result.failed()) {
					startFuture.fail(result.cause());
				} else {
					startFuture.complete();
				}
			});
		}
	}

	private static final class WriteStreamProxy implements WriteStream<Buffer> {

		private final WriteStream<Buffer> delegate;

		private WriteStreamProxy(final WriteStream<Buffer> aDelegate) {
			delegate = aDelegate;
		}

		@Override
		public WriteStream<Buffer> drainHandler(final Handler<Void> handler) {
			delegate.drainHandler(handler);
			return this;
		}

		@Override
		public void end() {
			delegate.end();
		}

		@Override
		public WriteStream<Buffer> exceptionHandler(final Handler<Throwable> handler) {
			delegate.exceptionHandler(handler);
			return this;
		}

		@Override
		public WriteStream<Buffer> setWriteQueueMaxSize(final int maxSize) {
			delegate.setWriteQueueMaxSize(maxSize);
			return this;
		}

		@Override
		public WriteStream<Buffer> write(final Buffer data) {
			delegate.write(data);
			return this;
		}

		@Override
		public boolean writeQueueFull() {
			final boolean result = delegate.writeQueueFull();
			System.out.println("writeQueueFull " + result);
			return result;
		}

	}

	public static void main(final String[] args) throws Exception {
		
		System.out.println(System.getProperties());

		final CompletableFuture<Void> sync = new CompletableFuture<Void>();

		final Vertx vertx = Vertx.vertx();
		vertx.deployVerticle(new TestVerticle(), result -> {
			try {
				final URL url = new URL("http://localhost:8080/");
				final HttpURLConnection conn = (HttpURLConnection) url.openConnection();
				conn.connect();
				final InputStream is = conn.getInputStream();
				is.close();
				conn.disconnect();
				System.out.println("closed ...");
				sync.complete(null);
			} catch (final Throwable th) {
				sync.completeExceptionally(th);
			}
		});

		sync.get();
		vertx.close();
	}

	private static final void pipe(final ReadStream<Buffer> aRead, final WriteStream<Buffer> aWrite) {
		
		aWrite.exceptionHandler(ex -> {
			new Exception().printStackTrace();
			System.out.println("write stream exception " + ex);
		});

		
		Pump.pump(new ReadStreamProxy(aRead), new WriteStreamProxy(aWrite)).start();
	}

}
```

**Comment by vietj** [comment]
hi, you should set a closeHandler on the HttpServerResponse and handle it like an HttpServerRequest exceptionHandler event.

we merged this change today that is related to this case : https://github.com/eclipse/vert.x/pull/2064

**Comment by CarstenLeue** [comment]
What would I do with the ReadStream in paused mode to prevent these instances from leaking?

**Comment by vietj** [comment]
actually sorry I misunderstood the issue, it's the other way around File -> Http . This works actually the same you should do the cleanup on close event and as you said the writeStream exception handler should report an exception as well.

**Comment by vietj** [comment]
So you should just close the file I think to release the resource.

**Comment by CarstenLeue** [comment]
The solution you are proposing depends on the nature of the ReadStream. Indeed in my example it's a file based stream, but I was just using this for illustration purposes.
The actual problem I am facing is production uses the response of another (server side) HTTP request as the ReadStream (actually io.vertx.core.http.HttpClientResponse). I have not found a way to close that stream.
In general it would be nice to have a solution that does not depend on the nature of the streams, in the end that's what these ReadStream and WriteStream abstractions seem to be for.

**Comment by vietj** [comment]
@CarstenLeue I agree with you, all stream should properly report errors and properly terminating the pump should be achieved. Probably we can improve the Pump to handle errors and stop pumping when error handlers or end event happen.

can you list the stream combination your are using and have error with ? and so we move forward on this item ?

**Comment by CarstenLeue** [comment]
ReadStream is io.vertx.core.http.HttpClientResponse and WriteStream is io.vertx.core.http.HttpServerResponse.

In my current solution I attached a closeHandler to the HttpServerResponse. Using an extra variable I keep track if streaming is going on and what streams are involved. In case the handler is called, while streaming is going on, I set a new data handler on the read stream that ignores all data and actively resume it. So its content will be exhausted and the implementation won't leak.

I find this a very complex solution given a relatively straight forward usecase.
One aspect that stroke me was that the io.vertx.core.streams.WriteStream.writeQueueFull() implementation of HttpServerResponse returns true in case the server response had been closed. This causes the read stream to enter paused mode. 
Does this make sense? Should the write queue really considered full in this case?

**Comment by vietj** [comment]
@CarstenLeue I believe that the response should report an error on the exceptionHandler when the stream closes before the end and the pump should manage to stop itself at this moment, so we should look first in this direction and then see

**Comment by CarstenLeue** [comment]
@vietj That would be awesome. Is your idea to extend the ReadStream interface to make the stream cancelable, so the pump would be able to do so in case of an error?

**Comment by vietj** [comment]
@CarstenLeue I believe that each resource has its own mechanism for cancelation / disposal, so at least there would be an handler to allow user code to perform cleanup

**Comment by oli-h** [comment]
Resurrect this issue: We work on project Gateleen and got the same issue when using Pump to connect A HttpServerRequest/Response with a HttpClient (i.e. be a http proxy).
We narrowed down the problem to a situation when the 'front' http request is closed by the client (i.e. XmlHttpRequest.abort() in a WebBrowser). Then the Pump pauses the readStream (from 'backend' http response) and never resumes it as the drainHandler of the (closed) http-front-response is closed.

**Comment by vietj** [comment]
you should set an exception handler on the WriteStream to unset the pump when it happens.

**Comment by vietj** [comment]
overall I believe that this case is so common that this project https://github.com/vietj/vertx-http-proxy should be somehow part of the stack to help writing gateways and proxies like servers.

**Comment by oli-h** [comment]
writeStream.exceptionHandler is not invoked. I tried all 'close' and 'exception' handlers I found on request, response and also on the underlying connection. None of them is being called - so they do not help resuming the backend readStream

**Comment by vietj** [comment]
so the HttpServerResponse#exceptionHandler is not called when the server request is closed ?

**Comment by oli-h** [comment]
Exact. Und the hood (somewhere in Netty's / NIO's channel objects) we see "isWriteable()" simply answers false - this is called by Vertx internally in HttpServerResponseImpl#writeQueueFull.
But the channel says "writeable=false" in two cases: 1) if the highWaterMark is reached but also 2) if the channel is closed.
Vertx's "writeQueueFull" cannot distinguish both cases - and pauses the readStream in the Pump (but in case 2) the drainHandler will not be invoked).
And - as I obsered, no closeHandler and no exceptionHandler is called. But I'm to far away from Netty/NIO channels to understand everything. But hopefully this explanation still helps

**Comment by vietj** [comment]
can you provide a reproducer for this case ?

**Comment by vietj** [comment]
I've run this test:

```
  @Test
  public void testServerResponseExceptionHandlerCalledWhenFull() throws Exception {
    CompletableFuture<Void> full = new CompletableFuture<>();
    server.requestHandler(req -> {
      HttpServerResponse resp = req.response();
      AtomicInteger errs = new AtomicInteger();
      resp.exceptionHandler(err -> errs.incrementAndGet());
      resp.setChunked(true);
      req.response().exceptionHandler(err -> {
        System.out.println("CLOSED! " + err.getMessage());
      });
      vertx.setPeriodic(1, id -> {
        if (resp.writeQueueFull()) {
          System.out.println("FULL");
          vertx.cancelTimer(id);
          full.complete(null);
        } else {
          resp.write(TestUtils.randomBuffer(8192));
        }
      });
    });
    startServer();
    client.getNow(DEFAULT_HTTP_PORT, DEFAULT_HTTP_HOST, "/somepath", resp -> {
      resp.pause();
      full.thenAccept(v -> {
        resp.request().connection().close();
      });
    });
    await();
  }
```

and I'm getting errors from the response exception handler, can you tell me how different is your case ?

**Comment by oli-h** [comment]
Give me some time to create a compact self contained reproducer.
The one I have atm. requires a full blown Gateleen based server.

**Comment by vietj** [comment]
thanks

**Comment by oli-h** [comment]
The reproducer for those 'half-paused" connections: https://gist.github.com/oli-h/ed8df718311a8480eb24adc0d5ceb408

Toggle in Lines 83/84 between Pump and non-Pump
Without Pump, the test runs without any Exception/Timeouts
**With** Pump you see (sooner or later - in my case after max. 10 seconds):

`Request id-5: starting
--------------- Proxy received request id-5
-------------------------- Backend-Server received request id-5
-------------------------- Backend-Server finished response id-5
Request id-5: Non-200-Status 500
Request id-5: finished (response complete)
java.util.concurrent.TimeoutException: The timeout period of 1000ms has been exceeded while executing GET id-5 for host localhost
	at io.vertx.core.http.impl.HttpClientRequestBase.timeout(HttpClientRequestBase.java:183)
	at io.vertx.core.http.impl.HttpClientRequestBase.handleTimeout(HttpClientRequestBase.java:168)
	at io.vertx.core.http.impl.HttpClientRequestBase.lambda$setTimeout$0(HttpClientRequestBase.java:126)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:870)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:829)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
`

The response from Backend-Server back to the Proxy is never handled. The Pump paused the response stream in a previous Request/Response cycle. Then (here in request "id-5") this 'half-paused' client connection is taken from the pool to talk to the BackendServer - but as it's paused, no reponse handlers are invoked. I assume that even the "HTTP 200 OK" is never routed to Vertx.

**Comment by vietj** [comment]
thanks, will investigate

**Comment by oli-h** [comment]
Probably this is related to https://github.com/eclipse/vert.x/issues/2230?
_Note: I testes with Vertx 3.5.0 - not yet with 3.5.1_

**Comment by oli-h** [comment]
Hm.. We now see that Vertx' HttpClient closes TCP-Connection after one http-Request/Response cycle.
So TCP keep-alive does not work any more. Note: we explict set httpClientOptions.setKeepAlive(true)

So the 'healing' of the paused ReadStream (which we talk about in this issue) can be a side-effect of the (unwanted) TCP-close in Vert.x 3.5.1.

Perhaps I don't see the whole picture - but: closing a TCP-connection when returning this connection to a connection-pool makes the pool senseless - wdyt?

**Comment by vietj** [comment]
@oli-h we have reimplemented proper TCP keep alive support (with header) that will be in a 3.5.2

**Comment by vietj** [comment]
try with master

**Comment by oli-h** [comment]
Confirm: It works with master (3.6.0-SNAPSHOT @ fb8d329ac40fbd05da6e82e1a22e674b70238681 as of 20. Apr. 2018):
- We see a real keep-alive between two http requests - even if there is pause between response of first request and begin of seconds request. See https://gist.github.com/oli-h/fe5607132509c51a57d130f821271189
- The problem with the 'half paused' connection does not occur

So when do you release? :-)

**Comment by vietj** [comment]
we are aiming a 3.5.2 release in the coming weeks (May would be a good target).

I'm closing this issue as it is fixed effectively.

thanks for checking.
