### ISSUE TITLE
HttpClientResponseImpl doesnt log when no handler is set

### ISSUE THREAD

**Issue by j040p3d20** [eclipse/vert.x#2067]
When HttpClientResponseImpl#handleException is called while treating a http response, if an handler was not set, the exception is completely hidden from the user. Please compare 

`io.vertx.core.http.impl.HttpClientRequestBase#handleException`

```public void handleException(Throwable t) {
    synchronized (getLock()) {
      cancelOutstandingTimeoutTimer();
      exceptionOccurred = t;
      if (exceptionHandler != null) {
        exceptionHandler.handle(t);
      } else {
        log.error(t);
      }
    }
  }
```

with 

`io.vertx.core.http.impl.HttpClientResponseImpl#handleException`

``` void handleException(Throwable e) {
    synchronized (conn) {
      if (exceptionHandler != null) {
        exceptionHandler.handle(e);
      }
    }
  }
```

please see this repo for a test case:

https://github.com/j040p3d20/vertx-response-handler-test

In our case, after the body handler has completed we continue with another future to do more work but 
there is a nullpointer exception and we dont reach that code and couldnt understand why because there was no trace of the exception anywhere.

Other than this, thank you for the great work, we love to work with vertx at Akio.com :)

**Comment by tsegismont** [comment]
Would you like to contribute a fix?

2017-07-21 13:02 GMT+02:00 j040p3d20 <notifications@github.com>:
