### ISSUE TITLE
Are there any plans on supporting Clojure in Vert.x 3?

### ISSUE THREAD

**Issue by Tombert** [eclipse/vert.x#2092]
Hello! 

I have some Clojure code that I would like to do some basic web stuff with.  I seem to recall in the past Vert.X supported it as a first class citizen...Is there a plan to bring that back?

**Comment by tsegismont** [comment]
No there is not. Maintaining a language module is hard and time consuming. Your only option is to use Vert.x via the Clojure Java interop.

**Comment by vietj** [comment]
that being said @Tombert we don't preclude of course a contribution to this support as @codepitbull did for Scala, it is just that the actual team of contributors does not have the bandwidth to contribute and maintain it

**Comment by niwinz** [comment]
If someone is interested, I started working on it (https://github.com/funcool/vertx-clojure).

It intend to expose a lightweight clojure friendly api for a subset of vertx (java) api. There are no intention to expose all vertx features. Only the one that make sense for clojure.

**Comment by vietj** [comment]
great news @niwinz when it becomes mature you might want to propose it to the reactiverse organisation

**Comment by tychobrailleur** [comment]
FWIW, I have also spent some effort expanding the whitewoodcity clojure support: https://github.com/tychobrailleur/vertx-lang-clojure (using codegen rather than @niwin 's excellent native approach).
