### ISSUE TITLE
Terminating vertx under Windows

### ISSUE THREAD

**Issue by iiliev2** [eclipse/vert.x#2098]
When launched as a background process, the vertx application cannot be gracefully terminated under Windows. For some reason only killing the process works, but that skips any shutdown hooks. This means that the Launcher start/stop commands cut major parts of the functionality described in the core manual.

The run command allows to gracefully quit the process by issuing ctrl+c within the cmd window it was run from. However, the process spawned by it is also not terminable from outside, e.g. taskkill /pid.

**Comment by cescoffier** [comment]
Terminating a windows process is a bit of a mystery. We are using `WMIC` to interact with the process (https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/impl/launcher/commands/StopCommand.java). If you know a better way, it would be awesome.

**Comment by codem4ster** [comment]
This is still an issue. I use to kill process manually on powershell by this command; `Stop-Process -Id (Get-NetTCPConnection -LocalPort 8008).OwningProcess -Force`. Is this may be used to kill the process and restart?

**Comment by tsegismont** [comment]
@vietj @cescoffier given that now Powershell is available on most Windows machines, perhaps we could replace the `WMIC` command?

In this case, would you mind to contribute the change @codem4ster ?

**Comment by cescoffier** [comment]
Agreed, any other solution would be better. The current one is quite unreliable.
