### ISSUE TITLE
Api on AsyncResult.map is wrong

### ISSUE THREAD

**Issue by kerko** [eclipse/vert.x#2099]
The documentation on AsyncResult.map contains the following passage:
> If the {@code mapper} throws an exception, the returned future will be failed with this exception.
>     When this async result is failed, the failure will be propagated to the returned future and the {@code mapper}     will not be called.

This is simply not true, throwing an exception in the Mapper results in an asyncresult that never completes and therefore breaks the complete flow. This passage should probably be removed from the docs or map should offer the advertised behavior.

**Comment by vietj** [comment]
you are right, the doc should be updated

**Comment by vietj** [comment]
fixed
