### ISSUE TITLE
HttpClient allow dangerous header values

### ISSUE THREAD

**Issue by mguillet** [eclipse/vert.x#2100]
The Vert.x http client accepts header values that contains LF in it. If a program were to add an extra header based on user input without proper data sanitation this could allow an attacker to perform header injection.

Here is a working example:
```java
@RunWith(VertxUnitRunner.class)
public class TestInjection {

  @ClassRule
  static public RunTestOnContext vertxRule = new RunTestOnContext();

  @Test
  public void testHttpHeader(TestContext context) {
    Vertx vertx = vertxRule.vertx();

    vertx.createHttpServer()
      .requestHandler(request -> {
        System.out.println(request.headers().entries().stream()
          .map(e -> e.getKey() + ": <" + e.getValue() +">").collect(Collectors.joining("\n")));
        request.response().end();
      })
      .listen(0, context.asyncAssertSuccess(server -> {
        Async async = context.async();
        vertx.createHttpClient()
          .getAbs("http://localhost:" + server.actualPort(), request -> async.complete())
          .putHeader("Content-Type", "text/plain\nX-EvilHeader: horrible injection")
          .end();
      }));
  }

}
```

This will produce the following input:
```
Content-Type: <text/plain>
X-EvilHeader: <horrible injecton>
Host: <localhost:xxxxx>
```

It seems that Vert.x does't ask Netty to perform header validation:
https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/ClientConnection.java#L451
When passing `true` in the `validateHeaders` parameter to DefaultHttpRequest's constructor an exception is then raised:
```
java.lang.IllegalArgumentException: only ' ' and '\t' are allowed after '\n': [...]
```

Is there any reason why Vert.x is not asking Netty to validate the header of the client request?

If not, I'll create a PR to fix this issue that we consider to be a SSRF vulnerability.

What do think?

**Comment by vietj** [comment]
@mguillet the main reason is speed. I think you could add this as a configuration in HttpServerOptions and HttpClientOptions

**Comment by mguillet** [comment]
Ok I'll create a PR for this so we can discuss about naming, default value, behaviour, etc.

**Comment by mguillet** [comment]
I've created the PR #2102, so I'm closing this ticket.
