### ISSUE TITLE
HTTP client connections should be pools per host and per virtual host

### ISSUE THREAD

**Issue by jo5ef** [eclipse/vert.x#2101]
When using an `HttpClient` for requests to different IPs with the same host header set, the connection pool only establishes one connection to one IP because the `ConnectionKey` for pooling only includes the host header (as `peerHost`). Also see this [mailing list conversation](https://groups.google.com/forum/#!topic/vertx/bGDQjjZ0mqM).

To allow for connections to multiple IPs using the same host header, the `peerHost` could be e.g. IP + hostname.

**Comment by Sammers21** [comment]
I m interested in working on it. @vietj, can I try?

**Comment by vietj** [comment]
this is not a priority at the moment

**Comment by vietj** [comment]
we are aiming at working on fixing for 3.5.1
