### ISSUE TITLE
Httpserver added idle timeout, but the channel also may not be closed

### ISSUE THREAD

**Issue by dinstone** [eclipse/vert.x#2124]
We found this problem in a production environment, and frequent under the mobile client.In positioning, we can easily simulate and reconstruct the problem, steps are as follows:

1. The service side httpserver add idle timeout : new HttpServerOptions () setIdleTimeout (180);
2. Clients use Telnet connect http server : Telnet 10.25.76.170 8802
3. To disable the client network card, this time the telent service disconnected, and then enable the client network card;
4. After 180 seconds, on the server can also see a link from the client, for example :
TCP 0 0 10.25.76.170:8802 10.25.76.15:61703 ESTABLISHED

Problems occurred in the HttpServerImpl, in support of h2c process, the risk of connection timeout does not shut down. Now, we disabled H2c (Settings - Dvertx disableH2c = true) to circumvent this problem, the effect is very obvious in mobile wireless environment.

**Comment by tsegismont** [comment]
Could you put together a reproducer on GitHub? Thank you

2017-09-12 4:47 GMT+02:00 dinstone <notifications@github.com>:

**Comment by dinstone** [comment]
I has an idle timeout test  with that code:
`
@RunWith(VertxUnitRunner.class)
public class HttpServerVerticleTest {
    private static Vertx vertx = Vertx.vertx();

    @Test
    public void testIdleTimeout(TestContext ctx) {
        final Async async = ctx.async();

        HttpServerOptions options = new HttpServerOptions().setIdleTimeout(5);
        vertx.createHttpServer(options).requestHandler(r -> {
            r.response().end("OK");
        }).listen(8081, server -> {
            NetClient netClient = vertx.createNetClient();
            netClient.connect(8081, "127.0.0.1", ar -> {
                if (ar.failed()) {
                    ctx.fail();
                    async.complete();
                    return;
                }

                NetSocket netSocket = ar.result();
                netSocket.handler(b -> {
                    String actual = b.toString();
                    System.out.println(actual);
                    String expected = "HTTP/1.1 200 OK\r\nContent-Length: 2\r\n\r\nOK";
                    ctx.assertEquals(expected, actual);

                    async.complete();
                });

                vertx.setTimer(10000, tid -> {
                    netSocket.write("GET / HTTP/1.1\r\n\r\n");
                });
            });
        });

        async.await();
    }

}
`
I set the idle timeout of the httpserver to 5 seconds, and then use the netclient connect to the server but not sending data, sending HTTP requests after 10 seconds, but the success have received a response.Obviously this is not to be expected.

**Comment by vietj** [comment]
fixed by https://github.com/eclipse/vert.x/commit/7e8995f1be6d31bd833def02c7be4465733c1879
