### ISSUE TITLE
mysql connection aborted 

### ISSUE THREAD

**Issue by lightway82** [eclipse/vert.x#2127]
I has test with that code:
```
        Async async = context.async();
        accountService.retrieveAllAccounts()
                      .subscribe((accounts) -> {
                          if(accounts.size()!=0) {
                              async.complete();
                          }else context.fail();

                      },context::fail);
        async.awaitSuccess(5000);

Connection closed automatically after unsubscribe:
 
 public  Single<SQLConnection> getConnection() {
    return client.rxGetConnection().flatMap(conn -> {
      Single<SQLConnection> connectionSingle = Single.just(conn);
      return connectionSingle.doOnUnsubscribe(conn::close);
    });
  }
```
I see  "Aborted connection" in console after  async.complete(), but if i don`t use   async.complete(); than connections closed normally.

**Comment by dgoetsch** [comment]
Is the "client" variable the client from `vertx-sql-common` / `vertx-jdbc-common`?  That library handles asynchronously getting connections.

**Comment by lightway82** [comment]
vertx-jdbc-client

**Comment by dgoetsch** [comment]
Does this issue belong in that repo?  https://github.com/vert-x3/vertx-jdbc-client;  If the issue belongs here you should be able to reproduce it without the SQLClient.

I've never used the `rxGetConnection()` method, and I think this example is misssing a lot of context.  I know that @vietj is going to ask for a test, and I have to agree the best way for us to understand whats going on here is to see a test demonstrating the issue.

**Comment by lightway82** [comment]
Tomorrow I will make a separate project for the test, in order to learn more about what is happening.

**Comment by dgoetsch** [comment]
Thank you!

**Comment by vietj** [comment]
@lightway82 can you move this issue to the vert-x3/vertx-jdbc-client repository as explained by @dgoetsch ? thanks

**Comment by lightway82** [comment]
I made detailed tests. This is not related to JDBC.
The problem occurs in the tests, if async.complete () is called, then the asynchronous call in the doOnUnsubscribe is  interrupted. This can be seen in these two tests.

```
 @Test
    public void otherTest1(TestContext context){
        Async async = context.async();

            Single.just(1).doOnUnsubscribe(() -> Single.just("MSG")
                                                       .delay(3, TimeUnit.SECONDS)
                                                       .subscribe(System.out::println))
                .subscribe((i) -> async.complete(), context::fail);

        async.await(5000);
    }

    @Test
    public void otherTest2(TestContext context){
        Async async = context.async();

        Single.just(1).doOnUnsubscribe(() -> Single.just("MSG")
                                                   .delay(3, TimeUnit.SECONDS)
                                                   .subscribe(System.out::println))
              .subscribe((i) -> System.out.println(i), context::fail);

        async.await(5000);
    }
```

I move this issue to vert-x3/vertx-unit
