### ISSUE TITLE
SLF4J location aware logger parameters are ignored

### ISSUE THREAD

**Issue by stijena** [eclipse/vert.x#2130]
I would like to refer to a possible issue concerning logging in vert.x. This has already been discussed in similar issue #1243 and #1280 . I'm trying to use SLF4J logging with {} parameters, **but instead of parameters, logger logs parenthesis**. 

Example:
`logger.error("Message : {}", "foo"); // logs "Message : {}" instead of "Message : foo"`

I created vert.x Logger instance by passing an SLF4J delegate to the constructor. 

The flow is as follows: Logger.error (using error call in this example, could be something else) calls delegate.error, which in turn calls error method in `SLF4JLogDelegate`. This method calls `log(int level, Object message, Throwable t, Object... params)` which check if `logger instanceof LocationAwareLogger` (line 173 in `io.vertx.core.logging.SLF4JLogDelegate`)  .

For this case, this is true and `l.log(null, FQCN, level, msg, parameters, t)` is invoked in `org.slf4j.impl.Log4jLoggerAdapter` (line 579 for 1.7.25) and this is a method that receives parameters (as `Object[] argArray`), but **ignores** them (apparently a bug in SLF4j). I believe this method should not be invoked when parameters are present. Instead, an appropriate method should be called for each separate level, since each has a MessageFormatter that includes parameters.

**Comment by alexlehm** [comment]
When I write a small example program and run it with slf4j logging, it seems to work, maybe the issue depends on how the logger is constructed. Could you please put up a reproducer that shows the issue?

**Comment by vietj** [comment]
can you check with latest version from master ?

**Comment by alexlehm** [comment]
question: are you using the slf4j log4j 1.2 adaptor? In this case the template functionality is not available as log4j does not implement it.
When I switch from slf4j-simple to slf4j-log4j12, the {} is printed

**Comment by alexlehm** [comment]
@vietj behaviour is the same with 3.5.0-snapshot

**Comment by alexlehm** [comment]
@stijena ok, you are right, the slf4j adapter calls the log method which leaves out the formatter in log4j, that is quite easy to fix I think, i will create a pr

**Comment by alexlehm** [comment]
@vietj should we unit test this? since slf4j uses a static class as logging impl, this would require running different jvms for the test

**Comment by alexlehm** [comment]
@stijena ok, its not so easy after all, the log.error() and similar methods have no way to provide the logger class name so that it would log the wrong class name and line number, so we cannot use that. since log.log() does not process the template, we have to run MessageFormatter from org.slf4j.helpers directly

**Comment by alexlehm** [comment]
I implemented the message formatting in the slf4j delegate directly, I guess this could need some more testing

https://github.com/alexlehm/vert.x/tree/issues/%232130-slf4j-format

**Comment by vietj** [comment]
we do have integration tests that test the output, look at Log4J2LogDelegateTest.

To run them : "mvn verify -Dtest=FooTest" (FooTest allows to skip the unit tests to save time).

**Comment by vietj** [comment]
the fix seems legit

**Comment by vietj** [comment]
will write a test and do a copy paste from Alex's repo

**Comment by vietj** [comment]
@stijena what is the actual `LocationAwareLogger` you are using ?

**Comment by vietj** [comment]
all credits to @alexlehm

**Comment by AceHack** [comment]
I'm still having this problem and unaware of how to solve it.  I'm using log4j-slf4j-impl

**Comment by vietj** [comment]
@AceHack I don't know what is the issue, but we do recommend you use SLF4J API directly and not vertx API for logging

**Comment by alexlehm** [comment]
@AceHack can you please try to use slf4j with the vert.x logging without going the way with log4j-slf4?

if that doesn't work, can you please create a reproducer project?
