### ISSUE TITLE
ProxyErrorTest.testProxyHostUnknown() depends on normal dns, which may not work

### ISSUE THREAD

**Issue by alexlehm** [eclipse/vert.x#2141]
The test uses unknown.hostname to get a dns resolution error, this will not work when the providers dns returns an ad page for unknown hosts.
We will set up a fakedns instead

**Comment by vietj** [comment]
yup

**Comment by alexlehm** [comment]
issue belongs to this thread: https://groups.google.com/d/msg/vertx-dev/9RI99ZPM3Eo/MdeVLMpNAQAJ

I will implement a new test when i have time

**Comment by alexlehm** [comment]
pr#2157

**Comment by alexlehm** [comment]
closed with merge #2157

**Comment by vietj** [comment]
thanks Alex!
