### ISSUE TITLE
Java 9 CommandBuilder incompatibilty

### ISSUE THREAD

**Issue by lukyer** [eclipse/vert.x#2143]
Hi,
after upgrading to Java9 jdk vertx startup throws:

java.lang.IncompatibleClassChangeError: Method io.vertx.ext.shell.command.CommandBuilder.command(Ljava/lang/String;)Lio/vertx/ext/shell/command/CommandBuilder; must be InterfaceMethodref constant (c.m.w.l.LauncherVerticle#?)
13:11:10.287 ERROR# - Future{cause=Method io.vertx.ext.shell.command.CommandBuilder.command(Ljava/lang/String;)Lio/vertx/ext/shell/command/CommandBuilder; must be InterfaceMethodref constant} (c.m.w.l.LauncherVerticle#?)

Is it some kind of java 9 incompatibilty? How can I fix it? 
Thanks.

**Comment by vietj** [comment]
that's weird, can you provide a reproducer ?

**Comment by lukyer** [comment]
It was caused by another Kotlin bug. I was calling CommandBuilderImpl from Kotlin code and translation from java9 to java8 (only one supported by Kotlin) caused this.

Not related to vertx, sorry.

**Comment by vietj** [comment]
thanks for reporting!
