### ISSUE TITLE
Install plugin with Eclipse IDE?

### ISSUE THREAD

**Issue by ORESoftware** [eclipse/vert.x#2148]
Are there instructions on how to install the plugin with the Eclipse IDE?

newb here.

**Comment by tsegismont** [comment]
Vert.x is not an Eclipse IDE plugin. It's an Eclipse foundation project. You can use it in any JVM app. The [Vert.x documentation](http://vertx.io/docs/#get_started) is a good place to start for newcomers.

**Comment by ORESoftware** [comment]
Thanks, one more newb question for you! Does vertx give the developer any ability to do an incremental build upon file system changes and hot-load the server? Or should I try to use JRebel?

**Comment by vietj** [comment]
you can read that http://vertx.io/docs/vertx-core/java/#_live_redeploy

**Comment by tsegismont** [comment]
The Vert.x CLI, the Maven plugin and the Gradle plugin all have
redeploy/reload options:

http://vertx.io/docs/vertx-core/java/#_live_redeploy
https://github.com/fabric8io/vertx-maven-plugin
https://github.com/jponge/vertx-gradle-plugin

They rebuild the app completely. Doesn't take too long usually, a few
seconds (no complex dependency tree to build!)

But it's not partial reloading like JRebel.

For future questions please use the Vert.x forum (see vertx.io/community)


2017-09-29 4:31 GMT+02:00 Operations Research Engineering Software+ <
notifications@github.com>:

**Comment by ORESoftware** [comment]
@tsegismont thank you for the info
