### ISSUE TITLE
Can Router expose vertx?

### ISSUE THREAD

**Issue by trajano** [eclipse/vert.x#2150]
The RouterImpl already has a method that would expose `vertx()` but only to the default classes.  Is there a reason why it was not exposed on the `Router` level?

The reason I am asking is I am trying to build a simple API that would help me build routes, but I would need `vertx` on construction to use the `executeBlocking` for long initialization sequences.

**Comment by trajano** [comment]
At the moment I used the following hack

        final Vertx vertx;
        try {
            final Method vertxMethod = router.getClass().getDeclaredMethod("vertx");
            vertxMethod.setAccessible(true);
            vertx = (Vertx) vertxMethod.invoke(router);
        } catch (IllegalAccessException
            | IllegalArgumentException
            | InvocationTargetException
            | NoSuchMethodException
            | SecurityException e) {
            throw new RuntimeException(e);
        }

**Comment by vietj** [comment]
can you move this issue to the vertx-web repository ?
