### ISSUE TITLE
AsyncResult improvements

### ISSUE THREAD

**Issue by ruslansennov** [eclipse/vert.x#2158]
I believe `AsyncResult.map()` must handle exceptions in mapper function. 
Also it seems that `AsyncResult.succeededAsyncResult()` and `AsyncResult.failedAsyncResult()` static factories will be useful.

If these proposals makes sense I can provide PR

**Comment by vietj** [comment]
- what's your proposal for map ? I think this is debatable and it was discussed before (I can't find the issue). I think the main issue is that the result is lazy and it should be done with some care.

- there are method on `Future` for that which returns an optimized immutable Future that represent the async result so it would be more or less the same, see `Future#succeededFuture()`

**Comment by ruslansennov** [comment]
Yes, I know about the immutable `Future` implementations, I use them and it is OK for me. But as I see, there is no other classes that implement `AsyncResult` interface. This means that` AsyncResult.map()` (which has a different behavior than `Future.map()` in part of checking exception) can't be used. We can make this method abstract or change it like overridden method in `Future` with additional static factories

**Comment by vietj** [comment]
I think we should change the contract/implementation in `AsyncResult` to match the `Future#map` contract and satisfy `((AsyncResult)Future.succeededFuture().map(t -> throw new RuntimeException()))'

**Comment by dgoetsch** [comment]
I see `AsyncResult` as being informally similar to a Try monad (see scala standard lib or kotlin funktionale library).
 
In scala Try, the `map` function handles functions as proposed here - it caches exceptions and wraps them in a `Failure`, or wraps the successful result in a `Success`;  Similarly, it may be useful to provide a `flatMap` method (or `compose` to align with `Future`): `flatMap(Function<T,AsyncResult<U>> mapper)`.

It also might be nice to have a couple of defualt implementations of AsyncResult (Success and Failure), and provide static methods on AsyncResult that return an instance of AsyncResult.Success or AsyncResult.Failure.  I've wanted those in a few projects and often end up implementing them myself in some gross Util object.

**Comment by vietj** [comment]
@dgoetsch keep in mind that the goal of AsyncResult/Future is to not become a functionnal monads. Besides in the future we might want to replace them with more common types such as `CompletableFuture` instead, so I'm not keen on providing more than what it is necessary.
