### ISSUE TITLE
SSLHelper has confusing options 

### ISSUE THREAD

**Issue by johnoliver** [eclipse/vert.x#2179]
SSLHelper has:

```
  private static final String[] DEFAULT_ENABLED_PROTOCOLS = {"SSLv2Hello", "TLSv1", "TLSv1.1", "TLSv1.2"};
```

However later builds up the enabled protocol list with:

```
protocols.retainAll(Arrays.asList(engine.getEnabledProtocols()));
```

And since netty by default does not enable SSLv2Hello ([ref](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/JdkSslContext.java#L84) ), SSLv2Hello in fact is not enabled, and I believe it is not possible to enable any protocols other than TLSv1/1.1/1.2.

This could be regarded as a feature as it prevents developers selecting insecure protocols, however is confusing that `addEnabledSecureTransportProtocol` will only actually work if its  TLSv1/1.1/1.2.

Could be fixed by removing SSLv2Hello from the default list to make it less confusing, and maybe documenting what protocols are available. Or by re-enabling all protocols by changing

```
protocols.retainAll(Arrays.asList(engine.getEnabledProtocols()));
```

to

```
protocols.retainAll(Arrays.asList(engine.getSupportedProtocols()));
```

**Comment by johnoliver** [comment]
Having looked at the OpenSslEngine it seems that SSLv2Hello cant be disabled:

https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngine.java#L1353

So may have to go with the latter fix so the code actually does do what it should, as it may be just as confusing that it is not listed but OpenSsl adds it.

**Comment by vietj** [comment]
is it possible to provide a test for asserting this behavior ?

**Comment by vietj** [comment]
ping @johnoliver

**Comment by philrykoff** [comment]
I need SSLv3 and SSLv2Hello support for a customer's legacy devices. Let's not discuss the security implications here, but I also saw what johnoliver saw during debugging.

I'll PR a fix. I am not so sure regarding a test, as I don't see any getter for retrieving the enabled protocols.

**Comment by philrykoff** [comment]
@vietj : would you accept a PR adding this feature?

**Comment by vietj** [comment]
ah you change by supported protocols

**Comment by vietj** [comment]
yes I'm all for that, Vert.x should not get in your way if you want to shot in your feet :-)

**Comment by vietj** [comment]
fixed

**Comment by vietj** [comment]
@johnoliver @philrykoff I will remove _SSLv2Hello_ from the list of default enabled protocols. Actually this protocol was already filtered by the previous code (as the engine supports it but does not enable it by default) : so the behavior will be the same for users. Also some tests don't pass with _SSLv2Hello_ like the SNI tests (I think it does not supports SNI but I can't find evidence of it).

**Comment by vietj** [comment]
I will add a test that checks we can still use this protocol by setting it in the protocols list

**Comment by philrykoff** [comment]
Makes sense.
