### ISSUE TITLE
Unable to build vertx as describe in the readme

### ISSUE THREAD

**Issue by ctron** [eclipse/vert.x#2183]
The readme file says to build vertx by issuing the following command:

    mvn package

However this results in the following error:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Vert.x Core 3.5.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for io.vertx:vertx-codegen:jar:3.5.1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.825 s
[INFO] Finished at: 2017-10-20T10:45:32+02:00
[INFO] Final Memory: 13M/594M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project vertx-core: Could not resolve dependencies for project io.vertx:vertx-core:jar:3.5.1-SNAPSHOT: Failure to find io.vertx:vertx-codegen:jar:3.5.1-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

I guess there is some step missing.

**Comment by tsegismont** [comment]
No, it's just that we are releasing 3.5.0 right now and the CI server has
not built the new snapshots already.

Bad timing 😀

Le 20 oct. 2017 10:47 AM, "Jens Reimann" <notifications@github.com> a
écrit :

**Comment by bbossola** [comment]
This is happening at least since 12 hours. Can somebody take a look please?

**Comment by vietj** [comment]
going to look at it.

damn CI!

**Comment by vietj** [comment]
the issue with a release is that it makes all  build concurrent and create race issues.

**Comment by bbossola** [comment]
Sorry for being the bearer of bad news, we just noticed as Vert.x is one of the featured projects at [meterian.io](https://www.meterian.io), my stealth startup :)

**Comment by vietj** [comment]
no problem, any chance you might appear on this page ? http://vertx.io/whos_using/

**Comment by bbossola** [comment]
Well, we'd be glad, Vert.x is certainly a great project, but we are not really using it: instead, we are constantly assessing it for known vulnerabilities, as you can see from the report here:
https://www.meterian.io/report/gh/eclipse/vert.x

You should add our badges, as your project is doing quite well :), happy to PR.

**Comment by ctron** [comment]
Ok .. So it was just bad timing after all 😀 

It might be best to just close this issue then.
