### ISSUE TITLE
"update-returning"   isn't supported by vertx-pg

### ISSUE THREAD

**Issue by duanxianwp** [eclipse/vert.x#2188]
![b26yn ix cex026x_oq4yo7](https://user-images.githubusercontent.com/20347297/32040251-b7a80170-ba62-11e7-8f1f-0644a58ea3f4.png)

I don't get result for this sql . (PS: I want to get the type)
 "update  table set ****     returning  type".

**Comment by vietj** [comment]
can you open this issue in the correct repository ? and close this one ?
