### ISSUE TITLE
Expose FakeClusterManager for application test code

### ISSUE THREAD

**Issue by seanf** [eclipse/vert.x#2191]
For unit testing code which uses cluster-related APIs (eg `io.vertx.core.shareddata.SharedData.getClusterWideMap()`) in a non-clustered environment it would be very handy if the class `io.vertx.test.fakecluster.FakeClusterManager` were exposed. Otherwise there seems to be no way of unit testing such code ("Can't get cluster wide map if not clustered") - except by writing another dummy/local ClusterManager.

This class can be accessed via the dependency 'io.vertx:vertx-core:3.5.0:tests' but it doesn't seem to be documented anywhere, and I imagine that the contents of the tests jar are subject to change.

**Comment by vietj** [comment]
actually it hasn't much changed in years, but in reality it could indeed change.

Perhaps that @tsegismont has an opinion on the subject ?

btw cool avatar :-)

**Comment by seanf** [comment]
Thanks!

I had another thought: something like `FakeClusterManager` could also be used to allow the same application code to run in clustered or non-clustered environments, ie for production. When I changed my code to use a cluster-wide `AsyncMap` instead of a `LocalMap`, I was a bit disappointed to realise that I could no longer run my code without setting up a real cluster. A supported `FakeClusterManager` would allow more flexibility in deployment, and would make it easier to migrate a non-clustered application to a cluster, in a more gradual way.

**Comment by tsegismont** [comment]
I would rather not expose the `FakeClusterManager`. The problem here is that `getClusterWideMap` should return a "local async map" when Vert.x is not clustered. If you take a look at locks and counters, there is no distinction between local/cluster. We should do the same for `AsyncMap`.

**Comment by tsegismont** [comment]
See #2137

**Comment by seanf** [comment]
Thanks @tsegismont. The local AsyncMap in #2137 covers my use case perfectly well.

**Comment by gadieichhorn** [comment]
I am trying a similar thing and face an error

also tried with the context vertx option rule, same error.

    @Rule
     public RunTestOnContext rule = new RunTestOnContext(new VertxOptions().setClustered(true));

and in my test I call the cluster wide map, lock and counters. but I get error on the first call for the cluster data service.

```
        vertx.sharedData().<String, Long>getClusterWideMap(map, m -> {

```
here is the error.

```
  SEVERE: Unhandled exception
    java.lang.IllegalStateException: Can't get cluster wide map if not clustered
        at io.vertx.core.shareddata.impl.SharedDataImpl.getClusterWideMap(SharedDataImpl.java:63)
...

        at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:81)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:294)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:748)

```
any advise how to test this?

**Comment by tsegismont** [comment]
There is a new method `getAsyncMap` in 3.5.1 which works in both local and clustered mode. It should be released next week. In the meantime, you can try with a master branch snapshot.
