### ISSUE TITLE
Sending RxJava2 items to eventbus with backpressure

### ISSUE THREAD

**Issue by nicolaferraro** [eclipse/vert.x#2192]
Following the vertx rx-java 2 documentation, it seems there's a easy way to transform a read stream into a flowable, using the `FlowableHelper.toFlowable` utility method, but **nothing for write streams**.

The documentation uses the following example to send data from rx-java to the eventbus:
```
observable.
    buffer(1, TimeUnit.SECONDS).
    map(samples -> samples.
        stream().
        collect(Collectors.averagingDouble(d -> d))).
    subscribe(heat -> {
      vertx.eventBus().send("news-feed", "Current heat is " + heat);
    });
```

But if you send messages to the eventbus in the `subscribe` method, you cannot handle backpressure correctly (I've an example that hangs if I send too many messages, but I don't get any exception to confirm that backpressure is the only problem).

Is there a way to turn a write stream into a `Subscriber`?
E.g.:
```
Subscriber<X> subs = FlowableHelper.toSubscriber(vertx.eventBus().publisher("address"));
observable.subscribe(subs);
```

Or something similar..

**Comment by vietj** [comment]
I think it was discussed a couple of times but not on GitHub tracker.

can you close this issue and open one in this repository https://github.com/vert-x3/vertx-rx ?

**Comment by vietj** [comment]
marked as invalid as it will not resolve in this repo

**Comment by vietj** [comment]
ideally we would like to turn WriteStream into Observer I think
