### ISSUE TITLE
Since 3.5.0: failed to parse /etc/resolv.conf on Windows

### ISSUE THREAD

**Issue by s1monw1** [eclipse/vert.x#2199]
I'm having problems with starting a webserver on Windows10 since updating to 3.5.0:

```
[vert.x-eventloop-thread-1 @coroutine#50] DEBUG i.n.r.d.UnixResolverDnsServerAddressStreamProvider - failed to parse /etc/resolv.conf and/or /etc/resolver
    java.lang.IllegalArgumentException: \etc\resolv.conf didn't provide any name servers
```

Might also be a result of adding coroutine support to my app...

Is this a known issue? Any workaround?

**Comment by vietj** [comment]
is it preventing you from using vertx ?

**Comment by vietj** [comment]
why did you close the issue ? I would like to understand if that warning is normal or not.

normally UnixResolverDnsServerAddressStreamProvider should not be used on Windows, it may be a netty or vertx issue

**Comment by s1monw1** [comment]
After further research my problems were not related to this, I got distracted by this log. You’re right, it shouldn’t be used on Windows but does not cause obvious problems

**Comment by rkbalgi** [comment]
The issue appears to be an issue with netty in DnsServerAddressStreamProviders which simply returns the Unix resolver irrespective of the platform

**Comment by SELLAM** [comment]
you can use: Java -jar xxx.jar -Dvertx.disableDnsResolver=true

**Comment by rkbalgi** [comment]
Thanks. That did appear to get rid of the errors at the moment.

**Comment by vietj** [comment]
duplicate of https://github.com/eclipse/vert.x/issues/2204
