### ISSUE TITLE
Missing log.trace-ing for HTTP client calls

### ISSUE THREAD

**Issue by myok12** [eclipse/vert.x#2200]
I noticed that turning TRACE for io.vertx outputs HTTP server logs, but unfortunately no HTTP client logs. I am using swagger-codegen to generate clients dynamically and thus would love to see what goes on over the wire -- I currently use a packet analyzer to inspect, but obviously that rules out HTTPS. I created a branch in my fork (https://github.com/myok12/vert.x/tree/tracing_http_client) and can send a pull request (I have signed the ECA) or can have you copy my changes.

**Comment by myok12** [comment]
Diff: https://github.com/eclipse/vert.x/compare/master...myok12:tracing_http_client?expand=1

**Comment by vietj** [comment]
you can get tracing with http://vertx.io/docs/vertx-core/java/#logging_network_activity
