### ISSUE TITLE
HttpClient connection pool improvements

### ISSUE THREAD

**Issue by vietj** [eclipse/vert.x#2208]
Provide a better implementation of the HttpClient pool: the current pool has a few drawbacks, race conditions , inconsistencies and is tightly coupled to the logic for establishing HTTP connections.

The new pool only retains the logic of managing connections and the HTTP logic has been factored out. The pool is a state machine that reacts to events and tries to progress to satisfy the waiter list based on the connections managed by the pool and the connection provider to create new connections.

The logic for managing effectively connections has been factored out of the pool, leaving room for reusing this pool potentially in other components that would need a pool with similar behavior. This also allow to build establish HTTP connection without the pool (i.e by promoting an existing socket into an HTTP connection).

The pool also clarifies that the connection waiter will always be called on the connection event loop without owning a lock from the pool, to avoid deadlock reentrency with the pool lock.

The fallback from HTTP/2 to HTTP/1 has also be improved, the previous way was switching the HTTP/2 pool by the HTTP/1 pool. The new pool provides instead a way to deal with both at the same time and honour the max pool capacity consistently.

The HTTP/1 pipelining accounting logic has been retrofitted into the pool and is not anymore handled by the HTTP/1 connections, HTTP/1 connections only schedule the pending requests on the connection reactively.

**Comment by luengnat** [comment]
with this, does it mean that it is now safe to share HttpClient across threads?

**Comment by vietj** [comment]
it is not recommended for performance reason

the main idea is that it is thread safe, because sometimes when performance does not matter (like writing a unit test), then you can use it from non vertx thread (the junit thread).

when running in vertx, there should be one client per event loop for performance reason.

**Comment by luengnat** [comment]
The problem is that it's actually making it hard to use it correctly. If you use vert.x as a client, you will see that it's quite painful to do it correctly to make a call from the eventloop. The code will be littered with vertx.runOnContext (which is a bad way to do it anyway). Sometimes, I feel like the right model is to have one default Context per vert.x instance.

**Comment by vietj** [comment]
@luengnat can you clarify what is making hard ? it's not clear
