### ISSUE TITLE
HttpClient connection leaks when exceptions thrown when receiving inbound messages

### ISSUE THREAD

**Issue by brian65535** [eclipse/vert.x#2212]
We are observing HttpClient connection leaks due to exceptions in receiving inbound messages in certain conditions.

The leak we are seeing is caused by io.netty.handler.codec.compression.DecompressionException, but there could be other cases that trigger the similar leaking situation.

Some details about the case we are seeing: when a client has `tryUseCompression` set to `true`, and a server returns `Content-Encoding: gzip` in a response header, BUT then returns an invalid gzip response (could simply be some plain texts) for some reasons, DecompressionException is thrown, but the connection is not properly cleaned up.

So far we suspect the direct cause of the issue is that `VertxHandler.channelInactive` is not fired after a channel is closed by `exceptionCaught`. But we are not sure the problem is in netty or vertx.

Here is a unit test to reproduce the issue:
https://github.com/brian65535/connection_leak

**Comment by vietj** [comment]
thanks for the reproducer, I will try it

**Comment by vietj** [comment]
it seems to happen in Netty,  `HttpContentDecoder` does:

```
    @Override
    public void channelInactive(ChannelHandlerContext ctx) throws Exception {
        cleanup();
        super.channelInactive(ctx);
    }
```

the `cleanup()` has a side effect to rethrow an exception which prevents to call `super.channelInactive(ctx)`. Imho the exception should be returned by `cleanup()` and eventually rethrown when appropriate.

**Comment by vietj** [comment]
cc @normanmaurer any opinion on this ?

**Comment by normanmaurer** [comment]
@vietj  +1 ... I will create a patch

**Comment by normanmaurer** [comment]
@vietj @brian65535 I think this should fix it: https://github.com/netty/netty/pull/7415

Thanks for pinging

**Comment by vietj** [comment]
@normanmaurer do you think that is a decent work around until Vert.x can uses your patch:

```
new HttpContentDecompressor(true) {
        @Override
        public void channelInactive(ChannelHandlerContext ctx) throws Exception {
          try {
            super.channelInactive(ctx);
          } catch (Exception e) {
            ctx.fireChannelInactive();
          }
        }
      }
```

**Comment by normanmaurer** [comment]
@vietj I think you still would like to ensure you also propergate the exception if `super.channelInactive(...)` throws.

Something like this should work:

```
try {
    super.channelInactive(ctx);
} catch (Exception e) {
    ctx.fireExceptionCaught(e);
   ctx.fireChannelInactive();
}
```

**Comment by vietj** [comment]
but the exceptions seems already thrown in the pipeline during service time and the channel becomes inactive because vert.x closed it as reaction to the initial decoder exception

**Comment by vietj** [comment]
so it would be duplicate

**Comment by vietj** [comment]
but better ssafe (2 exceptions) than sorry (no exception)

**Comment by vietj** [comment]
I'll use this work around until we can get the fix

**Comment by brian65535** [comment]
Thanks for making the fixes with lightning speed!

**Comment by vietj** [comment]
@brian65535 I'll add this workaround in the meantime
