### ISSUE TITLE
switching to 3.5 - StaticHandlerImpl.isFileExisting

### ISSUE THREAD

**Issue by Sergey80** [eclipse/vert.x#2213]
I have a web-static handler in one of my verticle.
It used to work.

  @Override
    public void start(Future<Void> startFuture) {
        configureHttpServer(startFuture);
        ...

where

 private void configureHttpServer(Future<Void> future) {

        int PORT = config().getInteger("http.port");

        // TODO: for tests
        router.route("/*").handler(StaticHandler.create());

        vertx.createHttpServer()
            .requestHandler(router::accept)
            .listen(PORT, ar -> {
                if (ar.failed()) {
                    future.fail(ar.cause());
                } else {
                    future.complete();
                }
            });
    }

Now when I start and try to connect in browser to "/" or "/index.html"

Nov 16, 2017 9:52:29 PM io.vertx.ext.web.impl.RoutingContextImplBase
SEVERE: Unexpected exception in route
java.lang.NullPointerException
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.isFileExisting(StaticHandlerImpl.java:261)

Did I miss something? Should it still work?

in /resources/webroot I have index.html that is used to show some content.

**Comment by Sergey80** [comment]
I did try         router.route("/files/*").handler(StaticHandler.create("webroot")); and then http://localhost:35001/files/index.html - still the same

**Comment by Sergey80** [comment]
I did try

 pathToWebRoot = "src/main/resources/webroot";
            System.out.println("pathToWebRoot: " +pathToWebRoot);

        // TODO: for tests
        router.route("/*").handler(StaticHandler.create(pathToWebRoot));

since I run it from ide, and the webroot is in src folder

same thing

**Comment by vietj** [comment]
can you open this issue in the vertx-web project instead ?

**Comment by vietj** [comment]
can you report this issue in vertx-web project ?
