### ISSUE TITLE
HazelcastKubernetesDiscoveryStrategyFactory in vertx-3.5.0

### ISSUE THREAD

**Issue by phsmip** [eclipse/vert.x#2215]
Hello,

I have just upgraded my application in vertx-3.5.0. Since this upgrade, my application doesn't start anymore and generate this error:
java.lang.ClassNotFoundException: io.vertx.servicediscovery.hazelcast.HazelcastKubernetesDiscoveryStrategyFactory

This class is mentionned in META-INF/services/com.hazelcast.spi.discovery.DiscoveryStrategyFactory in this artifact `<artifactId>vertx-service-discovery-bridge-kubernetes</artifactId>`, but i didn't find it in the jar file.

Could you please tell me if it's a bad configuration or a bug?

**Comment by cescoffier** [comment]
This has been fixed by https://github.com/vert-x3/vertx-service-discovery/pull/74

**Comment by cescoffier** [comment]
If you need an hazelcast cluster, refer to the hazelcast kubernetest documentation (https://github.com/hazelcast/hazelcast-kubernetes)
