### ISSUE TITLE
vertx run --help incorrect

### ISSUE THREAD

**Issue by murphye** [eclipse/vert.x#2216]
In doing vertx run --help, I see this:

`Usage: vertx run [-cp <classpath>] [--cluster] [--cluster-host <host>]
       [--cluster-port <port>] [--conf <config>]  [--ha] [--hagroup <group>]
       [--instances <instances>] [--on-redeploy <cmd>]  [--quorum <q>]
       [--redeploy <includes>] [--redeploy-grace-period <period>]
       [--redeploy-scan-period <period>] [--redeploy-termination-period
       <period>]  [--worker] main-verticle'

This is backwards as the -- switches come after main-verticle, i.e. 

`vertx run src/main/js/io/vertx/example/web/helloworld/server.js --redeploy=src/**/*.js --launcher-class=io.vertx.core.Launcher'

**Comment by cescoffier** [comment]
The order should not matter. Do you have a reproducer?

**Comment by murphye** [comment]
You are right. I must have made some other mistake. Upon testing again, it works. Closing.

P.S. Almost all examples I have seen use -- at the end, but it works both ways.
