### ISSUE TITLE
version 3.5.0, The -conf option does not point to an existing file or is not a valid JSON object

### ISSUE THREAD

**Issue by laudylcp** [eclipse/vert.x#2219]
when use io.vertx.core.Launcher, no problem!!!!
but use custom MyLauncher extends io.vertx.core.Launcher, throw exception:
The -conf option does not point to an existing file or is not a valid JSON object.

public class MyLauncher extends io.vertx.core.Launcher {

    public static void main(String[] args) {
        new MyLauncher().dispatch(args);
    }

    @Override
    public void afterConfigParsed(JsonObject config) {
        super.afterConfigParsed(config);

        System.out.println("config：" + config.encodePrettily());
    }
}

ide program arguments:
run com.example.demo.MainVerticle --redeploy=**/*.class --launcher-class=com.example.demo.MyLauncher -conf=config.json

if use:
run com.example.demo.MainVerticle --redeploy=**/*.class --launcher-class=io.vertx.core.Launcher -conf=config.json
then:
successfully!!!

is version 3.5.0 bug???

**Comment by vietj** [comment]
@cescoffier any idea ?

**Comment by cescoffier** [comment]
Investigating.

**Comment by cescoffier** [comment]
@laudylcp which IDE are you using? Can you give me more details about your "run".

I've tried:

```
java -jar target/bug-config-1.0-SNAPSHOT.jar run io.vertx.starter.MainVerticle --redeploy="**/*.class" --launcher-class=io.vertx.starter.MyLauncher -conf=config.json
```

and it's working. 

I've also tried in my IDE (attached a screenshot of the configuration), and it's also working.

![blank](https://user-images.githubusercontent.com/402301/33545392-5d2bae50-d8de-11e7-9fe4-aa4466b54971.png)

**Comment by laudylcp** [comment]
@cescoffier Thanks for your reply.
I'm using IntelliJ IDEA version:2017.2.4.

MyLauncher.java:
![image](https://user-images.githubusercontent.com/23287431/33586174-ef3ac7f8-d9a2-11e7-81df-a235295f2907.png)
MainVerticle.java:
![image](https://user-images.githubusercontent.com/23287431/33586199-0c3a67e6-d9a3-11e7-956f-001015f70302.png)
Run/Debug Configurations:
![image](https://user-images.githubusercontent.com/23287431/33586252-746b5334-d9a3-11e7-92d3-d36cba71b35a.png)
Result:
![image](https://user-images.githubusercontent.com/23287431/33586288-ae9db132-d9a3-11e7-94a2-66e0e50d2b83.png)

**Comment by laudylcp** [comment]
@cescoffier I looked source code  of getConfiguration() method, It looks like can't find config file.
screenshot is below:
![image](https://user-images.githubusercontent.com/23287431/33587075-614e0356-d9a7-11e7-8289-8c93689fe3ec.png)

**Comment by cescoffier** [comment]
Your config file seems to be in src/main/resources, while you point to ./config.json. Did you try changing the path to src/main/resources/config.json?

**Comment by laudylcp** [comment]
@cescoffier Thanks, After I changing the path to src/main/resources/config.json, The problem is no longer recurring.
![image](https://user-images.githubusercontent.com/23287431/33600515-66d738aa-d9e4-11e7-9d3b-9a5a49adcc95.png)
Thanks again!!
