### ISSUE TITLE
Use new SniCompletionEvent from Netty

### ISSUE THREAD

**Issue by vietj** [eclipse/vert.x#2226]
and try to remove `VertxSniHandler` - see https://github.com/netty/netty/pull/7444

**Comment by Sammers21** [comment]
Hi, I m interested in working on the issue. Can you point me out?

**Comment by vietj** [comment]
look at `VertxSniHandler#replaceHandler` method, the idea is to use instead the event fired to obtain the hostname rather than the current override of `replaceHandler` to set the `VertxSniHandler.SERVER_NAME_ATTR` on the channel.

**Comment by vietj** [comment]
keep in mind this requires a later version than the actual netty version
