### ISSUE TITLE
Clustered Eventbus with dynamic port assignment

### ISSUE THREAD

**Issue by MazizEsa** [eclipse/vert.x#2236]
Hi all.

Is there any mechanism that vertx can handle when used in aws ECS if you decided to make the port mapping of the host port to be dynamic?

This is a must in order for the ECS service to be scalable.

**Comment by tsegismont** [comment]
The clustered event bus port is assigned randomly by default.

Please use the Vert.x user forum for questions (see http://vertx.io/community)
