### ISSUE TITLE
About Metrics using Dropwizard

### ISSUE THREAD

**Issue by vertxjava** [eclipse/vert.x#2237]
Can I monitor the status of my cluster using "Metrics using Dropwizard"?

**Comment by vietj** [comment]
yes : http://vertx.io/docs/vertx-dropwizard-metrics/java/

**Comment by vietj** [comment]
I think you should look more at how to do that from the Dropwizard Metrics side and report to a shared store

**Comment by vertxjava** [comment]
Thanks!
