### ISSUE TITLE
About kafka client.

### ISSUE THREAD

**Issue by vertxjava** [eclipse/vert.x#2238]
When I use vert.x kafka client,I can't send messages to Kafka, the code is as follows:
`Map<String, String> config = new HashMap<>();`
`config.put("bootstrap.servers", "192.168.237.128:9092,192.168.237.128:9093");`
`config.put("key.serializer", "org.apache.kafka.common.serialization.StringSerializer");`
`config.put("value.serializer", "org.apache.kafka.common.serialization.StringSerializer");`
`config.put("acks", "1");`
`KafkaProducer<String, String> producer = KafkaProducer.create(vertx, config);`
`KafkaProducerRecord<String, String> record = KafkaProducerRecord.create("topicReport", "test");`
        `producer.write(record, done -> {`
         `   if (done.succeeded()) {`
            `    RecordMetadata recordMetadata = done.result();`
           ` } else {`
          `  }`
      `  });`
`
Is there a Kafka version limit for the Kafka client using vert.x? thanks!

**Comment by tsegismont** [comment]
Please report your issue to https://github.com/vert-x3/vertx-kafka-client and include any other relevant info like error in the console.
