### ISSUE TITLE
add methods for byte arrays to rx lib

### ISSUE THREAD

**Issue by njleonzhang** [eclipse/vert.x#2243]
according to this [thread](https://groups.google.com/forum/#!topic/vertx/AhRW62sOAu0), methods for byte arrays are lacked in rx library. This cause lots of migration effort. Any plan to add this lost methods?

**Comment by vietj** [comment]
can you open this rather in the https://github.com/vert-x3/vertx-rx repository and attach examples ?

**Comment by vietj** [comment]
closing this as it's the wrong repo.
