### ISSUE TITLE
how much memory is being used when i open a new verticle?

### ISSUE THREAD

**Issue by anuger** [eclipse/vert.x#2245]
In a project, I started four verticle, is it normal to used 680+M memory?

**Comment by vietj** [comment]
@anuger tell us more about your verticles

**Comment by anuger** [comment]
@vietj 
one for static resource,one for timer,others for restful api

**Comment by vietj** [comment]
that seems unusually wrong, can you make an HEAP histogram using https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/tooldescr014.html 2.14.2 and post the result here ?

**Comment by anuger** [comment]
The reason seems to be that I used the cluster，thx @vietj

**Comment by vietj** [comment]
@anuger even for cluster usage it seems unusual

**Comment by anuger** [comment]
@vietj yes, When I restart the service, the memory is only occupied more than 100 M.However, with the increase in the number of requests, memory usage more and more until 600M,request just return the result of a sql.Because of this?
``` java
            if (res.failed()) {
                done.handle(Future.failedFuture(res.cause()));
            } else {
                done.handle(Future.succeededFuture(res.result()));
            }
```

**Comment by vietj** [comment]
have you inspected your heap ?

**Comment by anuger** [comment]
this is the result about 'jmap - histo'
[histo.txt](https://github.com/eclipse/vert.x/files/1574663/histo.txt)
