### ISSUE TITLE
Provide system property for native transport

### ISSUE THREAD

**Issue by EmadAlblueshi** [eclipse/vert.x#2253]
Currently, it seems the only way is programmatically. It would be very convenient to have system property to enable that  

```javascript
Vertx vertx = Vertx.vertx(new VertxOptions().
  setPreferNativeTransport(true)
);
```

**Comment by EmadAlblueshi** [comment]
I found it ` -Dvertx.options.preferNativeTransport=true`

**Comment by vietj** [comment]
this could be mentioned in the documentation

**Comment by EmadAlblueshi** [comment]
@vietj Yes it should
