### ISSUE TITLE
Missing bind failure callback in case of shared server round robin

### ISSUE THREAD

**Issue by rstrauss** [eclipse/vert.x#2257]
There's no way for a user to discover a bind exception occurred, except to crawl through the log.
See line 347 in   io.vertx.core.http.impl.HttpServerImpl.java

344          bindFuture = AsyncResolveConnectHelper.doBind(vertx, SocketAddress.inetSocketAddress(port, host), bootstrap);
345          bindFuture.addListener(res -> {
346            if (res.failed()) {
347              vertx.sharedHttpServers().remove(id);  <-------
348            } else {

If a BindException occurs, the server is removed, but the caller isn't notified.

The exceptionHandler(new BindException(host+":"+port)) should be called.
Yes, a BindException is thrown and caught already, 
but there's no way for the caller to discover it...

**Comment by vietj** [comment]
can you contribute a reproducer test and possibly a fix ?

**Comment by vietj** [comment]
The listen handler is actually notified in another block that listen to the actualServer.bindFuture that is the real physical bind. The listener you are referring to maintains the http server book keeping. If you expected is an issue with your setup, please make a reproducer and reopen this issue.
