### ISSUE TITLE
Stop chunked response when client disconnects

### ISSUE THREAD

**Issue by maltalex** [eclipse/vert.x#2266]
I'm playing around with vertx and vertx-web. I have a simple endpoint that produces a chunked response by endlessly printing "hello" once a second.

How do I detect when the client disconnects? Vertx doesn't seem to throw an exception when attempting to write to a disconnected client, and `routingContext.response().closed()` keeps returning false long after the client is gone.

Here's a minimal example, I'm using curl as the client:

	public static void main(String[] args) {
		Vertx vertx = Vertx.vertx();
		HttpServer server = vertx.createHttpServer();
		Router router = Router.router(vertx);
		router.route("/hello").handler(rc -> {
			rc.response().setChunked(true).putHeader("Content-Type", "text/plain");
			vertx.setPeriodic(1000, l -> {
				if (rc.response().closed()) {
                    System.out.println("Stopping"); //Doesn't happen
					vertx.cancelTimer(l);
				}
				try {
					System.out.println("hello"); // Keeps printing long after the client disconnects
					rc.response().write("hello\n");
				} catch (Exception e) {
					e.printStackTrace(); // Doesn't happen
					rc.response().close();
				}
			});

		});
		server.requestHandler(router::accept).listen(8080);
	}

I'm using Vert.x 3.5.0

**Comment by vietj** [comment]
it looks like a bug

**Comment by vietj** [comment]
can you reproduce without vertx web and a plain vertx http server ?

**Comment by maltalex** [comment]
Sure. Just try this:

	public static void main(String[] args) {
		Vertx vertx = Vertx.vertx();
		HttpServer server = vertx.createHttpServer();
		server.requestHandler(request -> {
			request.response().setChunked(true).putHeader("Content-Type", "text/plain");
			vertx.setPeriodic(1000, l -> {
				if (request.response().closed()) {
					System.out.println("Stopping");
					vertx.cancelTimer(l);
				}
				try {
					System.out.println("hello"); // Keeps printing long after the client disconnects
					request.response().write("hello\n");
				} catch (Exception e) {
					e.printStackTrace(); // Doesn't happen
					request.response().close();
				}
			});
		});

		server.listen(8080);
	}

**Comment by vietj** [comment]
now I think that the write should throw an IllegalStateException, can you try with the 3.5.1-SNAPSHOT ?

**Comment by vietj** [comment]
however not sure about request.response().closed()

**Comment by maltalex** [comment]
Yeah, the snapshot (commit 887f95e0dc00cf30151332e64d12a2299d85767b) seems to work correctly. 

The line `request.response().closed()` returns false when the client disconnects, and `request.response().write("hello\n");` throws an `IllegalStateException`. That exception is a bit unexpected since it's not really a state issue, but an I/O issue, so expected an IOException. But either way, its definitely an improvement. Thanks!

**Comment by vietj** [comment]
fixed in https://github.com/eclipse/vert.x/issues/2181 for the record

**Comment by maltalex** [comment]
Thanks. When is 3.5.1 due to appear?

**Comment by vietj** [comment]
in a few weeks, we are working on it

**Comment by maltalex** [comment]
Thank you.
I appreciate the work you guys are putting into the project.
