### ISSUE TITLE
Documentation for "Asynchronous Verticle start and stop" unclear

### ISSUE THREAD

**Issue by lonerzzz** [eclipse/vert.x#2267]
The documentation for the "Asynchronous Verticle start and stop" section in the core documentation does not clearly explain what is necessary to make the verticle deloyment work asynchronously making initial use of vertx more frustrating than need be, especially because it uses verticle deployment in the example making it self referencing.

I would suggest adding some vertx.executeBlocking() code to the start method in the example code and referencing the "Running blocking code" section to show how it is done to make it clearer to first time users.

**Comment by vietj** [comment]
I think we can use just an asynchronous timer instead that would be more clear

**Comment by vietj** [comment]
I've a patch with an HTTP server instead of children verticles
