### ISSUE TITLE
Why not find a template is an exception Why not 404

### ISSUE THREAD

**Issue by shenzhenMirren** [eclipse/vert.x#2282]
一月 18, 2018 7:19:00 下午 io.vertx.ext.web.impl.RoutingContextImplBase
严重: Unexpected exception in route
freemarker.template.TemplateNotFoundException: Template not found for name "templates.ftl".

**Comment by shenzhenMirren** [comment]
![qq 20180118194706](https://user-images.githubusercontent.com/24805209/35096772-665b0818-fc88-11e7-9f2d-d82a2a419ffd.png)
 **↑** Not found
![qq 20180118195154](https://user-images.githubusercontent.com/24805209/35096964-18269896-fc89-11e7-98b9-e82566adfa14.png)
 **↑** found
![qq 20180118195405](https://user-images.githubusercontent.com/24805209/35097042-5f96352e-fc89-11e7-9840-72444ebf4cab.png)
 **↑** error

**Comment by shenzhenMirren** [comment]
finally, use routeWithRegex("/statics/.*") solution

**Comment by shenzhenMirren** [comment]
and create statics under templates

**Comment by pmlopes** [comment]
400 errors are errors that happen from actions performed by the user. However if a template is missing it’s not really the end user’s fault.

Most of the times this is a developer issue so it should be a 500 class error. However you could catch it and convert it to what you want.

**Comment by pmlopes** [comment]
In your case you could use the engine directly instead of the handler. It gives you full control on which template to render and avoids the path manipulation and your need for regular expressions.

‘Engine.render’ is something to consider.

**Comment by vietj** [comment]
can you reopen this issue in vertx-web ?
