### ISSUE TITLE
 SQLConnection  batchWithParams did not work

### ISSUE THREAD

**Issue by XiaohuChen** [eclipse/vert.x#2285]
vertx-mysql-postgresql-client(3.5.0 version) 
OS: windows 10;

List<JsonArray> batch = new ArrayList<>();
JsonArray params = new JsonArray().add("val1").add("val2").add("val3");
batch.add(params);

SQLConnection connection = connect.result();
connection.batchWithParams("SQLQuery", batch, create -> {
System.out.println("batchWithParams");
connection.close();
});

As soon as the 'batchWithParams; method is called on SQLConnection, the event loop gets hanged, and no statements inside the handler are executed, and no exceptions are thrown. I'm facing similar issue while calling the 'batch' method of SQLConnection class as well.

I tried finding similar queries on this group, but couldn't find any relevant ones

**Comment by tsegismont** [comment]
Moved to the relevant repo
