### ISSUE TITLE
JsonObject: mapFrom misses some fields if the PoJo extends a Hashtable

### ISSUE THREAD

**Issue by acabarbaye** [eclipse/vert.x#2286]
Using swagger codegen to generate POJOs from an OpenAPI spec file, I obtain some objects of the following type:
```
...
public class MyClass extends HashMap<String, String> implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("name")
  private String name = null;

  public MyClass name(String name) {
    this.name = name;
    return this;
  }
...
```
When converting this particular object into a Vertx JsonObject (i.e. `JsonObject json = JsonObject.mapFrom(obj);`), only the key/value "fields" present in the hashtable are kept and not the extra fields present in my class e.g. name in the above example.

**Comment by vietj** [comment]
I think it's because the underlying code does:

```
new JsonObject((Map<String, Object>) Json.mapper.convertValue(obj, Map.class))
```

can you try with

```
new JsonObject((Map<String, Object>) Json.mapper.convertValue(obj, MyClass.class))
```

and see what you get ?

**Comment by acabarbaye** [comment]
Hi,

I think I did not describe the issue properly.
when doing this` JsonObject json = JsonObject.mapFrom(obj)` (or `new JsonObject((Map<String, Object>) Json.mapper.convertValue(obj, MyClass.class)`));
the underlying map of the json object is of MyClass type and actually has the extra fields such as name in addition to the fields present in the hashtable.

However, when I try to use any methods of a JsonObject to retrieve fields such as `get("key")`, `getString("key") `or `encode()`, it looks like the extra fields are not present.

To be clearer, when considering the example above, I get this:

```
MyClass obj = new MyClass();
obj.name("a name");
obj.put("a key", "a value");
obj.put("another key", "another value");
JsonObject json = JsonObject.mapFrom(obj);
System.out.println(json.encode());
System.out.println(jjson.getString("a key"));
System.out.println(json.getString("name"));
System.out.println(((MyClass ) json.getMap()).getName());
> {"another key":"another value","a key":"a value"}
> a value
> null
> a name 
```

**Comment by hradecek** [comment]
This is Jackson's mapper behavior, which isn't likely to be changed, I think, but there's opened discussion at https://github.com/swagger-api/swagger-codegen/issues/5187 about this (considered as bug).

**Comment by vietj** [comment]
thanks for the info @hradecek - will close this issue then

**Comment by acabarbaye** [comment]
I can confirm this is an underlying issue in Jackson (see example below).
However, I think it should still be mentioned in Vert.x documentation as a limitation. 
Currently, the documentation states that any object can be mapped from/to.

example:
```
public class TestJackson extends HashMap<String, String> implements Serializable {
    /**
     *
     */
    private static final long serialVersionUID = 1L;
    @JsonProperty("name")
    private String name = null;

    public TestJackson name(String name) {
        this.name = name;
        return this;
    }

    /**
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name
     *            the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /*
     * (non-Javadoc)
     *
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "TestJackson [name=" + name + ", values=" + values() + "]";
    }

    public static void main(String[] args) {
        try {
            TestJackson test = new TestJackson();
            ObjectMapper mapper = new ObjectMapper();
            test.name("a Name").put("a key", "a value");
            System.out.println(test);
            String json = mapper.writeValueAsString(test);
            System.out.println(json);
            TestJackson testFromJson = mapper.readValue(json, TestJackson.class);
            System.out.println(testFromJson);
            json = "{\"name\":\"a name\",\"a key\":\"a value\"}";
            testFromJson = mapper.readValue(json, TestJackson.class);
            System.out.println(testFromJson);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

```

Result:
```
TestJackson [name=a Name, values=[a value]]
{"a key":"a value"}
TestJackson [name=null, values=[a value]]
TestJackson [name=null, values=[a value, a name]]
```
