### ISSUE TITLE
Thread blocked

### ISSUE THREAD

**Issue by simonsunmm** [eclipse/vert.x#2296]
vertx 3.5.0 issue
public static void main(String[] args) {
        Vertx vertx = Vertx.vertx();
        log.debug("start call");
        vertx.executeBlocking(f->{
            try {
                for (int i =0 ; i< 10; i++){
                    Thread.sleep(10000);
                }
                f.complete();
            }catch (Exception e){
                f.fail(e);
            }
        },ar->{
            log.debug("start end {}",ar.succeeded());
        });
    }
13:12:01.907 [vertx-blocked-thread-checker] WARN  i.v.c.i.BlockedThreadChecker - Thread Thread[vert.x-worker-thread-4,5,main] has been blocked for 61988 ms, time limit is 60000
io.vertx.core.VertxException: Thread blocked

but use 3.3.3 version is ok

**Comment by luengnat** [comment]
That is expected. You are holding the thread for more than 60 seconds.
