### ISSUE TITLE
How can I get the *.ttf file？

### ISSUE THREAD

**Issue by anuger** [eclipse/vert.x#2297]
in my project, I can't get ttf file.
the response state is 403.
how can i do?

**Comment by anuger** [comment]
![image](https://user-images.githubusercontent.com/24793128/35424442-a121cc1e-028e-11e8-995d-bb766f9ec5ac.png)

**Comment by vietj** [comment]
this shold be opened in vertx-web project not in vertx core

**Comment by vietj** [comment]
or better ask on the vertx google group instead of using an issue tracker to ask questions
