### ISSUE TITLE
spring-boot-maven-plugin and 'Main-Verticle' are not working together.

### ISSUE THREAD

**Issue by smil2k** [eclipse/vert.x#2313]
Launcher is not using the Main-Verticle manifest header in case the Main-Class does not match with itself. I'm not certain about the intent of this check, but this causes this issue:
As spring-boot has its own JarLauncher, therefore it won't see itself there.

**Why use the spring-boot plugin?**
Shade puts everything together into to root. If there are some clashes, eg. resource files, then you need transformers. SB plugin creates a jar classloader for each embedded jars, multiple resources can be found without magic.
After creating the classloaders, the class under "Start-Class" will be started.

I'm certain, that vert.x should not be concerning about this in the Launcher. "Start-Class" is an implementation detail of a different world.

Maybe Laucher could be more lax about the main class/verticle when a manifest entry instructs it to do so. Or a vertx specific manifest entry would be able to override the checks for "Main-Class" to something else.

**Comment by tsegismont** [comment]
@smil2k the launcher/cli classes are extensible. Create your own `Launcher` class and override the `getMainVerticle` method:

```java
public class CustomLauncher extends Launcher {
  @Override
  protected String getMainVerticle() {
    return MyMainVerticle.class.getName();
  }
}
```

**Comment by smil2k** [comment]
This is what I wanted to omit: creating an application class per deployment. 

It would help much if the code which loads the verticle would be extracted and the decision not to use it would be in the getMainVerticle(), therefore the doGetMainVerticle could be reused in my custom one without much copy-pasting.

What do you think?

**Comment by tsegismont** [comment]
The customer launcher in https://github.com/eclipse/vert.x/issues/2313#issuecomment-363046327 was just an example. You could lookup your own Manifest entry. No copy-pasting.
