### ISSUE TITLE
Are there any limits for "lengthfieldbased" mode about RecordParser

### ISSUE THREAD

**Issue by Orioline** [eclipse/vert.x#2314]
I can see there are delimited and fixed size modes in RecordParser.java, but I could not find a parser which acts like `LengthFieldBasedFrameDecoder` in Netty;
I think I might achieve that by extending `RecordParser` or `Handler<Buffer>` interface, however, may I ask are there any limits about writing that decoder/Parser with Vert.x's `Buffer`? Thanks.

**Comment by tsegismont** [comment]
`RecordParser `currently doesn't support length-prefixed messages. There has been some demand recently, so we could add it.

In the meantime, take a look at this [answer ](https://stackoverflow.com/a/47557302/2133695) I wrote on Stackoverflow. The question was about an Rxified version, but you can use the `LengthPrefixedStream` as is.

**Comment by Orioline** [comment]
Got it, I'll try that. Thanks very much for your reply.

**Comment by vietj** [comment]
closing this issue, if there is need for new feature we should open an issue with a proper description
