### ISSUE TITLE
HTTPRequestValidationHandler addQueryParamWithPattern does not work

### ISSUE THREAD

**Issue by biolearning** [eclipse/vert.x#2315]
The following API does not work for the specified pattern, after trouble-shooting, the cause is - the pattern was not correctly set, instead, it was set as default value. I would like to join as contributor to solve this issue if possible.

- HTTPRequestValidationHandler addQueryParamWithPattern(String parameterName, String pattern, boolean required)

- this.addQueryParamRule(ParameterValidationRuleImpl.ParameterValidationRuleFactory  .createValidationRuleWithCustomTypeValidator(parameterName, ParameterTypeValidator.createStringTypeValidator
        (pattern), !required, false, ParameterLocation.QUERY));

- ParameterTypeValidator  createStringTypeValidator(Object defaultValue)

**Comment by vietj** [comment]
you need to open this issue on the https://github.com/vert-x3/vertx-web project
