### ISSUE TITLE
ContentType 'application/json; charset=UTF-8' was rejected by vertx validator

### ISSUE THREAD

**Issue by biolearning** [eclipse/vert.x#2316]
ContentType is required to be exactly equal with 'application/json' or 'application/xml', so our ContentType 'application/json; charset=UTF-8' was rejected with statusCode=400 and null failure Throwable object. 

It is better to change to startWith 'application/json' or 'application/xml', since it is very typical to append the charset in the ContentType.

I am willing to join as contributor to solve this if possible.

**Comment by vietj** [comment]
you need to open this issue on the vertx-web project https://github.com/vert-x3/vertx-web
