### ISSUE TITLE
Remote client IP call inside Docker container returns an internal IP

### ISSUE THREAD

**Issue by CharlieTapSonin** [eclipse/vert.x#2317]
Calling context.request().remoteAddress().host() returns an internal address, like 10.x.x.x, which is odd as the service is bound from port 80 on the host onto port 80 on the vertx server. This is essentially means I can't create an IP Whitelist for my service

**Comment by tsegismont** [comment]
The remote address of the underlying socket in this case is the address of your host on the Docker private network. This is not specific to Vert.x

If you want to create an IP Whitelist you should inspect the [X-Forwarded-For](https://en.wikipedia.org/wiki/X-Forwarded-For)
