### ISSUE TITLE
Is there an official changelog someplace?

### ISSUE THREAD

**Issue by maltalex** [eclipse/vert.x#2318]
There are ~240 commits between 3.5.0 and 3.5.1, is there a changelog someplace?

**Comment by HugoCrd** [comment]
I think it’s not live yet
You can find it here for now :
https://github.com/vert-x3/vertx-web-site/blob/37a3ee3fbaf8cd1abd230f5539cbb21f7477ae7c/src/site/blog/posts/releases/2018-02-05-vertx-3.5.1-release.md

**Comment by HugoCrd** [comment]
Well, sorry for the confusion. The above link says that release notes will be on Vert.x wiki ;)

https://github.com/vert-x3/wiki/wiki/3.5.1---Release-Notes

**Comment by vietj** [comment]
https://github.com/vert-x3/wiki/wiki/3.5.1-Release-Notes

**Comment by vietj** [comment]
the notes are not yet complete (the release has not yet been announced)

**Comment by maltalex** [comment]
Thanks!
