### ISSUE TITLE
Hazelcast cluster.xml JVM property usage documentation

### ISSUE THREAD

**Issue by StephenOTT** [eclipse/vert.x#2322]
Would be great to add the following type of documents for the hazelcast setup:

When using docker with a `-ha` or `cluster` you have typically set the `-cluster-host`.

The hazelcast cluster.xml file does not support ENV vars as per: https://github.com/hazelcast/hazelcast/issues/11676

But as per the `11676` issue, you can use JVM system properties:

so the `cluster.xml` file can look like:

```xml
...
    <interfaces enabled="true">
      <!-- <interface>10.10.1.*</interface> -->
      <interface>${INTERFACE_IP}</interface>
    </interfaces>
...
```

and your dockerfile can look like:

```dockerfile
...
WORKDIR $VERTICLE_HOME
ENTRYPOINT ["sh", "-c"]
CMD ["exec vertx run $VERTICLE_NAME -ha -cp $VERTICLE_HOME/* -cluster-host $INTERFACE_IP"]
```

and a docker-compose can look like:

```yaml
...
  worker_02:
    build: worker/.
    environment:
      - JAVA_OPTS=-Duser.timezone=America/Montreal -DINTERFACE_IP =${INTERFACE_IP}
...
```

and the `.env` file is:

```
# INTERFACE_IP is used in the Java_Opts below, which is then used in the cluster.xml file for hazelcast
INTERFACE_IP=127.0.0.1
```

env file is needed because of: https://github.com/docker/compose/issues/4189#issuecomment-274915631

happy to do a PR if i can get some direction of the best location to add this: (in the docker manual, hazelcast, HA, clustering, etc.

edit: cleanup of examples and naming
edit: in addition i think it helps to cleanup clarity around: http://vertx.io/docs/vertx-hazelcast/java/#_using_wrong_network_interface

reference example: https://github.com/hazelcast/hazelcast-code-samples/blob/master/hazelcast-integration/docker-compose/src/main/docker/hazelcast.yml

**Comment by tsegismont** [comment]
@StephenOTT the best location would be the `vertx-hazelcast` documentation.

Can you first reopen your issue in the right repo: https://github.com/vert-x3/vertx-hazelcast ? Thanks. We'll follow up there

**Comment by tsegismont** [comment]
(closing invalid, wrong repo)

**Comment by StephenOTT** [comment]
👍
