### ISSUE TITLE
vertx run's -conf <config_file> argument: Where does it stand in precedence?

### ISSUE THREAD

**Issue by StephenOTT** [eclipse/vert.x#2323]
https://github.com/eclipse/vert.x/blob/c79c698d2dc36f26245e4c390c0db755eb1a91fd/src/main/java/io/vertx/core/package-info.java#L928

http://vertx.io/docs/vertx-core/js/#_the_vertx_command_line

>-conf <config_file> - Provides some configuration to the verticle. config_file is the name of a text file containing a JSON object that represents the configuration for the verticle. This is optional.

http://vertx.io/docs/vertx-config/js/#_using_the_config_retriever

>By default the Config Retriever is configured with the following stores (in this order):
>- The Vert.x verticle config()
>
>- The system properties
>
>- The environment variables
>
>- A conf/config.json file. This path can be overridden using the vertx-config-path system property or VERTX_CONFIG_PATH environment variable.

Does the `-conf` argument count as the `A conf/config.json file.` location?

**Comment by cescoffier** [comment]
`-conf` is used to populate the (main) verticle `config()`

**Comment by StephenOTT** [comment]
thaks
