### ISSUE TITLE
Why is Vertx.addCloseHook/Vertx.removeCloseHook not exposed?

### ISSUE THREAD

**Issue by luengnat** [eclipse/vert.x#2327]
Vertx.addCloseHook/Vertx.removeCloseHook should be exposed via ```Vertx``` interface rather than  just ```VertxInternal``` interface so that we can allow some cleanup code to be executed when Vert.x is shutdown.

**Comment by vietj** [comment]
I think we can have something but exposed in a simpler manner, i.e simply a `closeHandler(Handler<Void>)`

**Comment by vietj** [comment]
feel free to make a PR for a simple Vert.x close handler.
