### ISSUE TITLE
Document that VertxOptions.setClustered is for internal usage

### ISSUE THREAD

**Issue by hasalex** [eclipse/vert.x#2328]
The javadoc explains almost nothing about VertxOptions.setClustered(boolean clustered) or EventBusOptions.setClustered(boolean clustered).

In fact, this option is not for public usage, as clustered mode has to be enabled by calling Vertx.clusteredVertx.

You should either lower the access to setClustered to "package" or add some explanations in the javadoc.

**Comment by vietj** [comment]
actually it's not really for internal usage, it's design for when you want to run a clustered vertx and programmatically set a cluster manager. it works also the same for MetricsOptions.

**Comment by hasalex** [comment]
It would be nice to have this explanation in the javadoc.
