### ISSUE TITLE
Launcher setClustered invalid

### ISSUE THREAD

**Issue by shenzhenMirren** [eclipse/vert.x#2332]
my VxApiLauncher is extends Launcher
in beforeStartingVertx i setting Clustered is true
but in afterStartingVertx or myVerticle clustered is false 
![cluster](https://user-images.githubusercontent.com/24805209/36972441-06b3e0d8-20aa-11e8-98ea-113dd67bc4bf.png)
vert.x version 3.5.1

**Comment by cescoffier** [comment]
Which version of Vert.x are you using?

Clement

**Comment by shenzhenMirren** [comment]
@cescoffier both version3.5.0 and 3.5.1 hava the same problem

**Comment by cescoffier** [comment]
Thanks, I will have a look.

**Comment by cescoffier** [comment]
Found the issue. In your code, you create a new `VertxOptions` object. You can't do this, you need to use the one that is passed as parameter. For instance, the following code is working:

```
package io.escoffier.demo;

import io.vertx.core.Launcher;
import io.vertx.core.Vertx;
import io.vertx.core.VertxOptions;

public class MyLauncher extends Launcher {

    public static void main(String[] args) {
        new MyLauncher().dispatch(args);
    }

   @Override
   public void beforeStartingVertx(VertxOptions options) {
       options.setClustered(true);
   }

   @Override
   public void afterStartingVertx(Vertx vertx) {
       System.out.println("Is vert.x clustered: " + vertx.isClustered());
   }
}
```
