### ISSUE TITLE
HttpClient send form with file upload

### ISSUE THREAD

**Issue by k-mack** [eclipse/vert.x#2339]
Creating an HTTP server to receive `multipart/form-data` requests with file uploads is as easy as adding the `BodyHandler.create()` handler to a Router's `route()`. It would be great to just as easily to create an HTTP client request that  _sends_ `multipart/form-data` with (one or more) file uploads.

This would be helpful for:

* Unit testing HTTP servers that can accept file uploads
* Uploading files to external services that require them to be sent using `multipart/form-data`

Currently, uploading files like this can be done with the HttpClient, but it takes much more work than writing an HTTP server that can accept file uploads. Thankfully, Vert.x has test code that can help users understand how to do this: https://github.com/eclipse/vert.x/blob/7798d8931f63bd4321a89e5d1349aa7f2d2f3bdd/src/test/java/io/vertx/test/core/HttpTest.java#L2542

This topic has also been briefly discussed on the Google user group:

* https://groups.google.com/forum/#!searchin/vertx/httpclient$20file$20upload%7Csort:date/vertx/IPBIRQkaM2w/mpfd4PAmAQAJ
* https://groups.google.com/forum/#!searchin/vertx/httpclient$20file$20upload%7Csort:date/vertx/yWqCleIg52E/eVE6ZAQKAwAJ

**Comment by vietj** [comment]
you should look at the Vert.x Web Client that shall rather do that and is provides a better API.

**Comment by k-mack** [comment]
Moved to vert-x3/vertx-web#862.
