### ISSUE TITLE
HttpClient: wrong poolSize option

### ISSUE THREAD

**Issue by gmagniez** [eclipse/vert.x#2342]
Hi,
in `HttpChannelConnector`, pool sizes are swapped between HTTP1/HTTP2:
```
this.http1Weight = client.getOptions().getHttp2MaxPoolSize();
this.http2Weight = client.getOptions().getMaxPoolSize();
```

**Comment by vietj** [comment]
this is actually normal (although it sounds weird),  the pool uses a weight mechanism to keep track of the number of connections, for instance if http2Size = 2 and http1Size= 5 : maxWeight = 10 and the http1Weight = 2 which means that the pool can contain maxWeight / http1Weight = 5 connections

**Comment by vietj** [comment]
that's a good idea yes

**Comment by vietj** [comment]
done
