### ISSUE TITLE
Make HttpClientRequest#host() returns the actual server origin of the request instead of the host header

### ISSUE THREAD

**Issue by marcust** [eclipse/vert.x#2346]
I was looking into metrics and wanted to group HTTP client request metrics by host. Unfortunately the original host is not easily accessible and before I PR something I wanted to point out that the whole host handling is somewhat confusing right now and start a discussion about naming. 

So `HttpClientRequestBase` has a `host` field, that will be populated in the constructor by the default host or the host from the actual request depending on the use case. Albeit it does not have a direct access method for it.

There is a protected `hostHeader()` method, that does depending on the ssl type of the request return the host or the host plus port. Otherwise the field is completely encapsulated and only used for the `absoluteURI` method. 

To make things a little confusing the `HttpClientRequestImpl` has a `getHost()` method that returns the content of the `hostHeader` field in that class. Furthermore it overrides the `hostHeader()` method to give precedence to this field, but that is still protected. 

My naive approach would have been to add a `getRawHost()` or `getBaseHost()` to `HttpClientRequestBase` but that feels fishy at least. Any suggestions?

**Comment by vietj** [comment]
actually the current `host()` on HttpServerRequest should be called `virtualHost()` rather and the `host()` should return the value of the server the connection is done.

**Comment by vietj** [comment]
right now I don't want to add a more confusing method to access the host value and I would rather correct this instead in a way that does not break.

**Comment by vietj** [comment]
you are right, that's something we should improve, calling this header `host` was not a good idea

**Comment by vietj** [comment]
I would be inclined to fix this in 3.6.0 event if it may break things. In practice people using this will parse the method to detect the colon and just get the part they are interested to, that's what Vert.x Web does in the virtual host handler:

```
      boolean match = false;
      for (String h : host.split(":")) {
        if (regex.matcher(h).matches()) {
          match = true;
          break;
        }
      }
```

**Comment by vietj** [comment]
in addition the vertx-web-client has an `host` on `HttpRequest` that is clearly the connecting host.

**Comment by vietj** [comment]
Actually all these names are very confusing :-)

**Comment by vietj** [comment]
at the same time I find also not incorrect to name it `host`

**Comment by vietj** [comment]
can you explain your use case ? it seems that you are actually implementing a Metrics SPI ?

**Comment by vietj** [comment]
now that I think about it, the host value is actually context: when creating a request (i.e connecting to a server) then host means the server to connect to, when dealing with the request, then host means the host header.

**Comment by marcust** [comment]
Hey @vietj, yes, I'm talking about the vertx-prometheus-metrics, or rather my fork of it. The original uses the full request URI as a metric label, which results in a lot of metrics and is somewhat not really useful, at least for my use-case. I guess it is great when you talk to some defined endpoints, but as soon as you have IDs in your URL it becomes messy. I have a vert.x based api facade and think metrics per backend host could actually be of value.

Having a host() accessor in a dot release would be enough for me. I can PR that tomorrow.

**Comment by vietj** [comment]
for now this would be confusing, what I'm inclined to have is this host field public (final) on HttpClientRequestBase and have you cast until we figure out the best thing to do in the future

**Comment by vietj** [comment]
alsos I think we need to think about upcoming socket unix domain support, how do you intent to handle this case ?

**Comment by marcust** [comment]
My rationale was more that a `host()` method would at least make it consistent on the `HttpClientRequestBase`, no? All the other things (`hostHeader()`, `getHost()`) are either `protected` or on the `HttpClientRequestImpl` which is not part of the interface. It is nicer than exposing a field, also from the maintenance point of view. 

I didn't have a look in the unix domain sockets yet, if you point me to code I'll have a look.

**Comment by marcust** [comment]
Actually, it has to go to the `HttpClientRequest` as well, because that is the overall interface. And then we are just stuck with the confusing `getHost()` method that can be renamed in the next major version as a breaking change. That looks like the cleaner migration path to me.

**Comment by vietj** [comment]
having both host() and getHost() would be very confusing API and I haven't figured out what would be the best thing to do since the _host_ name is overloaded (which is a source of confusion). My proposal requires you to cast HttpClientRequest to HttpClientRequestBase but has the benefit to be straightforward to implement and solves the issues immediately.

**Comment by marcust** [comment]
Ok, I can live with the casting, but can we at least still have an accessor method? I don't want to access the bare field....

**Comment by vietj** [comment]
sure thing

**Comment by vietj** [comment]
we can open up I think, it still remains impl

**Comment by marcust** [comment]
Ok
