### ISSUE TITLE
vertx reactive route debugging loosing information.

### ISSUE THREAD

**Issue by kevlarC** [eclipse/vert.x#2351]
The following is a debug statement from the router

Route matches: Route[ path:/internal/locationservice/v1/location/upload pattern:null handlers:[io.vertx.reactivex.ext.web.Route$1@6eb5570f] failureHandlers:[io.vertx.reactivex.ext.web.Route$4@472a4fc4] order:21 methods:[POST]]@1207255076

Note that the context of the handlers are totally lost so the debug statements are pointless.
This is due to the delegate mapping from io.vertx.reactivex.ext.web in io.vertx.reactivex.ext.web.Route.handler. The anonymous class removes the toString of the handler.

To make this relevant in the wrapping either 
1. remove the delegate wrapping here and put the handler directly into the router.
Or
2. make the anonymous class decorate the toString with the relevant handler.

This was found in the 3.5.2 release.

**Comment by tsegismont** [comment]
Sounds like a valid concern to me. But could you please move it over to
https://github.com/vert-x3/vertx-rx/ ?

Thank you!

**Comment by vietj** [comment]
@kevlarC can you reopen this issue in the vertx-rx repo ?
