### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by dinhnn** [eclipse/vert.x#2363]
https://github.com/eclipse/vert.x/blob/354abf0332a5218959c32f237b622bdfcd26faae/src/main/java/io/vertx/core/impl/DeploymentManager.java#L205

Need to catch as Throwable.
Explain: MavenVerticleFactory resolve "compile" scope only. MavenVerticleFactory will missing some runtime dependencies, NoClassDefFoundError will throw and this block can not catch it.
Console prints only "INFO: Resolving xxxxx.xxx"
 and nothing happen after that.No way know why application not run without debuging

**Comment by vietj** [comment]
can you provide a reproducer ?
