### ISSUE TITLE
How does the BlockedThreadChecker work?

### ISSUE THREAD

**Issue by KingWang93** [eclipse/vert.x#2371]
where BlockedThreadChecker call registerThread（VertxThread）?

**Comment by tsegismont** [comment]
It is called in `VertxThreadFactory`: https://github.com/tsegismont/vert.x/blob/a5790d57e00d68ba62ba7fe6524fdb967cc388c3/src/main/java/io/vertx/core/impl/VertxThreadFactory.java#L59
