### ISSUE TITLE
net client idle in ms

### ISSUE THREAD

**Issue by micou** [eclipse/vert.x#2376]
Hello,
I am using vertx redis and I need to idle timeout in less than a seconds. I am using Redis vertx and I have checked that NetClientImpl always call IdleStateHandler in a way that it will idle in seconds.

Do you support only TimeUnit.SECONDS for a specific reason ?

**Comment by micou** [comment]
Ok, I will implement it this week.

Thanks @vietj

**Comment by KowalczykBartek** [comment]
I guess that this ticket can be closed :)
