### ISSUE TITLE
CONTENT_LENGTH should be set in the end method not write

### ISSUE THREAD

**Issue by earezki** [eclipse/vert.x#2381]
I encountered a behaviour which looks weird when I was trying to create a seperate Handler that ends a Response. [For a reason!].

As a solution, I think we should write the headers only in the end method and if we're trying to and not while writing.

If you agree, let me know to create a PR.

Cheers

**Comment by vietj** [comment]
hi @earezki can you first create a test for this issue ?

**Comment by earezki** [comment]
It's not a real issue, but more of an improvement.
In the 'HttpServerResponseImpl', the CONTENT LENGTH header is set in the 'write' method with a value of "-1L" (as of version 3.5). Now, I think that the only way to add the content length to the headers, is if I explicitly put it in the response headers, or If I used 'end(DataType)', but If I write(Data) then end(), the CONTENT LENGTH is not updated (It keeps the old -1L).
what I suggest, is to elevate the logic of populating the headers to the end() method. Giving that we already have 'bytesWritten'.
What do you thibk?

**Comment by vietj** [comment]
any change of behavior should have a corresponding test

**Comment by earezki** [comment]
I don't fully understand how this currently works, non the less the how to enhance it.
I'll close this issue as It's not an issue,
If I'm able to fully understand this in the future, I'll re-open this.
Thx Julien.

**Comment by vietj** [comment]
sure
