### ISSUE TITLE
can Future restore？

### ISSUE THREAD

**Issue by anuger** [eclipse/vert.x#2384]
I had a method as:
``` java
public Function<JsonArray, Future<Void>> dbUpdate(String sql) {

        return params -> {
            return Future.<Void>future(ft -> {
                PGConnector.getAsyncClient().updateWithParams(sql, params, res -> {
                    if (res.failed() || res.result().getUpdated() != 1) {
                        ft.fail("db fail");
                    } else {
                        try {
                            ft.complete();
                        } catch (Throwable t) {
                            ft.fail("has exception");
                        }
                    }
                });
            });
        };
    }
```

When catch a exception， happend:
![image](https://user-images.githubusercontent.com/24793128/38592205-57502e5e-3d6d-11e8-8601-c3a28cb97d17.png)

* **how can i do? or is there any better way to write it?**

* **This will solve the problem, but it will be so bad**
![image](https://user-images.githubusercontent.com/24793128/38592387-5a50a9d4-3d6e-11e8-96e4-731d6266fee2.png)

**Comment by vietj** [comment]
it's not clear what you want to achieve
