### ISSUE TITLE
public interface VertxInternal exposes package private classes WorkerPool and WorkerExecutorImpl

### ISSUE THREAD

**Issue by diliuskh** [eclipse/vert.x#2385]
I'm trying to implement a wrapper for Vertx instance that would do some custom stuff before delegating to actual instance. Implementing only Vertx interface would not work(in some cases Vertx instance is casted to VertxInternal inside vertx libs).

**Comment by vietj** [comment]
can you provide a PR for this ?

**Comment by diliuskh** [comment]
@vietj sure.

**Comment by vietj** [comment]
can you just make a PR that exposes the types without introducing new types ?

**Comment by vietj** [comment]
i.e changing package visibility with a comment to say that's it's used for wrappers of VertxInternal

**Comment by diliuskh** [comment]
@vietj uploaded new version.
