### ISSUE TITLE
oAuth introspect token works only with POST url

### ISSUE THREAD

**Issue by MeiyappanKannappa** [eclipse/vert.x#2396]
Hi We are working to implement oAuth2 in our vertx application. We have configured path in while creating oAuth2Oauth and tokens are generated. When we try to introspect token using oauth2oauth.introspecttoken() method it throws error "405 Method not allowed". Reason is introspect token method fetches the introspect URL using POST. But our r provider is custom oauth provider and the validate URL is GET URL. 

So is it possible to provide http method as config to oAuth provider or can we create custom oauth provider. If so can anyone please refer a link for custom oAuth provider. Many thanks!

**Comment by pmlopes** [comment]
Out of curiosity which server is this? The server is clearly wrong as the RFC clearly states it should be a POST request: https://tools.ietf.org/html/rfc7662#section-2.1

**Comment by MeiyappanKannappa** [comment]
Hi Sorry, its my mistake. I used a wrong URL to validate the token. It works now :)
