### ISSUE TITLE
Can't capture javax.net.ssl.SSLHandshakeException when using HttpClient

### ISSUE THREAD

**Issue by nahuelmyob** [eclipse/vert.x#2400]
Can't capture javax.net.ssl.SSLHandshakeException when using HttpClient.

See the following snippet:
```
private val httpClient : HttpClient =
            this.vertx.createHttpClient(HttpClientOptions(HttpClientOptions()
                    .setSsl(true)
                    .setPemTrustOptions(PemTrustOptions().addCertPath("my-cert"))))

 suspend fun postIt(port : Int, host: String, requestUri: String, body : JsonObject,
                       token: String) = awaitEvent<HttpClientResponse> {
        this.httpClient.post(port, host, requestUri)
                .putHeader("Content-Type", "application/json")
                .putHeader("Authorization", "Bearer $token" )
                .handler(it)
                .end(body.toString())
    }
```

When using `postIt` method and `my-cert` does not match the cert in the server I get:
```
app           | Apr 19, 2018 4:15:01 AM io.vertx.core.http.impl.HttpClientRequestImpl
app           | SEVERE: javax.net.ssl.SSLHandshakeException: Failed to create SSL connection
app           | 2018-04-19 04:15:01.844 [vert.x-eventloop-thread-0] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
app           | io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
```
But this exception happens at Netty level apparently and I'm not able to capture it to report it to interested parties. 

Is there anyway to handle this exception? I'm also integrating the service with Prometheus but I don't see Vertx publishing any of these stats.

**Comment by nahuelmyob** [comment]
Sorry I made a mistake by clicking 'Close'.

**Comment by tsegismont** [comment]
Take a look at https://vertx.io/docs/vertx-lang-kotlin-coroutines/kotlin/#_getting_one_shot_asynchronous_results

I believe you should wrap the `postIt()` method invocation with a try/cacth block to get the exception.

>I'm also integrating the service with Prometheus but I don't see Vertx publishing any of these stats.

This is covered by a separate module: https://vertx.io/docs/vertx-micrometer-metrics/kotlin/

**Comment by vietj** [comment]
I think also you should get it with WebClient that provides a cleaner API for this matter
