### ISSUE TITLE
[issue][help help] read wrong audio data from HttpServerRequest.getFormAttribute. UTF8 will change illegal byte to EFBFBD.

### ISSUE THREAD

**Issue by wang990099** [eclipse/vert.x#2405]
[issue]
but we read wrong data from HttpServerRequest.getFormAttribute. UTF8 will change illegal byte to EFBFBD.

didn't find any method to read binary data from vertx HttpServerRequest like like getReader or others

Do you have any comments about this? thank you in advance

**Comment by tsegismont** [comment]
Please do not file the same issue in two different repos at the same time.

**Comment by tsegismont** [comment]
Duplicates vert-x3/vertx-examples#285
