### ISSUE TITLE
Cleanup expired HTTP client connection every second instead of milliseconds

### ISSUE THREAD

**Issue by oli-h** [eclipse/vert.x#2406]
https://github.com/eclipse/vert.x/blob/5945cd3aabbfad8ef8b79fab3fd0feca98f5ee35/src/main/java/io/vertx/core/http/impl/ConnectionManager.java#L62
starts a Timer with 1 _milli_-second delay to search for closeable/evictable connections.

Is it really required to do this so often? - Especially as we can define the keep-alive time only as whole seconds.

**Comment by vietj** [comment]
I think we should have a different value, I've seen your PR, I think it's ok to have 1 second as the default timeout value is 30 seconds for HTTP/1 and 60 for HTTP/2

**Comment by oli-h** [comment]
It would be more elegant to set the timer value in a smart way - i.e. look on all open connections in the pool, find the one with the nearest "to-be-closed" timestamp and set the timer accordingly.
Of course the timer then has to be cancelled and re-scheduled if another connection suddenly has to be closed earlier, e.g. when a http-Server suddenly says "Keep-Alive: timeout=1" on some other connection.

**Comment by vietj** [comment]
let's keep 1 second period for the entire HTTP client for now as it's very simple and let's have something smarter.
