### ISSUE TITLE
Datagram socket resolve hostname even on IP address 

### ISSUE THREAD

**Issue by ensirius** [eclipse/vert.x#2407]
We are sending packets directly to IP and noticed that it's trying to resolve hostname. https://git.io/vpmfI `addr.isUnresolved())` are always true.

**Comment by vietj** [comment]
can you explain why it does not work ?

**Comment by ensirius** [comment]
When you create `InetSocketAddress` object using static method `createUnresolved(host, port);` It's create an object with `addr` as null. If you look at `isUnresolved` it's just a boolean that checks if `addr` not null.

**Comment by ensirius** [comment]
bump

**Comment by vietj** [comment]
can you show some vertx core ?

**Comment by vietj** [comment]
you mean that we should fix this code to not resolve on IP addresses:

```
    InetSocketAddress addr = InetSocketAddress.createUnresolved(host, port);
    if (addr.isUnresolved()) {
      context.owner().resolveAddress(host, res -> {
        if (res.succeeded()) {
          doSend(packet, new InetSocketAddress(res.result(), port), handler);
        } else {
          handler.handle(Future.failedFuture(res.cause()));
        }
      });
    } else {
      // If it's immediately resolved it means it was just an IP address so no need to async resolve
      doSend(packet, addr, handler);
    }
```

**Comment by vietj** [comment]
I've looked an internally, the resolver will actually look if the host is an IP and in this case create a resolved IP address for it without a DNS lookup, so we actually should remove this code and it will work correctly. It is actually correct now but this code is unnecessary as the resolveAddress will actually be a synchronous resolution. See io.netty.resolver.dns.DnsNameResolver#doResolve method which has:

```
        final byte[] bytes = NetUtil.createByteArrayFromIpAddressString(inetHost);
        if (bytes != null) {
            // The inetHost is actually an ipaddress.
            promise.setSuccess(InetAddress.getByAddress(bytes));
            return;
        }
```

**Comment by vietj** [comment]
@ensirius beside this have you experienced undesired DNS lookup in practice ?

**Comment by vietj** [comment]
I've removed this unnecessary code in master
