### ISSUE TITLE
Feature - Provide a wrapping of an InputStream into a ReadStream<Buffer>

### ISSUE THREAD

**Issue by cazacugmihai** [eclipse/vert.x#2410]
This comes after [these](https://groups.google.com/forum/#!msg/vertx/XwgHFfC4vKI/yagj6jvRAgAJ) [discussions](https://groups.google.com/forum/?fromgroups#!searchin/vertx/inputstream$20pump%7Csort:date/vertx/x3VmUmtwIsQ/KRBZcWzTBAAJ).

@cescoffier already provided an implementation [here](https://github.com/wisdom-framework/wisdom/blob/master/core/wisdom-vertx-engine/src/main/java/org/wisdom/framework/vertx/AsyncInputStream.java).

Thank you!

**Comment by vietj** [comment]
open this rather in the vert-x3/issues repository thanks
