### ISSUE TITLE
HttpServerResponse::exceptionHandler not called when any HttpServerResponseImpl::headersEndHandler throws

### ISSUE THREAD

**Issue by osklyar** [eclipse/vert.x#2411]
Java, Vert.x 3.5.0

When an exception occurs within one of `HttpServerResponseImpl::headersEndHandler` this exception does not seem to be processed by `HttpServerResponse::exceptionHandler` and the response remains not ended. The following tests proves this on the example of an incorrect cookie (triggering an `IllegalArgumentException` in `cookie.encode()`), which leaves the server response in limbo:

	import java.util.concurrent.CompletableFuture;
	import java.util.concurrent.TimeUnit;
	import java.util.concurrent.TimeoutException;

	import org.junit.Rule;
	import org.junit.Test;
	import org.junit.rules.ExpectedException;

	import io.vertx.core.Vertx;
	import io.vertx.core.http.HttpClientOptions;
	import io.vertx.core.http.HttpServer;
	import io.vertx.core.http.HttpServerResponse;
	import io.vertx.ext.web.Cookie;
	import io.vertx.ext.web.Router;
	import io.vertx.ext.web.handler.CookieHandler;

	public class TestCookieException {

		@Rule
		public ExpectedException exception = ExpectedException.none();

		@Test
		public void withCookie_onNoException_responseEnded() throws Exception {
			onPortWithCookieValue(14352, "aPerfectlyValidCookieValue");
		}

		@Test
		public void withCookie_onEncodeException_responseNotEnded() throws Exception {
			// FIXME this should be the case: exception.expectMessage("Cookie value contains an invalid char");
			exception.expect(TimeoutException.class);
			onPortWithCookieValue(14353, "values with spaces are not supported");
		}

		private void onPortWithCookieValue(int port, String cookieValue) throws Exception {
			CompletableFuture<Void> responseEndedOnServer = new CompletableFuture<>();
			Vertx vertx = Vertx.vertx();
			Router router = Router.router(vertx);
			router.route()
				.handler(CookieHandler.create())
				.handler(ctx -> {
					Cookie cookie = Cookie.cookie("session", cookieValue);
					cookie.setPath("/");
					cookie.setMaxAge(3600);
					ctx.addCookie(cookie);

					HttpServerResponse response = ctx.response();
					response.endHandler(responseEndedOnServer::complete);
					response.exceptionHandler(responseEndedOnServer::completeExceptionally);
					response.setStatusCode(200).end();
				});

			CompletableFuture<HttpServer> serverStarted = new CompletableFuture<>();
			vertx
				.createHttpServer()
				.requestHandler(router::accept)
				.listen(port, "0.0.0.0", (s) -> serverStarted.complete(s.result()));
			HttpServer server = serverStarted.get(2, TimeUnit.SECONDS);

			vertx
				.createHttpClient(new HttpClientOptions().setDefaultHost("localhost").setDefaultPort(port))
				.get("/")
				.handler($ -> {})
				.end();

			try {
				responseEndedOnServer.get(2, TimeUnit.SECONDS);
			}
			finally {
				server.close();
			}
		}

	}

**Comment by vietj** [comment]
yes, that's expected, the response/request exception handler channels the exception from the socket and its protocol.

normally you should be able to get this exception on the Context#exceptionHandler rather

**Comment by osklyar** [comment]
@vietj  You mean `vertx.getOrCreateContext()`? This one is not request specific, so this means there is no way to cleanly complete the request with 500? All I want is to let the client know that there was some server-side exception in this case, is it possible?

**Comment by vietj** [comment]
I think then you should wrap your handlers with a try/catch block and act accordingly

**Comment by osklyar** [comment]
Ok, so I will need a custom implementation for the `CookieHandler/CookieHandlerImpl`, which is unfortunate, but acceptable.

**Comment by vietj** [comment]
@osklyar calling the http exception handler on this could create infinite callback loops if you exception handler fails itself

**Comment by vietj** [comment]
which CookieHandler are you refering to ?

probably the Vert.x Web CookieHandler shouldn't throw an exception and if that happens it means it's a bug in Vert.x Web

**Comment by osklyar** [comment]
Yes, that one, `CookieHandlerImpl` line 61 throws in `cookie.encode()`.

**Comment by vietj** [comment]
can you open this issue in vert.x web project https://github.com/vert-x3/vertx-web that the CookieHandlerImpl should handle the `cookie.encode()` errors and propagate an error in the Vert.x Web router

**Comment by osklyar** [comment]
Will do later today.

**Comment by gmuecke** [comment]
What about using a failureHandler on the route?

     Router router = Router.router(vertx);
      router.route()
                .handler(CookieHandler.create())
                .handler(ctx -> {
      ...
      }).failureHandler(ctx -> {
         System.out.println("Failure occured");
         responseEndedOnServer.completeExceptionally(ctx.failure());
      });

The failure handler is triggered by the IllegalArgumentException cookie.encode()

**Comment by vietj** [comment]
I think it should work but it's in vertx-web project :-)

**Comment by vietj** [comment]
@gmuecke I think @osklyar is reporting a bug in Vert.x Web `CookieHandlerImpl` where the error cannot be rerouted via the vertx web router
