### ISSUE TITLE
Possible deadlock when trying to get multiple locks

### ISSUE THREAD

**Issue by nolequen** [eclipse/vert.x#2418]
Here is the code, which illustrates the problem.
The `Consumer` verticle acuires `lock1` and gets stuck.
I have reproduced the same problem using `HazelcastClusterManager` and `IgniteClusterManager`.

```java
    Vertx.clusteredVertx(
        new VertxOptions().setClusterManager(new HazelcastClusterManager()),
        result -> {
          final Vertx vertx = result.result();

          final int messagesToSend = 10;

          final Consumer consumer = new Consumer();
          vertx.deployVerticle(
              consumer,
              new DeploymentOptions(),
              event -> {
                if (event.succeeded()) {
                  vertx.deployVerticle(
                      new Supplier(messagesToSend),
                      new DeploymentOptions()
                  );
                }
              }
          );

          vertx.setTimer(
              messagesToSend * DEFAULT_LOCK_TIMEOUT,
              timer -> {
                final long failsNumber = messagesToSend - consumer.counter.sum();
                if (failsNumber != 0) {
                  System.err.println("Failed to get " + failsNumber + " locks");
                }
                vertx.close();
              }
          );
        }
    );
```

```java
  class Supplier extends AbstractVerticle {
    private final long messagesToSend;

    public Supplier(long messagesToSend) {
      this.messagesToSend = messagesToSend;
    }

    @Override
    public void start() {
      final LongAdder sent = new LongAdder();
      vertx.setPeriodic(1, timer -> {
        vertx.eventBus().send(TEST_ADDRESS, "message");
        sent.increment();
        System.out.println(sent.sum() + " messages sent");
        if (sent.sum() >= messagesToSend) {
          vertx.cancelTimer(timer);
        }
      });
    }
  }
```

```java
class Consumer extends AbstractVerticle {
    private final LongAdder counter = new LongAdder();

    @Override
    public void start(Future<Void> startFuture) {
      vertx.eventBus().consumer(
          TEST_ADDRESS,
          event -> {
            vertx.sharedData().getLock("lock1", lock1 -> {
              if (lock1.failed()) {
                System.out.println("Failed to get lock1: " + lock1.cause());
              } else {
                System.out.println("Succeeded to get lock1");
                vertx.sharedData().getLock("lock2", lock2 -> {
                  if (lock2.failed()) {
                    System.out.println("Failed to get lock2: " + lock2.cause());
                  } else {
                    System.out.println("Succeeded to get lock2");
                    counter.increment();
                    System.out.println(counter.sum() + " messages consumed");
                    lock2.result().release();
                  }
                  lock1.result().release();
                });
              }
            });
          }
      ).completionHandler(startFuture);
    }
  }
```

**Comment by tsegismont** [comment]
This is not a bug. Vert.x locks are not reentrant. In practice, they are
implemented as a semaphore with a single permit.

**Comment by nolequen** [comment]
It's ok that the locks are not reentrant.
In any case Consumer should not get stuck, it might and should get the lock2 after lock1 was acquired (when first message is received), but this doesn't happen because of other locks in queue.

**Comment by tsegismont** [comment]
@nolequen right, I misunderstood the problem. Actually it's because lock acquisition is ordered on the internal blocking executor so if they are pending lock requests (for any lock), new requests have to wait for completion. Nice catch

**Comment by vietj** [comment]
to be sure to understand, does this problem happen with clustered event bus consumer or is it independent, i.e the reproducer could just be a dual lock acquisition ?

**Comment by vietj** [comment]
it seems independant of event bus.

looking at it, indeed it seems related to execute blocking because we are running into a self deadlock due to ordering.

perhaps we need to introduce a task queue per lock

**Comment by vietj** [comment]
@tsegismont I think we need a little discussion on this and in general usage of execute blocking in cluster manager :-)

**Comment by vietj** [comment]
we actually need to maintain ordering per resource to avoid concurrent modification of this resource because the API are blocking and because we don't want to have race conditions (i.e modify twice the same hazelcast or whatever building block) or use non blocking APIs

**Comment by tsegismont** [comment]
> to be sure to understand, does this problem happen with clustered event bus consumer or is it independent, i.e the reproducer could just be a dual lock acquisition ?

@vietj it's independent, it happens if you try to acquire a lock on the same context while there are pending lock requests

**Comment by vietj** [comment]
yes @tsegismont gotcha after looking at the reproducer in practice

**Comment by tsegismont** [comment]
> perhaps we need to introduce a task queue per lock

@vietj this is getting a little carried away :)

I believe ordering was used originally so that a user can write:

```java
sharedData.getLock("lock1")
sharedData.getLock("lock2")
```

And get the locks in order. Or am I missing something?

I believe that we should simply stop trying to guarantee order. The proper way to get two locks in order is to try acquiring lock2 when lock1 has been acquired:

```java
sharedData.getLock("lock1", onSuccess -> {
  sharedData.getLock("lock2", ...)
})
```

**Comment by vietj** [comment]
I disagree with you @tsegismont : we need to find the most appropriate thing to do, wether it's to keep what is currently in place, change it or remove like you said ordering.

**Comment by vietj** [comment]
order is important because this is what allows you to reason about things

**Comment by tsegismont** [comment]
>I disagree with you @tsegismont : we need to find the most appropriate thing to do, wether it's to keep what is currently in place, change it or remove like you said ordering.

Not sure what you mean. I totally agree with this statement. I'm just saying that, imo the most appropriate thing to do is to remove ordering.

>order is important because this is what allows you to reason about things

That's pretty general. Can you explain how it applies to this particular problem?

**Comment by tsegismont** [comment]
>I'm just saying that, imo the most appropriate thing to do is to remove ordering.

I mean, remove ordering in executeBlocking invocation. Locks should be acquired in order to avoid deadlocks. So this makes sense:

```java
sharedData.getLock("lock1", onSuccess -> {
  sharedData.getLock("lock2", ...)
})
```

**Comment by vietj** [comment]
@tsegismont at which level ? in locks ? for hazelcast implementation ? for all implementation ?

yes that's general, i.e if the user send 2 messages on the event on an address then the 2 messages will be received in order by the consumer, which allows to reason about this and create interactions between the producer and the consumer, etc...

**Comment by vietj** [comment]
@tsegismont if you are speaking at lock level, then the question is : do we need ordering when using the various APIs ? i.e what happens when you have a concurrent lock acquisition in the same VM by two threads with Hazelcast, Infinispan, etc...

**Comment by vietj** [comment]
@tsegismont my initial thought would be to have ordering per lock which solve the issue we are encountering now and avoid to handle race conditions at the API level (i.e have a Map<String, TaskQueue> of temporary entries in the cluster manager like we do have for concurrent multimap lookup).

**Comment by tsegismont** [comment]
> @tsegismont at which level ? in locks ? for hazelcast implementation ? for all implementation ?

Our comments crossed. I meant remove ordering in executeBlocking invocation. So:

```java
ContextInternal context = (ContextInternal) vertx.getOrCreateContext();
// Ordered on the internal blocking executor
context.executeBlockingInternal(fut -> {
  ISemaphore iSemaphore = hazelcast.getSemaphore(LOCK_SEMAPHORE_PREFIX + name);
  // ...
}, resultHandler);
```

becomes:

```java
vertx.executeBlocking(fut -> {
  ISemaphore iSemaphore = hazelcast.getSemaphore(LOCK_SEMAPHORE_PREFIX + name);
  // ...
}, false, resultHandler);
```
>yes that's general, i.e if the user send 2 messages on the event on an address then the 2 messages will be received in order by the consumer, which allows to reason about this and create interactions between the producer and the consumer, etc...

I see the point for messaging. But not for locking.

> @tsegismont if you are speaking at lock level, then the question is : do we need ordering when using the various APIs ? i.e what happens when you have a concurrent lock acquisition in the same VM by two threads with Hazelcast, Infinispan, etc...

We don't need ordering when invoking HZ or ISPN objects.

> @tsegismont my initial thought would be to have ordering per lock which solve the issue we are encountering now and avoid to handle race conditions at the API level (i.e have a Map<String, TaskQueue> of temporary entries in the cluster manager like we do have for concurrent multimap lookup).

This is what I would like to avoid. This would increase complexity for a benefit which I can't really see in the case of locks.

**Comment by vietj** [comment]
@tsegismont gotcha, so I guess we need to test this concurrent behavior as well inside the same JVM

**Comment by tsegismont** [comment]
@vietj there are tests already for locks acquired concurrently:

- in different vert.x clustered instances
- in the same clustered instance

Is that what your were thinking about?

**Comment by vietj** [comment]
This code (from HZ, but same for others) is serialized, i.e `hazelcast.getSemaphore(...)` is serialised (i.e there is no concurrent executions by two threads)

```
    context.executeBlocking(fut -> {
      ISemaphore iSemaphore = hazelcast.getSemaphore(LOCK_SEMAPHORE_PREFIX + name);
      ....
    }, resultHandler);
```

if we do remove ordering then the cluster manager will run concurrent lock acquisition on the cluster manager. We need to ensure this case is handled.
