### ISSUE TITLE
io.vertx.core.buffer.Buffer tightly coupled with io.netty.buffer.ByteBuf

### ISSUE THREAD

**Issue by Melozzola** [eclipse/vert.x#2425]
The ```Buffer``` interface is tightly coupled with the netty ```ByteBuf```. IMO this is an unfortunate design and the ```Buffer``` should be completely third-party classes agnostic.
The default implementation offered by Vert.x could rely on the netty ```ByteBuf``` (essentially wrapping it), but other implementations should be allowed without using the ```ByteBuf```

**Comment by vietj** [comment]
what would be the benefit ?

there is currently a Buffer factory in vertx, you can have a buffer backed by something else than ByteBuf but it needs to be able to return a bytebuf for internal operations

**Comment by vietj** [comment]
I will close this issue, if there is a real concern, come discuss on vertx-dev google group.
