### ISSUE TITLE
Behavior when clustered Vertx instance crashes and Lock is acquired

### ISSUE THREAD

**Issue by pekajota** [eclipse/vert.x#2427]
I'm using Vertx with Hazelcast as the cluster manager and I am stuck with a problem on how to deal with the situation where a Vertx node acquires a lock and crashes right after it. As no body else will be able to acquire that Lock, there is no way to release it with without recycling the cluster. Is that the expected behavior or am I missing something? Will Hazelcast deal with a crashing node that's holding a Lock?

**Comment by vietj** [comment]
@tsegismont any idea ?

**Comment by tsegismont** [comment]
In the Hazelcast cluster manager, locks are implemented as a Hazelcast semaphore with single permit. When a node goes down, Hazelcast release any permit it may have acquired. In other words, other Vert.x nodes may acquire the lock.
