### ISSUE TITLE
Missing @Nullable annotations

### ISSUE THREAD

**Issue by tsegismont** [eclipse/vert.x#2434]
Building this list so that we can track any missing `@Nullable` annotation until 3.6 is released

[ ] `Vertx.executeBlocking`

[ ] `Context.executeBlocking`

[ ] `WorkerExecutor.executeBlocking`

[ ] `AsyncMap.get`
[ ] `AsyncMap.putIfAbsent`
[ ] `AsyncMap.remove`
[ ] `AsyncMap.replace`

------ _Original comment_

Currently, the `executeBlocking` result handler type is not annotated with `@Nullable`.

As a result, the generated Rxified API returns a `Single<T>`. But it's quite common to use `Future<Void>` for a blocking task which does not need to return any result.
Then if the user simply invoke `future.complete()`, the program fails at runtime.

As a workaround, the user can use a `Future<Object>` and invoke `complete()` with any non-null value.

**Comment by tsegismont** [comment]
@vietj there's a similar issue with `AsyncMap.get`, `AsyncMap.putIfAbsent` and `AsyncMap.remove`. Should I create another issue or rename this one?

**Comment by vietj** [comment]
I think a single issue to fix all missing `@Nullable` is good
