### ISSUE TITLE
Use of system properties to configure cluster settings is not documented

### ISSUE THREAD

**Issue by chefhoobajoob** [eclipse/vert.x#2452]
When using the command line or launcher API to launch vertx, it is possible to use system properties to configure values for the cluster properties found on [the VertxOptions class](https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/VertxOptions.java#L270), but there is no [public documentation](https://vertx.io/docs/vertx-core/java/#_the_vertx_command_line) describing the naming convention for these properties.

There is a brief sentence indicating that it is possible to use system properties, but with no description of what the property names are:

> You can also set system properties using: -Dkey=value

**Comment by tsegismont** [comment]
The system properties used to setup clustering are deprecated and should no longer be used. This is why they are not advertised any more.

See https://github.com/eclipse/vert.x/blob/3ed3fea53990e31bdf63762c0bd67f1a0a5d6dc3/src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java#L281-L282
