### ISSUE TITLE
ClosedChannelException occurs when writing

### ISSUE THREAD

**Issue by jg513** [eclipse/vert.x#2459]
I'm building a server with Vert.x 3.5.1, after I use `setIdleTimeout()` to setup a idle timeout for some sockets, sockets will be closed by timeout. I keep writing to the sockets continuously,  some sockets may throw `java.nio.channels.ClosedChannelException`.

```
五月 17, 2018 10:33:08 下午 io.vertx.core.net.impl.ConnectionBase
严重: Unhandled exception
java.nio.channels.ClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
```

Here's what I have tried, the exception may be thrown.
- I wrote to sockets by `write()` method from other workers continuously, stop when `endHandler` or `closeHandler` invoked.
- I tried to send buffer to `WriteHandlerId` through EventBus. When a socket is closed, the `WriteHandlerId` will automatically unregisterd.
- I tried with `WebSocket` and `Socket`, they both throw the exception.

How to avoid this exception?

**Comment by vietj** [comment]
can you try with the 3.5.2.CR1 release ?

**Comment by jg513** [comment]
@vietj I tried several times with 3.5.2.CR1, and the exception never occurs. Thanks!
