### ISSUE TITLE
Add ability to set queueing strategy for WorkerPool

### ISSUE THREAD

**Issue by fzakaria** [eclipse/vert.x#2465]
At the moment the _workerPool_ in _VertxImpl_ is initialized as follows:

```java
ExecutorService workerExec = Executors.newFixedThreadPool(options.getWorkerPoolSize(),
        new VertxThreadFactory("vert.x-worker-thread-", checker, true, options.getMaxWorkerExecuteTime()));
```

This creates an underlying _ThreadPoolExecutor_ with an unbounded _LinkedBlockingQueue_
When our HTTP server is under immense load the queue grows which causes our latencies to grow unbounded.
We would prefer to fail fast or at least set a fixed size for the worker queue.

How do you feel about a new _VertxOptions#workerPoolQueueCapacity_ ?
I could provide the accompanying PR as well.

**Comment by vietj** [comment]
what would be then the behavior ? rejecting tasks ?

if you create too many worker pool tasks, it means that you should size the capacity of the traffic to a smaller value (for instance accepting less HTTP requests and use some kind of rate limiting)

**Comment by fzakaria** [comment]
I think a reasonable solution might be to reject tasks vs. growing a queue completely unbounded.
(At the very least allow the application to decide)
The max length of the queue is a form of rate limit/traffic control, so it seems useful to be able to instrument the value/rejection policy.

**Comment by vietj** [comment]
@fzakaria fine, it's important to have such guards when you need it and protect the application when resources are low.

**Comment by fzakaria** [comment]
I'm not trying to arm wrestle into having you believe me @vietj. 
I'm running a large service on vert.x and noticed we go into quite the death spiral when worker thread queue grows insane. 
We'd like to implement other traffic coming troll solutions but in the meantime placing a hard limit on the queue depth will give more consistent latency.

**Comment by fzakaria** [comment]
I've created an attached pull-request with a potential solution.
