### ISSUE TITLE
some dependence does not contain version such as netty in pom.xm

### ISSUE THREAD

**Issue by dingaiminGIT** [eclipse/vert.x#2483]
clone project down my local,but some dependence dose not have contain version suan as netty in pom.xml

[ERROR]     'dependencies.dependency.version' for io.netty:netty-common:jar is missing. @ line 77, column 17
[ERROR]     'dependencies.dependency.version' for io.netty:netty-buffer:jar is missing. @ line 81, column 17
[ERROR]     'dependencies.dependency.version' for io.netty:netty-transport:jar is missing. @ line 85, column 17
[ERROR]     'dependencies.dependency.version' for io.netty:netty-handler:jar is missing. @ line 89, column 17
[ERROR]     'dependencies.dependency.version' for io.netty:netty-handler-proxy:jar is missing. @ line 93, column 17
[ERROR]     'dependencies.dependency.version' for io.netty:netty-codec-http:jar is missing. @ line 97, column 17
[ERROR]     'dependencies.dependency.version' for io.netty:netty-codec-http2:jar is missing. @ line 101, column 17
[ERROR]     'dependencies.dependency.version' for io.netty:netty-resolver:jar is missing. @ line 105, column 17
[ERROR]     'dependencies.dependency.version' for io.netty:netty-resolver-dns:jar is missing. @ line 109, column 17
[ERROR]     'dependencies.dependency.version' for io.netty:netty-transport-native-epoll:jar is missing. @ line 113, column 17
[ERROR]     'dependencies.dependency.version' for io.netty:netty-transport-native-kqueue:jar is missing. @ line 118, column 17
[ERROR]     'dependencies.dependency.version' for com.fasterxml.jackson.core:jackson-core:jar is missing. @ line 125, column 17
[ERROR]     'dependencies.dependency.version' for com.fasterxml.jackson.core:jackson-databind:jar is missing. @ line 129, column 17
[ERROR]     'dependencies.dependency.version' for io.vertx:vertx-codegen:jar is missing. @ line 161, column 17
[ERROR]     'dependencies.dependency.version' for io.vertx:vertx-docgen:jar is missing. @ line 166, column 17

**Comment by vietj** [comment]
make sure you have vertx dependencies (which are snapshots) in your maven repo.

you can add sonatype oss repository to your settings to help this : https://stackoverflow.com/questions/7715321/how-to-download-snapshot-version-from-maven-snapshot-repository
