### ISSUE TITLE
Internal references to local Locks taken using SharedData.getLock() are not cleaned up

### ISSUE THREAD

**Issue by dano** [eclipse/vert.x#2484]
Every time a unique lock name is taken via `SharedData.getLock(...)`, it gets added to a Map inside of `SharedDataImpl`. Currently, entries added to this Map are never removed, even if all references to the lock have been released, and there are no pending waiters. This means the Map can grow infinitely if an application takes locks using generated names, rather than hard-coded ones. To avoid this, entries could be removed from the internal map at the point the lock is released, as long as there are no pending waiters.

**Comment by tsegismont** [comment]
@dano nice catch

**Comment by dano** [comment]
@vietj @tsegismont Thanks for the fix! Will this be backported to 3.5.3?

**Comment by vietj** [comment]
yes it should be

**Comment by tsegismont** [comment]
@vietj will you take care of it?

**Comment by vietj** [comment]
sure
