### ISSUE TITLE
Websocket client and server don't send back close frame in closing handshake 

### ISSUE THREAD

**Issue by upwell** [eclipse/vert.x#2486]
### Issue
While using vertx to implement a websocket server, certain websocket client library (okhttp) got failure callback when closing the websocket from its side.

### Finding
After doing a package capture, I found vertx didn't respond a __CLOSE__ frame after receiving one. This behavior doesn't follow the RFC.

https://github.com/eclipse/vert.x/blob/e69a81a039400af76b256a55b38d8b65c3b07ca1/src/main/java/io/vertx/core/http/impl/HttpServerImpl.java#L695-L703

I checked vertx source code, and did some debug. I believe there is a __bug__ at Line __699__. From the comment, these lines of code intend to `Echo back close frame`. 
 
Actually the Line 699 would always fail.
```
ch.writeAndFlush(wsFrame).addListener(ChannelFutureListener.CLOSE); 
```

After adding some debug code there, it actually throws the following exception. The `wrFrame` cannot be passed to `writeAndFlush` directly.

```
java.lang.UnsupportedOperationException: unsupported message type: WebSocketFrameImpl (expected: ByteBuf, FileRegion)
	at io.netty.channel.nio.AbstractNioByteChannel.filterOutboundMessage(AbstractNioByteChannel.java:266)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:877)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1371)
```

### Solution

Change Line 699 to the following code solves the issue.
```
ch.writeAndFlush(new CloseWebSocketFrame(wsFrame.closeStatusCode(), 
    wsFrame.closeReason())).addListener(ChannelFutureListener.CLOSE);
```

**Comment by vietj** [comment]
can you explain how to reproduce this ?

**Comment by upwell** [comment]
Reproduce steps:
1. Do packet capture with `wireshark` or `tcpdump`;
2. Client connect to web socket server implemented by vertx;
3. On client web socket side, call `close` which would trigger a `CLOSE` type frame to server.
4. Stop packet capture
5. From packet capture, vertx server didn't echo `CLOSE` type frame back to client as expected. It just finished the tcp connection.

From code side, change Line 699 to the following debug code.  

```java
ChannelFuture future = conn.channel().writeAndFlush(wsFrame);
future.addListener(ChannelFutureListener.CLOSE);
if(!future.isSuccess()) {
  future.cause().printStackTrace();
}
```

After a client side close the web socket and a `CLOSE` frame was received. The `future.cause().printStackTrace();` would always output the following exception:

```
java.lang.UnsupportedOperationException: unsupported message type: WebSocketFrameImpl (expected: ByteBuf, FileRegion)
	at io.netty.channel.nio.AbstractNioByteChannel.filterOutboundMessage(AbstractNioByteChannel.java:266)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:877)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1371)
```

Hope this would help.

**Comment by vietj** [comment]
this should help thanks

**Comment by vietj** [comment]
yes now the issue is obvious :-) , thanks for pointing out
