### ISSUE TITLE
Deploying HelloWorld Verticle in OpenShift v3.7.46 ThreadDumps

### ISSUE THREAD

**Issue by gpthome** [eclipse/vert.x#2492]
Thought I would start with this group, but it may be more of an OpenShift issue.

We are seeing threads block deploying the simplest of applications.  We are new to Vertx, so it could be how we have something configured in the Dockerfile.  Attached is the console dump from the OpenShift pod, and the Dockerfile we use to build the image (we do not use fabric8 yet to deploy to our main OpenShift clusters).

OpenShift Master: v3.7.46
Kubernetes Master: v1.7.6+a08f5eeb62
Vertx Maven Version: 3.5.2.CR3

I can run the same, generated container locally in Docker (version 18.03) on CentOs without seeing these issues.

Thanks for any help.
[threaddump-20180608.txt](https://github.com/eclipse/vert.x/files/2086487/threaddump-20180608.txt)

[Dockerfile.txt](https://github.com/eclipse/vert.x/files/2086491/Dockerfile.txt)

**Comment by vietj** [comment]
hi, the most appropriate is that you write to the vertx google group and ask your question here https://groups.google.com/forum/#!forum/vertx
