### ISSUE TITLE
vertx-jdbc-client 

### ISSUE THREAD

**Issue by wang007** [eclipse/vert.x#2497]
hi,  Today I went to see  vertx-jdbc-client and found a problem,  all get connectin and execute sql in the same thread，especially only one thread.  
code in theJDBCClientImpl  302 line，version 3.5.1

synchronized ExecutorService exec() {
      if (exec == null) {
        exec = new ThreadPoolExecutor(1, 1,
            1000L, TimeUnit.MILLISECONDS,
            new LinkedBlockingQueue<>(),
            (r -> new Thread(r, "vertx-jdbc-service-get-connection-thread")));
      }
      return exec;
    }

**Comment by vietj** [comment]
actually this is only the connection acquisition, this won't execute SQL.
