### ISSUE TITLE
NetServer bootstrap should set SO_LINGER option on the child channel instead of the server channel

### ISSUE THREAD

**Issue by DirkSchnell-zanox** [eclipse/vert.x#2498]
Hello.

If we use setSoLinger we only get:
`WARN i.n.b.ServerBootstrap [vert.x-eventloop-thread-7] Unknown channel option 'SO_LINGER' for channel`

Code right now is:
https://github.com/eclipse/vert.x/blob/357af84886367ef31dc61f00a646e6455f1ac8c8/src/main/java/io/vertx/core/net/impl/transport/Transport.java#L214-L216

According to [https://github.com/mrniko/netty-socketio/issues/481](url) it looks like that it should be like this:

```Java
if (options.getSoLinger() != -1) {
      bootstrap.childOption(ChannelOption.SO_LINGER, options.getSoLinger());
}
```

Hope somebody can help on this.

**Comment by vietj** [comment]
that's right thanks

**Comment by vietj** [comment]
actually I belive you are pointing the wrong line it should rather be:

https://github.com/eclipse/vert.x/blob/357af84886367ef31dc61f00a646e6455f1ac8c8/src/main/java/io/vertx/core/net/impl/transport/Transport.java#L237

**Comment by DirkSchnell-zanox** [comment]
Tthanks for your fast fix and response.
