### ISSUE TITLE
Initial Connection Pool on HttpClient

### ISSUE THREAD

**Issue by rkbalgi** [eclipse/vert.x#2512]
Currently, Vertx HttpClientOptions  only has a max limit on a HttpClient pool (both HTTP/1 and HTTP/2). Connections are opened only under a certain load. Is it possible to start the HttpClient with a initial number of connections?
The motivation for this comes from running applications in a Kubernetes environment where the HttpClient is trying to hit a service cluster. In my case only one of the pods is getting connected to while the rest sit idle.

**Comment by vietj** [comment]
connections are opened only when required, so under any request, it's not clear what you mean by "under a certain load"

**Comment by tsegismont** [comment]
@vietj as you said, a new connection is created only if the existing connections are busy. I believe @rkbalgi meant that the number of concurrent requests must be (relatively) high to make sure the maximum number of connections are created.

**Comment by vietj** [comment]
@tsegismont it seems that the concern is about eager creating connections, but it is not clear. Perhaps that pipelining is used in his case ?

**Comment by tsegismont** [comment]
>it seems that the concern is about eager creating connections

Right

>Perhaps that pipelining is used in his case ?

I'm not sure about the actual problem. But even with pipelining disabled, if you send requests rarely (again, this is all relative), the pool may hold just one conneciton

**Comment by vietj** [comment]
and that's very fine to hold one connection if you don't use it, given that now since 3.5.2 we evict connections that sits too long in the pool

**Comment by vietj** [comment]
the pool will create new connection when the pool connections are busy otherwise it will reuse one sitting in the pool.

**Comment by rkbalgi** [comment]
Thanks @tsegismont for rephrasing my query. Yes, my question was indeed about opening (eagerly) and maintaining a configurable number of connections. Looks as though it’s not possible in the current form.

**Comment by vietj** [comment]
@rkbalgi no that's not possible, are you aware of http client that implement this ?

at some point I want to have the ability to promote an existing `NetSocket` as an `HttpClient`, perhaps it can help your use case as you would operate at the connection level instead of pool level and have more freedom to operate in a fine grained manner with lot of control

**Comment by rkbalgi** [comment]
Hi @vietj , Unfortunately, there seem to be no http-client implementations that support this. I will check back in at a later time to see if NetSocket enhancement that you mentioned about. Thank you for taking time to answer my question.

**Comment by vietj** [comment]
@rkbalgi no worries

**Comment by vietj** [comment]
I will close this issue for now
