### ISSUE TITLE
OAuth2Auth does not extend AuthProvider in Scala dialect

### ISSUE THREAD

**Issue by jakubciepiela** [eclipse/vert.x#2513]
Hi,

Vertx version 3.5.2

I am trying to build social login with GithubAuth using Scala dialect of the Vertx.
To avoid repetitive authentication calls to the server i want to use session.

According to the docs code should look like this:

```
    val router = Router.router(vertx)
    router.route.handler( CookieHandler.create )
    val store1 = LocalSessionStore.create(vertx)
    val sessionHandler = SessionHandler.create(store1)
    router.route().handler(sessionHandler)

    val authProvider: OAuth2Auth = GithubAuth.create(vertx, "XXX", "YYY")
    router.route.handler(UserSessionHandler.create(authProvider))

```

The last line however does not compile as OAuth2Auth does not extend AuthProvider

I managed to make it work by using the following trick:

`router.route.handler(UserSessionHandler.create(AuthProvider(authProvider.asJava.asInstanceOf[JAuthProvider])))
`

It looks like the Scala API is incomplete.

Thanks,
Jakub

**Comment by vietj** [comment]
can you open this issue in https://github.com/vert-x3/vertx-lang-scala ?
