### ISSUE TITLE
HttpClient should behave according to the HTTP version returned by the server and not sent by the client

### ISSUE THREAD

**Issue by ashertarno** [eclipse/vert.x#2514]
Full discussion with Gists is available [here](https://groups.google.com/forum/#!topic/vertx/uc8XZEEnx0w). 

The problem goes as follows: vert.x http client submits 2 sequential requests to a http1.0 server.
First requests receives a response as expected, second one fails with VertxException. 
The issue seems to be introduced in 3.5.2 and didn't exist in 3.5.1.

Fixing _When the response does not contain Connection: Keep-alive in HTTP/1.0, the client has to assume Connection: close._

**Comment by vietj** [comment]
looks like a regression
