### ISSUE TITLE
Disable HttpClient TCP idle timeout when connection is in the pool

### ISSUE THREAD

**Issue by luengnat** [eclipse/vert.x#2517]
I noticed that in a corner case, we have a lot of test failure where the connection is not used very often. For example, I make a timeout to be of 10 seconds and I make a call every 10 seconds exactly. Every once in while, my request fails with VertxException (Connection is closed) since the checkout connection is closed right after the connection is polled from the connection pool. I only noticed this in 3.5.2 but not in 3.4.2

**Comment by vietj** [comment]
it's not clear which timeout are you referring to ?

**Comment by luengnat** [comment]
Take a look at IdleStateHandler. IdleStateHandler hooks up when the connection is created (in HttpChannelConnector.applyHttp1xConnectionOptions) . When the connection is reused, it does not try to reset the state. Therefore, by the time the connection is reused, the connection might be closed behind the scene and makes the request with keep-alive on to fail randomly.

**Comment by vietj** [comment]
by which timeout I'm asking which one you configure because there are several possible timeout (tcp idle, keep-alive, per request).

so I'm guessing you are referring to tcp idle timeout.

I will have a look.
