### ISSUE TITLE
The Kotlin documentation for vert.x has errors in it.

### ISSUE THREAD

**Issue by adam-arold** [eclipse/vert.x#2520]
I checked the documentation for Kotlin on [this page](https://vertx.io/docs/vertx-core/kotlin/) and it has some errors in it where code blocks should have been:

![docs_kotlin](https://user-images.githubusercontent.com/1253248/42138779-1af18736-7d83-11e8-98e7-6be284bc6ac9.png)

This is the same part from the Java docs:

![docs_java](https://user-images.githubusercontent.com/1253248/42138782-220b0f10-7d83-11e8-96e8-d16201f5028b.png)

I did not find the repo for the docs so I'm not sure this is the right place to mention this. This problem persisted for at least a year so I thought it might worth mentioning. I'd love to have good Kotlin docs.

**Comment by vietj** [comment]
yes we are aware of that, improvements to the doc have been done in vertx master: you can see the current version here https://vertx.ci.cloudbees.com/job/vert.x3-stack/ws/stack-docs/target/html/vertx-core/kotlin/index.html

**Comment by vietj** [comment]
I will likely back-port these changes to 3.5 so the web-site can be updated accordingly

**Comment by adam-arold** [comment]
Cool, thanks. I'll use the docs you provided in the meantime! Should I leave this open?

**Comment by vietj** [comment]
I think we can close it because this issue is not related to this repo directly.

**Comment by adam-arold** [comment]
Can you point me to the right repo?
