### ISSUE TITLE
is there any way to implement actors model with vertx?

### ISSUE THREAD

**Issue by hadyang** [eclipse/vert.x#2538]
I know Akka and it's acotrs is very powerful. 
My question is know how to implement actors model with vertx?

**Comment by Sammers21** [comment]
@hadyang, are you familiar with [verticles](https://vertx.io/docs/vertx-core/java/#_verticles)? You can think of them as actors. And you can use [event bus](https://vertx.io/docs/vertx-core/java/#event_bus) for sending/receiving messages, so actor model is already implemented.

**Comment by hadyang** [comment]
@Sammers21  Thanks for your answer. But there still a question, how to create signleton verticles in cluster mode? My solution is use unique adress to register verticles, is there any better solutions?

**Comment by vietj** [comment]
@hadyang vertx provides HA verticle deployment, it's explained in the docs

**Comment by hadyang** [comment]
@vietj Thanks your reply. Maybe i don't make it clear. 

For example, in my application, it have lots of orders. And every verticle is map to a order, any action on order will deliver to this verticle. so i need singleton verticle in cluster. Otherwise i need to handle synchronize issues.

**Comment by vietj** [comment]
@hadyang vertx HA deployment deploys a singleton on a cluster, please read the docs : https://vertx.io/docs/vertx-core/java/#_high_availability_and_fail_over

**Comment by hadyang** [comment]
@vietj  thank you very much.

**Comment by hadyang** [comment]
@vietj  Another question, in vertx how to identity the verticle? deployment id?

**Comment by vietj** [comment]
yes, or you can roll your own registry / identifier
