### ISSUE TITLE
mock websocket client connect, but throw NullPointException

### ISSUE THREAD

**Issue by sosojustdo** [eclipse/vert.x#2540]
@vietj 
`package com.cloudyoung.wx.test.base;

import java.util.concurrent.CountDownLatch;

import org.junit.Test;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Vertx;
import io.vertx.core.http.HttpClient;

public class VertxWebSocketServerTest extends BaseTest {

    private CountDownLatch latch = new CountDownLatch(1);

    @Test
    public void initWebSocketConnection() throws Exception {
        WebSocketVerticle verticle = new WebSocketVerticle();
        verticle.start();
        latch.await();
    }
    
    class WebSocketVerticle extends AbstractVerticle {
        
        private int port = 9090;

        private String host = "localhost";

        private String requestURI = "webSocketServer?appId=wxdc55ca89d7d4d1b8&module=WX_WEBSOCKET_DIALOGUE_MODULE&clientSign=7ab2c148-5bdb-4786-ad36-37ada47bb613";

        private int clientNum = 20;

        private int connectionNum = 60000;

        private Vertx vertx = Vertx.vertx();
        
        @Override
        public void start() throws Exception {
            for (int i = 1; i <= clientNum; i++) {
                HttpClient httpClient = vertx.createHttpClient();
                for(int j=1; j<= connectionNum; j++) {
                    httpClient.websocket(port, host, requestURI, webSocket -> {
                        webSocket.handler(buffer -> {
                            System.out.println("got number from server: " + buffer.toJsonObject().getInteger("number"));
                            try {
                                Thread.sleep(1000);
                            } catch (InterruptedException e) {
                                e.printStackTrace();
                            }
                        });
                    });
                }
            }
        }
    }
    
}
`
exception info:
19:24:30 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
19:24:30 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
19:24:30 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
19:24:30 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 16
19:24:30 [main] DEBUG io.netty.util.internal.PlatformDependent - Platform: MacOS
19:24:30 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
19:24:30 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8
19:24:30 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
19:24:30 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
19:24:30 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
19:24:30 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
19:24:30 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
19:24:30 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
19:24:30 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
19:24:30 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
19:24:30 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /var/folders/m3/27h81r2d4815l01bbfsfj4fh0000gn/T (java.io.tmpdir)
19:24:30 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
19:24:30 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
19:24:30 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 3817865216 bytes
19:24:30 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
19:24:30 [main] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
19:24:30 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
19:24:30 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
19:24:31 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
19:24:31 [main] DEBUG io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider - Default DNS servers: [/192.168.30.100:53, /202.106.0.20:53] (sun.net.dns.ResolverConfiguration)
19:24:31 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
19:24:31 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
19:24:31 [main] DEBUG io.netty.util.NetUtil - Loopback interface: lo0 (lo0, 0:0:0:0:0:0:0:1)
19:24:31 [main] DEBUG io.netty.util.NetUtil - Failed to get SOMAXCONN from sysctl and file /proc/sys/net/core/somaxconn. Default: 128
19:24:31 [vert.x-eventloop-thread-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 16
19:24:31 [vert.x-eventloop-thread-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 16
19:24:31 [vert.x-eventloop-thread-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
19:24:31 [vert.x-eventloop-thread-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
19:24:31 [vert.x-eventloop-thread-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
19:24:31 [vert.x-eventloop-thread-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
19:24:31 [vert.x-eventloop-thread-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
19:24:31 [vert.x-eventloop-thread-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
19:24:31 [vert.x-eventloop-thread-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
19:24:31 [vert.x-eventloop-thread-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
19:24:31 [vert.x-eventloop-thread-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
19:24:31 [vert.x-eventloop-thread-0] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
19:24:31 [vert.x-eventloop-thread-0] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
19:24:36 [vert.x-eventloop-thread-13] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 5803 (auto-detected)
19:24:36 [vert.x-eventloop-thread-13] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: ac:de:48:ff:fe:00:11:22 (auto-detected)
19:24:36 [vert.x-eventloop-thread-10] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
19:24:36 [vert.x-eventloop-thread-10] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
19:24:36 [vert.x-eventloop-thread-10] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
19:24:36 [vert.x-eventloop-thread-7] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.bytebuf.checkAccessible: true
19:24:36 [vert.x-eventloop-thread-7] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@35f3bcab
19:24:36 [vert.x-eventloop-thread-7] DEBUG io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13 - WebSocket version 13 client handshake key: DCBugaCiw81NPWbpEClurQ==, expected response: jH2EtzeVP+k+rAJ0AjrwbuFadfM=
19:24:36 [vert.x-eventloop-thread-1] DEBUG io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13 - WebSocket version 13 client handshake key: A4CwX+3VzVRbPOwpH2bqyA==, expected response: RsORCshbiUjp6/1UkHjoZ17VBo8=
19:24:36 [vert.x-eventloop-thread-14] DEBUG io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13 - WebSocket version 13 client handshake key: rz29DcMc7WYz/hLSygPOiQ==, expected response: XP94LxqAOM/Bn3eMVTOnYMbqU5I=
19:24:36 [vert.x-eventloop-thread-8] DEBUG io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13 - WebSocket version 13 client handshake key: namdWLhsBcn1SwSl+IrPUw==, expected response: 23w6+CWGIoLzfoXkb3I47e7KiMs=
19:24:36 [vert.x-eventloop-thread-4] DEBUG io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13 - WebSocket version 13 client handshake key: 6jBb1K326SvGsmPFsvoHUA==, expected response: XmVxmdhuYdRZXNEWknOCLrTzAeI=
19:24:36 [vert.x-eventloop-thread-12] DEBUG io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13 - WebSocket version 13 client handshake key: CfbYqKNEjAy0xmaxGvqKbQ==, expected response: HcK38aDk2ONaP1/SZDVO2E/f48U=
19:24:36 [vert.x-eventloop-thread-9] DEBUG io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13 - WebSocket version 13 client handshake key: zQ1IFdb5feHhMlv5Aj+v6g==, expected response: sxiDkUJJFVw870241E0ryhf7rjM=
19:24:36 [vert.x-eventloop-thread-15] DEBUG io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13 - WebSocket version 13 client handshake key: 0Jc72nZa+MskfAWVmwkFPg==, expected response: M6Mw4C2gENEyc4oXsN6BekgtSFE=
19:24:36 [vert.x-eventloop-thread-13] DEBUG io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13 - WebSocket version 13 client handshake key: ct5UNZGkkinrPdPnMy5IOQ==, expected response: 3Rmnnhy9AKkYjogeKsYojdCWK6Y=
19:24:36 [vert.x-eventloop-thread-0] DEBUG io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13 - WebSocket version 13 client handshake key: oppjdFJOWMziI8RzYwyl3w==, expected response: rY+bRyhcDyRXuOpUldCfqJ7GlA8=
19:24:36 [vert.x-eventloop-thread-3] DEBUG io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13 - WebSocket version 13 client handshake key: Ibgk/MIeZzY+xQV3EcgsUA==, expected response: YIEdcu0C9YUK38sW0zwaYGfFZCI=
19:24:36 [vert.x-eventloop-thread-10] DEBUG io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13 - WebSocket version 13 client handshake key: +NaoBLPOLly80PXBU6aU1A==, expected response: T4CSH8LrkJBO0r+PBYrW0pT4bLg=
19:24:36 [vert.x-eventloop-thread-6] DEBUG io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13 - WebSocket version 13 client handshake key: S5CpXs+zk24yNBJLWIkZlw==, expected response: YDUujFU3ybb+ULHp4d+hjNXxH7Y=
19:24:36 [vert.x-eventloop-thread-2] DEBUG io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13 - WebSocket version 13 client handshake key: WY68hG0tcQXt12Ybnk201w==, expected response: whI+Vq4w2yOugUVYWJ0hsynhWh0=
19:24:36 [vert.x-eventloop-thread-5] DEBUG io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13 - WebSocket version 13 client handshake key: ErBmPnqZNYDBOhSyqDk0lw==, expected response: Q/9FO6AYPMXTXobXbqssYtH+Gyc=
19:24:36 [vert.x-eventloop-thread-11] DEBUG io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13 - WebSocket version 13 client handshake key: D4XSHw9Z5HgYFjGATQiXWA==, expected response: YkMylc54LLHSki3xiekR5qT/Pbw=
七月 17, 2018 7:24:36 下午 io.vertx.core.http.impl.HttpClientImpl
严重: java.lang.NullPointerException: value
七月 17, 2018 7:24:36 下午 io.vertx.core.http.impl.HttpClientImpl
严重: java.lang.NullPointerException: value
19:24:36 [vert.x-eventloop-thread-6] DEBUG io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13 - WebSocket version 13 client handshake key: GUfEstOfYBKkmC6QgBNttA==, expected response: lo8lorxtK2YL7f+MNvCqcpuC0AY=
七月 17, 2018 7:24:36 下午 io.vertx.core.http.impl.HttpClientImpl
严重: java.lang.NullPointerException: value
19:24:36 [vert.x-eventloop-thread-14] DEBUG io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13 - WebSocket version 13 client handshake key: SKpjw3ho8j3dBVdECeRt8Q==, expected response: LnJj7PqkaYe8DEJnK/MXVVOJz50=
19:24:36 [vert.x-eventloop-thread-11] DEBUG io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13 - WebSocket version 13 client handshake key: qUBnp78dz0sMeu7NeHKQgg==, expected response: Xc7XnO+2eAQIuiHmSZ7qi3iMEZs=
七月 17, 2018 7:24:36 下午 io.vertx.core.http.impl.HttpClientImpl
严重: java.lang.NullPointerException: value
七月 17, 2018 7:24:36 下午 io.vertx.core.http.impl.HttpClientImpl
严重: java.lang.NullPointerException: value

**Comment by sosojustdo** [comment]
do you have people help me?
七月 17, 2018 7:24:36 下午 io.vertx.core.http.impl.HttpClientImpl
严重: java.lang.NullPointerException: value

**Comment by vietj** [comment]
you should go to the vertx google group for asking questions, this issue tracker is for tracking bug and features
