### ISSUE TITLE
Limit client connection count

### ISSUE THREAD

**Issue by zhengyangyong** [eclipse/vert.x#2542]
Hi,we are heavy use vert.x, and we want limit active client connection count both in HttpServer and NetServer.
If server had accepted certain amount of connection, new connection need reject for overload protection.
Any good idea ?

Best Regards & Thanks!

**Comment by vietj** [comment]
@zhengyangyong you can maintain the count and when a new connection happens above the limit you can close the connection, on HttpServer you have a connectionHandler that will be called when the client connects
