### ISSUE TITLE
Accessing Timers

### ISSUE THREAD

**Issue by jmcgill-public** [eclipse/vert.x#2566]
There appears to be no way for an application to discover if a Timer is active, or to inspect the metadata of a timer.
The timeouts map (io.vertx.core.impl.VertxImpl#timeouts) is private, as is the timer data (io.vertx.core.impl.VertxImpl.InternalTimerHandler).  All that is possible is to cancel a timer.  Is there a mechanic for managing timers that isn't obvious?

**Comment by vietj** [comment]
there is the Metrics SPI that provides callback to maintain such structure, have a look at `VertxMetrics`
