### ISSUE TITLE
Not able to overwrite the default decoder

### ISSUE THREAD

**Issue by ethirajsrinivasan** [eclipse/vert.x#2569]
Vertx version 3.5.1

Recently i migrated from vertx 2 to vertx 3.5.1. I am sending a value - %%SOME_VALUE%% in my paramater. But Vertx 3 throws error "invalid hex byte" while handling the request. I cannot change the format of the value due to some constraints but looking for some ways to handle within the vertx application. I am unable to overwrite the netty decoder used in vertx

**Comment by vietj** [comment]
can you give more context about your issue, because there is not enough to understand what your problem is.

**Comment by ethirajsrinivasan** [comment]
In vertx version 3.5 

We are hitting the url - http://example.com/api/test?cb=%%CACHEBUSTER%%

We have an internal requirement to replace the cachebuster value. But the application is not able to handle this request since it contains %% in the parameter and throws error as " invalid hex byte '%C' ". 

In vertx version 2 

we were able to hit the same url and it bypassed all the validation of the application and we were able to handle the request.

**Comment by vietj** [comment]
can you show which API you are using ?

HttpClient ?

**Comment by ethirajsrinivasan** [comment]
Vertx-Web 

```java
vertx.createHttpServer().requestHandler(req -> {
            try {
                router.accept(req);
            } catch(Throwable th) {
                req.response().setStatusCode(400).end(th.getMessage());
            }
        }).listen(port,listen);
```

**Comment by vietj** [comment]
can you open this issue in https://github.com/vert-x3/vertx-web instead ?

**Comment by ethirajsrinivasan** [comment]
https://github.com/vert-x3/vertx-web/issues/991 i have already raised this issue but there has not been any response.
