### ISSUE TITLE
HttpServer failed to listen java.lang.IllegalStateException

### ISSUE THREAD

**Issue by darkredz** [eclipse/vert.x#2576]
Using latest vert.x core 3.5.3
When trying to create a Http server listen on either port 80 of 127.0.0.1, 0.0.0.0, or ::
will result in an exception java.lang.IllegalStateException: failed to create a new resolver

Command run: vertx run Test.java

Code used.

```
import io.vertx.core.AbstractVerticle;
import io.vertx.core.http.HttpServer;
import io.vertx.core.http.HttpServerOptions;

public class Test extends AbstractVerticle {

  public void start() throws Exception {

    HttpServer server = vertx.createHttpServer();

    server.requestHandler(req -> {
      req.response().putHeader("content-type", "text/html").end("<html><body><h1>Hello from vert.x!</h1></body></html>");
    }).listen(80);
  }
}
```

console log when the process is executed:

> [root@vps290614 backend]# vertx run Test.java
> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> Using java.util.logging as the default logging framework 
> -Dio.netty.leakDetection.level: simple 
> -Dio.netty.leakDetection.targetRecords: 4 
> -Dio.netty.eventLoopThreads: 4 
> -Dio.netty.noUnsafe: false 
> Java version: 8 
> sun.misc.Unsafe.theUnsafe: available 
> sun.misc.Unsafe.copyMemory: available 
> java.nio.Buffer.address: available 
> direct buffer constructor: available 
> java.nio.Bits.unaligned: available, true 
> jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9 
> java.nio.DirectByteBuffer.<init>(long, int): available 
> java.nio.ByteBuffer.cleaner(): available 
> -Dio.netty.noKeySetOptimization: false 
> -Dio.netty.selectorAutoRebuildThreshold: 512 
> Default DNS servers: [/213.186.33.99:53] (sun.net.dns.ResolverConfiguration) 
> -Djava.net.preferIPv4Stack: false 
> -Djava.net.preferIPv6Addresses: false 
> Loopback interface: lo (lo, 0:0:0:0:0:0:0:1%lo) 
> /proc/sys/net/core/somaxconn: 128 
> -Dio.netty.allocator.numHeapArenas: 4 
> -Dio.netty.allocator.numDirectArenas: 4 
> -Dio.netty.allocator.pageSize: 8192 
> -Dio.netty.allocator.maxOrder: 11 
> -Dio.netty.allocator.chunkSize: 16777216 
> -Dio.netty.allocator.tinyCacheSize: 512 
> -Dio.netty.allocator.smallCacheSize: 256 
> -Dio.netty.allocator.normalCacheSize: 64 
> -Dio.netty.allocator.maxCachedBufferCapacity: 32768 
> -Dio.netty.allocator.cacheTrimInterval: 8192 
> -Dio.netty.allocator.useCacheForAllThreads: true 
> -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024 
> -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096 
> java.lang.IllegalStateException: failed to create a new resolver 
> Succeeded in deploying verticle 
> 

It is fine when I run on Mac OS but on a VPS (OVH) with centos 7 (firewall disabled) the Exception will be thrown and I can't get any content if I curl to the http end point.

On the same server if I yum install nginx and start it, it is fine on the same port. Only vertx had the problem on listen on the port. This vps instance is with both ipv4 and ipv6

Centos 7 ifconfig
> eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 209.46.145.138  netmask 255.255.255.255  broadcast 209.46.145.138
>         inet6 fe80::f016:3eff:ee6f:e624  prefixlen 64  scopeid 0x20<link>
>         ether fa:26:3e:6f:e6:14  txqueuelen 1000  (Ethernet)
>         RX packets 13056  bytes 1093307 (1.0 MiB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 9591  bytes 1411397 (1.3 MiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
>         inet 127.0.0.1  netmask 255.0.0.0
>         inet6 ::1  prefixlen 128  scopeid 0x10<host>
>         loop  txqueuelen 1000  (Local Loopback)
>         RX packets 193  bytes 39411 (38.4 KiB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 193  bytes 39411 (38.4 KiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by vietj** [comment]
have you tried with earlier versions ?

**Comment by darkredz** [comment]
Do you know where does exception comes from most probably? java.lang.IllegalStateException: failed to create a new resolver?
I am wondering if there's a jar conflict
