### ISSUE TITLE
JsonParser does not correctly perform flow control

### ISSUE THREAD

**Issue by ProgMaq** [eclipse/vert.x#2584]
- HttpClient (with SSL)
- JsonParser to process the response in objectValueMode
- Default configuration in the rest of the parameters

When I receive a JSON object inside the handle, I make a parser.pause() to prevent the arrival of new events, however, I get to receive some more events before it really stays paused (3~5).

I think that this is because internally JsonParser does not check when processing the tokens if it is paused, sending all the buffer read so far by the HTTP client. The stream is already paused, but if in this buffer there are 4 json objects, the method "handle" will be called 4 times.

**Comment by vietj** [comment]
@ProgMaq you are right, the current PR fixes that https://github.com/eclipse/vert.x/pull/2583

**Comment by vietj** [comment]
@ProgMaq can you check with latest master, since PR has been merged ?

**Comment by vietj** [comment]
closing as it's fixed in master

**Comment by ProgMaq** [comment]
Thank you!

I have not been able to run tests since I'm on holidays
