### ISSUE TITLE
Support temporary files and directories

### ISSUE THREAD

**Issue by gastaldi** [eclipse/vert.x#2586]
It would be nice if `io.vertx.core.file.FileSystem` supported the creation of temporary files and directories (using `java.nio.files.Files.createTempFile`and `java.nio.files.Files.createTempDirectory` respectively)

**Comment by tsegismont** [comment]
Sounds good to me. Would you like to contribute it?

**Comment by gastaldi** [comment]
Sure, I might give it a try ;)

**Comment by gastaldi** [comment]
@tsegismont there you go: https://github.com/eclipse/vert.x/pull/2587
