### ISSUE TITLE
NullPointerException when reporting a deployment failure without a completion handler

### ISSUE THREAD

**Issue by myok12** [eclipse/vert.x#2590]
In 3.5.3, when deploying a verticle using `deployVerticle(Class<? extends Verticle, DeployOptions)`, it throws a NPE if the class is not public (default: package-private).

e.g.
In `Main.java`: 
```
        vertx.deployVerticle(MessageReceiverVerticle.class, new DeploymentOptions().setInstances(10));
```

In `MessageReceiverVerticle.java`: 
```
class MessageReceiverVerticle extends AbstractVerticle {
}
```

NPE:
```
Exception in thread "main" java.lang.NullPointerException
	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:105)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:646)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:613)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:602)
	at com.groupon.api.test.Main.main(Main.java:13)
```

Reproducible example is provided: [vertx-test.zip](https://github.com/eclipse/vert.x/files/2288609/vertx-test.zip)

**Comment by vietj** [comment]
yes because there is no error, the actual error happens in:

```
      try {
        verticle = verticleSupplier.get();
      } catch (Exception e) {
        completionHandler.handle(Future.failedFuture(e));
        return;
      }
```

so it's the deployment manager error reporting that fails.

if you set a completion handler it will fail but this failure will be reported to the completion handler

**Comment by myok12** [comment]
Gotcha. Feel free to resolve the bug or leave it open if you need to track the missing completion handler issue.

**Comment by vietj** [comment]
I renamed the issue to describe the actual cause
