### ISSUE TITLE
how to set netty vertion

### ISSUE THREAD

**Issue by grubed** [eclipse/vert.x#2596]
when i use java vert.x 3.5.3 ,io.netty vertion is 4.1.19, but i got 
`
java.lang.NoSuchMethodError: io.netty.handler.codec.http2.Http2ConnectionEncoder.writePing(Lio/netty/channel/ChannelHandlerContext;ZJLio/netty/channel/ChannelPromise;)Lio/netty/channel/ChannelFuture;
at com.turo.pushy.apns.ApnsClientHandler.userEventTriggered(ApnsClientHandler.java:268) ~[pushy-0.13.3.jar:na]
at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329) [netty-transport-4.1.19.Final.jar:4.1.19.Final]
`
i need to update io.netty to vertion 4.1.27, how to do? thank you

**Comment by MrXionGe** [comment]
[https://mvnrepository.com/artifact/io.vertx/vertx-core/3.5.3](url)
When you open this URL, you can see its dependencies.
You can modify each one by yourself, about netty(there are 11).

**Comment by MrXionGe** [comment]
I also hope that vertx developers can upgrade the version of netty.

**Comment by vietj** [comment]
@MrXionGe we do upgrade the netty version when possible, a 4.1.27 netty ugprade is expected on master
