### ISSUE TITLE
Provide a way for verticles to reload configuration upon changes

### ISSUE THREAD

**Issue by jahanzebbaber** [eclipse/vert.x#2606]
As per documentation for config retriever [listening for changes](https://vertx.io/docs/vertx-config/java/#_listening_for_configuration_changes), the retriever reloads the configuration every 5 seconds. Issue is that there is no way provide that new configuration to the verticle without first undeploying and redeploying it with the new configuration or doing a app/pod restart. The reason for that is the `config` JsonObject that holds the configuration for the verticle is created via `new` constructor and there is no reference to this `config` object available. This functionality will be really helpful where API keys and certs are being rotated out and live traffic is being taken by the app.

**Comment by vietj** [comment]
can you provide an example of how this would ideally be achieved ?

**Comment by vietj** [comment]
thanks for the explanation @cescoffier

**Comment by jahanzebbaber** [comment]
Hi thank you for quick responses. I am unable to find `Propagating configuration changes to the event bus` anywhere. Can you please link to that?  Thank you

**Comment by rodolfodpk** [comment]
While I understand using ConfigRetriever.listen can be used to propagate config changes to many verticles and other components (and it is probably the right way), it would be nice to inform the ConfigRetriever to simply relaunch the main verticle / full  application. I usually have this in my main verticle: 
`public static void main(String[] args) {
    Launcher.executeCommand("run", MyMainVerticle.class.getName());
}`
and I wonder if it could work. Between some downtime on config changes and a simpler immutable app model I do prefer the latter. And if it could work with native apps (Quarkus and Graal), the downtime would be almost invisible.
