### ISSUE TITLE
WebSocket client does not report server protocol violations on the WebSocket exception handler

### ISSUE THREAD

**Issue by queer** [eclipse/vert.x#2610]
As the title says, basically. When a websocket client receives a payload larger than the configured max size, it seems that it just immediately closes the socket without warning - no logs, no exception, no close frame. I may have misunderstood something, but nothing I did short of changing the max sizes in the options gave any indication of the problem being displayed or fixed.

**Comment by vietj** [comment]
have you try setup an exception handler on the WebSocket itself ?

**Comment by queer** [comment]
Yes; it had no effect as far as I could tell. Specifically, I had done
```Java
socket.frameHandler(this::handleSocketFrame)
        .closeHandler(this::handleSocketClose)
        .exceptionHandler(Throwable::printStackTrace);
```
where `handleSocketFrame` specifically checked for a close frame (which it never got). Additionally, the exception handler never was called (no stack traces were ever printed).

**Comment by vietj** [comment]
can you make a reproducer ? I think this happens in netty decoder, the rerpdoucer would help investigate and eventually improve this

**Comment by vietj** [comment]
thanks

**Comment by vietj** [comment]
I'm using wireshark and it seems that there are no closed done by the server.

**Comment by vietj** [comment]
the client closes the websocket because it has detected a protocol violation from the server.

I think that this should at least reported as an exception in the exception handler and it is not.

**Comment by vietj** [comment]
I will work on a test+fix for vertx master branch
